### ISSUE TITLE
[Bug]: Secondary button background looks similar or identical to disabled in dark themes.

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#10004]
### Package

carbon-components

### Browser

Chrome, Firefox, Edge

### Package version

10.46.0 (via Svelte components)

### Description

The background color of the disabled button is similar or in one case identical to that of the secondary button.

This makes it hard to understand whether a button is actually interactive or not. Going by the convention that grey things are not interactive, users may directly assume the secondary buttons to be disabled.

### Screenshots

g100
![g100](https://user-images.githubusercontent.com/834235/139596711-c0cbcb59-b661-4482-982c-d1f0b99764d7.png)

g90
![g90](https://user-images.githubusercontent.com/834235/139596717-3813ce9d-17bc-4867-a423-04aa9bd0f552.png)

g80
![g80](https://user-images.githubusercontent.com/834235/139596723-511a59b3-e32a-4b4d-aaf5-75dac31e2f7d.png)

g10
![g10](https://user-images.githubusercontent.com/834235/139596730-22dde795-661d-4276-8c09-8caa70be635b.png)

white
![white](https://user-images.githubusercontent.com/834235/139596734-048b696d-7827-47b9-857a-fe007688eef8.png)

### Steps to reproduce

- Add disabled Button component
- Add secondary Button component
- Use a dark theme, g90 being the one with identical backgrounds

[Svelte REPL example](https://svelte.dev/repl/30cb2b152b2e4a9fa2449859a9a92686?version=3.44.0)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
@brunnerh this is a fair issue to bring up. Maybe we need some design research on this. Did you have design specs in mind as to what it should look like?

**Comment by jnm2377** [comment]
@carbon-design-system/design any thoughts on this? Gonna add this to our proposal/needs research pipeline.

**Comment by brunnerh** [comment]
@jnm2377 Did not know that the React components look different. To me those colors look a bit more reasonable, but I suspect that they are for some reason not using the colors defined by `carbon-components`.

The styles for the Svelte components are built from the original SCSS and the colors appear to be consistent with the demos on the [theming website](https://themes.carbondesignsystem.com/?nav=button):

![image](https://user-images.githubusercontent.com/834235/139750827-409bf5a3-bf32-4253-9730-3c7ef3a443fe.png)

I think the mid-range of greys is prone to being interpreted the wrong way, there might not be a great solution for the dark themes that preserves contrast without being over the top, though (e.g. using white).

The design of the tertiary and ghost buttons on the other hand in a way side-step this by just not using a background color, but these buttons cannot be used everywhere (e.g. the Modal component is specified to use secondary buttons).

**Comment by aagonzales** [comment]
## We do have a problem here
Thanks for raising this issue @brunnerh 

This is what I'm seeing in the v10 storybook. There is a difference in color background and text between the two states but they are very close. This problem is also kind of a design pickle (see further down).

![image](https://user-images.githubusercontent.com/11670886/141197467-fdfe211e-6725-4a9e-9d97-31974d9e4088.png)



**v11 Bug**: in the G90 theme, you've caught a bug. We've actually assigned `$button-secondary` and `$button-disabled` the same G60 value. I'll work on fixing that. 

**Inconsistency across assets**: I'm also seeing the disable buttons are darken than the secondary buttons in the design kit but they are lighter in the code. Not sure what's going on there. Below is what they look like in the kit.

![image](https://user-images.githubusercontent.com/11670886/141198917-4a3494ed-d5bf-43e7-8fe1-3afe3e59dac9.png)

 
 ----------

## The Pickle
As a rule, we want to keep all enabled button text (no matter the theme) white so any lighter secondary button would cause inaccessible text. And if we darken the button background then it gets too close to the theme background colors.   

The only solution would be play with the how the disabled button appears. I believe the original design intent is to have the disabled buttons have less contrast (ie darker) than the enabled ones. I think something like below provides enough difference what do you think?

![image](https://user-images.githubusercontent.com/11670886/141199593-18fe4bb5-0047-445e-9268-e1e2ae09ea2d.png)

**Comment by aagonzales** [comment]
**Regarding updating the v11 token values**
I actually think we should make these disabled states have an opacity in the dark themes like we decided to do decided to do with placeholder and disabled text, see https://github.com/carbon-design-system/carbon/issues/10054. This will also allow it to keep a similar contrast across layer colors.



  | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme
-- | -- | -- | -- | --
$button-disabled | Gray 30 | Gray 30 | Gray 50@ 30% opacity / rgba(141,141,141,0.30); | Gray 50 @ 30% opacity / rgba(141,141,141,0.30);
$text-on-color-disabled | Gray 50 | Gray 50 | $text-on-color @ 25% opacity / rgba(255,255,255,0.25); | $text-on-color @ 25% opacity / rgba(255,255,255,0.25);

<div data-node-type="line" id="magicdomid102" class="ace-line"></div>

**Comment by brunnerh** [comment]
> I think something like below provides enough difference what do you think?

@aagonzales If that question is directed at me: That would be sufficiently different; it is definitely a great improvement in any case.

If the text has to stay white, this solution is probably close to optimal. (And having bright, fully filled buttons in a dark theme becomes glaring anyway, so making the normal background much lighter is not really an option.)

**Comment by jnm2377** [comment]
@aagonzales can these enhancements be closed since they were implemented in v11 or was the idea to also implement them in v10?
