### ISSUE TITLE
[Bug]: Unordered list item markers extend beyond list bounds

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#10181]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.47.1

### Description

The top level elements of an unordered list have `–` markers that end up outside the bounding box of the list.

The marker is added via `:before`:
```css
.bx--list--unordered>.bx--list__item:before {
    content: "\002013";
    left: -1rem;
    position: absolute;
}
```

Maybe the list should have some left padding to offset the marker placement?

### Screenshots

From [live demo page](https://www.carbondesignsystem.com/components/list/usage/#live-demo):

![image](https://user-images.githubusercontent.com/834235/143763760-2181dd2f-e453-4731-bbdd-c874436fce50.png)

### Steps to reproduce

- Create an unordered list component with items in it or go to [live demo page](https://www.carbondesignsystem.com/components/list/usage/#live-demo) and set variant selector to `Unordered list`
- Inspect DOM element layout of list `ul.bx--list--unordered` element

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
Hi @brunnerh thanks for opening this issue. This was done intentionally. The list components (both ordered and unordered) are meant to align the text on the grid, not the marker, as you can see here:
<img width="314" alt="Screen Shot 2022-01-06 at 12 28 50 PM" src="https://user-images.githubusercontent.com/32556167/148432795-1ea7cf30-3252-4a4f-8148-60c88939a623.png">
https://codesandbox.io/s/list-example-gfh2v?file=/index.js

Is there a design or a11y reason you think this is wrong?

**Comment by brunnerh** [comment]
@jnm2377 I think this makes too many assumptions about layout to work. The components will not necessarily be directly in a grid (otherwise the usefulness of the component is severely limited), nor does it always work in the grid itself, which has responsive breakpoints which cause the markers to be cut off at small screen sizes.

![image](https://user-images.githubusercontent.com/834235/148434286-b6ae5b59-6d6e-4b84-bb8c-9b53122515ea.png)

**Comment by jnm2377** [comment]
@carbon-design-system/design do y'all have any input in terms of the layout?

**Comment by aagonzales** [comment]
This one is interesting because I'm not really sure why the bounding box was intentionally excluding the dashes from a design perspective. I don't think it's a grid thing. In the original duo spec the dashes and numbers are aligned to the paragraph and title next not the list text like suggested.

So im not sure where the weird indenting came from. Might need to check some old issues.

![image](https://user-images.githubusercontent.com/11670886/150576304-db61487e-fdc7-4398-a4a8-849666d1ec0e.png)


Even on the grid the dashes shouldn't be hanging in the gutter. That's not typographically correct and I don't think design would have recommended that. The dash or numbers are considered typographic elements and therefor aligning them to the other type is correct. You also need the intend for proper typographic hierarchy between a list and header or body copy. Seems like this is just a normal bug and not an intended design feature.

![image](https://user-images.githubusercontent.com/11670886/150577440-f7ff05a1-e787-46bf-bf57-6526067cf899.png)

**Comment by mjabbink** [comment]
here’s a good live sample 
https://www.ibm.com/design/language/philosophy/principles

**Comment by tay1orjones** [comment]
> Seems like this is just a normal bug and not an intended design feature.

With that in mind, I think the original suggestion seems reasonable to explore as a fix:

> Maybe the list should have some left padding to offset the marker placement?

**Comment by mjabbink** [comment]
The middle one looks good to me.
