### ISSUE TITLE
German umlauts are not displayed correctly in Chrome

### ISSUE THREAD

**Issue by andreas-schmitt-mi** [carbon-design-system/carbon#1022]
## Detailed description

On Chrome version 68 German umlaut characters (ÄÜÖ) are not displayed correctly in text input fields, if they are entered in uppercase. E.g. "Äpfel" is displayed as "Apfel". If I do the same in Firefox 52.9 it works fine and umlauts are displayed correctly. This might be related to the font-family. If I change font-family from "ibm-plex-sans" to Arial, the umlauts are displayed correctly in Chrome, too.

> Is this issue related to a specific component?
- I have noticed it in Text Input and Search component, maybe other components are affected as well.

> What did you expect to happen? What happened instead? What would you like to see changed?
- Umlaut characters in uppercase should be displayed correctly.

> What browser are you working in?
- Chrome 68

> What version of the Carbon Design System are you using?
- 9.6.4

## Steps to reproduce the issue

1. Open Google Chrome 
2. In a carbon components text input field enter "Äpfel" or "ÄÖÜ" e.g. on carbon components demo page [Text input](http://www.carbondesignsystem.com/components/text-input/code)
3. Instead of "Äpfel" the text input displays "Apfel"

## Additional information

- On Chrome 68
![capture](https://user-images.githubusercontent.com/42237709/43894470-66bd5394-9bd2-11e8-8307-8d6ca44188f9.JPG)

- On Firefox 52.9
![capture](https://user-images.githubusercontent.com/42237709/43894524-8a93255a-9bd2-11e8-9b77-324673243926.JPG)

**Comment by asudoh** [comment]
Got a reduced case without Carbon:
[umlaut.zip](https://github.com/IBM/carbon-components/files/2281953/umlaut.zip)

This problem seems to reproduce only with Windows (I used Windows7, not sure about Windows10). Adding a border there shows an interesting thing - The accent goes on the border. So it's behaving as though the glyph is crippled.

Not sure if the issue comes from the Plex font, or browser/OS, but given we can reproduce the problem without Carbon, moving this issue to Plex so that Plex folks can take a look at.

**Comment by asudoh** [comment]
Issue moved to [IBM/plex #191](https://github.com/IBM/plex/issues/191) via [**ZenHub**](https://www.zenhub.com/)
