### ISSUE TITLE
[Bug]: Tooltip allows mouse clicks to propagate to parent elements

### ISSUE THREAD

**Issue by obambrough** [carbon-design-system/carbon#10284]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.48.0

### React version

v17.0.2

### Description

A mouse click will open the tooltip. The mouse click event is propagating to the parent elements and not stopping with the tooltip. This started with carbon-components-react v7.48.0. 

In our product the tooltip's parent's onClick handler opens a sidebar - this shouldn't happen when the tooltip is clicked.

### CodeSandbox example

https://codesandbox.io/s/carbon-components-react-7-48-tooltip-click-propagates-rnj2o

### Steps to reproduce

Click on the tooltip's icon. The text below the yellow box counts each time the onClick handler of the yellow box is triggered. The count increases when the tooltip is clicked but shouldn't.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
> In our product the tooltip's parent's onClick handler opens a sidebar

@obambrough Unfortunately, interactive controls can't have focusable descendants. Nested interactive controls [are not announced by screen readers](https://dequeuniversity.com/rules/axe/4.2/nested-interactive). Because of this, placing a Tooltip inside a parent element that is interactive will fail [WCAG Success Criterion 4.1.2](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value).

**Comment by tay1orjones** [comment]
Also, event propagation can be stopped in an `onClick` on a wrapping element. I made a slightly modified [codesandbox](https://codesandbox.io/s/carbon-components-react-7-48-tooltip-click-propagates-forked-vymrs?file=/src/index.js), the counter isn't incremented when the tooltip is clicked to open.

**Comment by obambrough** [comment]
Wrapping the tooltip is our current work-around but it has a problem with the label - if you click on the tooltip's icon the tooltip's content is displayed which makes sense, but clicking on the label doesn't open the tooltip (and now it doesn't open our sidebar either since its wrapped by the mouse click handler.) So that makes the label a bit of weird mouse click blackhole.

Based on your first comment it seems we should alter the UI to not have the "card" (which the tooltip is a child of) be clickable to open the details side-panel.

**Comment by FrivalszkyP** [comment]
@obambrough Hi there, I was the one who proposed and removed the stopPropagation call from the tooltip. See my comment about this exact use case here: https://github.com/carbon-design-system/carbon/pull/9959#issuecomment-957226667

I agree with Taylor that the stopPropagation() call simply masked a bigger problem that nesting buttons inside buttons should not be done. In your case, the wrapping component is a DIV, not a BUTTON, but that is an accessibility issue in itself, because a DIV cannot receive focus and is not announced to screen reader users as a clickable button. I strongly suggest talking to your UI design team and making it clear that tooltips are focusable, clickable elements (i.e. buttons) just like the tile itself, so it breaks the accessibility object model. 

Here are related links from a different comment by Taylor: https://dequeuniversity.com/rules/axe/4.2/nested-interactive https://www.w3.org/WAI/WCAG21/Understanding/name-role-value
