### ISSUE TITLE
Update design tokens with latest values

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#10292]
Before our RC0 release, we need to go through the tokens defined in our themes package and verify that the values match the latest in: https://carbondesignsystem.notion.site/final-List-of-new-tokens-c507394e43fe4daa9f0cd0eedb25d1e4

**Checklist**

- [ ] Correct the values for the following tokens
  - [ ] `highlight` should be `blue-80` in `g100`
  - [ ] `toggle-off` should be `gray-60` in `g100`
- [ ] Compare the netlify preview with the final token list in Notion
- [ ] For any changes, update the values for the token in the corresponding theme file under: https://github.com/carbon-design-system/carbon/tree/main/packages/themes/src/next
- [ ] Create a PR with updates

**Comment by joshblack** [comment]
@aagonzales are there any values in particular that stood out as wrong that I should add to the checklist to be changed before doing an overall audit?

**Comment by aagonzales** [comment]
Just the ones that were brought up in the discussion thread.

**Comment by joshblack** [comment]
@aagonzales I have `highlight` and `toggle-off` from that thread in the checklist, are there any others ones from the discussion? I wanted to confirm specific changes as I was unsure what the takeaways were in the discussion for tokens like `text-error`.

---

As a reference to those reading this issue, this is the discussion that we're referring to: https://github.com/carbon-design-system/carbon/discussions/10247#discussioncomment-1802728

**Comment by aagonzales** [comment]
[WIP comment]
When auditing the tokens today, I've noticed a lot of the interactive states are still using the old `adjustLightness` function instead of the new IDL hover tokens. Here is the list that needs to be updated.

**[White theme](https://github.com/carbon-design-system/carbon/blob/main/packages/themes/src/next/white.js)**

- [ ] `backgroundInverseHover`: Gray-80-hover
- [ ] `backgroundSelectedHover`: Gray-20-hover
- [ ] `layerHover01`: Gray-10-hover
- [ ] `layerHover02`: White-hover
- [ ]

**Comment by tay1orjones** [comment]
@aagonzales `$layer-disabled` is used in the following places: 

https://github.com/carbon-design-system/carbon/blob/963eb58b288e65e99d3ae0498f3042d2811259df/packages/components/src/components/data-table/_data-table-action.scss#L91-L96

https://github.com/carbon-design-system/carbon/blob/532a5c956be2749d14ac7fc9f50fddddac2da2bc/packages/styles/scss/components/code-snippet/_code-snippet.scss#L38-L50

https://github.com/carbon-design-system/carbon/blob/ce8966fb90bac9106e5ec6433954032545e0754c/packages/styles/scss/components/data-table/action/_data-table-action.scss#L96-L101

https://github.com/carbon-design-system/carbon/blob/d02a8e55ccfbdfb1383476dc183cce5c186e00d1/packages/styles/scss/components/tag/_tag.scss#L123-L126

https://github.com/carbon-design-system/carbon/blob/80ee23cc8447bef8a7f41d4ba7366446a11d4808/packages/styles/scss/components/tile/_tile.scss#L92-L98

https://github.com/carbon-design-system/carbon/blob/49933c30cad5c1458b31f9472bb0ed183e6d9ab3/packages/styles/scss/components/toggle/_toggle.scss#L301-L306

https://github.com/carbon-design-system/carbon/blob/49933c30cad5c1458b31f9472bb0ed183e6d9ab3/packages/styles/scss/components/toggle/_toggle.scss#L581-L585

Do you think these should be updated to something else so we can remove `layerDisabled`, or should we keep it based on these usages?

**Comment by tay1orjones** [comment]
@aagonzales `$field-disabled` is used in a few spots too:

- `carbon-components`
  - date-picker
  - search
  - text-input
- `@carbon/styles`
  - date-picker
  - list-box
  - number-input
  - select
  - slider
  - text-area
  - text-input


[This link](https://cs.github.com/carbon-design-system/carbon?q=%24field-disabled) shows each one in context. Same deal - I can update them if you'd like to aim for removing `$field-disabled`. Otherwise we can leave it in?

**Comment by aagonzales** [comment]
Yeah I know I talked to @joshblack about this and maybe we never opened a ticket for it but anywhere where `$field-disabled` is used we're just going back to using `$field` and same with `$layer-disabled` (should be replaced with just `$layer`.

So they're in use now but they shouldn't be. Code needs to be updated to replace the disabled tokens.
