### ISSUE TITLE
Selectable Tile needs to stopPropagation and preventDefault for space key events

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon#1029]
http://carbondesignsystem.com/components/tile/code

- Click twice on the "Selectable Tile" example. The checkbox is selected/deselected.
- Type Enter twice. The checkbox is selected/deselected.
- Now type Space twice. The checkbox is selected/deselected, _but_ the page also scrolls, which makes the user lose the context of where they are on the page.

Typing space is a valid way to select/deselect a checkbox, so a keyboard user would expect this to work properly when the checkbox has focus, without doing the browser's default scroll behavior.

**Comment by alisonjoseph** [comment]
Hi @carmacleod thanks for making this issue. 

Does it make sense to override the browser default scroll behavior on space bar for this. @joshblack @asudoh @aledavila @chrsfshr  thoughts?

**Comment by asudoh** [comment]
Hi @alisonjoseph my apologies for being late on getting back on this - I see the issue stems from the approach allowing keyboard focus on the `<label>` instead of the `<checkbox>`. That said, I see a few solutions (as you would see):

1. Put the `<checkbox>` next to the `<label>` (breaking change)
2. Apply the focus tracker of our checkbox JS code to the selectable tile
3. `.preventDefault()` (as this issue suggests)

I personally like 1. the best, but given the nature of breaking change it'd be for a major release. I like 2. over 3. for the sake of code reuse and consistency, but fine with 3.

**Comment by carmacleod** [comment]
Still a problem.

**Comment by carmacleod** [comment]
Argh. _Stop doing that_, stalebot!!
Someone please reopen.
And... please slow that stalebot down. 14 days is too fast.
If everybody is forced to spend 5 minutes re-reading/pinging Carbon issues every 14 days, I'll bet that adds up to a lot of wasted time.

**Comment by Cicko** [comment]
Ok I see this was still not fixed 😅

**Comment by emyarod** [comment]
this should already be resolved https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tile/Tile.js#L299

can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging? this is not reproducible in the steps outlined in the original ticket
