### ISSUE TITLE
Separate tab and tab content rendering

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#10313]
### Summary

The current Tabs component in React renders the tab content immediately after the list of Tab buttons. It would be useful to be able to separate these two pieces of content without losing the automatic management of the tab content.

### Justification

In @carbon/ibm-products we place the tabs inside a header component which has a background and a bottom border separating it from the content. We wish to use the tabs to control the content displayed below the header and as a result, have to wire these up using onClick.the 

### Desired UX and success metrics

While the intention is to separate the content from the tabs, no UX changes are expected. This does allow for tab and content to be rendered separately, so we may with to document that is not desirable.

### Required functionality

In @carbon/ibm-products we can remove the need for our users to wire up the Tabs to the content when placing the content in a separate section.

### Available extra resources

Can apply solution used in PR above to Carbon.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
@lee-chase Hey I think this is now possible with the Tabs API improvements made in v11. 🎉 🦖 

Let me know if not and we can reopen!

**Comment by ariellalgilmore** [comment]
Hi, bringing this issue back up, but with a slightly different solution. We recieved this issue in IBM Products: https://github.com/carbon-design-system/ibm-products/issues/4989.

This is another example Lee shared using IBM Products page header with the issue: https://github.ibm.com/lee-chase/project-paris/blob/main/src/routes/Builds/Releases/Details/BuildsReleasesDetails.jsx and this is the site: https://pages.github.ibm.com/lee-chase/project-paris/#/builds/releases/0

The problem here is that the `<TabList>` and `<TabPanels>` live in seperate areas and not contained under `<Tabs>`. This results in not being able to connect the `id`s for each togther creating a11y issues. 

@davidmenendez and I were thinking we could potentially solve this issue by allowing the users to manually add their own `id`s vs right now `<Tabs>` is automatically generating `id`s: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Tabs/Tabs.tsx#L134

**Comment by davidmenendez** [comment]
@carbon-design-system/developers any thoughts one this one?

**Comment by ljcarot** [comment]
@tay1orjones I think this question is directed to someone from core.  Thoughts?
