### ISSUE TITLE
[Bug]: MultiSelect.Filterable does not render options properly when clearing input via backspace key

### ISSUE THREAD

**Issue by ask-42** [carbon-design-system/carbon#10336]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

latest (7.50.0, 10.50.0)

### React version

^17.0.2

### Description

When typing a filter in the Filterable MultiSelect, and then clearing it by pressing backspace (say you make a typo after typing one character, and then press backspace to delete it, or want to update your filter), it does not render/filter on the '' input value, so the options do not appear until you begin typing a new filter.

Clicking out of the input when it is blank, and then back into it, causes them to reappear, but that requires additional user interaction.

### CodeSandbox example

https://codesandbox.io/s/boring-noether-kme19

### Steps to reproduce

1. Type the letter `a` into the filter, to show just item `a`
2. Press the backspace key to clear the filter
3. No items render. All items (`a`,`b`, and `c`) should render right now based on the default filtering logic, but there is nothing.
4. Clicking out of the input and back in at this point causes them to render properly

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by TannerS** [comment]
I believed narrowed this issue to this line, any reasoning for this line @joshblack or @tay1orjones ?

It apears to act the same except when I change that line to pass true instead of false, the full drop down appears on an empty string (when i erase the thing i typed) 

https://github.com/carbon-design-system/carbon/blob/aa6347943351052ba4f795b6136a4cc4a5451c83/packages/react/src/components/MultiSelect/FilterableMultiSelect.js#L282
