### ISSUE TITLE
[Feature Request]: Delayed Opening for Definition Tooltips

### ISSUE THREAD

**Issue by SThiara** [carbon-design-system/carbon#10372]
### Summary

Definition tooltips currently pop in immediately on mouse hover or focus. It would be nice if an additional prop could be passed in to designate the amount of time a user needs to hover or focus over the tooltip to make that definition appear, or if they were inherently delayed by 0.5s since that seems to be the number frequently requested. 

### Justification

Customers that use our IBM licensed software program have requested this feature to make navigating pages more user-friendly. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @SThiara! 👋 

This is a fantastic feature request and thankfully the behavior of all of our Tooltips in v11 will be to support configuring how long it takes for the tooltip to appear and be dismissed.

This is unlikely something that we will backport into our v10 library, however, as tooltips in generally are being changed in order to be more accessible and flexible for different types of experiences.

Let me know what you think about this and if you have any follow-up questions!

**Comment by SThiara** [comment]
Thanks for the update Josh, that sounds great. We look forward to it.
