### ISSUE TITLE
[Bug]: Data table stickyHeader prop causes row incorrect spacing

### ISSUE THREAD

**Issue by kenguo573** [carbon-design-system/carbon#10395]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.50.0

### React version

17.0.2

### Description

when data wraps onto another line, there's no bottom spacing for columns that wrapped
disabling `stickyHeader` fixes the issue, alternatively setting `size` to `short` also fixes it

![image](https://user-images.githubusercontent.com/63412869/149213337-176b1420-67ea-430c-a0c2-455e5197b6e9.png)

### CodeSandbox example

https://codesandbox.io/s/wonderful-poincare-o7hjd?file=/index.js

### Steps to reproduce

1. enable `stickyHeader`
2. set `size` to `normal`
3. in data table, have columns that wraps onto another line

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jagathgj** [comment]
while adding prop like stickyHeader w have to unset the defined height of row in data table so that rows won't overlap.

```
.bx--data-table--sticky-header tr {
  height: auto;
}
```

And for checkboxes alignment, we need to change it like below

```
.bx--data-table--sticky-header tbody tr td.bx--table-column-checkbox {
  align-items: flex-start;
  padding-top: 0.875rem;
}
```

[Sandbox](https://codesandbox.io/p/sandbox/carbon-v10-data-table-forked-d7cjgc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clscv6k6y00073b6inwrt9pxg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clscv6k6y00033b6i30fw5w81%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clscv6k6y00043b6ika5lea2r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clscv6k6y00063b6i1iariuh7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clscv6k6y00033b6i30fw5w81%2522%253A%257B%2522id%2522%253A%2522clscv6k6y00033b6i30fw5w81%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clscv6k6y00063b6i1iariuh7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clscv6k6y00053b6ir1l34sv1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clscv6k6y00063b6i1iariuh7%2522%252C%2522activeTabId%2522%253A%2522clscv6k6y00053b6ir1l34sv1%2522%257D%252C%2522clscv6k6y00043b6ika5lea2r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clscv6k6y00043b6ika5lea2r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
