### ISSUE TITLE
Code-snippet: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10411]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] ~Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))~ NA

 **Website** (v11)
 _Design checks_
- [x] Style tab has correct design tokens listed 
- [x] ~Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)~ NA
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- Live Demo has applied v11 changes
   - Themes are rendering correctly
   - ~Size props are named correctly~ NA
   - No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] ~Component using the correct size prop names~ NA
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

**Comment by laurenmrice** [comment]
## Visual bugs (in React)

- [ ] **For all code snippet variants:** There should not be a light prop version anymore and should be using the contextual color tokens.

### Inline code snippet

- [ ] **Enabled state:** Background color should be color token `$layer`.
- [ ] **Hover state:** Background color should be color token `$layer-hover`.
- [ ] **Active state**: Background color should be color token `$layer-active`.

### Single line code snippet
- [ ] Check to make sure all spacing tokens use the format $spacing-01, etc. instead of having to prefix the token with $carbon--.

### Multi line code snippet
- [ ] Check to make sure all spacing tokens use the format $spacing-01, etc. instead of having to prefix the token with $carbon--.
- [ ] Enabled state: Background color should be color token`$layer`.

**Copy snippet button**
- [ ] Enabled state: Background color should be color token `$layer`.
- [ ] Hover state: Background color should be color token `$layer-hover`.
- [ ] Active state: Background color should be color token `$layer-active`.

**Copy feedback tooltip**
- [ ] Text in tooltip should be using type token `body-compact-01`.

**Show more/less button**
- [ ] Text in button should be using type token `body-compact-01`.
- [ ] Enabled state: Background color should be color token`$layer`.
- [ ] Hover state: Background color should be color token `$layer-hover`.
- [ ] Active state: Background color should be color token `$layer-active`.

**Overflow indicator**
- [ ] Background-image color token should be `$layer`.

**Comment by laurenmrice** [comment]
## Website

**Single line code snippet**
- [ ] The container color token should be `$layer`

**Comment by laurenmrice** [comment]
### Design kit

**All code snippet variants**
- [ ] Enabled background colors should be color token `$layer-01`

**Multi line code snippet**
- [ ] Chevron icon should be color token `$icon-primary`. Correct the blue color override.

**Comment by tw15egan** [comment]
@laurenmrice just pushed a PR up for the token fixes. It looks like the layering issue you pointed out is resolved by switching the `copy-button` to use the `layer` token (it now gets lighter on dark themes)

**Comment by tw15egan** [comment]
Dev checks are complete and PR is up 👍🏻

**Comment by aagonzales** [comment]
Closing as all updates are complete. Live demo fixes are being tracked in https://github.com/carbon-design-system/carbon/issues/10889
