### ISSUE TITLE
Tooltip: v11 audit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#10439]
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [ ] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] ~Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))~ NA

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [x] ~Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)~ NA
- [x] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [x] ~Size props are named correctly~NA
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [x] ~Component using the correct size prop names~ NA
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [x] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [ ] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [ ] Design
   - [x] Develop

**Comment by laurenmrice** [comment]
## Visual bugs
###  scss
- [ ] For `Tooltip styles` the focus should be using color token `$focus`
>     &:focus {
>       @include focus-outline('border');
> 
>       fill: $button-primary-hover;
>     }

**Icon button tooltip**
- [ ] Tooltip `type-style` should be using $body-compact-01`
- [ ]  Check to make sure all spacing tokens use the format `$spacing-` instead of having to prefix the token with `$carbon--`.

**Definition tooltip**
- [ ] Hover state: The icon should be using color token `$icon-primary`. It may be using this but I just didn't see the token explicitly in code.
- [ ] Enabled state:`border-bottom` should be using color token `$border-interactive`.

### Storybook
 - [ ] The Tooltip story needs to come out of Experimental and into Stable before the v11 release.
 - [ ] There should be 3 variants under the main component `Tooltip`: Standard, Icon button, and Definition. We need to rename the story "Default" to be `Standard` and we need to add a story for `Icon button`.
 Example of our usage guidance:
<img width="777" alt="Screen Shot 2022-02-08 at 11 30 30 AM" src="https://user-images.githubusercontent.com/43969356/153042755-0d40c9e7-c923-4860-b343-9e8a11b41c79.png">

**Comment by laurenmrice** [comment]
## Website

**Usage tab**
- [ ] Overview section: "tool tip" should be one word and "toggle tip" should be one word.
- [ ] Variants section: there should be a period after each sentence under the Purpose column in the Variants table.

**Style tab**
- Definition tooltip image still says " Definition Toggletip". Should be "Tooltip".

**Live demo**
