### ISSUE TITLE
The expand/collapse icon location in an expandable tile

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon#10493]
### Package

carbon-components

### Browser

Chrome, Safari, Firefox

### Package version

V11

### Description

For the expandable tiles example in v11: 
https://v11.carbondesignsystem.com/components/tile/usage/#expandable
I think the collapse icon jumps to the bottom of the tile could be a usability problem. 
1. For the mouse users, they have to move to the bottom of the tile to collapse the tile. It could be an annoying task if the user's just looking around.
2. For the keyboard users, they might need to press a few tabs to go down the list in order to collapse the tile. 
I think the expand/collapse icon should remained in the fixed location. It's easier for both mouse users and keyboard users. 

### Screenshots

Here's the Carbon example:
https://v11.carbondesignsystem.com/59894a81e27a5f35850678c36329d619/tile-usage-5.gif

Here's a proposal:
![image](https://user-images.githubusercontent.com/40870771/150438860-270f0b3c-adaa-47bd-99e8-a96fdc60bbc2.png)

### Steps to reproduce

Go to: 
https://v11.carbondesignsystem.com/components/tile/usage/#expandable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @thefirstartist 👋  Thanks for making this issue!  The usage guide for expandable tile doesn't make this clear but, in the component itself, users can click, or alternatively use space or enter when tabbed into the tile, anywhere in the tile to expand and collapse the component. There's no need to navigate to the actual chevron to expand/collapse the tile. You can see that behavior in our storybook [here](https://react.carbondesignsystem.com/?path=/story/components-tile--expandable)

**Comment by thefirstartist** [comment]
Thanks Abbey for replying. 
If clicking on the tile can expand/collapse the entire tile, what if there are interactive items in the tile, like the CTA button or links? How do users interact with them? I'm sure mouse users will want to click on the chevron to expand/collapse the tile.
For keyboard users, they would need to tab through all interactive items in order to reach the chevron. Having the chevron in the same location is important too.

**Comment by sstrubberg** [comment]
Website needs to reflect the storybook regarding all the Tile permutations. Connecting this issue to the #11351 epic.

**Comment by mbgower** [comment]
I think both @thefirstartist's comments are worth considering:
- interaction/focus on expand/collapse being triggered
- mechanism for triggering, particularly where the component contains actionable items OR is itself an actionable component (for something other than just expanding content)

The latter is particularly challenging because if the whole tile is actionable JUST to expand (i.e., every expandable tile will be a control), how is anyone to know when clicking on the tile causes a _different_ action than expand to take place, and they need to click on the expand icon? It seems to compound the challenge we have trying to provide visual affordances to distinguish tiles that are non-actionable containers (potentially containing controls) versus tiles that are themselves actionable.

IMO, restricting the expand target to JUST the chevon/triangle is probably one of the simplest ways to reduce this friction.

**Comment by thyhmdo** [comment]
@mbgower @thefirstartist The team took a look at this issue. We have a few concerns about visual and keyboard order, but we want to hear more about it from you. Would you two be able to come to one of our Design Office Hours so that you can demo this for us?

**Comment by thefirstartist** [comment]
@thyhmdo Absolutely. I'll be there.

**Comment by mbgower** [comment]
PS, it was pointed out that the Code snippet component has a Show more disclosure pattern that _does_ do this. The use case seems different to me, but wanted to record that, having made my [comment](https://github.com/carbon-design-system/carbon/issues/10493#issuecomment-1282584555) that I didn't know of any.

**Comment by thyhmdo** [comment]
@mbgower yeah, we actually chatted about this before you came in the room. We think it makes sense in this case since the code snippet is a continuous flow rather than having different elements insides it.

**Comment by thyhmdo** [comment]
@thefirstartist   Though moving forward, we are going to keep our expansion tile the same but will keep your proposal for more research in the future, Sam. 

Another suggestion here, I think there's a line to separate the content in your proposal design but just want to clarify that we'd use `border-subtle` for that line and have 16px margin instead of extending it to the sides. 

![Suggestion](https://user-images.githubusercontent.com/77697351/199319605-d15fabda-bc60-4270-bc82-232f839b30bb.png)
