### ISSUE TITLE
[Bug]: Inefficient space usage by inline notification on small screens

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#10501]
### Package

carbon-components, carbon-components-react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v10.51.0 / v7.51.0 (react)

### Description

On small screens (width < 42rem) the inline notification has a `max-width` of `18rem`, which is counter-productive in terms of utilizing the already limited available space.

### Screenshots

![image](https://user-images.githubusercontent.com/834235/150630069-60f2107f-5906-478e-bd59-31ae7aac97ac.png)

### Steps to reproduce

- Add inline notification component
- Resize window viewport to under 42rem width

[Sandbox](https://codesandbox.io/s/inline-notification-layout-4xprw)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Those are the default `max-inline-size` values we have set up for the notifications. But it is possible to write a style and override those styles

https://github.com/carbon-design-system/carbon/blob/abff3a5b12dee8edef8c81b4e935562293e8e545/packages/styles/scss/components/notification/_inline-notification.scss#L26-L52

Just use the `max-inline-size` if you want to have a custom size for your notification. You can also add a `className` instead of using a css inline.

```
  <InlineNotification
    title="Notification title"
    subtitle="Subtitle text goes here"
    style={{ maxInlineSize: '100%' }}
  />
```
