### ISSUE TITLE
Form input labels no longer get highlighted on focus

### ISSUE THREAD

**Issue by subinpc** [carbon-design-system/carbon#1052]
## Detailed description
Until recently, the label of a form input element would get highlighted along with the input element when the element gets focussed. It no longer does that. Is this change intentional? I didn't see this change get mentioned anywhere.

> Is this issue related to a specific component?
form input components

> What browser are you working in?
chrome

> What version of the Carbon Design System are you using?
v9.8.5

## Add labels
`discussion`

**Comment by alisonjoseph** [comment]
This is a known issue, we had to move the order of the label/input for a11y reasons and haven't fixed this yet. 

related to this issue in React https://github.com/IBM/carbon-components-react/issues/1173

**Comment by asudoh** [comment]
Wanted to see with @carbon-design-system/design if the original `v9` behavior is still desirable for `v10` - Especially because the blue highlight color we had in `v9` does not seem applicable to `v10`:

![image](https://user-images.githubusercontent.com/1259051/57053783-25367e80-6ccb-11e9-8159-c42a9a3801d6.png)
