### ISSUE TITLE
[Release Partner] <Electric Boogaloo>

### ISSUE THREAD

**Issue by BorjaOlmos** [carbon-design-system/carbon#10684]
**What is your team's name?**

 Electric Boogaloo

**Why would you like to join the Release Partner Program?**

 Because we are going to start using Carbon and it would be great if we could start using the latest versions in order to avoid future changes.

**Are you interested in participating in biweekly feedback sessions for the release?**

 No

**Who should we reach out to for more info?**

 borja@emitwise.com

**Comment by jnm2377** [comment]
Hi @BorjaOlmos thanks for opening this issue and we're glad you're interested in being a Release Partner. To clarify, you don't have to be a Release Partner to use the latest versions of Carbon. Being a Release Partner means you're willing to collaborate with us to give us feedback on the latest releases; that's where the "partner" comes in. It seems like you're not interested in doing that, however, since you wrote `no` under `Are you interested in participating in a biweekly feedback sessions for the release?` Is this accurate?

**Comment by joshblack** [comment]
Hi there @BorjaOlmos! 👋 

Thanks for your interest in release partners. Unfortunately, this group is no longer accepting additional participants. You are still completely free to use the latest versions of v11 and provide feedback through the relevant discussions that we share in our blog posts.

Let me know if you need help getting started with that, thanks again for your time and interest here! We really appreciate it 🙏
