### ISSUE TITLE
Composed Modal with Tooltip: tooltip info sometimes visible after modal close

### ISSUE THREAD

**Issue by katherinelee703** [carbon-design-system/carbon#10931]
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.54.1

### Description

When rendering a `Tooltip` inside a `ComposedModal` there is unexpected behavior upon close.

Example:
If you click on the tooltip to display its information, but then do not click it again to close it and then proceed to close the modal (by clicking anywhere over the tooltip, not by clicking the 'x' button or pressing escape), the tooltip textbox will still be visible after the modal disappears. You will then have to click 1 more time outside the lingering tooltip message to make it go away. 

### CodeSandbox example

https://codesandbox.io/s/composed-modal-with-tooltip-possible-issue-n3gmhm?file=/src/index.js

### Steps to reproduce

- Click to show the full tooltip inside of the ComposedModal

![composed modal with tooltip](https://user-images.githubusercontent.com/58742933/157101482-03a579b6-ac21-4dff-8fcf-e5207fce2f2f.png)

- Click on the tooltip (the text, box, or arrow area)
  - the modal will disappear but leave the tooltip text still showing

![leftover tooltip](https://user-images.githubusercontent.com/58742933/157101328-7da64ef8-d55f-4a53-a6a8-369b52f702ac.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
Hey @katherinelee703 thanks for catching this bug and opening this issue! 🙏🏽 Can confirm I am also seeing the bug in your sandbox example. It only happens when I click on the open tooltip. If I open the tooltip and click anywhere else outside the modal, the tooltip closes along with the modal. It seems to think that the tooltip within the modal is outside the modal, my guess would be bc of where it's placed in the DOM, because when I use the prop `preventCloseOnClickOutside` that doesn't happen.

**Comment by tw15egan** [comment]
It seems like this is also solved in V10 by setting `data-floating-menu-container` on the `ModalBody` so that the `Tooltip` is rendered inside the `Modal`, rather than a child to `document.body`. This allows the proper close logic to apply, and not close the tooltip since it is inside of the `Modal`

[Here is an example](https://codesandbox.io/s/composed-modal-with-tooltip-possible-issue-forked-6fu2d7?file=/src/index.js), hope that helps! Going to close as resolved.
