### ISSUE TITLE
Address interactive token layering issues

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#10988]
Issue to track the implementation of the outcome decided in https://github.com/carbon-design-system/carbon/discussions/10871

**Comment by aagonzales** [comment]
I think we should go with option 3 for now and see how it plays out with teams. Since its just token values it will be easy to update later if needed. I think option 3 "works" because it at least keeps the IDL base and hover colors correctly assigned. I think if it becomes a larger issue for people we should look at updating the IDL palette instead of hacking the colors together like I did with option 1 (I think Mike A also mentioned this at one point too).

Option 3 also only requires updating two tokens in the _G90 theme_.

- `$layer-selected-03`: Gray 70 / `#525252`
- `$layer-selected-hover-03`: Gray 70 Hover / `#636363`
