### ISSUE TITLE
[Bug]: Pointer events on assistive text for icon-only buttons get in the way

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#11120]
### Package

carbon-components, carbon-components-svelte

### Browser

Chrome, Firefox, Edge

### Package version

v10.56.0 (via carbon-components-svelte)

### Description

When using icon buttons in tables, the tooltip popup can get in the way. Consider action icons at the end of a row:

![image](https://user-images.githubusercontent.com/834235/161030295-e5916655-f810-4627-85e1-1ebce4d7da59.png)

When hovering one of the buttons, the button in the adjacent row is almost completely obscured by the tooltip and the pointer events stop the cursor from interacting with the other button:

![image](https://user-images.githubusercontent.com/834235/161030635-41e624cd-7107-4c18-af38-f7197ca02f3d.png)

When creating a CodeSandbox example, I noticed that for the React library the description appears above, but the issue is the same:
![image](https://user-images.githubusercontent.com/834235/161033286-21fd6c28-3bc0-40e0-a77f-b2423f033ae4.png)

There appears to be a specific rule for icon only buttons that enables pointer events:

![image](https://user-images.githubusercontent.com/834235/161033975-56890584-7ca1-407e-b802-a5ead4db9976.png)

### CodeSandbox example

https://codesandbox.io/s/carbon-assistive-text-issue-9xc962?file=/src/index.js

### Steps to reproduce

- Add a table
- Add icon-only buttons with icon descriptions to every row
- Hover over one of the buttons and try to access the button underneath the tooltip in another row

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by brunnerh** [comment]
@abbeyhrt
> tooltips on buttons have to appear on hover to be accessible

The tooltips appear on hover without any issue, even without the tooltip itself having pointer events. I even overrode the offending CSS rule and testet the behavior with a screen reader: The tooltip is being read regardless.

The rule probably exists so clicking the tooltip will trigger the button, though one would probably have to look at the history to be sure.

**Comment by brunnerh** [comment]
(Placing the tooltip on the side would not help if multiple actions are available per row, it just shifts the problem elsewhere.)

**Comment by tay1orjones** [comment]
> The rule probably exists so clicking the tooltip will trigger the button

Hi @brunnerh, to follow up on Abbey's point, my understanding is the tooltips are given pointer events so that the tooltip remains visible when hovering on the button or the tooltip itself. This provides disabled users the ability to hover on the tooltip in addition to the button to aid in comprehension. Following the cursor with their eyes when reading, for instance. I think this is also required to facilitate interactions like copying/selecting the text within the tooltip.

The Tooltips are intentionally transient though and will be dismissed once the button and/or tooltip are no longer hovered/focused. Without the tooltip, this icon would have no visible descriptive element and fail accessibility requirements. Passing click events "through" the tooltip to the action behind it could be equally or more confusing. 

In the examples you shared I wonder if the actions within the row might be confused with the row expansion icons (if present), additionally for navigable actions it may be more appropriate to provide the user a formal `Link` instead of an icon button?

Let me know what you think. Overall I don't think we're too keen right now for these tooltips to be user configurable since it's so easy to run into these accessibility pitfalls.

**Comment by brunnerh** [comment]
@tay1orjones 

> Without the tooltip, this icon would have no visible descriptive element and fail accessibility requirements.

I am not advocating for the complete removal of the tooltips, that would make no sense.

> Passing click events "through" the tooltip to the action behind it could be equally or more confusing.

That is not what would happen if pointer events are removed, instead the tooltip would just disappear as soon as the button is no longer hovered.

> In the examples you shared I wonder if the actions within the row might be confused with the row expansion icons (if present), additionally for navigable actions it may be more appropriate to provide the user a formal `Link` instead of an icon button?

The expansion is on the left, and these action buttons will be on the right. A `Link` would work but icon buttons are used in the interest of saving space in the table. There may be other actions like editing or deleting:

![image](https://user-images.githubusercontent.com/834235/168884183-da665d77-139c-44d5-915f-f60dc0cc7594.png)

(Here all actions of the row below are almost completely blocked in this state.)

> This provides disabled users the ability to hover on the tooltip in addition to the button to aid in comprehension. Following the cursor with their eyes when reading, for instance.

This is the only valid reason for this behavior, though the default behavior for browser-native tooltips (via the `title` attribute) is to disappear as soon as the titled element is no longer hovered. So I am wondering if this is really necessary if even browsers do not behave like this.

It would be nice if there were a `@media` query that could be used to detect whether an eye tracker is used for input, then this behavior could be turned on conditionally, because as is, this *is* violating user expectations and a nuisance in this use case.

> I think this is also required to facilitate interactions like copying/selecting the text within the tooltip.

Selection within tooltips is disabled (at least in v10).

**Comment by tay1orjones** [comment]
@brunnerh I appreciate your thorough response, thanks! 

The interaction pattern established for these tooltips on icon buttons was part of a collaboration with IBMa and aims for a more accessible icon button. It's important to note that by comparison, `title` has inherent [accessibility issues](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns) and the [reason for a supplemental tooltip](https://inclusive-components.design/tooltips-toggletips/) is compelling.

In this case we're prioritizing the needs of someone with a disability to be able to hover on the tooltip and the tooltip not disappear.

The alternative you propose would be to instead prioritize the minor inconvenience of moving the mouse off of the tooltip for a moment so it can disappear and interact with a button behind the tooltip.

This might change with future WCAG requirements, but for now this is the status and works as intended.

**Comment by tay1orjones** [comment]
I also want to mention that we have made a slight change to this in v11. The button now uses a Popover, which has `pointer-events: none` on the popover container. The popover content still gets `pointer-events: auto` though.

In any case, if you have a use case that requires modification to this behavior, you can make the override to `pointer-events: none` in your application's styles.

**Comment by ErraticFox** [comment]
Kind of hilarious how HTML standards gives accessibility options to the developer, but it's not forced upon them (i.e. alt attr. for img tag) but here it's

1) Do it yourself through overriding CSS
2) Our way or the highway

Instead of just adding an option to not have it at all for specific use cases or adding an option just to have something like the alt attr. where it can still be read by accessibility but not show anything.
