### ISSUE TITLE
Move website deployment to github pages

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#11173]
#### Problem
Cloud Foundry continues to cause outages and degraded performance for [https://www.carbondesignsystem.com](https://www.carbondesignsystem.com)

#### Proposed solution
Migrate to Github pages [REF](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/workflows/deploy-canary.yml)

#### Alternative solution
From Joe: 

New theory: Normally when a 404 is hit, there's no error logged on the site, but under certain conditions, it looks like the actual underlying OS is doing an unsuccessful fopen, which results in an error because of a non-existent file.
I see that every time one of these requests is logged, the client and server addrs are always the same:
client: 10.247.123.201, server: localhost 10.247 would be an internal network, so I'm not sure where/how/why that request is coming from, but my best guess would be some internal process is hitting the app in an unexpected way every so often, leading to an outage because of some low-level file operation failures.

**Comment by tay1orjones** [comment]
I'm going to update this to be moving the deployment off cloudfoundry to github pages since we've all said it looks like a good path forward, ala https://github.com/carbon-design-system/carbon-website/pull/2871

https://carbon-design-system.github.io/carbon-website/

@joshblack it looks like some of the images aren't being pulled in?

Do we want to use subfolders and a rewrite/dns for the older versioned sites?

**Comment by joshblack** [comment]
Moved over to GitHub Pages today 🎉
