### ISSUE TITLE
Plex “fi” ligatures aren’t working

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#11175]
@alisonjoseph commented on [Mon Mar 28 2022](https://github.com/carbon-design-system/carbon-platform/issues/448)

Carbon Next
<img width="96" alt="Screen Shot 2022-03-28 at 1 01 38 PM" src="https://user-images.githubusercontent.com/2753488/160459216-4fb31f8b-9508-488a-b8c9-45fb3d6ea461.png">

Example of what should be happening from the Gatsby theme
<img width="98" alt="Screen Shot 2022-03-28 at 1 00 45 PM" src="https://user-images.githubusercontent.com/2753488/160459218-dce40498-149d-4a6d-8946-f4de62ec35b4.png">

_Note, this may be an issue coming from core Carbon_ 👀 

---

@mattrosno commented on [Mon Mar 28 2022](https://github.com/carbon-design-system/carbon-platform/issues/448#issuecomment-1080979886)

We didn't do anything custom for fonts; using Carbon v11 straight up. This is all happening for us with `@use '@carbon/react';` in `/styles/vendor/_carbon.scss`.

---

@mjabbink commented on [Wed Mar 30 2022](https://github.com/carbon-design-system/carbon-platform/issues/448#issuecomment-1083362680)

Probably core Carbon. I think the dotcom sites are not missing that as well.

---

@alisonjoseph commented on [Thu Mar 31 2022](https://github.com/carbon-design-system/carbon-platform/issues/448#issuecomment-1085355490)

Confirmed this is an issue coming from core Carbon

---

@mjabbink commented on [Thu Apr 07 2022](https://github.com/carbon-design-system/carbon-platform/issues/448#issuecomment-1092023697)

@alisonjoseph is there an issue made in core Carbon or should I make one?

**Comment by tay1orjones** [comment]
We should add some example text to the [elements preview](https://carbon-elements.netlify.app/type/examples/preview/) that can test for common/all ligatures.

**Comment by mjabbink** [comment]
FYI: The ligatures have been working for several years or more. Not sure what was done recently to remove the OpenType feature.

**Comment by mjabbink** [comment]
FYI: The ligatures have been working for several years or more. Not sure what was done recently to remove the OpenType feature.

**Comment by abbeyhrt** [comment]
@mjabbink I meant to update this a couple of days ago, sorry about that! I was able to narrow down the problem!. Ligatures are working in a general sense,  through the fonts that are delivered through the "complete" folder and through variable fonts which is what the gatsby theme is using,  but they are not available through the "split" folder because that layout feature isn't turned on. We export the "split" version because the "complete" and variable ones are just way too big for us to deliver by default.  I believe the next steps would be to get this addressed in `@ibm/plex`, as far as I know it should be pretty simple for them to include ligatures as a layout feature. Let me know if you have any questions!

**Comment by abbeyhrt** [comment]
More details about how we figured this out: 

I did some experimentation to recreate the problem and to see which fonts were impacted. I found that, in all fonts that I tested, the unicode for ligatures was available. So, for example, if you copied in the unicode for 'fi', it worked as expected.  However, for some fonts, notably the "split" font that we export, if you just typed "fi" (meaning not the unicode) it didn't automatically ligature the way we want it to. 

That led me to this site: https://wakamaifondue.com/ which always you to see all of the information about the font provided, including which layout features are available. 

Testing the `IBMPlexSans-Regular`, which is a "complete" one, you can see all of the layout features it provides, including ligatures 

You can see that here: 
![Screen Shot 2022-04-22 at 1 23 21 PM](https://user-images.githubusercontent.com/17281178/164772683-9876afc6-2b90-4842-9ced-b036051fec5a.png)

Now looking at the "split" one, `IBMPlexSans-Regular-Latin1`: 
![Screen Shot 2022-04-22 at 1 25 35 PM](https://user-images.githubusercontent.com/17281178/164772977-976b7926-7a71-44bf-9544-8acd556a9ed2.png)
 
You can see that the only layout feature it supports is kerning, so ligatures won't show up by default when typing since that is not an included layout feature. 

I would say that the solution needs to be addressed by `@ibm/plex` because there are many different ways for people to bring in plex and some ways, specifically the ways that are more performant, not supporting ligatures leads to an inconsistent use. Even casually browsing ibm.com you can find pages that ligature as expected and ones that don't, which obviously isn't ideal.

**Comment by tay1orjones** [comment]
@abbeyhrt @mjabbink should we create an issue for this in `@ibm/plex` and involve Bold Monday?

**Comment by tay1orjones** [comment]
Just as a follow up note, technically a workaround for this is that the unicode character is present in the font and can be used, but the font feature automatically converting `fi` to the ligature is not present.

**Comment by tay1orjones** [comment]
@abbeyhrt Yeah I think so, wouldn't hurt to open an issue.

**Comment by tay1orjones** [comment]
Got a PR up for the new plex release fixing this. Once it's in/published we'll need to

- [ ] update the version used in the repo
- [ ] update the akamai cdn version

**Comment by tay1orjones** [comment]
Tthe new Plex version is out with the fix. The Akamai server has been updated - assets containing the ligature fix can be used via the `$use-akamai-cdn` scss config variable.

I've opened a new issue to address a lingering problem with the plex dependency, https://github.com/carbon-design-system/carbon/issues/11661

**Comment by mjabbink** [comment]
Just catching up on this. Plex has always had ligatures but looks like you all solved this within the split files.
