### ISSUE TITLE
Dropdown with sub-categories Pattern Submission

### ISSUE THREAD

**Issue by TanB123** [carbon-design-system/carbon#11220]
Description: Menus with category labels Overview: 
There is already a pattern for menus with options that are grouped using lines. This pattern builds on that for the case where category labels are necessary to make scanning options easier. 

When To Use: 
• Only use this option if there is a reasonable number of options that makes categorizing necessary 
• Include a search field in the menu to make finding an option easier and faster 
• Sub-groups are optional 
• Avoid categories that have fewer than 3 options
<img width="219" alt="Screenshot 2022-04-13 at 12 02 59 PM" src="https://user-images.githubusercontent.com/96617414/163114469-087ce309-0496-489d-b30f-b45cf4c9ed18.png">
1.	Search bar 
2.	Category label: productive-heading-01 
3.     Category divider line: 1px line 
4. 	Sub-category divider line: 1px line, lighter color than the Category divider line

Anatomy

<img width="475" alt="Screenshot 2022-04-13 at 12 04 18 PM" src="https://user-images.githubusercontent.com/96617414/163114649-62287be2-c8db-4b58-88a8-4b62c45c2044.png">

<img width="476" alt="Screenshot 2022-04-13 at 12 04 47 PM" src="https://user-images.githubusercontent.com/96617414/163114724-f73799b3-429b-41de-b601-2bd660fc5afc.png">

Best practices:  
Use categories only when the list of options is too long. 
Use sub-categories when there are many options under categories and, to make scanning easier. 

Keyboard Accessibility:  
Users can tab through the checkbox and primary/secondary buttons. 
Up and down arrows activated once focus is inside the options area to navigate up or down. 
Option can be activated by clicking on enter/return.

**Comment by tay1orjones** [comment]
> There is already a pattern for menus with options that are grouped using lines.

@TanB123 could you provide a link to this? 

I think your goals outlined above might go beyond the use case of a typical Dropdown and may fall into the category of a custom component build using a [Popover](https://carbondesignsystem.com/components/popover/usage/).

**Comment by sstrubberg** [comment]
Hey @TanB123, i'm with @tay1orjones on this. Based on your use-case, I think you'd find a better experience using popover, rather than dropdown. If it's patterns you're looking to contribute, I couldn't tell if you were an IBMer or not. I was going to suggest coming to our design office hours to harden your specs. Let me know!

**Comment by laurenmrice** [comment]
Hey @TanB123  👋

Thanks for opening this proposal. Some of the stylistic patterns you are showing here for dropdown categories and setting/filter menus are part of our [Disclosure pattern](https://carbondesignsystem.com/patterns/disclosures-pattern/).

In our Disclosure pattern we show a couple different visual examples of potential layouts for these type of scenarios. We recommend to use the [Popover component](https://carbondesignsystem.com/components/popover/usage/) as the base when building these, especially if you have interactive elements (for accessibility reasons). 

Your specs do not always have to match our examples on the disclosure pattern exactly, because they can vary depending on the context and use case. As long as you are using our color, spacing, and type tokens and following our guidance, what you have illustrated above works well. However I would recommend that for the settings/filter menu that you use our `Large (48px) button`. 

I also think for your dropdown categories, that you could use `ui-03` for both section rules and sub section rules instead of using both border colors. Here is an example of an alternative you could use.

![Artboard](https://user-images.githubusercontent.com/43969356/183700498-33b59513-53e7-4865-9995-921300958a9d.png)
