### ISSUE TITLE
Codesandbox broken, can not fetch dependencies

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#11282]
When loading the `@carbon/react` codesandbox, you're shown an error

![image](https://user-images.githubusercontent.com/3360588/165124016-d0c69ac9-13c6-4c78-9987-471f0bab20bc.png)

This problem does appear to go away if you fork the sandbox, but can we fix it so the initial load doesn't have the error?

- [ ] Investigate and fix
- [ ] Ensure the same update, if needed, is provided to [@carbon/styles](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/examples/codesandbox-styles) sandbox
- [ ] Ensure the same update, if needed, is provided to [carbon-components-react](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/v10/packages/react/examples/codesandbox)
- [x] https://github.com/carbon-design-system/carbon-website/issues/2872

**Comment by joshblack** [comment]
Still can't figure out what's going on with this, a short-term fix could be to use Next.js as an example instead of CRA. There are some issues for this on codesandbox-client but none of them really seem to relate here.

The worst part of this is that the codesandbox will work if you save it / fork it which really makes it confusing as to why it doesn't work in the first place.

**Comment by tay1orjones** [comment]
https://github.com/codesandbox/codesandbox-client/issues/6443#issuecomment-1115103020
