### ISSUE TITLE
[Feature Request]: How to configure label at top of slider thumb

### ISSUE THREAD

**Issue by NEERAJ241196** [carbon-design-system/carbon#11297]
### Summary

In the existing slider carbon component, there is no feature by which we can add label at the top of slider thumb. As the styling are inherited from carbon core component i.e slider in this case , so this feature should be implemented.   

### Justification

User have to move the slider to adjust the bike price. As the slider moves, the label on top of slider thumb should also moves with the label indicating the bike price. 

![image](https://user-images.githubusercontent.com/79775575/165538444-ce7fd08b-6c32-4de0-a436-f32f85b208ab.png)

### Desired UX and success metrics

As soon as the user moves the slider thumb, the label appearing at the top of slider thumb should also moves along with. The value of label should change according to value of slider . 

### Specific timeline issues / requests

This is related to upcoming release. Deadline : 5th May 2022

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
hey @NEERAJ241196, thanks for the feature request. Our team reviewed your proposal today and we had some concerns around this feature, specifically around what the experience would be like for non-sight users. Also, we sort of already surface this need. Instead of the number hovering above the slider, it's off the right, as you can see on our [storybook](https://react.carbondesignsystem.com/?path=/story/components-slider--default). For these reason, we won't be pursuing at this time. Thanks again!
