### ISSUE TITLE
[Question]:

### ISSUE THREAD

**Issue by Petraki1** [carbon-design-system/carbon#11521]
### Question for Carbon

 Hallo, 
with v8 design system i created a lot of tables in my documents in drupal, where the first row and the first column need to be in dark gray. 
Currently in the carbon design i do not see any possibility to create such tables. 
Can you give me an advice how to create such tables?

Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by aledavila** [comment]
If I'm understanding correctly you want to change the color of the the data-table first row and first column. The data table already has the header row dark grey. You would need to create your own custom css file to implement those styles and target the first column to change the color of it. You could do so by targeting the first element of each row since they are grouped in rows. For example the first `td` of each row. 

<img width="331" alt="Screen Shot 2022-06-02 at 10 48 37 AM" src="https://user-images.githubusercontent.com/12533409/171669828-c937c489-5adc-4133-8a9e-2c7e70cecd96.png">

**Comment by Petraki1** [comment]
Thank you for suggestion. Since Im not very familiar with css files, could you give me an example of such file and a simple small table. So i can play around with this?

**Comment by joshblack** [comment]
bump @aledavila when you get a sec!

**Comment by sstrubberg** [comment]
Closing this issue as it's probably not the right forum for this discussion. @Petraki1 feel free to hit us up at [office hours](https://ibm.biz/carbon-dev-office-hours) or you can start this conversation up over in [discussions](https://github.com/carbon-design-system/carbon/discussions).
