### ISSUE TITLE
[Bug]: tree shaking no longer works for icon imports

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/carbon#11543]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.4.0

### React version

17.0.1

### Description

With the upgrade to Carbon 11 tree shaking no longer works on icon imports unless you import each icon from it's full path.

### Reproduction/example

https://github.com/tkolanko/carbon-bundle-issue 

### Steps to reproduce

I created a repo at https://github.com/tkolanko/carbon-bundle-issue showing the issue

To reproduce:

Clone the repo
move .env.example to .env
run npm i
run npm run build

This is a fork of the carbon tutorial repo but ejected from create-react-app so we can show bundle reports

There are two branches on this repo, here is what the bundle generates from `main`:

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/63593302/171697718-5d8250c3-2573-4db9-b463-1102e9dd2c39.png">

and another branch (https://github.com/tkolanko/carbon-bundle-issue/pull/1/files) with the full path imports

<img width="614" alt="image" src="https://user-images.githubusercontent.com/63593302/171697841-a08c67b8-f233-4c3f-9975-7866170bb9d6.png">

The code to reproduce this is very minimal:

```jsx
import React from 'react';
import {Add, Subtract} from '@carbon/react/icons'
import {IconButton} from '@carbon/react'


export const App = () => {
  return (
    <div>
      <IconButton kind="ghost" label="Add">
        <Add />
      </IconButton>
      <IconButton kind="ghost" label="Subtract">
        <Subtract />
      </IconButton>
    </div>
  );
}


export default App;
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by joshblack** [comment]
Hi there @tkolanko! 👋 Just wanted to say thanks for such a detailed issue, it's super helpful when debugging 🙏 

When looking at the repo you linked, it appears that the build script is not including Terser in the `optimization.minifier` section of the Webpack config. As a result, I believe that tree-shaking is not being applied because Terser is what is responsible for removing unused code (Webpack will only annotate code as unused, it does not perform tree-shaking directly).

When comparing a fresh create react app to what you had shared, I believe that is the difference and should help to reduce the bundle size / correctly tree shake icons.

**Current**

![image](https://user-images.githubusercontent.com/3901764/171915222-67484a4c-07f2-4da4-8154-f791ad049b4b.png)

**From a fresh create-react-app that's been ejected**

![image](https://user-images.githubusercontent.com/3901764/171915284-f398d3eb-403f-4fef-8364-01ec2a8290be.png)

Hope this helps! Let me know if you have any questions 😄

**Comment by tkolanko** [comment]
@joshblack thanks for looking but that's not it, I added terser in the latest commit (not sure what happened when I ejected) and the same problem exists https://github.com/tkolanko/carbon-bundle-issue

I found this problem in our product after upgrading to carbon 11 where we do have terser

**Comment by tkolanko** [comment]
@joshblack to make sure it wasn't related to the outdated version of create-react-app from the carbon tutorial I did the following:

Created a new react app
Downgraded to react 17
ejected
added the webpack bundle analzyer
created the same basic import of two icons from above

I was able to reproduce the problem, the repo is here https://github.com/tkolanko/carbon-bundle-v2

**Comment by joshblack** [comment]
@tkolanko can confirm, thanks! I went ahead and made: https://github.com/carbon-design-system/carbon/pull/11569 to try and mitigate this. When testing, it appears that the webpack/terser combo is not removing code with the shape:

```jsx
const ModuleName = /*#__PURE__*/ React.forwardRef(function ModuleName() {
  // ...
});

ModuleName.propTypes = {};
```

This makes sense, technically `propTypes` in this position is considered a side effect. On our end, we annotated the package with `sideEffects: false` but this does not seem to impact anything in this position.

We have a couple of options:

- Wrap `propTypes` in a dev check so that this assignment only happens in dev and not prod
- Wrap components in an IIFE, annotate this as `/*#__PURE__*/`, and return the component value in this expression
- Author a component generator function, like `GenIcon` which would return a valid component

The above PR takes the first approach as an interim approach, most likely we'll want to move to the last approach. The trade-off for this is a negligible runtime cost to initialize the components. This is the approach `react-icons` takes in its package
