### ISSUE TITLE
Carbon react icons increases bundle size when app is growing [Question]: 

### ISSUE THREAD

**Issue by hirantha-129** [carbon-design-system/carbon#11554]
### Question for Carbon

I am using Carbon react icons and pictograms for a project. But when we introduce new icons and pictograms, it increases the app bundle size accordingly. Roughly icon increases bundle size by 0.6 KBs and pictogram increases bundle size by 2KBs. My app bundle is already to 2.5 MB and I am worrying that Carbon icons would increase the bundle size to a large value in the long run.

Any solutions for this?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @hirantha-129! 👋 Just out of curiosity, what is expected behavior when adding new imports into your project?

From what I understand, as you include new imports from a package your bundle size will grow according to the size of the import. If you're noticing more than that coming in, definitely let us know! This may be a sign that tree-shaking is not working as intended. However, if it's growing proportional to what is being used then I believe that is working as intended.

Hope this helps, let me know if you have any questions or if I misunderstood anything!

**Comment by joshblack** [comment]
@hirantha-129 the package itself should support tree shaking! If you're using recent versions of this package, we also have a fix in to make sure this use-case works: https://github.com/carbon-design-system/carbon/pull/11569

However, tree shaking will only prune unused icons from your bundle. Each icon that you use should bring in the icon code itself (and no more). If this is still a challenge, let me know! Outside of supporting tree shaking I'm not sure what else we can do to help out. If you have ideas or suggestions I would definitely appreciate it!
