### ISSUE TITLE
tabindex does not get passed down to tab component

### ISSUE THREAD

**Issue by shaziajk** [carbon-design-system/carbon#11563]
Makes accessibility difficult for keyboard use only as you can not access the currently not selected tab with just the keyboard
In the clip below the second tab is still interactable with the mouse but as seen in the clip when using the keyboard it just gets tabbed over, this even happens when a tabIndex prop is provided and upon further inspection the tabIndex is not being passed down to the component.

https://user-images.githubusercontent.com/44590418/172196942-782e15a3-ad9b-41b1-9fc6-d3b84da0c9bc.mov

**Comment by joshblack** [comment]
Hi there @shaziajk! 👋 Tabs uses a roving tabindex pattern for navigation based on the W3C ARIA Practices examples: https://w3c.github.io/aria-practices/examples/tabs/tabs-automatic.html

Users are expected to navigate via arrow keys (Arrow Left, Arrow Right) instead of tabbing through the tabs themselves.

Hope this helps! Let me know if you have any follow-up questions or I misunderstood what you shared.

**Comment by shaziajk** [comment]
Hi @joshblack yep thats exactly what i needed thank you! Closing issue as its no longer an issue
