### ISSUE TITLE
[Feature Request]: Table with pagination

### ISSUE THREAD

**Issue by fabpico** [carbon-design-system/carbon#11604]
### Summary

Currently [table](https://carbondesignsystem.com/components/data-table/code) and [pagination](https://carbondesignsystem.com/components/pagination/code) are separate components. Combining both together with preserving built-in table features seem to be tricky, since some state is handled within the table component. Pagination state currently has to be handled outside of the table.

**Example**
Given I have 12 Rows. On paginate (custom state handling) I slice the rows to be rendered to maximum 10, so the table shows only 10 rows (after a force rerender, since incoming updated items won't update the rows).
When I sort a column (built-in state handling in the table component),
then not all 12 rows are considered but only the 10 rows since I sliced the rows prop from outside.

So to fix this unexpected behavior, I would have to build the entire table sort state handling by myself, outside of the table together with the pagination.

Is my conclusion correct or am I missing something?

So my request at the end is:
- If the table component provides built-in state handling which can't be controlled well, a fully functioning built-in pagination feature should also be provided ready-to-use.
- Items should be updatable without having to force-rerender.

There was already another similar issue which was closed without solution https://github.com/carbon-design-system/carbon/issues/6863 .

### Justification

Fast component usage. Reduce complexity. Clean state handling.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
He @fabpico thanks for submitting a feature request! Unfortunately, at this time, due to the complexity of your request, we won't be able to take it on as our backlog is already filled up for the next couple of quarters. If you're still passionate about your feature and would like to discuss further, you can always hit us up during our [office hours](https://ibm.biz/carbon-dev-office-hours) and we could explore alternative solutions as well as community driven work.
