### ISSUE TITLE
Experimental Component Feedback - UI Shell

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1167]
@tomlroach
4. UI Shell http://www.carbondesignsystem.com/experimental/ui-shell/code
The expanding left side panel on the UI shell has some unpleasant behaviour - when a user moves their mouse over one of the icons, the shell slides out, but also expands, which in many cases leaves the user hovering over a different area to the one they moved their mouse into. Perhaps a slower vertical transition could make the experience better, although I'm not sure that would be enough. I think the component has some issues. I think perhaps it ought to be a mouse over to initiate the horizontal slide, and then a click on a subtitle causes the vertical expand, rather than doing both in a single motion. 
![2018-10-04 09 39 54](https://user-images.githubusercontent.com/6569324/46481755-af604800-c7b9-11e8-9784-30461c452f7e.gif)

**Comment by aagonzales** [comment]
Yeah I think part of the problem is the side bar is not supposed to be shrinking upward and definitely makes it more jarring. I think this is a product of imbedded view port. 

Preview should look something more like this: 

![image](https://user-images.githubusercontent.com/11670886/46490477-b5602400-c7cd-11e8-9bf1-f00edd88074c.png)

**Comment by alisonjoseph** [comment]
Yes, ideally/eventually we will want a full view preview for this I think instead of squishing it into the component viewport.
