### ISSUE TITLE
[Bug]: SkeletonIcon's style prop allows for too much freedom

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11870]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.8.0

### Description

While working on building this component in Salesforce LWC, we noticed that the [Skeleton Icon](https://react.carbondesignsystem.com/?path=/docs/components-skeleton-skeletonicon--default) have a "Style" property that allows for any styling CSS-possible. This is unexpected because typically, the controls available are restricted to `width` or `height` as seen in other skeleton components. 

The freedom to add background image to a skeleton icon is not needed. Is this sudden lift of guardrails due to poor implementation / a mistake?

<img width="972" alt="image" src="https://user-images.githubusercontent.com/15144993/181303700-3dad5525-3aae-433f-993c-e48bb4082671.png">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-skeleton-skeletonicon--default

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/docs/components-skeleton-skeletonicon--default
2. Open inspect and select the element
3. Add any custom CSS style you wish

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
I believe all components allow a `style` prop, as it's built into React natively. I don't believe we want to stop allowing this, because the users would still be able to attach any styles they want by passing in a custom `className` prop, and adding the styles that way.  For now, I'll remove the `style` prop from the `PropDefinitions` so it isn't exposed as a first-class prop. Let me know if you need any more clarification Shixie!
