### ISSUE TITLE
[Bug]: Assorted bugs on Notifications

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#11890]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.8

### Description

1. When `kind = warning-alt` and `lowContrast = true`, the exclamation mark inside warning icon is not accessible. This applies to all variants of notification (toast, inline)
**Current**
<img width="326" alt="image" src="https://user-images.githubusercontent.com/15144993/182095380-f3c0b803-ff8c-4c13-b7cf-c45d7662df8c.png">

**Expecting** the exclamation mark to be filled with gray100 or black like in `warning`: 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/15144993/182095727-2140f3a3-0030-4ab4-9d4b-8cdbd36a61e8.png">

2. Keyboard focus doesn't work for `close` button on all variants of the Notification. Expecting a standard focus outline on the `close` button 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/15144993/182098784-56f1d1ec-3680-41da-8be9-710bb59cf594.png">

3. A line break in Inline notification between title and description is not expected: 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/15144993/182098742-799e5c24-d52a-4ad9-acd6-c6efca53c036.png">

When title text is long and wraps to 2 or more lines, the description drops to second line. Shouldn't the description continue after title on the same line? 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/15144993/182098405-da9fe1b0-e536-4407-8e35-561b9b51afc6.png">

4. Curious if there is a reason that "Actionable notification" is added as a variant? From what I can tell, "Actionable" is not a variant like `Toast` and `Inline`, which are different in form. "Actionable" is more like an attribute that can apply to both `Toast` and `Inline` forms. I think it would make more sense to remove "actionable" from `Variants` and represent it as an attribute/option or knob in storybook.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/15144993/182096893-792937f0-b809-443e-ae3d-c4cb455a1cad.png">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-notifications-actionable--playground&args=kind:warning-alt;lowContrast:true

### Steps to reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by abbeyhrt** [comment]
Hey @shixiedesign, thanks for detailing this! 

1.  The exclamation point should be black, we'll get that addressed!
2. That is intended and comes from a collaboration with IBMa. The idea here is that the close button is an affordance for sighted users because keyboard users don't need to dismiss the notification, they would just navigate away from it. It is breaking with the pattern of "all interactive items should be accessible" but as far as I'm aware, it's intended. 
3. As far as I can tell, there is no line break between the title and subtitle? I can't tell if your screenshot is supposed to be the as is or the intended. 
4. Design-wise, yes Actionable is visually just a variant of toast or inline but code-wise they are completely different components with different props and functionality that needed to be specifically configurable for `Actionable` and not the other variants. Dev-wise, it's not a great experience to have props that are dependent on other props being true and isn't something we wanted to do in v11.  That is why we chose to make it a separate component.
