### ISSUE TITLE
Breaking changes should be clearly called out in the release notes

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/carbon#11925]
`@carbon/react@1.9.0` introduces breaking changes to the `NumberInput` component. The PR https://github.com/carbon-design-system/carbon/pull/11804 removed the `imaginaryTarget` property that the previous version of NumberInput was using but made no mention of this change

**Comment by tay1orjones** [comment]
In this case it looks like we intended to ship this breaking change in the initial v11 release, but it was missed due to a misconfigured feature flag.

Sorry for the inconvenience and confusion on this, but the signature of the onChange event is slightly different now, though you can sill access the value to do what you did before.

The signature for onChange now looks like this:
onChange(event, {value, direction})

Related: https://github.com/carbon-design-system/carbon/issues/11926
