### ISSUE TITLE
Experimental Component - Number Input - Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1203]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
Starting this component today ^

**Comment by laurenmrice** [comment]
https://app.zenhub.com/workspace/o/ibm/carbon-components/issues/1210

**Comment by laurenmrice** [comment]
## Number input (Fixed)
Sketch file: https://ibm.ent.box.com/file/330629947005
![Screen Shot 2018-10-15 at 4.57.25 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/7bd8eb09-4ffc-4d73-8156-c36fe6368e6d)

**Comment by laurenmrice** [comment]
*Notes:
- Design added a bottom border line to number input to meet 3:1 accessibility ratio.
- Using Hover 10 color for hover state to be consistent with specs we did for text input, dropdowns, etc.
- Changed all carets to Gray 100 instead of Gray 70 to be consistent with Dropdown. Took off small color hover interaction around caret but keep cursor change. Kept all Focus states the same.


@IBM/carbon-developers ready for dev 👍
