### ISSUE TITLE
[Bug]: v11.* carbon-components not found on unpkg.com

### ISSUE THREAD

**Issue by arkadianriver** [carbon-design-system/carbon#12052]
### Package

carbon-components

### Browser

Chrome, Firefox

### Package version

v11.12

### React version

n/a

### Description

Was there an error during deployment of v11.12? Because unpkg.com is returning errors when attempting to access carbon-components Javascript and css files. In fact, for all v11, I can only find scss files when browsing unpkg. That's not expected is it?

Attempting to access: https://unpkg.com/carbon-components@11.12.0/scripts/carbon-components.min.js
results in: Cannot find "/scripts/carbon-components.min.js" in carbon-components@11.12.0

### Reproduction/example

see Description

### Steps to reproduce

See Description

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by arkadianriver** [comment]
The standard URL (https://unpkg.com/carbon-components/scripts/carbon-components.min.js) also attempts to redirect to 11.12.0, resulting in the error.

**Comment by andreisaikouski** [comment]
Also have this issue, affecting a production webpage

**Comment by NorthDecoder** [comment]
You can see an affected page at [https://vividventures.biz/random-password-generator/](https://vividventures.biz/random-password-generator/)

**Comment by tay1orjones** [comment]
@arkadianriver @andreisaikouski @NorthDecoder You should not be using unpkg links in production without specifying a version range. Unpkg resolves `https://unpkg.com/carbon-components/*` to the version corresponding to the `latest` tag.

For now I have reapplied the `latest` tag to `v10.x` instead of `v11.x`. Any non-versioned unpkg links should now resolve to `carbon-components@v10.x` again.

Appending `@10` to the package name will ensure unpkg resolves to the latest v10 version:

`https://unpkg.com/carbon-components@10/css/carbon-components.min.css`
`https://unpkg.com/carbon-components@10/scripts/carbon-components.min.js`
