### ISSUE TITLE
Experimental Component - Number Input - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1210]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by laurenmrice** [comment]
Design are ready: https://app.zenhub.com/workspace/o/ibm/carbon-components/issues/1203
Sketch file: https://ibm.ent.box.com/file/330629947005

@IBM/carbon-developers ready for dev 👍

*Notes
- Design added a bottom border line to number input to meet 3:1 accessibility ratio.
- Using Hover 10 color for hover state to be consistent with specs we did for text input, dropdowns, etc.
- Changed all carets to Gray 100 instead of Gray 70 to be consistent with Dropdown. Took off small color hover interaction around caret but keep cursor change. Kept all Focus states the same.
