### ISSUE TITLE
Experimental Component - Toggle - Development - add to website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1212]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [x] Add to carbon-components
- [x] Update website (add to the experimental section and update component status page)

**Comment by aledavila** [comment]
Waiting on design

**Comment by jeanservaas** [comment]
Hey @aledavila, i assigned you to this just because you asked for it earlier. 

Again, security handled this component a little differently that the Duo specs, so I wouldn't bother trying to repurpose their component. I attached the specs... there's also an animation element to this component and I included the cubic-bezier specs for that too.

[Toggle.zip](https://github.com/IBM/carbon-components/files/2470863/Toggle.zip)

**Comment by aledavila** [comment]
Thanks @jeanservaas

**Comment by alisonjoseph** [comment]
I had some questions around colors being used for the toggle. You have the background color as `gray-30`, but the only place we are using that anywhere else so far is as a disabled color. Would it make more sense to have it as gray-20 which is also mapped to `ui-03` currently? Or should we create a new `ui-05` color for gray-30?

@aagonzales @jeanservaas

**Comment by alisonjoseph** [comment]
re-opening to add to website
