### ISSUE TITLE
[Bug]: Checkbox not clickable

### ISSUE THREAD

**Issue by GeorgeLolos** [carbon-design-system/carbon#12144]
### Package

@carbon/react

### Browser

Chrome

### Package version

v105.0.5195.125

### React version

v18.2.0

### Description

The checkbox is not clickable, and it doesn't change its state.

I believe the reason is that the input for the checkbox has an absolute position and a very small size, and the clicking event does not propagate to the input element.

### Reproduction/example

https://stackblitz.com/edit/github-hh6dvn?file=src/App.jsx

### Steps to reproduce

1. Import the Checkbox component
2. Create a state handler
3. Click the checkbox

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there, @GeorgeLolos it looks like there were a few issues that may have been contributing to the issue. The `id` prop is marked as required, so that was causing the click issues. Adding an `id` seemed to resolve that. If you are controlling the state yourself, you'd need a `handleCheck` function to toggle the `checked` state, here is an example: https://stackblitz.com/edit/github-hh6dvn-zf7v7y?file=src%2FApp.jsx

If you want it checked by default and want the `Checkbox` to handle the state itself, you can use the `defaultChecked` prop.

I hope this helps, I'm going to close this but feel free to comment if you are still running into issues

**Comment by GeorgeLolos** [comment]
Hi @tw15egan and thanks!
I have an id, but I guess it resolves to undefined because it's an empty string and that doesn't work. Is that because the label needs an anchor to the input? Or what's the reasoning behind the need for the id?

Thanks for taking the time to help!

**Comment by tw15egan** [comment]
The `id`  is required for accessibility reasons. The `label` element needs a `for` attribute, which is supposed to reference the `input` element` The `for` attribute is auto-populated by us based on the user provided `id`. Without it, screen readers and other assistive technologies would have trouble parsing the HTML structure and not be able to provide necessary assistance. Hope that helps clear it up!

**Comment by GeorgeLolos** [comment]
It does. Thank you!
