### ISSUE TITLE
[Bug]: Popover doesn't overlay nearby components that create new stacking contexts

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#12142]
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

1.13.0

### React version

17.0.2

### Description

When placing elements and components that create a stacking context (for example anything with `position: relative`) near a Popover, the PopoverContent doesn't overlay those elements and components.

### Reproduction/example

https://stackblitz.com/edit/github-ghmbz9?file=src%2FApp.jsx

### Steps to reproduce

Example:
1. Place a `<Button>` near a `<Popover>`
2. Open the Popover

<img width="192" alt="image" src="https://user-images.githubusercontent.com/28265588/191915487-d528fc43-b94a-41fe-91fe-7b015b0602a7.png">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/28265588/191915513-aad75f6d-5f5c-4d10-9ccb-a3601a618d6e.png">

```jsx
<Popover open={open}>
  <button
    onClick={() => {
      setOpen(!open);
    }}
  >
    Toggle popover
  </button>
  <PopoverContent>
    <div style={{ padding: '1.5rem' }}>Popover content</div>
  </PopoverContent>
</Popover>
<br />
<Button kind="ghost">Button</Button>
<div>position: static</div>
<div style={{ position: 'relative' }}>position: relative</div
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
This one's challenging. Popover doesn't use a portal because we wanted to avoid the accessibility headache. I can't think of an immediate fix here other than to avoid this scenario (not great, I know).

Even placing `isolation: isolate` on the containing element doesn't help because even when these elements are on the same stacking context, a new one is created by the elements with `position: relative` or [any other property that creates a new stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context#the_stacking_context).

Definitely open to suggestions on this one.

**Comment by tay1orjones** [comment]
More on why we avoided a portal here: https://github.com/facebook/react/issues/24987

**Comment by tay1orjones** [comment]
@janhassel Yes, sorry I forgot to remove the auto-close on #12786 

The last piece to address here is that when two or more popovers are placed adjacent to one another (vertically or horizontally), a popover content (when open) does not properly overlay the other popovers.
