### ISSUE TITLE
[Bug]: Pagination shows redundant information when `pagesUnknown` is set to true.

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon#12252]
### Package

@carbon/react, carbon-components-react

### Browser

Chrome, Firefox, Edge

### Package version

v1.14

### Description

In pagination component, when `pagesUnknown` prop has been set to `true`, the page number is shown twice. 

e.g.
1 page 1
If I change the page number via `select`, the page number also updates as such:
2 page 2
3 page 3
...etc,

The first number is the page option selected from the select element. Then the same information is repeated in the following text.
Shouldn't it just be `Page <select element with number>` [TEXT (SELECT ELEMENT)]? Is there a reason for repeating the page number?  
  
I'm not sure if this counts as a design defect, but this issue was raised in [Carbon Angular](https://github.com/IBM/carbon-components-angular/issues/2199), just forwarding it here so we know what steps to take.

### Screenshots

![image](https://user-images.githubusercontent.com/38994122/194210271-a53bd206-62fa-4cd8-bc5b-270c101970ca.png)
![image](https://user-images.githubusercontent.com/38994122/194210685-292b4b76-9b1f-40ec-85c1-b8528450b132.png)
![image](https://user-images.githubusercontent.com/38994122/194210637-ce777b2e-29ff-4cb9-acf8-c951d9b5e50c.png)

### Steps to reproduce

Go to the following storybook (props have been already set, so no changes required):

https://react.carbondesignsystem.com/?path=/story/components-pagination--default&args=pagesUnknown:true

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Also posted in #12302 

I think this can be fixed just by passing down ` pageText={() => ''}` to the `Pagination` component as-is. It seems like there is a slight styling issue in this scenario, but can be fixed by just adding the following CSS to `_pagination.scss`

```scss
.#{$prefix}--pagination__right .#{$prefix}--pagination__text:empty {
    margin: 0;
}

**Comment by tw15egan** [comment]
If we still want to keep the `page` text, we could modify the `pageText` default function, but it could still be overridden if anyone is passing in their own translation strings via `pageText`.

```js
    pageText = (page) => {
      return `page  ${pagesUnknown ? '' : page}`;
    },
```

We would then add two opposite ternary renders inside `pagination__right` like so:

Before the `Select`
```jsx
        {pagesUnknown ? null : (
          <span className={`${prefix}--pagination__text`}>
            {pagesUnknown ? pageText(page) : pageRangeText(page, totalPages)}
          </span>
        )}
```
After the `Select`
```jsx
{pagesUnknown ? (
          <span className={`${prefix}--pagination__text`}>
            {pagesUnknown ? pageText(page) : pageRangeText(page, totalPages)}
          </span>
        ) : null}
```

Which gets us.
<img width="263" alt="Screen Shot 2022-10-14 at 10 39 39 AM" src="https://user-images.githubusercontent.com/11928039/195874027-ce2773b0-eb14-46b4-9de0-9c14077e168b.png">

Would probably need to do some style adjustments as well to get the text inside of the border instead of outside to the left

**Comment by 61130061** [comment]
@tw15egan 

Add two opposite ternary renders inside `pagination__right` work for me. 

About border, I already moved `border-left` from `selector` to `pagination__right` div which also work with code you suggested as well.

which gets us.
![Screen Shot 2565-10-14 at 22 24 19](https://user-images.githubusercontent.com/54393468/195883521-b2a96641-8531-4a2a-bd3c-b3083bcbca06.png)
![Screen Shot 2565-10-14 at 22 24 26](https://user-images.githubusercontent.com/54393468/195883535-0e750358-69c7-4909-8231-9f6ec91e17a0.png)


However, would be better if we use `label` tag instead of `span`? which is similar to `ItemPerPageText`, so user can click on the `pageText` to focus on the `selector`.

**Comment by 61130061** [comment]
@tw15egan

Like this.
```js
{pagesUnknown ? (
  <label
    id={`${prefix}-pagination-select-${inputId}-right-label`}
    className={`${prefix}--pagination__text ${prefix}--pagination__page-text`}
    htmlFor={`${prefix}-pagination-select-${inputId}-right`}>
    {pagesUnknown ? pageText(page) : pageRangeText(page, totalPages)}
  </label>
) : null}
```

Just wonder. If you prefer `span`, I will go for it.

**Comment by tw15egan** [comment]
@61130061 I believe we already have a hidden label for the `select`, so I'd just keep it a `span` to avoid redundant screenreader text.

Your examples look great 👍🏻

**Comment by 61130061** [comment]
@tw15egan All done! Thanks for your suggestions. 🙏🏻

**Comment by hudlow** [comment]
I'm confused. How do you populate the dropdown if the number of pages is unknown?
