### ISSUE TITLE
[Bug]: Overflow menu is cutted

### ISSUE THREAD

**Issue by mateBe95** [carbon-design-system/carbon#12362]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

10.54.0

### React version

16.2.0

### Description

https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default&args=size:lg

When user open overflow menu component, the left sidenav is covering overflowmenu. I have the similar case with my sidenav. Is any solution to not cover the menu (z-index doesn't work). Would be nice to hace always overflow menu on the top.

__

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default&args=size:lg

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default&args=size:lg

1. Set large overflow menu.
2. Open.
3. You will see >
![1FA482F1-2E32-4D29-A16D-4EF209F0F781](https://user-images.githubusercontent.com/23103157/197189536-b5607305-e02a-4850-a306-5a9ad17657e0.jpeg)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@mateBe95 This happens in the storybook because the story is rendered within an iframe. There's nothing we can do there to get it out from behind the storybook sidenav other than reposition how much padding there is on the story so it renders further from the edge.

If this is happening in your application, you're probably dealing with conflicting [stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). This would be why a z-index change doesn't help. You'll have to inspect the structure of the DOM in your app to attempt to resolve it. 

The most robust way to avoid this issue though is to properly set `menuOffset` or `menuOffsetFlip` props so that the element does not render behind the sidenav.

Hope this helps!

**Comment by mateBe95** [comment]
props `menuOffsetFlip: {{left: 5}}`
it really helps.
Thank you @tay1orjones
