### ISSUE TITLE
[Question]: Vanilla JavaScript support question?

### ISSUE THREAD

**Issue by luizas** [carbon-design-system/carbon#12361]
### Question for Carbon

We are on Carbon 10.56  (SPM-Components) right now but we want to move to v11. We have are own implementation of Carbon Modal where we are using Vanilla JavaScript. Could you tell me what option we have now to make our Modals work? 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hi @luizas! In v11, `carbon-components` is now a proxy of `@carbon/styles` and no longer ships vanilla JS code. If you're relying on this vanilla js, that code is no longer available through `carbon-components@11.x` (and also therefore `@carbon/styles@1.x`). The vanilla JS implementation/project has moved to a community-maintained status, but there has not been interest from a team yet to take this on and update it to v11. If you're interested in taking this on, let me know.

If you're _not_ relying on that code at all from the package, and instead have your own totally independent implementation of modals written in vanilla JS, you can now get all the new v11 styles from `@carbon/styles` instead of `carbon-components`. Your existing implementation might not need much change beyond modifying the classname prefix from `.bx--` to `.cds--`.

We've seen many teams using vanilla JS looking towards moving to [`carbon-web-components`](https://github.com/carbon-design-system/carbon-web-components). It's a natural segue for most teams using vanilla JS. It might be an alternative path to v11 for your project. The team is working on updating the web components to v11 right now.
