### ISSUE TITLE
Experimental Component - Tabs - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1241]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
https://github.com/IBM/carbon-components/issues/1293

**Comment by jeanservaas** [comment]
## Tabs

Sketch File: https://ibm.box.com/s/polgkcgh8ypvi1pkttmieubulzja9jqj
- Because this version of the tabs is closer to the current Carbon component; we're going to start with this and then do the version with the background and boarders.
- Security has this component, but the tabs are smaller, the copy is centered and there's a lot of space between each tab when they're grouped; our version is left aligned and matches the DL design
- Made specs for Tab variation for future release.

![tabs_light_theme_1](https://user-images.githubusercontent.com/43144260/47385455-a7683980-d6cf-11e8-897e-ed45594ccd20.png)
![tabs_specs_1](https://user-images.githubusercontent.com/43144260/47385456-a7683980-d6cf-11e8-8d4c-f9119d51b947.png)
