### ISSUE TITLE
Experimental Component - Pagination - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1251]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- Security looks like they are using the Carbon pagination component still.
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## Pagination

Sketch file: https://ibm.box.com/s/2okdoruxty50zrhu14hxwy3x9op51ubx
- Instead of stylized dropdown we are using select dropdowns. This was used in Carbon before, and Select component was not built in Duo originally.
- Specd the pagination to Gray 10, however it could also be White in the White theme.

![Pagination_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/7320ad6c-6110-430e-80ef-6c2323c62701)
![Pagination_Light_Theme_White_Specs.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/cb203333-f691-4e87-9ff5-ee75efe27d7a)

**Comment by laurenmrice** [comment]
Ready for dev ✅ : #1304
