### ISSUE TITLE
Experimental Component - Progress Indicator - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1252]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## Progress Indicator
Sketch file: https://ibm.box.com/s/sa6ertotoju480evtur8cid926jcz9q8

- Omitted semibold text for current step because that is not a consistent pattern with the rest of Duo component styles.
- Incomplete step icons are Gray 100 instead of Blue 60.
- Focus state changed to match and stay consistent with focus on all other components.
- Using full length of section bar instead of indicating progress increments.

![Progress Indicator_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/dd78f4c6-354c-4145-8e72-0e87d157486b)
![Progress Indicator_Light_Theme_Specs.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/3b13e568-84fa-4ce0-9f68-6987f9bc4025)

**Comment by laurenmrice** [comment]
Ready for dev ✅ @IBM/carbon-developers
Dev issue: #1300
