### ISSUE TITLE
Experimental Component - Content Switcher - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1253]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## Content Switcher

Sketch File: https://ibm.box.com/s/osmvf7zqm6c3vxmv5euhqqmwvbf46fsx
- Omitted radius rounded edges of component.
- Omitted full border to align with other design decisions we have made for Carbon.
- Changed focus border to inside instead of center (I think it was a mistake in duo file)
- Made specs for Icon variation for future release.
![Content Switcher_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/1a34d83c-7b53-4c14-95f2-bd340bb569e0)
![Conetent Switcher_Specs.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/708b3b79-830c-4476-b649-fbb89c9ac58a)

**Comment by laurenmrice** [comment]
Ready for dev ✅ @IBM/carbon-developers
Dev issue: #1294
