### ISSUE TITLE
Experimental Component - File Uploader - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1255]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [x] confirm Security design matches duo intent
- [x] confirm Sketch file sizing/spacing specs
- [x] screen grab sizing guidance and add to GitHub issue

**Comment by laurenmrice** [comment]
## File Uploader
Sketch file: https://ibm.box.com/s/jvywa1198xk4lrwri8oe64qtg2wtbc8d
- Omitted outer border to be consistent with other patterns
- Gray 100 icons instead of Gray 70
- Cursor change on hover only
- Updated error pattern to be consistent with other error treatments and disabled text
![File Uploader_Light_Theme_White.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/bc688423-b082-4f06-9303-01488da1cdfe)
![File Uploader_Light_Theme_White_Specs.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/195a6b80-4bdd-450c-bd50-bf4a299cd545)

**Comment by laurenmrice** [comment]
Ready for dev ✅ @IBM/carbon-developers
Dev issue: #1296
