### ISSUE TITLE
Add TypeScript types to ToggleSmallSkeleton

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#12566]

**Comment by waldothedeveloper** [comment]
Hi there @tay1orjones, I'm taking this one home...will bring it back in Typescript :)

**Comment by S-Mann** [comment]
I think since this https://github.com/carbon-design-system/carbon/issues/12565 issue was closed and it already defines the skeleton for the `ToggleSkeleton` component there shouldn't be a separate `ToggleSmallSkeleton` component since **carbon-design-system** doesn't have a separate `Toggle` component for each `size`.
