### ISSUE TITLE
Make expand-collapse column in Data Table fixed width, to avoid jiggle

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon#1260]
### Summary

The Data Table component jiggles when you expand and collapse a row inside it, because the expand-collapse arrow changes width when it is rotated by 90 degrees. We recommend giving the expand-collapse-arrow column a fixed width, so the table doesn't jiggle when expanded. 

This is a design & dev item.

### Justification

Movement of the table when expanding a row draws unnecessary attention to the table itself, when the area the user is concerned with is the expanded state of the row.

### Extra stuff

This effect occurs on the carbon website (https://www.carbondesignsystem.com/components/data-table/code) as well as in production.

**Comment by aledavila** [comment]
Hi thanks for reporting this. It does seem like a bug to me. The fix looks simple and works well. I'd like to see what other devs think. 

@IBM/carbon-developers The added widths to all of the rows when expanding seems unintentional to me. On first inspection adding a max-width to only that column prevents the whole row from expanding. Was the jiggle intentional or can we add this fix?

**Comment by alisonjoseph** [comment]
It seems that it might also be dependant on the content inside the expanded table view? 

I agree on adding a width/height to the button arrow though.
