### ISSUE TITLE
[Bug]: Data table content inside cells should top align when with text wrap in some cells  

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#12610]
### Package

@carbon/styles

### Package version

Latest

### Description

Currently, when some cells' content wrap to 2 lines, the text alignment is middle/center aligned.
Expecting all the content to top align:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/15144993/201662983-86dfff79-4abf-43ac-8418-bfdf2802311c.png">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--default

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--default
2. Narrow down browser width to see text wrapping and alignment bug

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by shixiedesign** [comment]
Hey @sstrubberg or @tay1orjones, checking to see if this is getting prioritized. I believe a lot of products will benefit from this alignment fix just because data table is used everywhere. Thank you so much!

**Comment by tay1orjones** [comment]
Hi @shixiedesign - Yes, with it classified as a Severity 3 it's a bit lower on our priority list compared to [all the Severity 2 issues we have](https://github.com/carbon-design-system/carbon/issues?q=is%3Aopen+is%3Aissue+label%3A%22severity%3A+2%22).

The fastest way to get this fix made would be through a contribution from your team.

In the meantime, it should be possible to force this alignment in your project by targeting the table cells with custom styling for `vertical-align` or perhaps `align-items` in a flex container.

**Comment by jsehull** [comment]
Alright, so working on this fix opened up a GIANT can of worms with cascading impact on other table elements and got complex and ugly. After talking with Alison, I wanted to document some findings so we can be aware of potential considerations for future fixes.
_____
**A few takeaways:**

Almost Good: We can fix the wrap for multi lines (`vertical-align: top`)
![Example](https://user-images.githubusercontent.com/9935383/219698115-c64eebad-96cb-48fc-b37c-77a8ce0df85c.png)

Bad: this fix makes the rows bleh when not wrapping
![Pasted Graphic 4](https://user-images.githubusercontent.com/9935383/219698149-6c325591-b24e-4025-9997-66bb23939e10.png)

False positive fix: Add padding above and below the cell (i.e. `1rem`) to create a more ‘centered’ text when not wrapping
- This does NOT work due to negatively impacting the users `size` settings on the table itself

**Other elements impacted** (checkboxes, overflow menus, expansion, others?)
- if we do pursue an alignment option, it WILL have downstream impact on other row items listed here.
- we would need confirmations on design change and possible feature impacts

Checkboxes
- IF we go with the above solution, we would need to center the checkboxes or decide where they should align, otherwise they look like the bottom area with lots of white space
![Protocol](https://user-images.githubusercontent.com/9935383/219698216-0cde8315-c687-414c-88d0-160eb7430bee.png)


Overflow menus
- Same as above, where do we try to align this to match text/other elements? (I’ve spent so much time on this that finding a way to center this wasn’t worth it for the picture 😆)
![Protocol Port](https://user-images.githubusercontent.com/9935383/219698340-33986918-6153-4a0e-aaf2-51408a0c74aa.png)

Expansion carrot buttons
- Not impacted by the vertical alignment (because they are buttons and have other classes?), so this may be okay!
![Protocol](https://user-images.githubusercontent.com/9935383/219698378-53e59cda-e5d0-45ac-9f7b-7fe774f85419.png)


**Other notes**
- Flexbox: this immediately changed many things and would potentially require reworking LOTS of features.
- Adding a new overflow scroll feature
  - use “static height” on the row so that there is no wrap + overflow scrolling
  - While I am a fan of the feature and it could be a “fix” for the above, it’s possible others may want a paragraph of text that DOES wrap and does NOT have a static height.
  - Does this bring up the designed intention of the table in the first place in what the table should and should not be able to do?
  - (image below from DaisyUI)
![Cy Ganderton](https://user-images.githubusercontent.com/9935383/219698759-0cbd039d-0423-446f-afaf-4ab7fe05b46d.png)

**Comment by sstrubberg** [comment]
@jsehull: Do you have the invite for our [Office Hours](https://ec.yourlearning.ibm.com/w3/event/10322733)? Based on the complexity of the problem you're trying to solve, this would be a great conversation to have with our devs on a call rather than spilling all over GH ;)

**Comment by jsehull** [comment]
@sstrubberg yup, I'll try to bring this issue up then

**Comment by mjabbink** [comment]
Perfecto. Gotta solve it cause here’s another example along with the ones from Master @shixiedesign. It’s hard on the eyeballs.

<img width="1282" alt="Screenshot 2023-03-30 at 3 29 29 PM" src="https://user-images.githubusercontent.com/32881239/229942078-1c4f5b19-3d4e-4218-94dd-05abdd0d7433.png">
