### ISSUE TITLE
[Bug]: Page jumps when modal opened/closed

### ISSUE THREAD

**Issue by tomfletch** [carbon-design-system/carbon#12705]
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.57.1

### React version

18.2.0

### Description

When launching a modal, the page behind the modal shifts to the right because the scrollbar disappears.
This is happening on Mac with show scrollbars 'Always' or 'Automatically based on mouse or trackpad' when using a mouse.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Reproduction/example

https://carbondesignsystem.com/components/modal/usage/

### Steps to reproduce

Click on Launch modal on the demo at https://carbondesignsystem.com/components/modal/usage/
Watch the page in the background shift as the scrollbar disappears

This is closely related to https://github.com/carbon-design-system/carbon/issues/4435
However, in this bug the modal does not jump, just the page behind the modal

https://user-images.githubusercontent.com/4648196/203048400-fbf21b31-9dbd-4c1f-8124-a1450701642a.mov

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Thanks for reporting this @ThomasMatthewFletcher. This happens because the page content is scrollable and when the modal appears, focus is moved to it, and the modal does not overflow the container/page. 

If you're seeing this in an application and would prefer the scrollbar to remain, you can set `overflow-x: scroll` or `overflow-y: scroll` on the modal container to ensure the scrollbar always stays visible. This will prevent the flicker/shift you see on our website.

We can't assume this behavior for the entire system though. We instead respect the browsers interpretation of providing scrollbars or not based on content overflow in most/all cases. For this reason we won't be adding `overflow-x: scroll` to the modal by default. Thanks again for bringing this up though!
