### ISSUE TITLE
[Bug]: Width of the Inline FilterableMultiSelect dropdown truncates texts

### ISSUE THREAD

**Issue by aechvz** [carbon-design-system/carbon#12744]
### Package

carbon-components-react

### Package version

v7.59.5

### React version

v17.0.2

### Description

The width of `Inline FilterableMultiSelect` dropdown is narrower compared to other dropdown widths like `Inline Dropdown`. Also, the width size does not change depending on the selected content.
This truncates the dropdown option texts and the issue is more prevalent in translated versions of the app.

Unselected option
<img width="477" alt="multiselect (1)" src="https://user-images.githubusercontent.com/119436467/204619714-0948dd85-efba-414e-a0d8-98ba707a10fc.png">

Multiple items selected
<img width="420" alt="Screen Shot 2022-11-22 at 5 09 41 PM" src="https://user-images.githubusercontent.com/119436467/204619716-ec41d914-2770-4240-82e7-ea9ce0a48927.png">

Storybook demo for `Multiselect default` and changing the UI Type to `Inline`
<img width="1252" alt="Screen Shot 2022-11-22 at 5 27 08 PM" src="https://user-images.githubusercontent.com/119436467/204619718-8016de74-8136-415a-9c16-d13b127d0f2e.png">

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://v7-react.carbondesignsystem.com/?path=/story/components-multiselect--default

### Steps to reproduce

Click on the link for Carbon's Storybook [Multiselect - default](https://v7-react.carbondesignsystem.com/?path=/story/components-multiselect--default) component
Select Knobs tab
Scroll down to the `UI type (Only for '<MultiSelect>') (type)` field
Select the` Inline` option
See that `'An example option...'` is truncated. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sstrubberg** [comment]
Notes from our Backlog cleaning today:

- Need to jam with design on how wide this can go. Possibile implications here.
- A consumer can change the CSS of Listbox to what they need, effectively making this a sev3 (if this was treated as a bug)
- Underlying need (as we are interpreting the request): "If something is really long, I don't want truncation"
- Devs: "This could get really messy."
- What is the issue with the truncated text? What's the purpose of this enhancement?
- Why not design filterablemultiselect to be wider?

Due to the nature of this request and our discussion today, while we see value in this idea, we won't be able to dedicate resources to it anytime soon. Would be happy to entertain further design exploration or prototypes in code if the community finds value in this exploration.

Thanks for the request!
