### ISSUE TITLE
[Feature Request]:  Datepicker - better documentation and example

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon#12841]
### The problem

Hi, the datepicker has a bad documentation and examples. There is no examples of ow to read the values in a forms with a validator like Formik.

### The solution
```
 <DatePicker
                      dateFormat="d/m/Y"
                      datePickerType="single"
                      size="md"
                      locale="it"
                      value={this.state.datacollaudo5anni}
                      onChange={(e) => {
                        values.datacollaudo5anni = e;
                      }}
                      id="datacollaudo5annifield"
                    >
                      <DatePickerInput
                        labelText="Data Collaudo 5 Anni"
                        placeholder="dd/mm/yyyy"
                        size="md"
                        id="datacollaudo5anni"
                        name="datacollaudo5anni"
                     
                      />
```

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
hey @biapar thanks for submitting this feature request. I'm a bit confused by the problem and solution you have outlined. Would be you open to revising your ask so we can better triage your issue? Thanks! I'll re-open when it's been updated :)

**Comment by biapar** [comment]
Hi. It's a bit difficult to understand how to read the picked date using only the component documentation and the examples into the storybook. I'm using Carbon to build our internal software. My solution is to solve the problem If you put a date picker into a form and using FORMIK to manage the form. I was not able to read data also without Formik.
 I made a lot of trials before I'm able to read data from date picker.

**Comment by jdharvey-ibm** [comment]
@sstrubberg To roughly summarize what we talked about in Slack:

- The events provided by the `DatePicker` via `onChange` / `onClose` / etc. are not full-blown DOM Events; they look to be arrays of `Date` objects.

- The forwarded `ref` of the `DatePicker` is `<div class="cds--form-item">…</div>` and not an HTML input field or other form element.

@biapar I'm not familiar with Formik, but I gave it a look and fiddled around with it for a while. I pretty much concluded the same thing as you did in your solution above. If you use React's two-way-binding, you can control the value of the `DatePicker` directly and manage it in your component's local state.

From what I can tell, this two-way-binding approach won't let you directly use the `Field` component from Formik or attach its `handleChange` callback directly to the DatePicker, but it will give you access to the current value of the picker since you're using the component in a "managed" way.

One idea as far as hooking this up to Formik's validation would be to create a hidden `input` element of type "date", and set its value to the same `this.state.datacollaudo5anni` you're using for the `DatePicker`, and then attaching Formik's `handleChange` to that element. It's not a perfect solution by any means, but it should be doable with how Carbon works today.

@sstrubberg Perhaps what we could do as an action item from this issue is to add an example of using DatePicker as a "managed" component? Right now all of the examples look to be using it "unmanaged". But we might also need to check with the dev team to see if the `value` prop is intended for use on more than just the first render. Currently the docs don't say that:

> By default DatePicker will set the current date as its value. If you'd like to start this at a different date, you can pass in a date string or date object.

https://react.carbondesignsystem.com/?path=/docs/components-datepicker--simple#datepicker-value

**Comment by tay1orjones** [comment]
Here's an example of DatePicker being fully controlled by a custom state handler. 

https://stackblitz.com/edit/github-pzlus6?file=src%2FApp.jsx

**Comment by tay1orjones** [comment]
> (is) the value prop is intended for use on more than just the first render

@jdharvey-ibm Yes. Any input component with a `value` prop is intended to be able to be controlled. For some components we offer `defaultValue` or `initial*` for the first render if consumers would prefer to leave the input uncontrolled.

Here's an example from NumberInput

https://github.com/carbon-design-system/carbon/blob/54268796d91ac9349518b3a517a6792c95e2193f/packages/react/src/components/NumberInput/NumberInput.js#L292-L295

https://github.com/carbon-design-system/carbon/blob/54268796d91ac9349518b3a517a6792c95e2193f/packages/react/src/components/NumberInput/NumberInput.js#L404-L407
