### ISSUE TITLE
Experimental Component - Modal - Design

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1284]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
## Modal

Sketch File: https://ibm.box.com/s/b5jfyvfgcjiwpkj2tq36wbo21dw7sdbv
- Design language suggests setting width to breakpoints; our devs suggest 50% screen width (my guidance shows screen width)
- Since this is a unique component, I added page illustrating modals at various breakpoints
- There was a question about having the clear icon in the transactional modals but that relates more to Carbon functionality and less to the new design
- Changed focus border to inside instead of center (I think it was a mistake in duo file)
- Security built their modal using the fluid buttons with bottom padding vs. the fixed buttons; we are not doing this in Carbon; the margin bottom under their body copy is much larger than ours
- Chiu has seen this file

![modal_light_theme](https://user-images.githubusercontent.com/43144260/48099986-1fae1f00-e1e7-11e8-9688-2d91fe610ca0.png)

![modal_specs](https://user-images.githubusercontent.com/43144260/48099991-2472d300-e1e7-11e8-91e9-fa3b8c98c3f6.png)

![modal_scaling](https://user-images.githubusercontent.com/43144260/48100002-2c327780-e1e7-11e8-882a-04f5dd0c0979.png)
