### ISSUE TITLE
[Question]: prop-types intellisense in vscode

### ISSUE THREAD

**Issue by rcronin** [carbon-design-system/carbon#12890]
### Question for Carbon

With some of @carbon/react in typescript and most still using prop-types, does anyone have any recommendations on how to get Intellisense working in VSCode for the prop-types bit?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
You'll probably need a plugin or extension to help out with this since VSCode relies on the Typescript annotations for intellisense. [Here's one I found](https://marketplace.visualstudio.com/items?itemName=OfHumanBondage.react-proptypes-intellisense) after a cursory glance on the marketplace.

Intellisense will be significantly improved as more types are added to the package, #10752, #12513
