### ISSUE TITLE
Experimental Component - Notification - Development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1295]
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

**Comment by tw15egan** [comment]
Sketch File: https://ibm.ent.box.com/file/337346495669

**Comment by jeanservaas** [comment]
**Looking good... couple things**

1. The decorative vertical side bar is spec'd at 3px and needs to be the same width in both Line Notifications and Toast Notifications. Right now they're different.

![image](https://user-images.githubusercontent.com/43144260/47858161-a064b980-dda8-11e8-8284-f6d10aa9b0a4.png)

![image](https://user-images.githubusercontent.com/43144260/47858141-98a51500-dda8-11e8-9a8b-c224df30908b.png)

2. I would just get rid of hover and active states. Right now on Carbon, the cursor changes and that's it... I think we should just keep that functionality rather than getting into more colors; I also verified this with Chiu. There will still be a focus state though.

3. The icon needs to stay in place, 14px from the top edge when the line breaks... right now it's going to vertical center.

Yours:
![image](https://user-images.githubusercontent.com/43144260/47858453-57f9cb80-dda9-11e8-92af-bc84357b5f6b.png)

Spec:
![image](https://user-images.githubusercontent.com/43144260/47859624-eff8b480-ddab-11e8-8ee3-62dfd6467ce8.png)

4. I realize that I didn't specify a right padding for those line notifications... I just gave it 16px. I realize that on really wide screens, we'd need to break the line way before that. We've been adding a right padding of 25% on components like accordion and it looks like you've got something specified here. We can talk about this one.

![image](https://user-images.githubusercontent.com/43144260/47859767-4239d580-ddac-11e8-9a34-fb7517c5ae1a.png)

5. The yellow icon is bitch because of accessibility... it won't pass contrast if we don't make a one-off icon with a black exclamation mark in the center instead of a knocked out one. _Note: you were right to use the triangle... I spec'd a circle which is old, we updated it._

Yours:
![image](https://user-images.githubusercontent.com/43144260/47860125-0d7a4e00-ddad-11e8-986f-65d61c22475a.png)

Spec:
![image](https://user-images.githubusercontent.com/43144260/47860141-1834e300-ddad-11e8-91e9-a41c4fc27c9f.png)

**Comment by tw15egan** [comment]
We need to update the Sketch file specs, the inline notifications are specc'd at 2px (although inspecting the bar, it is 3px). 

<img width="273" alt="screen shot 2018-11-01 at 10 47 08 am" src="https://user-images.githubusercontent.com/11928039/47862648-9dc38d80-ddc3-11e8-9115-81199afbf857.png">



Making the changes on the code side now

**Comment by tw15egan** [comment]
Also, do you have an svg of the yellow warning icon with black fill?

**Comment by tw15egan** [comment]
@jeanservaas updates can be viewed here: http://carbon-dev-environment-exp-notification-active-lemur.mybluemix.net/?nav=notification
