### ISSUE TITLE
[Bug]: manually input end date for range in DatePicker make dateFormat wrong

### ISSUE THREAD

**Issue by Gong-la** [carbon-design-system/carbon#13128]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.22.0

### React version

v17.0.2

### Description

when set DatePicker's dateFormat="d/m/Y", the date format will wrong after change end date manually

### Reproduction/example

https://stackblitz.com/edit/github-bcvgpb?file=src/App.jsx

### Steps to reproduce

1. Select start and end date (29/01/2023 and 09/02/2023)
2. change the end date manually to `08/02/2023`, onblur the input box
3. the end date input value become `02/08/2023`
4. the start date input value become `aN/aN/0NaN`

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by cknabe** [comment]
I cannot reproduce this on v1.25. But that might be because specifying a different date format, such as d/m/Y appears to be broken. I updated flatpickr to 4.6.13, but that didn't resolve it.

Maybe it is due to testing with the playground locally?
1. Set the playground with the following:
- allowInput: true
- datePickerType: range
- dateFormat: d/m/Y
- placeholder: dd/mm/yyyy
2. Input 05/02/23, tab to the 2nd input, and input 15/02/23
3. After tabbing/pressing enter the first input in the range changes to 02/15/23 and the 2nd is empty.

The dates are displayed in m/d/Y. If I try to do the same thing outside of the Playground in Storybook, I see that it sets the 2nd date to 01/05/2001 and the first date is empty.

So clearly there are some issues going on here. I'm running out of time to debug them.

**Comment by cknabe** [comment]
"version": "1.25.0",
and 
    "flatpickr": "4.6.13",
