### ISSUE TITLE
Experimental Component - Search - Design

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/carbon#1324]
**Design**
Create final design specifications that are ready for production. Functionality and variations should match as is Carbon components.
- [ ] confirm Security design matches duo intent
- [ ] confirm Sketch file sizing/spacing specs
- [ ] screen grab sizing guidance and add to GitHub issue

**Comment by jeanservaas** [comment]
## Search

Sketch File: https://ibm.box.com/s/owluwdqf72y1a23hqmys4k8jgv3ujaxs
- Used v. with magnifying icon on the left to mirror what Carbon has now (in that it assumes the component will be attached to a "no return for results" or type ahead functionality
- Eventually there need to be two versions of search ("return for results" where the magnifying icon is on the right and functions as an active button; Right now Carbon does not make the distinction
- Changed focus border to inside instead of center (I think it was a mistake in DL file)
- Made specs for magnifying icon on the right for future release
- Beginning to alter icon padding in all components to mirror padding for active icons (those in a square)

![search_light_theme_lrg](https://user-images.githubusercontent.com/43144260/47739655-da687b00-dc43-11e8-8ced-aaff0a13695b.png)
![search_light_theme_small](https://user-images.githubusercontent.com/43144260/47739656-da687b00-dc43-11e8-8836-0f5603b4e8e3.png)
![search_specs](https://user-images.githubusercontent.com/43144260/47739657-db011180-dc43-11e8-9605-18949631c972.png)
