### ISSUE TITLE
Past date is not showing up on Date picker when we use minDate=today

### ISSUE THREAD

**Issue by subhak77** [carbon-design-system/carbon#13292]
When I open Date picker with some past date to be display, it is not displaying past date on before click on it. 
Can someone please make it show as readable when passing past date to Date picker with minDate=today prop
![image](https://user-images.githubusercontent.com/42539457/221774282-186c1497-21ad-4c78-b210-815116699c90.png)

If I remove `minDate="today"` prop form date picker then it will show value 02/01/2023 (past date)
If we keep `mindate="today"` it show blank on it.

Here is the sample code snippet on stackblitz
https://stackblitz.com/edit/github-wh4z6k?file=src%2FApp.jsx

**Comment by tay1orjones** [comment]
@subhak77 This behavior is intentional. The current value for the DatePicker must be within the range of `minDate` and `maxDate`.

If an existing value of the DatePicker is a date before the intended `minDate`, I'd recommend not specifying `minDate` initially. Place `invalid` on the DatePickerInput and then set the `minDate` when the user opens the DatePicker.
