### ISSUE TITLE
Interactive tag: Selectable Tag Implementation

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#13337]
## Acceptance criteria

- Add the Selectable tag variant to the Tag component.
- Make sure this works against Jan's Contextual Layout System.

-----

**New Tag variant**
- Add the Interactive tag umbrella under the existing Tag component
  - Add Selectable tag variant

**Renaming things in Storybook**
*Question: Will renaming these tags going to be a breaking change? 
- Rename "Default" tag to "Read-only" tag.
- Rename "Filterable" tag to "Dismissible" tag.

**Moving things around in Storybook**
- Can we have the file structure like this in the React storybook?
  - Overview
  - Read-only
  - Dismissible
  - Selectable
  - Operational
  - Skeleton
  - Playground

**Icons**
- Having the ability to add icons to tags in all variants (except for the small size).

**Sizes**
- Add the Large size (32px height) for the Read-only, Dismissible, Selectable, and Operational tag variants.
- Do not allow icons in the Small size (18px height) for the Read-only, Dismissible, Selectable, and Operational tag variants.
*Note: The AI slug in the small size is fine as is. It is just decorative icons we are not allowing in the small size.

**Colors**
- Selectable tags should only be available in the color of the design specs provided. It will not be allowed to be used in the other colors.

-----

### Selectable Tag Design Spec

<img width="3087" alt="Selectable tag" src="https://github.com/carbon-design-system/carbon/assets/43969356/2b6bf703-288e-490a-8461-b8bea794b9ce">

**Comment by tay1orjones** [comment]
It might be worthwhile to pop OperationalTag out into it's own issue.

> Can we have the file structure like this in the React storybook?

Yes, the first level of nesting can stay in the existing story file, the second level of nesting (interactive) will need to be in a separate `.stories` file so that we can add the extra level of nesting to the title.

### SelectableTag

Additional notes from sizing:

* RenderIcon is already in tag
* We already have small and medium, can normal tags be large as well?
* Does "no icon on small" pertain to the AI slug as well?

### OperationalTag

* Is the existing skeleton style what we want to use? The spec shows a new style of skeleton for the operational tag. Do we want these to diverge from one another?
* Would be good to put a toggletip and popover example into storybook, especially if the component doesn't handle this automatically and requires the dev to configure it

**Comment by laurenmrice** [comment]
> It might be worthwhile to pop OperationalTag out into it's own issue.
I made a separate implementation issue for OperationalTag: [#15529](https://github.com/carbon-design-system/carbon/issues/15529) 

### SelectableTag

> We already have small and medium, can normal tags be large as well?
Yes, Normal tags (aka Read-only tags) can be in the Large size. All tag variants can be in the Large size (Read-only, Dismissable, Selectable, and Operational.)

> Does "no icon on small" pertain to the AI slug as well?
The AI slug existing in the Small size tag is fine as is. It is just that we do not want the decorative icon that leads before the text in the Small size tags.

### OperationalTag

> Is the existing skeleton style what we want to use? The spec shows a new style of skeleton for the operational tag. Do we want these to diverge from one another?
Oh, for some reason in the Figma kit they are different. No, lets just use our current Skeleton states that we have in React. I have updated the Spec image to reflect that. 

> Would be good to put a toggletip and popover example into storybook, especially if the component doesn't handle this automatically and requires the dev to configure it
Agreed, I can provide spacing specs on this if needed.

**Comment by sstrubberg** [comment]
Make sure this works against Jan's Contextual Layout System.
