### ISSUE TITLE
Document support for other languages

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#1335]
We should add some documentation around how folks can use other languages with the Carbon Design System, especially with some of the new type faces coming from IBM Plex 👍

**Comment by dcwarwick** [comment]
Yes. For example, if a product has an arabic version/localisation, what are the options for specifying fonts for Carbon?

This page https://www.ibm.com/innovate/brand/typography/ suggests that, pending arabic glyphs being added to IBM Plex, we should "continue to use" a typeface such as Madrasah Light. I presume, though, that we would want to encourage/require IBM Plex to be listed first, so that if/when the necessary glyphs are present in IBM Plex they are used from there.

So would we suggest the following specification when the arabic version/localisation is active?
```css
  font-family: 'ibm-plex-sans', 'Madrasah Light', 'Helvetica Neue', Arial, sans-serif;
```

Or would we suggest that an extended specification is ALWAYS used when arabic/chinese/greek/etc versions/localisations are available, regardless of whether they are currently selected?
```css
  font-family: 'ibm-plex-sans', 'Madrasah Light', 'Helvetica Neue LT W1G Light', 'M Hei PRC Light', 'Helvetica Neue LT W1G', 'Narkis Tam Light MFO', 'Hiragino Kaku Gothic ProN W3', 'Yoon Gothic 100 OTF 10', 'Helvetica Neue', Arial, sans-serif;
```

Or what are the consequences of simply continuing with the standard basic font specification for Carbon,
```css
  font-family: 'ibm-plex-sans', 'Helvetica Neue', Arial, sans-serif;
```
since browsers seem to fall back to locally available fonts for any glyphs not found in any of the CSS-specified font families?

It would be useful to be able to point teams at some definitive guidance.
