### ISSUE TITLE
[Bug]: Content Padding removed after inserting Theme in HeaderContainer

### ISSUE THREAD

**Issue by LouisRoth** [carbon-design-system/carbon#13450]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.26.0

### Description

I followed the docs by introducing a <Theme /> component between the <HeaderContainer /> and <Header /> to change the color of the header to dark. By adding the <Theme /> component the (top) padding which is set by the <Content /> component is removed and therefore the content is partially behind the header. 

### Screenshots

![Content](https://user-images.githubusercontent.com/78984446/229379316-f961b260-8d6b-47cc-bc6a-08ac5370fd49.png)
![Header with theme](https://user-images.githubusercontent.com/78984446/229379318-7ec48ac1-8b3b-4a22-a01b-275762992c1a.png)
![Header without theme](https://user-images.githubusercontent.com/78984446/229379319-cb91dd0e-760c-4b55-932e-8e1074c57cca.png)

### Steps to reproduce

I started with a new react project (created with npx create-react-app ...) and installed @carbon/react and react-router-dom. I started to set up basic routing capabilities with a root page containing the header + the <Outlet /> inside the <Content /> component. After everything worked fine, I added the <Theme theme='g100'> component to change the theming to dark for the header. Afterwards, the padding for the content was removed. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by francinelucca** [comment]
Hi @LouisRoth, could you Re-create this issue using Stackblitz or Codesandbox so we can take a better look? Here's [our template](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx)
TIA!

**Comment by LouisRoth** [comment]
So I finally had time to reproduce the issue. The project can be found on StackBlitz via this link: https://stackblitz.com/edit/github-gab1sd?file=src/App.jsx

I hope it will help.

**Comment by francinelucca** [comment]
Confirmed issue can be reproduced

**Comment by alisonjoseph** [comment]
This is being caused because of a sibling selector, when wrapped in a Theme component it is no longer a sibling to the content component. 

`.#{$prefix}--header ~ .#{$prefix}--content `
https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/ui-shell/content/_content.scss#L22

We could add a fix using `:has` `div:has(.#{$prefix}--header)  ~ .#{$prefix}--content` however that is not currently supported in Firefox. I would recommend as a workaround for now is to add `margin-top:$spacing-09;` (or 3rem) to the content. 

The other option would be to always add the top margin to the Content component, this would be a breaking change. We could also add a prop to the Content component that adds margin in. 

Changing this to a sev3, as there is a workaround.
