### ISSUE TITLE
[Feature Request]: Officially support Carbon for Flutter

### ISSUE THREAD

**Issue by Luckey-Elijah** [carbon-design-system/carbon#13472]
### The problem

I'd like to use an officially supported Carbon Design System package for [Flutter](https://flutter.dev/) published on [pub.dev](https://pub.dev/). Currently there is an unofficially maintained package [`carbon_flutter`](https://pub.dev/packages/carbon_flutter) available, but it is missing many components. 

### The solution

Publish an officially supported Flutter package to pub.dev that includes all of Carbon's components.

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by sstrubberg** [comment]
Hey @Luckey-Elijah, apologies for the delayed response. Unfortunately, due to constraints with [our other business priorities](https://github.com/orgs/carbon-design-system/projects/39/views/87), we won't be able to take this on at this time. Of course, we are always open to community driven contributions for projects like this. Let me know if that is something you'd like to explore and lead. Closing this issue for now!

**Comment by Luckey-Elijah** [comment]
Thanks for getting back. I will consider it! Will come back it that is the case. 👍🏻

**Comment by sunderee** [comment]
Hi IBM team, I've started developing Carbide, a Carbon Design System implementation for Flutter: https://pub.dev/packages/carbide.

Happy to collaborate on official support. Let me know how I can help.
