### ISSUE TITLE
[a11y]: Accessibility issue in Modal component

### ISSUE THREAD

**Issue by QxiaoQ** [carbon-design-system/carbon#13504]
### Package

carbon-components-react

### Package version

v7.59.6

### React version

v17

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Description

The ARIA attributes "aria-labelledby" are not valid for the element <div> with implicit ARIA role "generic"
```
<div
    aria-labelledby="bx--modal-header__label--modal-1"
    class="bx--modal-content"
    id="bx--modal-body--modal-1">
```

### Reproduction/example

Reproduce

### Steps to reproduce

1. In chrome open story book https://v7-react.carbondesignsystem.com/?path=/story/components-modal--default
2. open IBM Equal Access Accessibility Checker
3. run scan
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/31646170/231120512-eef2f7bb-125b-4386-aeed-ec820444f8d5.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@QxiaoQ When running the accessibility checker against storybook, it's important to test against the isolated iframe/story view. If you don't, there's a number of false positive errors that will show due to the storybook environment.

I'm not able to reproduce this, but happy to reopen and take a closer look if you could reproduce the issue in a [stackblitz](https://stackblitz.com/github/carbon-design-system/carbon/tree/main/examples/vite?file=src%2FApp.jsx)


https://user-images.githubusercontent.com/3360588/232583651-ba1e9792-2d87-4500-96f8-a5fbd55ef4cf.mov

The errors remaining on this are also false positives. The first is due to the storybook environment, the other is due to the dropdown in the modal not having a label.

**Comment by xiaolixu** [comment]
I am facing the same issue too.
