### ISSUE TITLE
Add TypeScript types to ContentSwitcher, Switch

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13550]

**Comment by anton-tsymuk-viacomcbs** [comment]
Hi. If you do not mind, I would try to help with the migration. I opened a PR for this issue

**Comment by wkeese** [comment]
Hmm, this isn't working for me, I get

> TS2305: Module '"@carbon/react"' has no exported member 'ContentSwitcher'.
> 12 import { ContentSwitcher } from "@carbon/react";

ISTM that there are a couple problems:

* There's no generated components/ContentSwitcher/index.d.ts file at all.   Because components/ContentSwitcher/index.js needs to be renamed to index.js.
* Even after that though, createClassWrapper() is a black-hole to the type information.  It needs to be converted to something like below but I haven't quite gotten it working yet

```ts
export function createClassWrapper<P>(Component: ComponentClass<P>): FunctionComponent<P> {
  function ClassWrapper(props) {
    return <Component {...props} />;
  }

  const name = Component.displayName || Component.name;
  ClassWrapper.displayName = `ClassWrapper(${name})`;

  return ClassWrapper as FunctionComponent<P>;
}
```
