### ISSUE TITLE
Compat tokens: Explore providing deprecation warnings for compat token usage via sass `@warn`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#13694]
This may not be feasible since tokens are not functions or mixins, but it would be great if we could throw a warning in the console for usage of tokens that are deprecated.

**Comment by tw15egan** [comment]
Played around with this for a bit, but I wasn't able to make any progress. There isn't any way to emit warnings for tokens. I was trying to see if there was a way to check if the token is being _used_, but it seems like we can only check if it _exists_, which it will since we define it.

Happy to pair up on this if you have any other suggestions, but going to close this as not planned for now 👍🏻
