### ISSUE TITLE
[Feature Request]: [OverflowMenu] Can there be a prop to the overflow menu to be widened to fit the text content of longer strings

### ISSUE THREAD

**Issue by youngjunekoh** [carbon-design-system/carbon#13860]
### The problem

![Screenshot 2023-05-23 at 10 45 49 AM](https://github.com/carbon-design-system/carbon/assets/60585804/321ca1a5-175d-40ae-9e5f-b978e941aee1)

Can there be a prop to widen the length of the overflow menu to support the full length of the menu item text?
I realize it may could be a problem if the text is too long but having an optional prop to the component to make it possible could be great

### The solution

as per description

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tw15egan** [comment]
Hey there @youngjunekoh ! We set a reasonable default `width` property in order to truncate text and show the ellipses. The default width is `10rem`, if you'd like to override this to be larger, you can simply target the class via CSS (there is no prop to handle this functionality).

```css
.cds--overflow-menu-options {
   width: 15rem;
}
```

Hope this helps!
