### ISSUE TITLE
Grid docs: Implementation page (DSAG review)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#13909]
- [x] Review Grid Implementation page with DSAG
- [ ] Review with @mjabbink 
- [ ] Review with Cameron calder

**Comment by jeanservaas** [comment]
Walked through grid docs on 6/8/23 DSAG.

Notes from DSAG:

**Button usage on grid**
- Update button guidance style tab content to communicate grid aware intent more clearly

**Gutter modes and mixing**
- Help designers understand gutter modes better, there's still a lot of confusion about when to use what and what components are compatible with each gutter mode
- Carrie suggested maybe an animation around gutter modes to show how they mix?
- Could also add gutter mode guidance to component page to help people understand which mode can be used with each component

**Breakpoints**
- Carrie also thought there could be more clarity around breakpoints; maybe an animation that shows responsive progression

**Grid influencers**
- need more guidance around when to use a grid influencer shell
- CIO is using grid influencer shell and grid template with a persistent left nav because of confusion

**Max plus grid size and high density style model**
- How do side panels transition in max + grid
- Kevin Camelo would love to be a part of future Max plus grid working group
