### ISSUE TITLE
[Bug]: configuration with "with" not allowed while using @carbon/styles/themes with @carbon/styles

### ISSUE THREAD

**Issue by lSilvani** [carbon-design-system/carbon#13906]
### Package

@carbon/styles

### Browser

Chrome

### Package version

1.30

### Description

Hello, I am using the @carbon/styles package and I now I want to override the value of a token from the theme. Following the [docs](https://github.com/carbon-design-system/carbon/tree/main/packages/styles), I am using the themes entrypoint and extending the theme, but I am getting an error.
Please notice that the issue is not present with CodeSandbox using @carbon/styles 1.2.

<img width="339" alt="Screenshot 2023-06-01 at 18 16 25" src="https://github.com/carbon-design-system/carbon/assets/116547024/3cbd6740-d92c-473a-837d-88ed3acb88cd">
<img width="860" alt="Screenshot 2023-06-01 at 18 16 44" src="https://github.com/carbon-design-system/carbon/assets/116547024/d6f487ab-da50-4156-8d28-78667efc51a3">

### Reproduction/example

https://codesandbox.io/s/mutable-moon-zt22w6?file=/style.scss:0-290

### Steps to reproduce

As per above

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there @lSilvani ! `@carbon/styles` pulls in the kitchen sink, including `@carbon/themes`.

To get around this, you can reference the `config` file directly if you need to configure any of those options, then pull in your theme config, and then pull in `@carbon/styles` directly

```scss
@use '@carbon/styles/scss/config' with
  (
    $prefix: 'bx',
    // To be changed to sds
    $css--default-type: true,
    $css--reset: true
  );

// // Override a token from the theme
@use '@carbon/styles/scss/themes';
@use '@carbon/styles/scss/theme' with
  (
    $theme: (
      background: #e2e2e2,
      text-primary: red,
    )
  );

@use '@carbon/styles';
```

Here is an example, hope that helps!

**Comment by lSilvani** [comment]
Thanks @tw15egan, this solved it! If I may, the docs are great but it has been a bit painful to find out the information, felt a bit scattered across the packages (themes, styles) and the sites (GitHub, official docs). One last question: button tokens are not accessible this way, should I pull them in separately?

**Comment by tw15egan** [comment]
@lSilvani definitely understand your frustration, we've tried our best to document as best as possible, but due to the large nature of the monorepo / design language, things can definitely get lost. If you have noticed anything that could be consolidated / improved upon, please let us know with a new issue with any specific things we could do to improve the discoverability. We also love PR's to help improve documentation, especially in areas that can be confusing.


In regards to Button tokens, those are exported a little bit different;y, as well as `Notification` and `Tag`.

You can access them like so: 

```scss
@use '@carbon/styles/scss/components/button/tokens' as button-tokens with
  ($button-primary: rebeccapurple);
```

I've [updated the example](https://stackblitz.com/edit/github-hf5kjr?file=src%2Findex.scss,src%2FApp.jsx,src%2Fmain.jsx) to show this as well.


More information if you scroll down a bit after the table, under `component tokens`: https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#components

If you have pulled down the repo locally, you can also play around with the custom-theme example: https://github.com/carbon-design-system/carbon/tree/main/examples/custom-theme

Hope this all helps! I'm going to close this, but feel free to let me know if you run into any other issues.

**Comment by lSilvani** [comment]
Thank you @tw15egan! I do have another question, as I am trying to override the font-family, as I need to use our own branded font. I have a partial _types.scss where I define a map and then I use this in the main stylesheet...but if use it through `@use '@carbon/styles/scss/config' with` it doesn't work, but if I use `@use '@carbon/styles' with` it does, not sure I understand why. The problem is that it throws an error with the themes module afterwards, which I did not have before. I have updated the example: https://stackblitz.com/edit/github-hf5kjr?file=src%2Findex.scss
Could you please help me on this?

**Comment by tw15egan** [comment]
Hey no problem, I've updated your example with what I was able to do to get your example working! I haven't tried anything like this, so it was good practice https://stackblitz.com/edit/github-hf5kjr-sfmrgv?file=src%2Findex.scss,src%2F_types.scss

All I needed to change to your example was add

```scss
  // set the body styles
  @include type.type-style('body-01');
```

at the beginning of the `body` selector, and then modified your font-family declaration to `font-family: type.font-family('sans');` You 



https://github.com/carbon-design-system/carbon/tree/v11.30.0/packages/type#font-family

**Comment by lSilvani** [comment]
Thanks a lot @tw15egan for the support and clarifications! 
I was looking at both the docs (website) and the readme and .md files, for styles and single packages, but I think what confuses me is that the syntax changes based on how you use the packages, and it seems there are different ways to achieve things. It may be helpful to put together a complete example somewhere (and maybe there is already and I totally missed it!). Last part for me is to understand how to manage light and dark mode, do you have any resources/examples I could go through? Many thanks again!
