### ISSUE TITLE
[Bug]: TableHeader ignores onClick prop when not sortable

### ISSUE THREAD

**Issue by djragsdale** [carbon-design-system/carbon#14016]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.30.0

### React version

v17.0.2

### Description

`TableHeader`'s `onClick` prop is used on an internal `<button>` when `isSortable={true}`, but the `onClick` prop is ignored when `isSortable={false}`.

### Reproduction/example

https://stackblitz.com/edit/github-kibieg?file=src%2FApp.jsx

### Steps to reproduce

1. Create a standard table with Carbon components.
2. Add an `onClick` prop to `<TableHeader>` with no `isSortable` prop (defaults `false`).
3. Click on the `<TableHeader>`.

A workaround can be accomplished by using `onMouseDown` instead of `onClick`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@djragsdale Correct - the onClick corresponds to the click of the button, which is only rendered when `isSortable={true}`

Be default a `th` doesn't receive focus and an `onClick` handler would be inappropriate to provide to the `th`. The interaction would not be available to keyboard users. If you'd like to act on interactions within the `th`, you'll need to include your own focusable element and attach an `onClick` to it. I hope this reasoning is helpful and sheds light on this. 

Since we won't be adding the `onClick` to the `th`, I'll close this.
