### ISSUE TITLE
[Bug]: onChange event handler not called on StructuredListInput when selecting an entry in a structured list

### ISSUE THREAD

**Issue by sbrunot** [carbon-design-system/carbon#14037]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.31.3

### React version

16.10.0

### Description

See the following example on StackBlitz: https://stackblitz.com/edit/github-xfrb3k?file=src%2FApp.jsx

When the single entry in the structured list is selected, the onChange event handler is not called.

### Reproduction/example

https://stackblitz.com/edit/github-xfrb3k?file=src%2FApp.jsx

### Steps to reproduce

Click the "Text for the first entry" list entry to select it.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by sbrunot** [comment]
For those facing the same defect, I ended up wrapping all my StructuredListRow components in a div with an onClick handler (and styled with "display: contents"):

```
<div className="structured-list-row-wrapper" onClick={() => (handlerProp(myDataToIdentifyTheRow)}>
    <StructuredListRow ...>
        ...
    </StructuredListRow>
</div>
```
and CSS:

```
/**
 * Div that wrap StructuredListRow element to workaround onChange event handler for StructuredListInput not working
 **/
.structured-list-row-wrapper {
  display: contents;
}
```

**Comment by tay1orjones** [comment]
That's a good workaround, thanks for including it here @sbrunot

**Comment by haocheng6** [comment]
It looks like the `onChange` prop of the `StructuredListInput` component is attached to an input element that has the `${prefix}--visually-hidden` CSS class, so you might not be able to click on that input element to trigger the `onChange` prop to be called.

It is possible to use keyboard to select the inner input element. In your example, if you use the Tab key to focus on the row and then press the Space bar, `alert('SELECTED');` will be called.

Here are some of my findings/thoughts:
- When using the keyboard to select a row, `setSelectedRow` is called twice by `StructuredListRow` and `StructuredListInput` because both the click and change events are fired from the inner input element (at least that's the behavior in Chrome). This might be unnecessary. Also, I am not sure in what case the `onChange` prop of the `StructuredListInput` component could be useful. Maybe a better design is to provide an `onClick` prop for the `StructuredListRow` component.
- The `StructuredListInput` component is tested by simulating a click event on the inner input element ([source](https://github.com/carbon-design-system/carbon/blob/bb0e5d1f4d84ce71a3131892993b76a5a6805495/packages/react/src/components/StructuredList/StructuredList-test.js#L327-L332)). The simulation might deviate from how the component would be used in practice because the internal input element is impossible to be clicked by a mouse.
