### ISSUE TITLE
[Bug]: TextInput focus lost when user is typing and type change from "number" to "text"

### ISSUE THREAD

**Issue by mateBe95** [carbon-design-system/carbon#14298]
### Package

carbon-components, carbon-components-react

### Browser

Chrome

### Package version

    "carbon-components": "10.58.7", "carbon-components-react": "7.59.8",

### React version

16.14.0

### Description

We have situation in IBM product that whenever user exceed number in TextInput with type number, we change type into = "text" but the cursor is going at the start of input whenever user typing which is confused.

I created sandbox. Try to typing something and after 3 seconds your cursor in the input will go to at the start.
https://codesandbox.io/s/textinput-focus-lost-when-type-change-vjclgv?file=/index.js

### Reproduction/example

https://codesandbox.io/s/textinput-focus-lost-when-type-change-vjclgv?file=/index.js

### Steps to reproduce

Try to typing something and after 3 seconds your cursor in the input will go to at the start.

https://github.com/carbon-design-system/carbon/assets/23103157/314d2ac6-94ec-48a1-a192-bc8b852b36bc

### Suggested Severity

None

### Application/PAL

IBM product

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
What is the reason for switching input types when a user interacts with the input? That seems like it could be problematic accessibility-wise. The reason the input is moving the cursor back to the start is because you're changing the input type, and it's causing a react re-render, there's no way to avoid that if you are changing an attribute on the fly. 

If you did want to go down this route, you could set the `selectionStart` to the length of the value when the change occurs, like so https://codesandbox.io/s/textinput-focus-lost-when-type-change-forked-ckvxy8?file=/index.js

**Comment by mateBe95** [comment]
hi @tw15egan ,
Can you link which paragraph of "accessibility-wise",  changing type of input violates type conversions from number to text? I will link it to our QA engineers as justification that it can't be done.

**Comment by tw15egan** [comment]
@mateBe95 I was worried that it would cause voiceover issues, but I just tested it with voiceover for Mac and it reads fine, so I guess it shouldn't be an issue. You can take a look at the example I posted to see how to implement it without the cursor jumping back to the start.

As for number two,  the `NumberInput` should match the same behavior as the HTML standard `input type="number"` and allows the character `e` to display large integers.  Going to close this one as resolved, if you are noticing an incorrect behavior with the `NumberInput` itself, please open a new issue regarding that component. Thanks!

**Comment by mateBe95** [comment]
> You can take a look at the example I posted to see how to implement it without the cursor jumping back to the start.

It doesn't resolve the issue @tw15egan :
https://codesandbox.io/s/textinput-focus-lost-when-type-change-forked-pfr7td?file=/index.js

**Comment by tw15egan** [comment]
You just need to conditionally render the component that you want, rather than changing the type on the fly since `selectionStart` is not available on `input type="number"`. Here is an example: https://codesandbox.io/s/textinput-focus-lost-when-type-change-forked-rc7sld?file=/index.js Regardless, this is not an issue with the Carbon library itself.
