### ISSUE TITLE
Incorrect vertical spacing on the select options for the multi-select and filter dropdowns

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon#1435]
The padding for the multi-select dropdown (both inline and normal) and the filter dropdown, is off for the options. 

https://www.carbondesignsystem.com/components/dropdown/code
![image](https://user-images.githubusercontent.com/6569324/48448637-49c28c80-e765-11e8-83b4-646efaf91bdf.png)

![image](https://user-images.githubusercontent.com/6569324/48448764-a756d900-e765-11e8-8cf7-9da8bc2deeec.png)

## Detailed description

When you open the multi-select dropdown (both versions) the options are shown not vertically aligned correctly, they are towards the top, not vertically centered. 

Chrome Version 70.0.3538.102

![2018-11-13 16 59 56](https://user-images.githubusercontent.com/6569324/48448733-94440900-e765-11e8-8bc9-7dcf0d5588db.gif)

**Comment by alisonjoseph** [comment]
Looks like this issue is related to the website example and not the actual component. Appears to be working correctly here. http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

moved to website repo.https://github.com/carbon-design-system/carbon-website/issues/554
