### ISSUE TITLE
[Bug]: 10.58.8 has dependency called "warning" that is not used but causes error in @carbon/charts UMD bundle

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon#14422]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.58.8

### Description

The file, browser.js:12, in a module called "warning" that is a dependency of `carbon-components@10.58.8`is making the assumption that `process.env.NODE_ENV` exists in a browser environment when it doesn't:
`process.env.NODE_ENV!=="production"`.

Looking over `carbon-components`, the "warning" module doesn't appear to be used. In fact, that module is not even included in `carbon-components@next`.

See https://github.com/carbon-design-system/carbon-charts/issues/1646

### Reproduction/example

https://stackblitz.com/edit/mmky7q?file=index.html

### Steps to reproduce

Run StackBlitz

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Application/PAL

@carbon/charts

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

## Other

I will submit a PR to pull out that unused dependency.

**Comment by tay1orjones** [comment]
`carbon-components@next` points to v11.x, which doesn't use `warning` because it's now a re-export of `@carbon/styles`. 

In v10.x `warning` is used in a few places.

https://github.com/carbon-design-system/carbon/blob/f1c92af3f40585631d8450a4aa381d121dc2c797/packages/components/src/components/floating-menu/floating-menu.js#L350-L355

https://github.com/carbon-design-system/carbon/blob/ce8966fb90bac9106e5ec6433954032545e0754c/packages/components/src/components/modal/modal.js#L112-L117

https://github.com/carbon-design-system/carbon/blob/f1c92af3f40585631d8450a4aa381d121dc2c797/packages/components/src/components/removed-component.js#L17-L21

---

The `__DEV__` checks compile to `process.env.NODE_ENV !== 'production'` via [`https://www.npmjs.com/package/babel-plugin-dev-expression`](https://www.npmjs.com/package/babel-plugin-dev-expression) expressed as `dev-expression` 

https://github.com/carbon-design-system/carbon/blob/0898114f2e0a3f0ec55aadd8048eeec85c8ce8ed/packages/components/package.json#L200

---

I don't think the gulpfile or build system for v10 has changed recently, so I'm not sure why this has started happening. In any case, this should be handled during the build via rollup. [`@rollup/plugin-replace`](https://www.npmjs.com/package/@rollup/plugin-replace) or something may need to be added to the UMD build plugins to ensure process.env.NODE_ENV is converted to be just "production".

In the meantime you can get around this by defining it on your page before loading the Carbon UMD file.
```html
<script>process = { env: { NODE_ENV: 'production' } }</script>
```

**Comment by nstuyvesant** [comment]
Yep, just added `@rollup/plugin-replace` to take that out - thanks. I will close this. Thanks for the response.
