### ISSUE TITLE
Single File Uploader: Implementation

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon#14502]
See specs in parent issue https://github.com/carbon-design-system/carbon/issues/6775

* Duplicate the existing drag and drop story, rename it to be "drag and drop single"
* Add a prop to conditionally render a FileUploaderButton inside the FileUploaderItem (with a `ghost` kind) to enable the "replace" behavior, add necessary styling to position the button correctly inside FileUploaderItem
* Truncation and tooltip detection will only be evaluated on initial render via a useLayoutEffect

**Comment by tay1orjones** [comment]
> * Truncation and tooltip detection will only be evaluated on initial render via a useLayoutEffect

Sorry this is so vague. I'll clarify for posterity:

The spec calls for a tooltip to be shown on hover/focus when the filename is too long to be displayed. Realistically this means the filename will need to be an interactive element so that focus can be placed there.

Visually truncating the text can be done with just a `text-overflow: ellipsis` style, but we need to detect in the component javascript if we should render a tooltip or not. This means we will need measure inside a `useLayoutEffect` if the filename element is greater in width than the parent element. If it is, the text should have the ellipsis visual treatment and also render the tooltip on hover/focus. If not, there's no ellipsis and no need for a tooltip.

This bulleted item really just means that we're not going to recalculate the tooltip if the window/browser/element size changes. We'll measure once at initial render, and then not measure again. It's expensive to measure on browser resize and also complicated. @tw15egan and I discussed this in a meeting the other day determined we didn't feel the benefits outweigh the additional cost of measuring when the browser size changes.
