### ISSUE TITLE
[Bug]: $border-subtle is using previous step's value

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon#14597]
### Package

@carbon/styles

### Package version

1.37.0

### Description

It seems like the $border-subtle tokens are always one step behind compared to the rest of the layering tokens.

<img width="542" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/dfdfe250-b025-4236-a825-afc7857865b3">

This means that a UI element with a $layer-02 background will be paired with a $border-subtle-01 border. In the dark themes, these two values are the same though, resulting in the border being invisible.

<img width="787" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/ccb0fd5f-ac81-4492-bd49-feee185cc13f">
<img width="786" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/4ee5ede4-e725-4120-9597-e76e2a30b405">

### Reproduction/example

https://stackblitz.com/edit/github-recj8l?file=src%2FApp.jsx

### Steps to reproduce

see above

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by guidari** [comment]
Hey @carbon-design-system/design can you guys help with that one? Please

Looks like the background is being paried with the wrong border-subtle.

In this file it's saying we should pair the `layer-02` with `border-subtle-02`, but in the current example showed in [Stackblitz](https://stackblitz.com/edit/github-recj8l?file=src%2FApp.jsx) we don't have that.

Here a PR to clarify the combination: https://github.com/carbon-design-system/carbon/issues/12355
We have also have this [PR](https://github.com/carbon-design-system/carbon/pull/13469) from @tw15egan 
Something seem weird about the dark theme

**Comment by tw15egan** [comment]
It's definitely a weird issue, since `border` has 4 values, and all other `layer` tokens have `3`. I recall some issues that came up when some of these elements that use a `border-subtle` were placed in a `Modal`.

**Comment by tay1orjones** [comment]
Here's some next steps we discussed today as a team:

1. Spin up a stackblitz with a dropdown on a background, dropdown on layer 1, layer 2, layer 3
  2. It's also super noticeable with Accordion
3. Review the issue with design by showing them this example
4. Determine next steps and how to fix

**Comment by janhassel** [comment]
@tay1orjones Here's a stackblitz demo: https://stackblitz.com/edit/github-tysskn?file=src%2FApp.jsx

The demo element is using `$layer` as the background and has a 1px `$border-subtle`.

<img width="1205" alt="image" src="https://github.com/carbon-design-system/carbon/assets/28265588/46a13e86-c71f-44ca-82dc-f6aed60ac7cd">

**Comment by alexandrutatarciuc** [comment]
The current implementation #15415, while functional, is a workaround that doesn't address the underlying issue. In fact, it creates a discrepancy between code and design and is problematic for those building upon the Carbon Design System, as it requires the implementation of a similar workaround.

The root cause appears to be that the `$border-subtle` contextual tokens point to the wrong layering tokens. Please compare the token definitions (g90 theme) in code to the documentation/Figma files:

Code: 
![image](https://github.com/user-attachments/assets/a64bc2ed-b422-41fe-9f82-f4d1783ff95b)

Documentation/Figma:
![image](https://github.com/user-attachments/assets/2dbc5e8e-b564-4529-9536-6fd8441109ad)

What I believe needs to be done is to change the implementation of `emit-layer-tokens` mixin in the `_layer-tokens.scss` to account for the `$border-subtle-00` use case.
