### ISSUE TITLE
AP - align on publisher name

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon#14794]
Need alignment on the name of the publisher site so we don't have to move content once established.

**Comment by kingtraceyj** [comment]
### Ideas:

Acquisition playbook for Carbon migration

Acquisition migration to Carbon playbook

Acquisition playbook for Carbon adoption

Carbon adoption playbook for acquisitions

Carbon and acquisitions playbook

Carbon migration playbook

Migrate to Carbon

Product migration to Carbon

Adopt Carbon

Carbon adoption for acquisitions playbook

### Questions:
Does this need to be acquisition focused or do we want to leave it generic for legacy products as well?

**Comment by ljcarot** [comment]
I like 'Carbon adoption playbook for acquisitions'

**Comment by aubrey-oneal** [comment]
My top picks are:
- Migrate to Carbon
- Adopt Carbon

I like the idea that the title is short and to the point -- longer headers can come in the body copy. I also like the idea of using a verb like migrate or adopt since it gives clarity on what the outcome is. There are lots of playbooks out there where you have to read them for a while until you realize their intended outcome. I'm also wondering whether we need to use the word 'acquisition'. What are the advantages/disadvantages? I'm thinking one disadvantage is that there could be products in IBM who need to migrate to Carbon (who aren't recent acquisitions) who might use this site.
