### ISSUE TITLE
[Feature Request]: Allow to change next and previous icons in PaginationNav

### ISSUE THREAD

**Issue by radarfox** [carbon-design-system/carbon#15012]
### The problem

We would like to migrate from our custom pagination component to PaginationNav. Our custom component uses chevron icons instead of caret icons on previous and next buttons.

### The solution

Allow to change next and previous icons, preferably like this:

```
import { ChevronLeft, ChevronRight } from '@carbon/react/icons';

<PaginationNav renderPreviousIcon={ChevronLeft} renderNextIcon={ChevronRight} />
```

### Examples

https://react.carbondesignsystem.com/?path=/docs/components-button--overview#button-rendericon

### Application/PAL

https://research.ibm.com/

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by jeanservaas** [comment]
Hi @radarfox — it seems like you're asking just to swap out caret, which the system uses, for a chevron. This is not a configuration that we'd really like to allow unless we made this change at the system level — i.e. If you feel that there's a strong case to be made for this change, I'd make the case/suggestion as a system change as it doesn't make much sense as a one-off stylistic difference. It also has no effect on the functionality of the pagination.

Also, I'd argue, that the intentional relationship between the carets for next/prev and the chevrons for dropdowns would become confused if we started swapping them out with each other in different experiences. I also feel that the carets work a bit better with the type whereas the chevrons begin to look like brackets.

<img width="848" alt="image" src="https://github.com/carbon-design-system/carbon/assets/43144260/ccd504fe-ed14-478f-bbc2-c1020f93b7d9">

I also have some UX questions here...why would a user in this situation want to page through 1628 pages... is this the really the best experience here? I can see a use for Next/Prev and jump to end... but jumping to middle seems odd, is that a use case that you really need? Maybe our paginiation nav is not the best situation for you here... what would be the ideal PageNav experience. Maybe the better proposal is something like a PagNav thats simplier. Like just Prev/Next and maybe First/Last. And it never shows exact pages...

<img width="458" alt="image" src="https://github.com/carbon-design-system/carbon/assets/43144260/a9435421-fba0-48f4-8be4-62fa21048cfa">

**Comment by radarfox** [comment]
> it seems like you're asking just to swap out caret, which the system uses, for a chevron.

Yes, that's what we need. I'm not sure why would you need to make a "system level change". The icon should stay the same for other Carbon users, just Research Website would provide this special configuration option. For example the Carbon Button component allows to do this. From my developer experience, this should be also pretty easy to implement.

I will link you up with our design team, so they can explain you the reasoning and design specs behind this. I will contact you over Slack, since this will involve confidential information.

> I also have some UX questions here...why would a user in this situation want to page through 1628 pages...

This is being discussed here: #15014
