### ISSUE TITLE
[Bug]: IBM Plex San font does not works well on some situation

### ISSUE THREAD

**Issue by guobinzhao** [carbon-design-system/carbon#15045]
### Package

@carbon/react, carbon-components, carbon-components-react, @carbon/icons

### Browser

Chrome

### Package version

Version 118.0.5993.88 (Official Build) (arm64)

### React version

16.13.1

### Description

https://github.ibm.com/tools-for-aps/zh/issues/36546#issuecomment-65558931
pls check the issue on the above link since we have not found a stable recreate steps, you can catch the problem in the vedio but disabling the local font will bypass the issue.

### Reproduction/example

we have not found a stable recreate steps

### Steps to reproduce

pls check the issue on the above link since we have not found a stable recreate steps, you can catch the problem in the vedio but disabling the local font will bypass the issue.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@guobinzhao The video reproduction in the issue you linked showed a resolution/workaround by disabling local fonts in the chrome devtools "rendering" pane. Carbon styles do not use `local()` sources in `@font-face` rules. [Here's a link to the compiled styling](https://unpkg.com/browse/@carbon/styles@1.40.0/css/styles.css) where you'll see a <kbd>cmd</kbd> + <kbd>f</kbd> searching `local(` returns no results.

If you search there for `src: url(`, you'll see Plex is only loaded from our Akamai CDN. Browsers may still choose to use the local font though. The font inspector in Firefox does a better job showing the source of the fonts on the page. This may help in debugging.

If you share the code for how you've configured your styling I'm happy to take a look. Ultimately this looks like a usage/configuration issue in your application. It might be hard to reproduce because this issue is isolated to only certain machines that may have an outdated/invalid version of Plex installed locally or something.
