### ISSUE TITLE
Please add more icons to the default icon library

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#151]
You can integrate some icons from IBM Design Language or from projects like Fontawesome.

**Comment by hellobrian** [comment]
All of our icons are from IBM Design Language, we only include a subset of the entire icon set because our design system has mainly been product-focused. Our products only use some of the icons, not all of them. 

As far as I know, Fontawesome only uses icon fonts and [we only wish to ship SVG](https://github.com/carbon-design-system/carbon-icons/issues/11) ;D 

I would also find it odd to integrate a set of other well-established assets that are already widely available on Fontawesome. 

Fontawesome is available [here](http://fontawesome.io/icons/) and there's nothing stopping you or anyone from using them with carbon-components. 

If you really need a specific icon added to carbon-icons, make a PR to carbon-icons. I'd love to hear more about what your use-case is.

**Comment by hellobrian** [comment]
Welp! Hope this clarifies our side of the story when it comes to adding icons. Going to close for now. If you have any future questions or requests for icons, you can make an issue in the [carbon-icons](https://github.com/carbon-design-system/carbon-icons) repo.
