### ISSUE TITLE
[Question]: Package Warning 

### ISSUE THREAD

**Issue by SujithPriyamRajan** [carbon-design-system/carbon#15243]
### Question for Carbon

#2412  
Hi Team,

We maintain our react application in version of **react --> 18.2.0** 
but carbon has a peer dependency on  **"react": "^16.8.6 || ^17.0.1",** 

this issue has a warning which is inevitable 
we suggest to move you peer dependency to match the range of the latest version of react & react-dom

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by guidari** [comment]
Hey @SujithPriyamRajan if you are talking about Cabon v10, we currently have no plans to make this change, since v10 is in maintenance mode.

In Carbon v11 we do have the peer dependency for v18.2.0

```
  "peerDependencies": {
    "react": "^16.8.6 || ^17.0.1 || ^18.2.0",
    "react-dom": "^16.8.6 || ^17.0.1 || ^18.2.0",
    "sass": "^1.33.0"
  },
```

Here it is a few useful links:
https://github.com/carbon-design-system/carbon/blob/main/docs/release-schedule.md#maintenance
https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md
