### ISSUE TITLE
[Question]: Scale Visual Elements To Improve Accessibility

### ISSUE THREAD

**Issue by migatt** [carbon-design-system/carbon#15453]
### Question for Carbon

First of all, thank you very much for providing this brilliant library.

I'm wondering if there are any form of best practices on how to increase the size of the visual elements (`@carbon/react`) to improve accessibility for certain user groups. If anyone could point me in the right direction I would be very grateful!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Generally we recommend projects rely on the default browser behavior - zoom, text size, etc. so that users can specify their own preferences for size. All our layout tokens and sizing properties use `rem`, so changes to font size or zoom should impact the entire scale of your app if you're using the design tokens.

There are also some new experimental density/sizing controls that we'd like to get more feedback on. They're called "contextual layout tokens" and are [documented here](https://github.com/carbon-design-system/carbon/blob/main/packages/styles/docs/sass.md#contextual-layout-tokens). The idea is that you can redefine these tokens to change all or part of your app to be more dense, less dense, smaller components, larger components, etc.

I hope this helps! I'm going to close the issue but happy to answer more questions if you have them.
