### ISSUE TITLE
[Dev] Data Table Implementation (Overflow menu)

### ISSUE THREAD

**Issue by Kritvi-bhatia** [carbon-design-system/carbon#15480]
"By default, the overflow menu icons are persistent on each row. Having the overflow menus always visible signals to the user actions can be taken on the table rows. Alternatively, a product team may use the overflowMenuOnHover prop to only show the **overflow menu on hover** and focus to reduce the visual clutter of an overflow menu on every row" 
_[Source](https://carbondesignsystem.com/components/data-table/usage/#overflow-menu)_

### **TO BE UPDATED :** In the [storybook](https://deploy-preview-15336--v11-carbon-react.netlify.app/?path=/story/components-datatable-toolbar--playground), by default state should be the menu icons are persistent on each row. 
Currently, we can add this under feature flag.

**CURRENT STATE :** Currently, we're having the over flow menu hover state as by default.
<img width="920" alt="image" src="https://github.com/carbon-design-system/carbon/assets/148799271/32407dd0-974a-48ce-9a51-43bee9c9104f">

------
References: 
- [Data Table Figma File Audit](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=28-147&mode=design&t=Tk3B3RGYDYwcQ3p7-4)
- [Data Table Figma File Solution](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=389-4264&mode=design&t=Tk3B3RGYDYwcQ3p7-4)

**Comment by tay1orjones** [comment]
@Kritvi-bhatia This can currently be done with the `overflowMenuOnHover` prop. [Here's an example](https://react.carbondesignsystem.com/?path=/story/components-datatable-toolbar--playground&args=overflowMenuOnHover:!false), you can configure the controls to toggle the prop.

I think we can close this issue _unless_ we want to mandate this change to always be visible. If we want it to be a configurable option like it already is, I think we can close this one.

**Comment by tay1orjones** [comment]
After discussing further, the determination is this will just be changing `overflowMenuOnHover` to be `false` by default. It's already mentioned on the website to be this way, so this unifies the implementation against the current documentation. This isn't new design guidance either, it's been present for quite a while on the website.

We think this does not constitute a breaking change because:
* This is a meaningful improvement to usability and accessibility for all users 
* It has a relatively low surface area and should not impact existing application test harnesses
* `overflowMenuOnHover` remains configurable - consumers can set it to `true` if they prefer the old functionality

**Comment by Kritvi-bhatia** [comment]
HI @tay1orjones, can you please help me understand what is this "[persistent](https://arc.net/l/quote/djrddpxn)" boolean is for? 
![image](https://github.com/carbon-design-system/carbon/assets/148799271/1985ef20-e1c0-4865-aef2-bf53624129b3)

**Comment by guidari** [comment]
Hey @Kritvi-bhatia17 
The persistent prop makes the search functionality not expandable and persistent.

Example: https://react.carbondesignsystem.com/?path=/story/components-datatable-toolbar--persistent-toolbar

**Comment by mranjana** [comment]
hi @guidari , Can i work on this?

**Comment by guidari** [comment]
Sure @mranjana I'll assign you!
