### ISSUE TITLE
[Bug]: Overflow Menu moves the focus to previously selected item

### ISSUE THREAD

**Issue by Vanitha-Allwin** [carbon-design-system/carbon#15524]
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Package version

8.41.2

### React version

18.2.0

### Description

When overflowmenu is opened, it moves the focus to previously selected item. This causes trouble when there is a scroll in the page/table. After the menu is opened, the scroll moves to the previously selected item. 

![image](https://github.com/carbon-design-system/carbon/assets/156284189/3d243e32-47a1-44ac-96ed-440c97623c67)

### Reproduction/example

https://codesandbox.io/p/sandbox/gracious-wilson-66qhg9

### Steps to reproduce

Please have more than one overflow menu in the same page (page should have scroll) and access the first and last menu. When the menu is accessed the second time, the focus moves back to previously selected overflow menu icon

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

React application 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kuri-sun** [comment]
Hello @Vanitha-Allwin,
I saw the Sandbox, but I don't think we can see the bug that you described...
Could you help me how to reproduce that?

**Comment by Vanitha-Allwin** [comment]
Please select the last menu in the page and select any other menu. The focus moves and menu does not open for second click.

**Comment by kuri-sun** [comment]
Thank you for the explanation! I understood. I am going to take a look at it, thanks!

**Comment by tay1orjones** [comment]
@Vanitha-Allwin Is this behavior what you're referring to?


https://github.com/carbon-design-system/carbon/assets/3360588/aa1a5a2d-4ba1-4cee-90ae-c3ee0c6faf55

**Comment by Vanitha-Allwin** [comment]
Yes

**Comment by tay1orjones** [comment]
The new OverflowMenu implementation behind the `enable-v12-overflowmenu` flag [also suffers from this](https://stackblitz.com/edit/github-hxghmq?file=src%2FApp.jsx), plus it intersects with https://github.com/carbon-design-system/carbon/issues/15521

Ideally OverflowMenu would work identically whether you've scrolled the element out of view or not. I also noticed the bug happens even if the overflowmenu is rendered out of view by just a bit (without scrolling).


https://github.com/carbon-design-system/carbon/assets/3360588/f93fa837-b674-42fd-a293-c8b6caa65c79



My guess is something's going awry within [FloatingMenu](https://github.com/carbon-design-system/carbon/blob/36685a0be5e62db11a60d938c76b1c49a402c99a/packages/react/src/internal/FloatingMenu.js). Debugging this and stepping through carefully will probably surface what's going on.

**Comment by finken2** [comment]
I came to the repo to open this same bug.  [Here's another sandbox](https://stackblitz.com/~/edit/github-dza35r-tbjsst?file=src%2FApp.jsx) that @crhuff-ibm created a couple weeks ago (although it doesn't look like you need it).

Another thing that would work for us: Can we get a prop that allows us to say "no tooltip" on the overflow menu? We really don't need the intrusive "Overflow menu" tooltip popping up every time someone uses the menu.

**Comment by tw15egan** [comment]
@finken2 I believe the tooltip is an a11y requirement for any icon only button, is that correct @mbgower ?

**Comment by finken2** [comment]
i'm sure it needs some aria info and maybe title text, but hopefully not a big ol' rendered tooltip.

**Comment by mbgower** [comment]
> @finken2 I believe the tooltip is an a11y requirement for any icon only button, is that correct @mbgower ?

Unlabelled buttons traditionally have a tooltip (if you begin to make a new comment on this github page, just have a look at them all in the rich text editor in github).
![image](https://github.com/carbon-design-system/carbon/assets/14298245/0bf6b72f-36d5-4d03-90e6-9784be1c8931)
 There are obvious reasons why it's good to explain to a user what an unlabelled button does. The a11y need is that the moment something shows a tooltip via mouse hover, there must be a way to show it via keyboard, in order to meet [WCAG 2.1.1](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html). 

Whether or not an unlabelled button should always have a tooltip for _anyone_ is a matter of debate. If no one can tell what a button does, everyone is encountering the same experience, so it's not an accessibility issue per se. 

Again, looking at this github experience, you'll notice that in this page of comments, the ellipsis button (the horizontal equivalent of the overflow menu kebab) for each comment does not have a label in github, nor does the smiley face icon. These _do_ have accessible names, but github does not display a tooltip. Oversight or intentional design?

> We really don't need the intrusive "Overflow menu" tooltip popping up every time someone uses the menu.

The fact a design puts a icon button in the same position of every row in a table (to pick a fairly common use case) makes it seem a little redundant to keep showing a tooltip saying the same test. I guess one thing I wonder is 'why doesn't each of these closely positioned buttons have some distinguisher in the tooltip so a user can differentiate the action?" It would be simple to concatenate a text distinguisher for each row of data. This especially helps low vision users, who need to distinguish which row they are on, yet cannot see enough of the row at once to get that context. Say it's a delete button. "Delete row 23" would be useful (if the rows were numbered); "Delete vm 21" (or whatever) would be even more useful.
