### ISSUE TITLE
Create website variant of Side-nav

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#1559]
Moved from https://github.com/carbon-design-system/carbon-website/issues/415

Goal from @shixiedesign 
(See below for updated designs and specs)

**Comment by aagonzales** [comment]
side note: can we name it something else besides `side-nav` since it will have different behaviors than the product side-nav? Like "website-nav" or "fixed-side-nav"

**Comment by joshblack** [comment]
@aagonzales definitely down for fixed side nav 👍 What kind of differences are there from the current UI Shell work?

**Comment by aagonzales** [comment]
Its got different row heights (website 32, product 48) and the side-nav in product has the collapsed bar feature and the website one collapses into a hamburger menu (but only at small break points).

**Comment by shixiedesign** [comment]
Site navigation (dark and light). For @jeanservaas 's reference. 
https://ibm.box.com/s/wf8br6zdln6hpwyocbqjuetgvvgbmcqw

![nav dark](https://user-images.githubusercontent.com/15144993/50186804-97d92b80-02e1-11e9-8de4-8c9883709d31.png)
![nav light](https://user-images.githubusercontent.com/15144993/50186805-97d92b80-02e1-11e9-8941-9d8dd705ba5f.png)

**Comment by jeanservaas** [comment]
## Website Side Nav Specs and Design

Sketch file: https://ibm.box.com/s/6pvun9ccxrolzzmqfcseejfkj30x57a0

- This should not be confused with the product shell, basic geometries are the same but it has a different job to do

- Ideal state, G100 theme side nav on homepage; White theme side nav for everything else

- Spacing has been updated to 32px link item heights everywhere (instead of 48px for categories and 32px for nested items)

- Colors have been updated to use the new Gray 100 theme tokens (type tokens are listed as well)

- Indents have been added for nested items (so the background tint has been removed)

- Breakpoint behavior and App Switcher specs are illustrated in the file

## Specs and tokens

![website_sq_specs dark homepage_only](https://user-images.githubusercontent.com/43144260/50613731-29c96280-0ea4-11e9-8093-752648e65185.png)


![website_sq_specs light](https://user-images.githubusercontent.com/43144260/50607003-6473d080-0e8d-11e9-91f1-7d673f0f90e5.png)


## States

![left nav](https://user-images.githubusercontent.com/43144260/50607056-88371680-0e8d-11e9-93cb-6ef06bec4a3e.png)

![left nav scroll](https://user-images.githubusercontent.com/43144260/50607060-8c633400-0e8d-11e9-95e1-37e5d52b6360.png)

![app switcher](https://user-images.githubusercontent.com/43144260/50607065-908f5180-0e8d-11e9-93b0-c0cb6e6a581b.png)


## Responsive Behavior

![image](https://user-images.githubusercontent.com/43144260/50607090-a7ce3f00-0e8d-11e9-8f0d-61efa570c8e3.png)
