### ISSUE TITLE
Incorrect tooltip styling

### ISSUE THREAD

**Issue by Dr-KiranJogu** [carbon-design-system/carbon#1567]
## Title line template: [Title]: 
In the latest carbon-components, the `.bx--tooltip div` has `align-items: flex-end;` . This is making the tooltip content to be displayed right aligned.  It should be `align-items: flex-start;`. 

## Detailed description
In the latest carbon-components, the `.bx--tooltip div` has `align-items: flex-end;` . This is making the tooltip content to be displayed right aligned.  It should be `align-items: flex-start;`. 

> Is this issue related to a specific component? 
Tooltip
  "carbon-components": "^9.61.1",
    "carbon-components-react": "^6.59.0",

**Comment by Dr-KiranJogu** [comment]
jmancilla@ibm.com
cc @jnm2377

**Comment by asudoh** [comment]
Hi :wave: given the element in question has `flex-direction: row`, `align-items: flex-end` is making the content bottom-aligned IIRC instead of right-aligned. Also, feel free to assign your custom CSS classes to override our style to get the desired style. Thanks!

**Comment by alisonjoseph** [comment]
Tagging @aledavila since you worked on this, but I think the fix would be to specifically set styles on `.bx--tooltip__footer` instead of `.bx--tooltip div` which is what we are currently doing. So its causing any div to align to the bottom. 🤔

**Comment by jnm2377** [comment]
@Dr-KiranJogu as @asudoh mentioned, the `align-items: flex-end` is making the items all align at the bottom as opposed to the top. I just want to clarify your issue, though. When you said all the content was _justified to the end of the div_, did you mean _"end"_ as in `right-aligned` or _"end"_ as in `bottom-aligned`? I just wasn't sure from your image if the problem was that you wanted to have the bold content on the left side, or you wanted the content at the top. 

Pasting this image from slack for reference on what his issue was @alisonjoseph @aledavila @asudoh 
> the issue with this styling is … all the tooltip content is justified to the end of the div

![image](https://user-images.githubusercontent.com/32556167/50166586-0059e580-02ad-11e9-8272-847a4c994725.png)

**Comment by aledavila** [comment]
Thanks @alisonjoseph. 

@Dr-KiranJogu Just to clarify flex-end is applying to the footer div and needs it, but I've changed styles so it directly applies to only footer and not other divs.

**Comment by Dr-KiranJogu** [comment]
Hi @aledavila ,
Thanks for fixing the issue.
The flex-end is getting applied to all the div s in the `.bx--tooltip`. The following figure clarifies that.

Your fix (above pull request) will solve this issue as it directly applies to only footer and not other divs.

Please let me know in which version the fix will be available, once the fix is merged.  Thanks

![image](https://user-images.githubusercontent.com/43074433/50199157-58f4b580-0375-11e9-8311-d1574dfe54cd.png)

**Comment by aledavila** [comment]
@Dr-KiranJogu bug fix has been merged. should expect to see it shortly.
