### ISSUE TITLE
[Dropdown: Combobox & Multiselect]: Focus state dev implementation

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon#15698]
Closes [#768](https://github.com/carbon-design-system/carbon-design-kit/issues/768)

## The problem

We recently have updated downshift which has resulted in changes to our focus states with the new guidance of [1.2 combo box change](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/). 
- Update Dropdown, Combobox and Multi-select (parent's and child's) focus states in the All themes Figma library to reflect these changes for both fixed and fluid styles.
- Add the missing state also 

## The solution

Ref : [Figma branch link](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/YoOEBjLBbiZbGsU1C3AMXf/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-308516&mode=design&t=XODtWWTjax6UXS7m-0)

_To update:_
### Dropdown
> **Default**
> - [ ] In this case, the parent child will not have the focus state when expanded.
> ![image](https://github.com/carbon-design-system/carbon/assets/158570656/87b03244-e8ee-4b8a-9307-25fd05a83ba1)

---

### Dropdown - Combobox
> **Default**
> - Remove the hover state from the Dropdown - Combo box - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291111&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291154&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> ![image](https://github.com/carbon-design-system/carbon/assets/158570656/32c43455-c30c-44c4-8e92-3b7b40a67bc8)

> **Fluid**
> - Remove the hover state from the Dropdown - Combo box - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291111&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291154&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> ![image](https://github.com/carbon-design-system/carbon/assets/158570656/9e898bf2-cba3-4032-bc52-c5f570820a1c)

---

### Dropdown - Multi-select
> **Default**
> - Add focus and hover state in the Dropdown - Multi-select - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291471&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291592&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> - [ ] The focus state for the child will be on the first selected option.
> ![image](https://github.com/carbon-design-system/carbon/assets/158570656/5e0a778d-dc45-4d72-9dd6-5c66f4516d15)

> **Fluid**
> - Add focus and hover state in the Dropdown - Multi-select - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291471&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291592&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> - [ ] The focus state for the child will be on the first selected option.
> ![image](https://github.com/carbon-design-system/carbon/assets/158570656/241a2573-403b-4904-bee7-d339c33bef9c)

> **Filterable - Multi-select**
> - Add focus state in the Dropdown - Multi-select - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291471&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291592&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> - [ ] The focus state for the child will be on the first selected option.
> ![image](https://github.com/carbon-design-system/carbon/assets/158570656/981fc330-c239-4d31-a632-6522ad33cbd8)

---

**Comment by tay1orjones** [comment]
@Kritvi-bhatia17 @laurenmrice is this a valid dev issue? We're not sure what the work here would be.

**Comment by Kritvi-bhatia17** [comment]
> @Kritvi-bhatia17 @laurenmrice is this a valid dev issue? We're not sure what the work here would be.

Hi @tay1orjones, so we would be needing to update these changes in storybook as well.

**Comment by tay1orjones** [comment]
I believe the storybook has most of the changes highlighted in the "after" screenshots. @Kritvi-bhatia17 Could you double check the current storybook and outline the specific changes we need to make in the storybook (styling/stoke changes, etc)?

**Comment by Kritvi-bhatia17** [comment]
Sure @tay1orjones, will do that!

**Comment by Kritvi-bhatia17** [comment]
Hi @tay1orjones @tw15egan,  I've made some updates to the issue and have included tasks under each category of dropdowns.

**Comment by Kritvi-bhatia17** [comment]
Hi @tw15egan!

As we discussed earlier, I've reached out to @michael to clarify a few things. Here are the points and insights I've gathered:

1. The mouse and keyboard interactions regarding the focus state will be consistent. So, whatever is depicted in the updated Figma kit images above will be implemented for both mouse and keyboard interactions.
2. I've noticed a minor bug - I'm unable to deselect any option in the dropdown, as shown in the video.
https://github.com/carbon-design-system/carbon/assets/158570656/7f69706a-a02a-49d0-8e77-a8b75d2c1c4b
3. The focus state will remain active even if we move the mouse cursor away from it, as demonstrated in the video.
https://github.com/carbon-design-system/carbon/assets/158570656/c4b9a185-4c6d-4ca6-840d-4a118f9a1d91

We can further discuss these points over a call to decide on the next steps for this issue, or if there's a need to create a new one.

**Comment by mbgower** [comment]
Yeah, and to explain the basic rationale here, it's not that removing the focus indicator from Option 1, as a result of mouse movement, is WRONG. It's that splitting keyboard and mouse interaction like this is likely to result in issues not that apparent, and so easily compounded.
This is a perfect example: when removing the focus indicator, the focus has also been altered.
To reproduce:
1) Open the dropdown, either with kb or mouse. Focus will be on selected subcomponent
2) Hover over the focused subcomponent, and then move pointer away from the dropdown. DON'T CLICK or in any way put something else in focus.
3) Now press the Down Arrow. Since focus has not been moved, expectation is that Option 2 will receive focus. Instead, the focus goes to the _first_ item in the drop down, in this case Lorem ipsum... 

In other words, the visual effect to remove the keyboard focus has actually triggered a REAL change of focus. IN a situation with a few items this seems a bit annoying. Imagine I've moved to the 30th position in the dropdown, move my mouse intentionally or unintentionally, and then try to act on the 30th item. My focus has returned to the top of the list. Not only may a user be very confused (especially if they have visual disability), but time on task has obviously taken a huge hit.

Taking the focus indicated off the dropdown item does not inherently mean it has to lose focus, but increases the likelihood of any issue not being discovered. Alternatively, leaving the focus on the dropdown item makes it much more likely that until the focus is actually moved somewhere by the user, their point of regard in the application is going to be maintained.
