### ISSUE TITLE
[Bug]: Accordion not closing when open prop is controlled from outside

### ISSUE THREAD

**Issue by BenceLovas** [carbon-design-system/carbon#15707]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.49.0

### React version

18.2.28

### Description

Accordion should be closed like this:
![image](https://github.com/carbon-design-system/carbon/assets/27259065/e205d442-f2a9-4bde-b47f-4f19d0c3b8fd)
But it is stuck like this:
![image](https://github.com/carbon-design-system/carbon/assets/27259065/be28818b-3ef2-4d88-a83d-381ec85efa6e)

I think this issue is related to: https://github.com/carbon-design-system/carbon/issues/15438

### Reproduction/example

https://codesandbox.io/p/devbox/goofy-liskov-2ljg99?file=%2Fsrc%2FExample%2FExample.jsx%3A12%2C18

### Steps to reproduce

1. Click 'Collapse all' button
2. Expand the first accordion by clicking on the accordion itself
3. Click 'Expand all' button
4. Click 'Collapse all' button

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by chrisdudley** [comment]
I'm seeing the same issue (using 1.50.0 and react 18.2.0)

**Comment by tay1orjones** [comment]
Yeah here's [another repro](https://stackblitz.com/edit/github-trp7pj?file=src%2FApp.jsx) I made 


https://github.com/carbon-design-system/carbon/assets/3360588/b169281d-d84f-4344-b36a-57a5df4d0a0c

The problem is specifically isolated to collapse for some reason after manually opening an AccordionItem. Expanding all and then trying to collapse all works. @guidari do you want to take another pass at this? It seems https://github.com/carbon-design-system/carbon/pull/15589 and https://github.com/carbon-design-system/carbon/pull/15676 didn't quite fix this bug all the way.
