### ISSUE TITLE
[Bug]: Dropdown skeleton state missing label

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#15853]
### Package

@carbon/react, @carbon/styles, carbon-components, carbon-components-react

### Package version

Latest

### Description

It appears that skeleton state of Dropdown component is missing the label. Only the field itself get skeleton-ized, and label went missing. This caused a small page jump when loading. Other common form inputs has the label in skeleton state already.

Also, because storybook doesn't contain the skeleton states of these components, I couldn't check what they are: 
- Multiselect
- Combo box
- Time picker

<img width="1054" alt="image" src="https://github.com/carbon-design-system/carbon/assets/15144993/e1d7800b-68f6-4606-b254-754caa4f46ac">

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-dropdown--skeleton

### Steps to reproduce

Click through for skeleton state story and look for label

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
> skeleton state of Dropdown component is missing the label

Interestingly, the DOM node is there, it's just not getting the appropriate styles it seems. I'm not sure why, but it's the same way [in v10]( https://v7-react.carbondesignsystem.com/?path=/story/components-dropdown--skeleton) as well. Also there is no `hideLabel` option. Maybe this was intentional at one point, but I think we should add the label in by default so there's no page jump when swapping out the skeleton for the real component, and also add the `hideLabel` option to toggle the rendering of the label or not for cases where a label isn't used on the real component.

> Also, because storybook doesn't contain the skeleton states of these components, I couldn't check what they are:
>
> 1. Multiselect
> 1. Combo box
> 1. Time picker

MultiSelect, FilterableMultiSelect, Combobox, and Dropdown are all part of the "Dropdown family", so the intent is for all of these components you would use the Dropdown skeleton. All the more reason why we should fix the label issue above.

Timepicker is a combination of TextInput and Select components. For a skeleton state experience you should be able to use the TextInputSkeleton without `hideLabel` next to 1-2 SelectSkeleton components with the `hideLabel`.
