### ISSUE TITLE
[Bug]: Button - Icon Button - kind = "danger--ghost", icon is not centered

### ISSUE THREAD

**Issue by paul-balchin-ibm** [carbon-design-system/carbon#15851]
### Package

@carbon/react

### Browser

Chrome

### Package version

1.51.0

### Description

Seemingly, only for the Icon Button variant and where kind = "danger--ghost", the icon is not centered in the button.

### Screenshots

What I see:

![image](https://github.com/carbon-design-system/carbon/assets/52505287/412b64f1-9ba4-4558-b047-c97f2a85ea5e)

What I expect to see:

![image](https://github.com/carbon-design-system/carbon/assets/52505287/0ebae3b2-8684-4a8e-8331-bd4c34617d47)

### Steps to reproduce

1. Open https://react.carbondesignsystem.com/?path=/story/components-button--icon-button&args=kind:danger--ghost.
2. Click **Controls** tab.
3. Scroll down to **kind**.
4. Select "danger--ghost" from drop down.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @paul-balchin-ibm, thanks for bringing this up. While you can technically put the component in this state both in code and in storybook, icon only buttons do not support Danger, Danger tertiary, or Danger ghost. This is called out in the [spec](https://carbondesignsystem.com/components/button/usage/#icon-only-buttons:~:text=Icon%20buttons%20can%20take%20the%20form%20of%20a%20primary%2C%20secondary%2C%20tertiary%2C%20or%20ghost%20variant) and the [Icon-only Buttons](https://react.carbondesignsystem.com/?path=/docs/components-button--overview#icon-only-buttons) section of the storybook docs.

Hope this helps, and sorry for the confusion. Due to the circular dependency between Button `hasIconOnly` and IconButton, it's very difficult to write conditional prop warnings to alert you of this in the browser console.
