### ISSUE TITLE
[a11y]: 4.1.2 Name, Role, Value The element with role "button" contains descendants with roles "checkbox" which are ignored by browsers

### ISSUE THREAD

**Issue by jan-adamski** [carbon-design-system/carbon#15911]
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

7.59.16

### React version

17.0.2

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Description

It seems that component SelectableTile can trigger 'The element with role "button" contains descendants with roles "checkbox" which are ignored by browsers' issue - described here https://able.ibm.com/rules/archives/latest/doc/en-US/aria_descendant_valid.html
<img width="1481" alt="image" src="https://github.com/carbon-design-system/carbon/assets/162590599/35ce6968-3d17-4090-82dc-4e9aa914bbc0">

### Reproduction/example

https://stackblitz.com/edit/github-hxj1cs?file=src%2FApp.jsx

### Steps to reproduce

You can try to use IBM Equal Access Accessibility Checker to reproduce

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tw15egan** [comment]
Hey there @jan-adamski , this seems to be an implementation issue rather than an issue with the Carbon component itself. Like the error states, you can't have something with a role of checkbox inside of a button, which the tooltip trigger is. One workaround would be to move the `TooltipIcon` as a child of `SelectableTile` instead, [like so](https://stackblitz.com/edit/github-jmuqds?file=src%2Findex.scss,src%2FApp.jsx). Hope that helps!
