### ISSUE TITLE
[Bug]: Toggle control "labelText" attribute should accept node

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#15928]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.52.0

### React version

v16.13.1

### Description

In Carbon v10, `labelText` used to support a react element `node`. Ref - https://v7-react.carbondesignsystem.com/?path=/docs/components-toggle--default

However is carbon v11, `labelText` only supports a `string`. Ref - https://react.carbondesignsystem.com/?path=/story/components-toggle--default

Opening this issue to add support for `labelText: node` in Toggle component in carbon v11. 

### Reproduction/example

https://stackblitz.com/edit/github-qfd97u?file=src%2FApp.jsx

### Steps to reproduce

In above stackblitz example, there's a warning in console -
```
Failed prop type: Invalid prop `labelText` of type `object` supplied to `Toggle`, expected `string`
```

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by janhassel** [comment]
Hi Neha! If you want to use a custom label, you can use the Toggle component like this:

```jsx
<div
 id="my-toggle-label"
>
  Custom label (node)
</div>

<Toggle
  id="toggle"
  hideLabel
  aria-labelledby="my-toggle-label"
/>
```

Take a look at the "With accessible labels" story of the component for more examples: https://react.carbondesignsystem.com/?path=/story/components-toggle--with-accessible-labels

---

*Note: in the latest release there's an issue with `aria-labelledby` not being set correctly but it has since been fixed (#15845) and should therefore be included in the next release.*
