### ISSUE TITLE
[Bug]: [Tabs] Storybook warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/carbon#16051]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.53.1

### React version

v18.2.0

### Description

Seeing a warning in console for `Tabs` components - `Warning: Each child in a list should have a unique "key" prop.`

`key` is not a prop in any of the `Tabs, TabList, Tab, TabPanels, TabPanel` components. 

![Screenshot 2024-03-25 at 10 21 05 AM](https://github.com/carbon-design-system/carbon/assets/25124000/57f555ef-0a0b-4587-88fc-81c18e5032d1)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-tabs--playground

### Steps to reproduce

Please see description. 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
We've been seeing this error in Storybook for quite some time. We can look into it a bit closer, but my understanding is that this is probably a bug in Storybook itself, not anything to do with these components. We should confirm though.

**Comment by tay1orjones** [comment]
`key` isn't documented in the prop tables, but's inherently supported in every component because we spread any additionally passed props onto a child within every component via `...rest` or `...other`

https://github.com/carbon-design-system/carbon/blob/04e231fabe07d1f51b67a73a6f38ec7d479bb05e/packages/react/src/components/Tabs/Tabs.tsx#L789-L800
https://github.com/carbon-design-system/carbon/blob/04e231fabe07d1f51b67a73a6f38ec7d479bb05e/packages/react/src/components/Tabs/Tabs.tsx#L880-L882

**Comment by tay1orjones** [comment]
[It appears](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1711484730418019?thread_ts=1711387130.845819&cid=C2K6RFJ1G) that placing a key on `tab` doesn't actually work. Maybe it's due to the `cloneElement` being used on the children?

https://github.com/carbon-design-system/carbon/blob/04e231fabe07d1f51b67a73a6f38ec7d479bb05e/packages/react/src/components/Tabs/Tabs.tsx#L588-L592

I'm not sure though because `key` and other props [should be filled in via cloneElement](https://react.dev/reference/react/cloneElement#parameters):

> The rest of the props will be filled from the original element.props. If you pass props.key or props.ref, they will replace the original ones.

**Comment by alisonjoseph** [comment]
@nmgokhale can you make sure you are passing a key to both the `Tab` and `TabPanel`? I was able to fix the errors in storybook by adding this.

**Comment by nmgokhale** [comment]
Thanks @alisonjoseph. Warning is fixed after adding key to both `Tab` and `TabPanel`.
