### ISSUE TITLE
[MultiSelect - FilterableMultiSelect]: Consistent interaction to open/close the dropdown via the badge

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon#16110]
### The problem

Tapping on the counter badge when the multiselect/filterablemultiselect dropdown is open, closes it. But tapping on the badge when the dropdown is closed doesn't open it. This interaction is inconsistent and leads the user to having to moving the cursor point between opening and closing the dropdown.

### The solution

Make the multiselect dropdown behaviour consistent while opening and closing 

- Option 1: Remove the interaction that closes the dropdown by clicking on the badge. Limit opening and closing dropdown by only clicking on the input field.
- Option 2: Add interaction to open the dropdown by clicking on the badge, when the dropdown is closed.

**Comment by tay1orjones** [comment]
The tentative plan here is to approach Option 1 - it's likely easier to implement (possibly with something as simple as `pointer-events: none;`). If we dig in and hit a ton of resistance, we could pivot to explore Option 2.

In any case it could also be beneficial to test these against user expectations.

**Comment by guidari** [comment]
@tay1orjones After taking a look in this issue I figure that the closing behaviour happens because of the `onBlur` action and not because that the Tag is clickable.

We can not use the Option 2, because the filter tag (or new dismissible) should not take any action when the badge is clicked, but only the Close Icon. 

To fix that we would have to add event listener to select the tag using a `document.querySelector()` and take no action if the `span` is clicked. But I would prefer to keep as it is instead of adding `document.querySelector()`.

**Comment by tay1orjones** [comment]
So based on this exploration what we have now follows the spec for both the input, as well as the tag. For now we'll keep this as is since there's no clear path of either having to diverge from the tag spec or the input spec.
