### ISSUE TITLE
Classify notifications, and explore how its variants fit within the design system

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#16220]
## Acceptance criteria

- [x] Evaluating the information architecture of our Design system (Components, Patterns, etc) so that there's clarity on  how notifications and its sub components should be classified in our system
- [x] Collecting data across internal and external design systems on the various ways users are kept informed in the product.
- [x] Document how notifications should be classified across our design system
- [x] Playback to dev/design/a11y team

**Comment by benjamin-kurien** [comment]
<img width="841" alt="image" src="https://github.com/carbon-design-system/carbon/assets/158569631/41363de6-7f30-4ef1-81eb-b481fab10224">

**Comment by Kritvi-bhatia17** [comment]
I need to do some competitor research to explore more types of notifications. Currently, the flowchart is based on what is mentioned in our documentation and on C4IP products.
![Image](https://github.com/carbon-design-system/carbon/assets/158570656/f879b110-8470-4fa0-88b7-5f8b3d1c9b84)

**Comment by benjamin-kurien** [comment]
Initiated work on evaluating our design system to understand how notifications should be classified across its various sections. 

The following were defined: 

Guidelines & Assets: Guidelines help create new components and layouts, so that they are aligned to the carbon design language. (They may also include a library of graphical elements that can be used as design assets)

Components: Components are visually styled modular blocks that fulfil a function. (Components can have multiple visual variants that fulfils the same function) 

Patterns: Patterns are UX recommendations that use a combination of components, layouts and guidelines to solve common user and business needs. 
 
Layouts: Layouts are common templates by which components can be used in design. They are provided only for an ease to start, and can be changed according to our guidelines to meet specific product needs. 

-----

Notification falls under the definition of patterns as it provides a set of guidelines and UX recommendations that help communicate information from the business to the users about their actions. This pattern is achieved through a combination of components like Inline and toast messages, Modal, etc ... which will be further classified in the upcoming stream of work

https://ibm.box.com/s/8oez07m6vl6hlz39qr8lxrwgbm3hila4

**Comment by benjamin-kurien** [comment]
A framework to classify communication components was reviewed with the team. https://ibm.box.com/s/xwxuiikbniv73m7aivy0gat5rmmemkvk

By taking consideration of product needs and effective ways of communication, the framework created a way to classify existing components and provides a structure to create new components.

![Communication framework](https://github.com/carbon-design-system/carbon/assets/158569631/417a100d-91be-4e1c-8fb6-94506f545737)
