### ISSUE TITLE
[Feature Request]: (Pagination) Allow consumer to specify which pages the user can jump to

### ISSUE THREAD

**Issue by imp-dance** [carbon-design-system/carbon#16264]
### The problem

We have a pagination component for a table that contains `47840` pages. When attempting to open the select that can jump to an arbitrary page - the website freezes for several seconds before loading the select options because of the huge amount of options listed.

### The solution

My proposed solution is to allow the consumer of the component to specify a custom `renderSelectItems` function that can bypass the internal util used in `Pagination`. This would allow me to do something akin to the following example.

### Examples

```tsx
// If more pages than 1000, render every other page - if more than 10,000 - render every fifth. Else render every page.
<Pagination {...props} renderSelectItems={(total) => {
   const items: React.ReactNode[] = [];
   const iterationInterval = total > 10000 
      ? 5 
      : total > 1000 
         ? 2 
      : 1;

   for (i = 0; i < total; i=i+iterationInterval) {
      items.push(...);
   }
   return items;
}} />
```

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

I could create a PR to implement this change if I get a OK from the team

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by aagonzales** [comment]
Hi @imp-dance! The problem of the pagination select being unable to handle extra large page counts has come up before. The previously proposed solution to this problem was to use a text-input or number-input instead of a select so the user can go directly to a specific page instead of loading the problematic select. See issue https://github.com/carbon-design-system/carbon/issues/5546 so more details and references to previous issues. 

Would a solution like that work for your problem? If not, please share a visual example of your proposed solution so we can better understand how the controls would work from an UX  perspective.

**Comment by imp-dance** [comment]
> Would a solution like that work for your problem? If not, [...]

This would absolutely work in our case as well!
