### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MaJingyiUtt** [carbon-design-system/carbon#16266]
### Package

@carbon/react

### Package version

1.55.0

### React version

18.2.0

### Description

TreeView closes during onClick

### Reproduction/example

https://stackblitz.com/edit/github-3xhbda?file=src%2FApp.jsx

### Steps to reproduce

click on treeview, it closes

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
@MaJingyiUtt In your example you're changing the local state and rendering the value of the local state. `useState` by design triggers a re-render. I think what's happening is that on re-render the open/close state of the treeview is lost and so it appears to be going from open to closed but it's just rendering with the default state (closed).

If you remove the local state call from your example it works as expected, even with an onClick configured. https://stackblitz.com/edit/github-3xhbda-l9acpa?file=src%2FApp.jsx

You can fix this in a number of ways:
* Use `useRef` instead of `useState`
* Use the new [controllable API for TreeView](https://react.carbondesignsystem.com/?path=/docs/experimental-feature-flags-treeview--overview) to manually manage the open/close state
* Move the state down so it's in a lower part of the component tree so it won't cause the TreeView to re-render

**Comment by MaJingyiUtt** [comment]
Hello Taylor, thank you for your response !
I tried useRef but it has the same behavior.
I already tried the new version of Carbon, because I needed Slug, but it has a bug with UI Shell, so I reverted back to the version "@carbon/react": "1.33.0". 
Could you explain more about the third solution please? I didn't understand.
