### ISSUE TITLE
Mobile approach?

### ISSUE THREAD

**Issue by antonmc** [carbon-design-system/carbon#163]
Carbon sketch components seem to me focused on desktop apps. I do see a couple of elements in a mobile view. I wonder if there's guidance on how to use the elements in a mobile context, that I'm missing.

In particular, thinking about iPhone development - how do the Carbon elements correlate to iOS elements, and navigation flow. Or does it matter?

**Comment by hellobrian** [comment]
Maybe @aagonzales can give more clarity on this, but as far as I know, all components are designed with breakpoints in mind. 

We size the viewport to be bigger and smaller.
Once the component starts to look bad or function incorrectly, we make a breakpoint.

Since Carbon started as a very product-specific system, a lot of the components are created desktop-first and we make sure that they're responsive on smaller viewports.

As for your question about iOS, we've been more focused on usage within a web browser. All of our "elements" closely correlate with HTML elements where possible so that mobile OSes can interpret them as expected. 

For example,

Number Input, (`<input type="number">`) would trigger a Number Keypad on a users device when focused.

**Comment by antonmc** [comment]
I understand, and very much respect the honesty in the answer. It is a major achievement to create a style guide for the web, and I'm more convinced about the value of it, having used it now :) Break points are perhaps not obvious in a static design?

The app I'm designing, and building, is a web app and a desktop app. It is pretty normal to make both things. I struggled to use the components for a mobile app, especially as someone who designs mobile apps with a strong understanding of iOS view components ... and if I was daring there are no watch design components in the system either ;)

I appreciate the design components for how they sped me along with my bluemix influenced design. 

But why not take it to the next level? Think ahead ... we already have an iOS app for Bluemix in the formative stages. It doesn't feel related to this system right now. We _should_ be thinking mobile first. And I can even see a few amazing and exciting opportunities for a watch app too. It'd show even more mastery to evolve the design system that far.

**Comment by antonmc** [comment]
Cross referencing to my other comment about a quick video intro to using the components ... maybe that video, or a related one, could also show how to use them for a mobile app.

**Comment by aagonzales** [comment]
> In particular, thinking about iPhone development - how do the Carbon elements correlate to iOS elements, and navigation flow. Or does it matter?

Carbon does not current have native iOS or Android components. Bluemix does have native apps in development but we have not incorporated those elements directly into Carbon yet. Native apps have very different core function and interactions than websites. Even the difference been Android and iOS can be huge. We understand this and its why we don't say our components work for native apps, especially watch components.

Carbon came from the need of Bluemix which is web app but as we grow and more teams use it adding in a iOS and Android components will be the logical next step. But for now our resources are limited and we remain web focused for the time. We always welcome collaboration and teams contributing back to the system so if you'd like to use you're great knowledge of the iOS space and contribute guidelines or native components back to the system it would be more than welcomed!

As Brian said from the product level most of our users are desktop or larger screen users and therefore the product is not mobile first. However, from the Carbon side of things we try and make all our our components completely responsive. Some components don't have "mobile" counter parts in the kit because their widths are the only thing that change. If you're ever curious how a component responds and you don't see it in the kit you can check on the "view full render" states on [the code page](http://carbondesignsystem.com/components/detail-page-header/code) and drag the browser around to see it demonstrated live.

**Comment by chrisdhanaraj** [comment]
All that said, the long term vision of Carbon is to create a set of components that could be used on Android/iOS (I can imagine us building react-native components or something depending on what the driving framework is). Not in the current timeframe though, unfortunately!
