### ISSUE TITLE
The Inline Loading Component should allow text on the left

### ISSUE THREAD

**Issue by loganmccaul** [carbon-design-system/carbon#1659]
The Inline Loading component currently only allows text to be right of the loading spinner. There should also be an option for text on the left.

![jan-17-2019 14-58-17](https://user-images.githubusercontent.com/7374889/51348435-5bc3f280-1a68-11e9-90b1-0d08d7a1d186.gif)

I would love design input, but I can handle the development.

### Justification

Sometimes action items where an Inline Loader can appear are right aligned on the page. This leave limited room for a detailed loading message.

### Available extra resources

What resources do you have to assist this effort?

I am available for all development efforts.

**Comment by joshblack** [comment]
cc @IBM/carbon-designers how do you all feel about this?

**Comment by designertyler** [comment]
This makes sense to me. The success state checkmark icon isn't shown in the example, but wanted to make sure it would also be configurable.

I'm curious if there's any other design feedback about this. Right aligned text usually isn't encouraged.

**Comment by asudoh** [comment]
Hi @loganmccaul 👋 I tried to move around `<p data-inline-loading-text-active>` and `<p data-inline-loading-text-finished>` at `https://www.carbondesignsystem.com/components/inline-loading/code with DOM inspector to make them left, and I saw everything still works. That said, it's just the matter of changing the markup, which can be done application-side. Don't hesitate to let us know if you see otherwise - Thanks!
