### ISSUE TITLE
[Status indicators] Get telemetry for IBM Products status indicators in React

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#16597]
- [x] Reach out to @mattrosno for telemetry numbers to understand the number of usage instances and teams using the code.

**Comment by thyhmdo** [comment]
### Data From Matt: https://ibm-studios.slack.com/archives/C053X4RFYJ1/p1716997631661079 (May 29th)

Component data for @carbon/ibm-products. The first column is the number of unique repos per product. The second column is the total number of metrics per component, which will be higher for repos that are more active.


- StatusIndicator used in 34 repos, compared to DataGrid used in 1,921 repos (the most used component in this library).
- It has no props, so there's nothing to evaluate there.
- For some reason, it hasn't been in any scans since 4/14.
- We don't yet have product mappings live to see which products are using it.

[2024-05-29_ibm-products_components.csv](https://github.com/carbon-design-system/carbon/files/15487139/2024-05-29_ibm-products_components.csv)

![Screenshot 2024-05-29 at 10 45 23 AM](https://github.com/carbon-design-system/carbon/assets/77697351/92b97c0b-d9c0-4017-b434-1f7b05c1693b)

-----

Here are how often each StatusIcon prop and prop values are set, if you want to look at which size is used the most, kind breakdown, etc.


[Component prop values.csv](https://github.com/carbon-design-system/carbon/files/15487164/Component.prop.values.csv)
[Component props.csv](https://github.com/carbon-design-system/carbon/files/15487165/Component.props.csv)
