### ISSUE TITLE
why does Carbon grid xs gets applied to large devices?

### ISSUE THREAD

**Issue by anusha801** [carbon-design-system/carbon#1665]
I am using carbon grid system and I am trying to create a space between 2 elements like between a label and a text box like below.
   

    ` <div class="bx--row">
                    <div class="bx--col-lg-1 bx--col-md-1 bx--col-xs-1">    </div>
                  <div class="bx--col-lg-2 bx--col-md-2 bx--col-xs-11"  >
                   	<label  class="bx--label">Employee Name</label>
                   </div>
                   <div class= "bx--col-xs-1"></div>
                   <div class="bx--col-lg-8 bx--col-md-8 bx--col-xs-11">
    			 		<input type="text"  class=" bx--text-input">
    			  </div>
    			  </div>`

I have tried to put 
` <div class= "bx--col-xs-1 bx--col-lg-0 "></div> `but still the space is getting added on large devices like laptop.

**Comment by joshblack** [comment]
Hi @anusha801! 👋 Would you mind re-creating this issue in a codesandbox or codepen? Thanks!

**Comment by DusanMilko** [comment]
@anusha801 xs styles apply because it is a mobile first approach which is the proper approach. bx--col-lg-0 is not a valid class and shouldn't be.

@joshblack
I would like to request carbon team to add visibility classes for breakpoints so you could do:
bx--col-xs-1 bx--col-lg-hidden <- this hides for lg and up, could also add bx--col-lg-only-hidden to hide for that breakpoint only. I can make a pr if you would prefer, let me know

Like foundation has done:
https://foundation.zurb.com/sites/docs/visibility.html

**Comment by joshblack** [comment]
@DusanMilko great suggestion! Made an issue over in: https://github.com/carbon-design-system/carbon-elements/issues/515

If you want to do a PR real quick, that'd be awesome! Would love to include it in the next release 😄
