### ISSUE TITLE
[Bug]: Switcher element crashes application when a react fragment is passed as a child

### ISSUE THREAD

**Issue by ychavoya** [carbon-design-system/carbon#16916]
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

`> v1.42.1`

### React version

v18.2.0

### Description

When you add a React Fragment as a direct child of the `<Switcher>` component, the application crashes with the following error in the console:

```
Uncaught TypeError: WeakMap key Symbol.for("react.fragment") must be an object
```

![Screenshot 2024-07-04 at 10 51 21 a m](https://github.com/carbon-design-system/carbon/assets/7907338/f74b913b-7eb7-443c-b3b0-b20927d3e8d9)

Example in v1.42.1 where it was working
https://stackblitz.com/edit/github-jhr7bv?file=src%2FApp.jsx

### Reproduction/example

https://stackblitz.com/edit/github-jhr7bv-rzbbuj?file=src%2FApp.jsx

### Steps to reproduce

- Add a `<Switcher>` component
- Add a React Fragment with other things inside `<></>`
- Check the console for errors

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by 2nikhiltom** [comment]
Hey @ychavoya ,

The currently purpose of [Switcher](https://carbondesignsystem.com/components/UI-shell-header/usage/#anatomy) is to provides a way for the user to easily navigate between products and systems and expects a [SwitcherItem](https://react.carbondesignsystem.com/?path=/docs/components-ui-shell-header--overview) as its direct child and `SwitcherItem` is expected to have a link/href to redirect somewhere when clicked

Instead of modifying the Switcher component to accommodate this, it makes more sense for consumers to use a custom function or a package to flatten the array. One of the package could be   [react-keyed-flatten-children](https://www.npmjs.com/package/react-keyed-flatten-children#react-keyed-flatten-children) 

[react-keyed-flatten-children](https://www.npmjs.com/package/react-keyed-flatten-children#react-keyed-flatten-children) package makes sure that it flatten arrays and React.Fragments into a regular, one-dimensional array while ensuring element and fragment keys are preserved, unique, and stable between renders

What are your thoughts ?

**Comment by ychavoya** [comment]
Thanks @2nikhiltom, I understand the component is not actually intended to use fragments as children, we actually fixed our code by removing them. 

The main purpose of me raising this issue was because the application crashes completely when you do this without a clear indication that this is the issue unless you examine closer. 

If the solution makes the code too complex, would you think it useful to set the allowed children (SwitcherItem instead of any node) in the prop types so it shows a warning on code?
