### ISSUE TITLE
[Bug]: TabPanels throws an error when using conditional rendering

### ISSUE THREAD

**Issue by danielannan17** [carbon-design-system/carbon#16934]
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.61.0

### React version

v18.2.0

### Description

The page doesn't render due to the error.

### Reproduction/example

https://stackblitz.com/edit/github-g3gust?file=src%2FApp.jsx

### Steps to reproduce

None, errors in the logs

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jesnajoseijk** [comment]
@alisonjoseph @danielannan17 Can I take up this task ?

**Comment by benjambo13** [comment]
Is there any update on this issue?

If its of any use, we have this patch as a workaround - Adding the `child &&` before `cloneElement`:

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/675f66ba-fc02-4d5f-8d62-3f132e16f41a">

Which I believe would this line in the code base - https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Tabs/Tabs.tsx#L1723

We currently have to have Carbon pinned so the patch can be applied which is not ideal. Thanks in advance.

**Comment by s100** [comment]
I would strongly discourage patching Carbon in this way as this patch is brittle and would potentially require manually re-applying on every patch bump of Carbon - it would also involve pinning to a specific version of Carbon which forces downstream consumers to do the same.

A simple workaround would be something like this:

```jsx
const App = ({ showTab3 }) => {
  const tabs = [
    <Tab>1</Tab>,
    <Tab>2</Tab>,
    showTab3 && <Tab>3</Tab>
  ].filter(Boolean)

  const tabPanels = [
    <TabPanel>one</TabPanel>,
    <TabPanel>two</TabPanel>,
    showTab3 && <TabPanel>three</TabPanel>
  ].filter(Boolean)

  return (
    <div>
      <Tabs>
        <TabList aria-label={''}>
          {tabs}
        </TabList>
        <TabPanels>
          {tabPanels}
        </TabPanels>
      </Tabs>
    </div>
  )
}
```

**Comment by s100** [comment]
@Gururajj77 My statement "I would strongly discourage patching Carbon in this way" is directed towards @benjambo, who is using [a package called `patch-package`](https://www.npmjs.com/package/patch-package) to patch Carbon _after `npm install`_ - this is very difficult to consume. Likewise, my suggested workaround is aimed at people who are experiencing this bug.

Exactly what you, the maintainers of Carbon, should do _inside_ the Carbon code to _fix_ this bug is entirely up to you. @benjambo13's patch may be exactly what you need.

**Comment by tay1orjones** [comment]
@benjambo13 Conditionally rendering tab and tabpanel elements can run you into accessibility problems ([1](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#all_descendants_are_presentational:~:text=Some%20assistive%20technology,that%20element%27s%20id), [2](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/#:~:text=It%20is%20recommended,the%20tab%20list)). 

I know the stackblitz example is intentionally contrived to just show the issue you're having, but it's not a valid way to use these components from an accessibility perspective. Without the elements in the DOM, screenreaders probably will not be able to properly convey how many tabs there are. The `aria-controls` properties will not have valid id values since the elements don't exist. Movement of focus could be delayed or not work as expected.

Is there a reason why conditionally rendering the contents isn't a feasible option for you instead of conditionally rendering the tabpanel?

```diff
 <Tabs>
   <TabList aria-label={''}>
     <Tab>1</Tab>
   </TabList>
-  <TabPanels>{false && <TabPanel>Test</TabPanel>}</TabPanels>
+  <TabPanels><TabPanel>{false && Test}</TabPanel></TabPanels>
 </Tabs>
```

**Comment by s100** [comment]
In the OP we have a rigged scenario where

1. the number of rendered `<Tab>`s can disagree with the number of rendered `<TabPanel>`s (sometimes a `<Tab>` has no `<TabPanel>`), and
2. sometimes the number of `<TabPanel>`s can be 0.

I think we're probably all in agreement that neither of these are a good idea, and I wouldn't expect `<Tabs>` to actively support either of these scenarios.

However, I think it's reasonable to want to conditionally render or omit a `<Tab>`/`<TabPanel>` pair. In general, I would not expect these two pieces of JSX to render differently, or cause accessibility problems:

```jsx
<List>
  <Entry>1</Entry>
  <Entry>2</Entry>
</List>
```

```jsx
<List>
  <Entry>1</Entry>
  <Entry>2</Entry>
  {false}
</List>
```

**Comment by danielannan17** [comment]
In the actual use case we're conditionally rendering all the tabs and tab panels in pairs so there's never a mismatch. The example was just to show the error. 
The issue with conditionally rendering the tab panel contents is it can lead to a mismatch of tab -> tab panel pair.

The workaround suggested above also has its own issues as it's causing the TabPanel never to be shown when you click the tab. It's is rendered in the DOM but just doesn't get shown.

**Comment by Gururajj77** [comment]
As we have discussed that we will not be considering this issue as it could run into accessibility violations, closing this.

**Comment by s100** [comment]
> As we have discussed that we will not be considering this issue as it could run into accessibility violations, closing this.

This is untrue, the linked accessibility notes do not indicate that any kind of issue would be introduced by fixing this bug, as I discussed. Please reopen this.
