### ISSUE TITLE
Pointer cursor usage

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#1712]
## Summary
I'd like the pointer cursor to only be used for links only.  It's currently used on buttons as well.

## Relevant information

> **The hand cursor is for links**
> The hand (and often underlined text) signifies a link. Links are not buttons. Links came along with the web. To help users understand that they are different, they are given the hand cursor. It serves as an extra clue. Here’s why:
> 1. Clicking a link opens a web page or resource.
> 2. (On desktop) I can right-click on a link and do many things (that I can’t do with a button). Open in new tab/window, save a link, copy address, add to reading list, bookmark it and more.
> 3. (On mobile devices) I can tap and hold on a link and get a similar context menu as per the previous point.
> 4. A link also tells me that I am just going somewhere else. I am not modifying any data or making changes in anyway (like a button is likely to do).

Source: [Buttons shouldn’t have a hand cursor](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)

Guidance from standards bodies and industry leaders is consistent:

> The cursor is a pointer that indicates a link.

Source: [W3C CSS3 UI Specification](https://www.w3.org/TR/css-ui-3/#valdef-cursor-pointer)

> **Hand pointers**
> Text and graphics links use a hand or “link select” pointer (a hand with the index finger pointing) because of their weak affordance. While links may have other visual clues to indicate that they are links (such as underlines and special placement), displaying the hand pointer on hover is the definitive indication of a link.
> To avoid confusion, it is imperative not to use the hand pointer for other purposes. For example, command buttons already have a strong affordance, so they don’t need a hand pointer. The hand pointer must mean “this target is a link” and nothing else.

Source: [Microsoft Design Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466%28v=vs.85%29.aspx#hand)

**Comment by joshblack** [comment]
cc @IBM/carbon-designers

**Comment by joshblack** [comment]
I think the spec is clear here, but unfortunately there is an expectation that things that are interactive on the web have a pointer cursor. For example, buttons in the GitHub UI around this issue thread. How would we work around that?

As an aside, does the MDG apply here since it's for desktop?

**Comment by elizabethsjudd** [comment]
We ran in to the same expectations as well but once we provided the above documentation and the education around why we chose to do what we did 99% of people were okay with it.  The pointer has become common for most people but we should be leading by example and following the industries' documented standards.  

*Plus Carbon is adding additional CSS bloat to overwrite the standards which are pre-determined by the W3C*

The references above were provided by a previous designer within Watson Health so I could maybe be persuaded to not count that one but the W3C is the standard for web so I feel like we should be following their guidelines.

**Comment by asudoh** [comment]
While standards are good references and tends to have better quality than other resources, it's sometimes put us in a trap of making them the definite source of truth. @joshblack has a good point about user's expectation on web - As I'm typing a comment here, getting hard cursor on Comment button is intuitive to myself and I kind of expect it, though people may be convinced such expectation is wrong. That said, I think this discussion is more about our designers' choice, while the discussion on web standards are worthwhile links for such discussion.

**Comment by scottnath** [comment]
A definitive source of truth is a good thing. It gives us all a point of reference from which to base our work. By using this as the "rules we all should follow" we give both designers and developers the freedom to put their efforts somewhere else. Less code to support, fewer design-screens to create, less technical debt, less documentation. 

The [medium article](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) makes an excellent point. In most other instances where a user interacts with an interface they expect arrows to trigger actions. The UI we create may often be used in interfaces that are seamlessly integrated into a screen (stand-alone kiosks, x-ray machines, Watson chat bots in a phone app) which, while not sites-in-a-browser, may nevertheless have links which should be indicated as such. App creators shouldn't be required to overwrite `cursor:` actions because their app is not "in a browser". They might not even realize they have make such changes until their app goes to QA.

Beyond that...it costs extra time and money to overwrite standards or requirements

For instance:

1. Design makes a new component in sketch
1. Component has multiple click-able links and buttons
1. Each item is treated with a separate screen to denote a where hand cursor is expected
1. Dev has to track each spot the designer expects a hand cursor
1. Dev has to create css to overwrite standard behavior
1. Dev has to create other css to overwrite the overwrite when an arrow should be expected
1. Project is open source, so users write issues to ask why standards are being overwritten
1. Multiple devs from the open source project need to respond
1. Documentation and requirements need to be written in to define why non-standard behavior exists

or...

1. Design makes a new component in sketch
1. Component has multiple click-able links and buttons
1. No extra screens are needed to explain non-standard behavior
1. No extra dev work is needed to explain, document, or create non-standard behavior

Cursors as pointers vs hand is a small item in the end. But if all members understand that rules around UI behavior have a root source of truth for what that behavior is, it not only frees us up to put our efforts into new interfaces, it also allows us to have an extremely clear definition of done.

This argument dovetails with the concept of written requirements for components. If there is a single source of truth for every aspect of a UI component, then it gives all team members from design to dev to QA clear understanding of expected behavior. If someone along the chain decides to deviate from that behavior... our first question can be `why`, which yields one of two results: 
1. the deviation is halted and expected behavior is used (reducing time-to-market)
1. the deviation is determined to have value and is thus integrated as a new requirement and a new expected behavior or extension of expected behavior (increasing value of component)

**Comment by joshblack** [comment]
I think articles that use OS-level behavior as evidence may be unfair in our comparison here. If we were working in that context, then it's evident we need to be doing this. However, when working in a browser context it does feel reasonable to say that users expect cursors for interactive elements when looking at the following web-based properties:

- Alphabet
  - Google.com
  - YouTube
  - Gmail
- Facebook
- Wikipedia
- Government
  - UK https://design-system.service.gov.uk/
  - US https://designsystem.digital.gov/

This is not a statistically significant sample by any means, but we do look to some of the design systems from gov.uk and the US one for guidance and it does appear that they also follow this pattern. When viewing the top 10 most popular sites based on: https://en.wikipedia.org/wiki/List_of_most_popular_websites we see a similar trend.

I do believe this is a situation where the add-on model helps us out a lot here. It's clear that one codebase can't serve every need, but we can always augment it for a particular domain through the add-on model if we want to go down that route.

If we want to change the existing behavior, then we need a really strong/compelling reason for diverging from the pack right now.

---

As an aside, I should say that I believe the trend could easily move towards the articles mentioned in this thread as PWAs start to become more prevalent (such an exciting future 🎉). Just the other day I turned on the PWA experiment in Chrome and it was insanely cool to have websites feel like apps in the host OS. I really feel like when this happens we would clearly need to adopt OS-level practices in order to truly feel seamless 👍

**Comment by elizabethsjudd** [comment]
At first I didn't really think that this was involved with accessibility but as I was thinking about it I could start to make this arguments as well:

Links denote navigation where buttons are an action but I've seen where they are styled the same.  The cursor difference informs the user that by clicking on an interactive element, if they will retain their current location or if they are navigating to new content.

---
I'm listening to the UX Pin presentation on accessibility and design right now and this isn't specific to cursors but I wanted to share their document on links vs buttons: https://www.garcialo.com/2019/uxpin/links-buttons.html

**Comment by asudoh** [comment]
To better explain my "definite source of truth" point - While I agree with @scottnath that having one may help us, we need to have good common sense to validate it by ourselves. e.g. Googing for `button mouse pointer cursor site:github.com/w3c` reveals something like issue# 1936 at https://github.com/w3c/csswg-drafts, where some standard guys, including one of the biggest voice in CSS world today, showed agreements.

**Comment by elizabethsjudd** [comment]
My point was that we should follow industry standards and we should not be overwriting them. The standards for **today** is that only links have pointers. Standards are allowed to grow and change and we should simply inherit any of those updates if/when they do change.  It creates bloat and technical debt to overwrite a standard.

**Comment by aagonzales** [comment]
Even though they are "industry standards" from a guidelines perspective they are not industry standard from a what-is-actually-done perspective. I think this is an important point from the users perspective. I think most users in a browser setting have come to expect the pointer cursor with buttons and other interactive elements. We run the risk of users thinking an element is not clickable. Perhaps someone can run some usability tests on this topic? 

Do you know of any sites that do this the standards way? I'd like to look at one.
