### ISSUE TITLE
[Bug]: Shouldn't v11 be latest?

### ISSUE THREAD

**Issue by memark** [carbon-design-system/carbon#17207]
### Package

carbon-components

### Package version

10.58.15

### React version

Svelte

### Description

Now that carbon-components v11 is stable, shouldn't it be tagged with the `latest` tag?  
The `next` tag is usually only used for alphas/betas/RCs.

### Reproduction/example

n/a

### Steps to reproduce

`npm v carbon-components dist-tags`

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by AlanGreene** [comment]
`carbon-components` is essentially deprecated and shouldn't really be used for v11.

See https://carbondesignsystem.com/developing/frameworks/vanilla

> If you were previously using `carbon-components`, the styles from this package are available under `@carbon/styles`. The `carbon-components` packages will stick around in v11 but will only be a re-export of `@carbon/styles`.

More context in https://medium.com/carbondesign/moving-forward-on-deprecating-carbon-components-and-carbon-components-react-4f2f0c3d8448

As for whether the v11 releases of `carbon-components` should be tagged `latest` or not, I'll leave that to the Carbon team for comment.

**Comment by tay1orjones** [comment]
The `latest` on `carbon-components` will never be moved from v10 because there are tons of projects out there using non-versioned unpkg.com cdn links in production environments. If a version isn't included in the unpkg url, unpkg will automatically use what's on `latest`.

We found this out in the first v11 release when we moved `latest` to `v11`. Our support channels became ablaze with reports of huge carbon-related problems in projects. Without a version specified in the cdn url, those prod environments immediately started using v11 assets and it broke everything.

We have some fault in this situation - the v10 website had a few places where unpkg.com was mentioned and those docs only included non-versioned unpkg link examples. It was never a recommendation for production environments but we decided to keep `carbon-components` latest on `v10` from now on.

Thanks for asking about this, I don't think we've ever explained the situation on GitHub before.
