### ISSUE TITLE
[Feature Request]: Link with paired icon, ability to position icon to the left of the Link text

### ISSUE THREAD

**Issue by adamlsmith981** [carbon-design-system/carbon#17246]
### The problem

Hi there, I was wondering if it was possible to enhance the Link component to be able to be paired with an Icon which renders to the left of the text. At the moment it only seems that `renderIcon` is only able to render to the right of the text 
<img width="105" alt="image" src="https://github.com/user-attachments/assets/ac108748-b82d-4eb5-b355-fa721d75aee7">

### The solution

I would like there to be an option to do this:
![image](https://github.com/user-attachments/assets/0803ea51-db62-4131-b101-3de9e440fb86)

This could be done by adding an optional prop that would trigger the icon to get rendered to the left hand side of the text link. Default could be left to the right so current implementations are not affected by the change. 

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by adamlsmith981** [comment]
If allowed and accepted as a reasonable enhancement, I would be more than happy to contribute a solution :)

**Comment by alisonjoseph** [comment]
Tagging @carbon-design-system/design to get their thoughts on this.

**Comment by alina-jacob** [comment]
Hi there @adamlsmith981, thanks for suggesting this issue
Carbon fundamentally follows [Flush left ](https://www.ibm.com/design/language/typography/type-basics#flush-left)alignment for text, if an Icon is introduced before the text, the text would appear indented, which is why we do not allow the icon to appear before the text. 

![image](https://github.com/user-attachments/assets/11a8658e-65d0-4574-b891-f84e0a583ce2)
