### ISSUE TITLE
The search input has an incorrect icon in Carbon X

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#1740]
## Detailed description
The clear button shows the magnifying glass instead of x

## Steps to reproduce the issue

1. Type something into a search field

- Screenshots or code
![image](https://user-images.githubusercontent.com/15086604/52427139-484ff880-2af7-11e9-8a6c-9fb8cc4c65c2.png)

**Comment by emyarod** [comment]
hi @lee-chase thanks for reporting this. ~~Can you tell me where the screenshot was pulled from?~~

edit:

I believe this issue was fixed in https://github.com/IBM/carbon-components/pull/1617. I'm assuming you are looking at the experimental documentation where the dependencies have not been updated or the latest updates have not been deployed?

**Comment by lee-chase** [comment]
Sorry and yes

https://next.carbondesignsystem.com/components/search/code

**Comment by emyarod** [comment]
thanks for the clarification. It looks like the dependency the docs website is using contains this fix, so a new build probably just needs to be deployed
