### ISSUE TITLE
[Pagination] Fix Adjacent ellipses in PaginationNav

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon#17628]
Bug issue: https://github.com/carbon-design-system/carbon/issues/15830
Closes https://github.com/carbon-design-system/carbon/issues/15830

```[tasklist]
### Tasks
- [x] Create design specs for Pagination
- [x] Implement the specs for Pagination
```

### Design Specs

![Image](https://github.com/user-attachments/assets/5c1feef2-55cd-4a90-8005-c1893eab0c6e)

**Comment by janhassel** [comment]
I already briefly shared this over in https://github.com/carbon-design-system/carbon/issues/15830#issuecomment-2049117899 but I again wanna voice a concern that surfaced during user testing with the proposed design update: the number of total buttons would change depending on the location of the current page. This means that the entire component grows and shrinks in size and can cause misclicks by the user.

In the first scenario depicted in these specs:
![Image](https://github.com/user-attachments/assets/5af02cc0-e1c8-456c-a950-52825a529a66)

If the user wants to reach page 4, they're likely not going through the OverflowMenu but just click on the right caret twice. After the first click, the position of the right caret changes though and the user would click on page 10.

This is a huge usability issue that users encountered during our testing of this design. That's why we opted to keep the number of buttons the same no matter what the current page is. I urge you to reconsider these specs.

**Comment by thyhmdo** [comment]
@janhassel thanks for the review. I'll take a look at it and update it soon.
