### ISSUE TITLE
UI Shell: Research & Audit playback

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#17783]
### Playback
Playback in a crit call to designers, a dev, and a11y.

- [x] UI Shell Header findings
  - Show the anatomy of the shell. Note the nomenclature differences in the system.
  - Show the difference between Core and the PALs. What do they have that we don't have?
- [x] UI Shell Left and Right Panel findings
  - Show the anatomy of the shell. Note the nomenclature differences in the system.
  - Show the difference between Core and the PALs. What do they have that we don't have?

**Comment by thyhmdo** [comment]
## Team meeting with Marion | Nov 6

**Team**
Alison, Anna, Olivia, Matt, and Sam Ting were on the call
**Intent**
Learning the landscape of MCSP(SaaS) and Cloud Pak (on-prem) from the perspective of on-prem 
**Goal**
- Need to understand our involvement from the Carbon team.
- Where to look for source of truth. Both teams should have one common place to share the guidance with a few specific guidances for each. Since Cloud Pak (on-prem) doesn't have the code so it explains the Github management only goes through from the MCSP side. 


## Reached out to Kiran Ravindra (UX designer) | Nov 8
- "I would guess that it was Gentry if MCSP is/was responsible for it, although she left last quarter. Randa might be your best bet in tracking down the origins. I did work on a small portion of MCSP related designs, although it was specific to URX forms. I know that these designs you've referenced were already created prior to that, mid last year." – Kiran


## Reached out to Randa Salem (Design Principal IBM MCSP) 
- Still waiting for her response
