### ISSUE TITLE
[Bug]: Fluid TextInput does not show a background in readonly mode

### ISSUE THREAD

**Issue by remagpie** [carbon-design-system/carbon#18152]
### Package

@carbon/react

### Browser

Firefox

### Package version

v1.71.0

### React version

18.3.0

### Description

According to the [design document](https://carbondesignsystem.com/components/text-input/style/#text-input-color), `TextInput` in Fluid style should have a background color in readonly mode. But when I try it with `@carbon/react` package, it shows a transparent background instead.

Expected:
![Image](https://github.com/user-attachments/assets/3a494067-84f4-4d16-ad42-3c662f03d67d)

Actual:
![Image](https://github.com/user-attachments/assets/84a049d3-e519-4de7-92fa-50ea5f1b1fe5)

### Reproduction/example

https://stackblitz.com/edit/github-jqvw5p?file=src%2FApp.jsx

### Steps to reproduce

Use the stackblitz link provided and render the `App.jsx` file.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alina-jacob** [comment]
Hi @remagpie, this is the intended implementation, you can check the read-only state documented [here](https://carbondesignsystem.com/components/text-input/style/#text-input-color) (scroll a bit further down)
![Image](https://github.com/user-attachments/assets/40775230-972c-4995-8cac-751e57ea54ae)

**Comment by remagpie** [comment]
@alina-jacob It seems that the image you gave me came from the Default mode of TextInput. My issue was related to the TextInput in Fluid mode. The document says the intended design has an gray background:

![Image](https://github.com/user-attachments/assets/1a703943-333d-448d-b8c4-acf565c792e7)

**Comment by remagpie** [comment]
And it seems that the image(the "Expected" one) I included in the issue was a wrong one. Sorry about that. It's now replaced with the correct image.

**Comment by alina-jacob** [comment]
Oh yes sorry about the default fluid bit. 
Upon double checking, turns out we have two stories for Fluid text input. The one you've linked in the incorrect one, [here's the correct one](https://react.carbondesignsystem.com/?path=/story/experimental-fluid-components-unstable-fluidtextinput--playground&args=readOnly:!true).  (Its marked unstable, but can you use it! Read more about unstable state [here](https://github.com/carbon-design-system/carbon/blob/4f3787a474ab93252975d717426c186ec4355812/docs/experimental-code.md#L4))

Just for reference, here's a [Stackblitz](https://stackblitz.com/edit/github-k1x4p7?file=src%2FApp.jsx) of both, one with error and one without error. 
We will fix the incorrect one, thanks for bringing it to our attention!
