### ISSUE TITLE
Content Switcher - experimental component (feedback from review)

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1863]
From @laurenmrice on Nov 15, 2018:

- [x] Need to have a 40 px option
- [ ] Text needs to left align (16 px from left side)
- [x] Incorporate corner radius (0;4;4;0)

**Comment by asudoh** [comment]
From @joshblack on Jan 29, 2019:

Hey @laurenmrice! 👋 Taking a look at this now, had a couple of questions:

>  Text needs to left align (16 px from left side)

Since the content in the tabs can change depending on what the user provides, I'm not sure how we could have them appeared left aligned. In the sketch file it seems like each tab is set to the size of the largest tab (32px) but we would be unable to replicate this effect without using JavaScript.

We could have each tab span 100% of the available width and left-align it that way, but then the tabs might appear too large for the desired effect here. For example:

![image](https://user-images.githubusercontent.com/3901764/51862408-2ccd3c80-2304-11e9-8b6e-2a8b891b5158.png)

>  Need to have a 40 px option

Is there a sketch file I could reference for this option? Is it just having the height of the control set to 40px instead of 32px? Also, what are we naming this variant?

>  Incorporate corner radius (0;4;4;0)

Is this for the last tab in the tab list, and then the first tab would be `4;0;0;4`?

**Comment by asudoh** [comment]
From @joshblack on Jan 29, 2019:

Resolved over Slack 😄 

Ideal would be to span 100% and left-align text here, although this does deviate from previous behavior where width is dictated by content.

**Comment by emyarod** [comment]
it may be helpful to get some more details from the resolution that happened over Slack

**Comment by asudoh** [comment]
@joshblack Do you recall any...? Thanks!

**Comment by asudoh** [comment]
CC @lovemecomputer

**Comment by asudoh** [comment]
@laurenmrice - Is it possible for you to explain more on below for @emyarod/@lovemecomputer? Thanks!

> Ideal would be to span 100% and left-align text here, although this does deviate from previous behavior where width is dictated by content.

**Comment by laurenmrice** [comment]
@asudoh  The text in each section has to be left aligned instead of center. So the longest word in the content switcher would determine the same width for the other sections (even if the text is shorter in the other sections).

Josh had said "The only drawback with the 100% span is that, depending on where someone is using it, it could span the full width of the browser. Right now it’s built so that the width is determined by the tabs themselves, so just wanted to confirm the change.

I think the span 100% width is exactly what we would want in this situation, to be honest. Then each one is the same width and the text looks left-aligned in the boxes that have shorter content. 

But this is one of those situations where we would be breaking from the existing behavior."

**Comment by lovemecomputer** [comment]
@asudoh @laurenmrice looks like ale was able to address this in the component audit PR, verifying: https://github.com/IBM/carbon-components/issues/1863

if it's all good we can close this issue too : )

**Comment by asudoh** [comment]
@lovemecomputer Could you let us know what PR addresses this...? Is it #2085? Thanks!

**Comment by asudoh** [comment]
Closing assuming #2085 is the one which closes this. In case if there are any remainders, let's track them at: #2092
