### ISSUE TITLE
Overflow - experimental component (feedback from review)

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1864]
From @laurenmrice on Nov 15, 2018 - Not sure if it's still valid, though:

- [ ] "Danger option" text looks to be 1px offset (possible Firefox issue)
- [ ] ~~Remove dropshadow on overflow icon only (reference dropdown component)~~

**Comment by asudoh** [comment]
Refs [IBM/carbon-components#1749](https://github.com/IBM/carbon-components/issues/1749)

**Comment by emyarod** [comment]
cc @IBM/carbon-designers can we confirm if this feedback still applies to the current version of the component?

**Comment by laurenmrice** [comment]
@asudoh There are some more problems with overflow menu I am seeing on the website that isnt listed in above.
-We want it to open the left instead of the right. 
-The overflow icon and the menu should have a seamless background together.(field-01, #f3f3f3)

Here are some specs below:
<img width="634" alt="screen shot 2019-02-21 at 1 53 08 pm" src="https://user-images.githubusercontent.com/43969356/53197592-20c15b80-35e0-11e9-9187-2223d60052b6.png">

**Comment by aagonzales** [comment]
- [x] change icon `.#{$prefix}--overflow-menu__icon` fill color to `$icon-01`
- [x] looks like the option is still using the old type styles and not the new type tokens. Should be using `$body-short-01`
![image](https://user-images.githubusercontent.com/11670886/53433118-6d7aad00-39b9-11e9-9ce1-51866170695a.png)
- [x] danger option text should be using color `$text-04` instead of `$inverse-01`
![image](https://user-images.githubusercontent.com/11670886/53433210-a024a580-39b9-11e9-8a2a-8a9089ce09d9.png)

**Comment by emyarod** [comment]
thanks for the updates, the latest feedback should be addressed in #1881 as well now
