### ISSUE TITLE
Experimental inline select - Determine how we do spacing around invalid icon

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#1885]
From @laurenmrice  https://github.com/IBM/carbon-components/pull/1756#pullrequestreview-203460756

> The spacing of the Inline Selects is still off. For all inline selects the icon will be 8 px / .5 rem away from the last letter in the field. Right now there is too much space between them.

We need to see if it can be done with a reasonable implementation (devs suspect not), and if it's yes, we should implement that.

**Comment by emyarod** [comment]
I think we most likely need to consider moving away from native `<select>` to implement this

**Comment by asudoh** [comment]
Though it's a fair intuition (I used to have the same one as yours), native `<select>` usage is the only differentiating factor between select and dropdown AFAIK.

**Comment by emyarod** [comment]
are there major reasons for choosing to use the native `<select>`? if we do decide to create a custom Select component, I believe there are still major differentiators between a `Select` component and a `Dropdown` that we could implement post-v10 (I think the dropdown name could be rolled into `OverflowMenu` or vice-versa)

**Comment by asudoh** [comment]
The team said it's for a11y back when before I joined Carbon team. @tw15egan do you recall any...? Thanks!

**Comment by tw15egan** [comment]
I think the main reasoning is that if it's being used in a form, semantically, it should be using the HTML5 form element. In this case, `select`. If this component is being used outside of a form, perhaps it should be moved under dropdown, and be changed to `inline dropdown`. 

If we can achieve the same a11y with a custom solution, I'm all for it, but I would defer to @dakahn

**Comment by dakahn** [comment]
A usable and accessible select control using a custom widget (like our Dropdown) is a thing that can happen, but it would take careful testing and you'd end up having to code a lot of screen reader friendly aria tech and bespoke keyboard controls that you get for free by using `<select>`. Some of that is already in there so that argument could be made. 🤷🏽‍♂️

If there's a user need for a fully customizable select control -- in terms of visual presentation -- then we can explore that, but I'd push back pretty strongly on any custom keyboard interaction patterns that don't meet a user's expectation for a `<select>` control in a form.
