### ISSUE TITLE
[Audit] Number input

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#1939]
- [ ] make hover area of the carets bigger (32px x 20px)
![image](https://user-images.githubusercontent.com/15144993/53517305-eb12eb80-3a93-11e9-8bad-105c6b8944ea.png)
- [ ] focus state should not change icon color: 
![image](https://user-images.githubusercontent.com/15144993/53518148-0a127d00-3a96-11e9-859c-4f1d88b30e6e.png)
- [ ] double check tokens:
![image](https://user-images.githubusercontent.com/15144993/53518073-d20b3a00-3a95-11e9-87c8-dcb010600676.png)
- [ ] make sure background color should be `$ui-01`. This should fix light mobile variant's button color:
Current: 
![image](https://user-images.githubusercontent.com/15144993/53517353-07168d00-3a94-11e9-9657-8c6950523add.png)
Should be: 
![image](https://user-images.githubusercontent.com/15144993/53517604-ab98cf00-3a94-11e9-946c-babc7e3ec546.png)

**Comment by emyarod** [comment]
@shixiedesign it looks like [we are still using the old type mixins](https://github.com/IBM/carbon-components/blob/master/src/components/number-input/_number-input.scss#L195) for this component. Which type tokens does this component need to use?

**Comment by emyarod** [comment]
> * make hover area of the carets bigger (32px x 20px)

could you show me how this would look with the error state styles also applied? (`:focus` around the arrow buttons + error icon + `:focus` around the input field). I pushed up a draft PR so you can view what it looks like currently on the netlify link https://github.com/IBM/carbon-components/pull/1967

> * focus state should not change icon color

originally the focus state did not change icon color, and after further investigation it looks like a recent PR we accepted introduced this change https://github.com/IBM/carbon-components/pull/1781. I'm not sure how we are handling theming, but it looks like there is a color token conflict here

> * make sure background color should be `$ui-01`. This should fix light mobile variant's button color

it looks like the button background color was set to `$ui-01` and the input field background color was `$field-02`, following the guidelines [here](https://next.carbondesignsystem.com/components/number-input/style). If I set both background color values to `$ui-01` it looks identical to the normal variant. Is this because we are not applying themes in our test environment (which the netlify link mirrors)

the label type token change will most likely be addressed as part of the Form component audit

**Comment by shixiedesign** [comment]
> originally the focus state did not change icon color, and after further investigation it looks like a recent PR we accepted introduced this change #1781. 

Just looked at this PR with Anna, she confirmed that she didn't catch that change so it's an error. We still wanna keep the icon Gray100 on Focus. We don't have it in the system anywhere else to change icon colors. @emyarod I'm still checking on your other comments. Will get back to you shortly!

**Comment by shixiedesign** [comment]
> could you show me how this would look with the error state styles also applied?

Designers all agreed to increase focus border on the carets to 2px! Unfortunately we can't do much about icon being so close to that corner...it's a temporary state so let's just leave it as is. See below image:
![image](https://user-images.githubusercontent.com/15144993/53829767-7eda3100-3f46-11e9-8811-c0afcb577ce9.png)

> it looks like the button background color was set to $ui-01 and the input field background color was $field-02

Right I made a mistake with the token assignment! Sorry! Hopefully below image & table helps (pls note the changes are in teal color) : 

| --- | button background | input field background |
| --- | --- | --- |
| Default desktop | NA | `$field-01` |
| Light desktop | NA | `$field-02` |
| Default mobile variant | `$ui-01` | `$field-01` |
| Light mobile variant | `$ui-02` | `$field-02` |


![image](https://user-images.githubusercontent.com/15144993/53828182-94e5f280-3f42-11e9-9bcf-0523062974d6.png)

**Comment by emyarod** [comment]
@shixiedesign I added those changes and set the PR as ready for review https://github.com/IBM/carbon-components/pull/1967
