### ISSUE TITLE
Update Checkbox style

### ISSUE THREAD

**Issue by bsonefeld** [carbon-design-system/carbon#197]
## Current Checkbox style
![screen shot 2017-06-22 at 2 52 03 pm](https://user-images.githubusercontent.com/11233508/27452991-6466d420-575a-11e7-8d2c-0ea67b710119.png)

## Updated style
* No rounded corners

![screen shot 2017-06-22 at 2 52 07 pm](https://user-images.githubusercontent.com/11233508/27452993-653f5980-575a-11e7-988c-37481ef75de5.png)

**Comment by tw15egan** [comment]
This was fixed with this PR: https://github.com/carbon-design-system/carbon-components/pull/169

Here is the live version: 
![screen shot 2017-06-22 at 2 55 23 pm](https://user-images.githubusercontent.com/11928039/27453127-fa63d126-575a-11e7-9aea-e0f4e5aebb4e.png)

Should be updated on the site next time we deploy

**Comment by bsonefeld** [comment]
Fastest turnaround ever 💯
