### ISSUE TITLE
fix(accordion) content type higher specificity

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon#1974]
## Detailed description

So I don't know if this is a bug, or not necessarily, but it broke what I had when I decided to update `carbon-components`. I'm not understanding why y'all styled accordion's content `p` only on active. This added to its specificity, and also just conceptually is odd to me that it's changing styles on click when it's not necessary. Y'all may have a very good reason for this, but from my point of view it's not making sense to me at the moment. 😄 

> Is this issue related to a specific component?

Accordion

> What did you expect to happen? What happened instead? What would you like to see changed?

```sass
// this is what it's doing now...
.bx--accordion__item--active .bx--accordion__content p { /* type style */ }

// this is what it was doing before...
.#{$prefix}--accordion__content p { /* type style */ }

// i might would prefer it to be this way...
.#{$prefix}--accordion__content { /* type style */ }
```

> What version of the Carbon Design System are you using?

`carbon-components@9.82.13`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Digital Design, no pressing release at the moment.

## Steps to reproduce the issue

See how it used to be here...
https://codepen.io/team/carbon/full/dZvdaN/

See reduced case in current state
https://codesandbox.io/s/zlj936m7kx

## Additional information

- [accordion.scss #259 (Line)](https://github.com/IBM/carbon-components/blob/master/src/components/accordion/_accordion.scss#L259)
- [#1883 (pull request)](https://github.com/IBM/carbon-components/pull/1883)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting. I believe the intent was for styling inner area of collapsible accordion content, instead of `<p>` in general. Hope it helps - Don't hesitate to speak up if you your application actually is affected by that style!

**Comment by photodow** [comment]
Thanks for the response @asudoh! I'm not sure I understand because y'all are still styling the `<p>` in this situation. I realized my "what I expect to happen section" is a little off. I realize that might be adding confusion, so sorry about that. I updated it above, and including it here below.

```sass
// this is what it's doing now...
.bx--accordion__item--active .bx--accordion__content p { /* type style */ }

// this is what it was doing before...
.#{$prefix}--accordion__content p { /* type style */ }

// i might would prefer it to be this way...
.#{$prefix}--accordion__content { /* type style */ }
```

Also, our application is affected because the specificity was increased, so our overrided text styling was affected. I can update this and match y'alls specificity, but I wanted to make sure this wasn't a mistake, and had a reasonable thinking behind it before I go to that far.

Also, if y'all have a better way to replace the type token used in this scenario that doesn't involve overriding on my I'd love to understand more. :)

**Comment by asudoh** [comment]
Thank you for elaborating your question @photodow! First, why `<p>` is a good question - I think if you try your preferred approach with DOM inspector at http://react.carbondesignsystem.com/?selectedKind=Accordion&selectedStory=Default gives you some answer. I tried it myself and I see it seems because of "type reset" applied to `<p>` (which is `1rem`), wining over the type style applied to the outer container (unless style is applied to specifically to `<p>` in accordion content).

Wrt `.bx--accordion__item--active .bx--accordion__content p` selector - I see [the same style is applied to non-active state, too](https://github.com/IBM/carbon-components/blob/v9.80.4/src/components/accordion/_accordion.scss#L238). Interesting to see why the same type style needs to be applied to active state (given the style of regular state is applied to active state, too). CC @jnm2377 in case she has any insights.
