### ISSUE TITLE
As a user I want to have widgets for graphing data (circles and bar graphs)

### ISSUE THREAD

**Issue by ifwatts** [carbon-design-system/carbon#2]
## Overview
While developing our application we have been asked to generate some graphing data.  We need to be able to generate some bar graphs and circle graphs in bluemix and it would make sence to have a standard IBM Bluemix type of graph that we should all use.

Convert this issue to an **Epic** if there are multiple `Scenarios`.
Each `Scenario` should be it's own issue that belongs to this **Epic**.

{{ long description }}

```gherkin
Feature: {{feature}}
  As a {{persona}}
  I want {{need}}
  So that {{rationale}}

  Scenario: {{scenario}}
    Given {{thing}}
    When {{action}}
    Then {{result}}
```

## Other

{{ Other notes here about this User Story that does not fit within `Feature` or `Scenario` }}

**Comment by hellobrian** [comment]
Hey @ifwatts, we currently don't have a formal recommendation for standard graphs or other data visualizations. In general, data visualizations have been outside of our scope since we've been mainly focused on the Carbon Design System that you see represented today on our website (components, guidelines, and docs, etc.)

I wanted to comment to just say that you're being heard. In my opinion, it would be good to get input from the multiple entities at IBM that currently rely on Carbon to evaluate the best possible recommendation for how to implement graphs and data visualizations in general.

**Comment by tomerm** [comment]
There are 2 main visualization "suppliers" in IBM: 

- [RAVE](https://www.ibm.com/blogs/ba-support-link/rave-customize-and-apply-visualizations/) - which is both language and visualization rendering engine for JDK, web (SVG), mobile (iOS/Android) platforms. I believe RAVE is [D3](https://d3js.org/) compliant - namely it can use D3 for the sake of visualization rendering. 
- [Brunel](https://github.com/Brunel-Visualization/Brunel) - language leveraging D3 as visualization rendering engine. Brunel is widely used in Jupyter Notebooks.

**Comment by chrisdhanaraj** [comment]
Closing this for now - totally hear the need for a standardized graphing system, will ping you when we do! Data visualizations are something we've been looking at creating a system around for a while

**Comment by ifwatts** [comment]
Is there a place I can see the "requirement" for this so I can +1 it?

**Comment by hellobrian** [comment]
> Is there a place I can see the "requirement" for this so I can +1 it?

Sorry,  I'm not sure I understand what you're asking for. If you have access to the IBM GitHub Enterprise, you may be able to find older issues where data-viz was mentioned.
