### ISSUE TITLE
Inline Select - add docs about width

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#200]
The caret for inline select should no be that far away from the text. There should be 10px of padding between the two. I realize that it is adjusting for the lengthier option from the dropdown menu (based on a character count I believe) but is there anyway to reduce the space? With that large amount of space it is difficult for people to see the association between the two elements.
<img width="552" alt="screen shot 2017-06-23 at 10 19 25 am" src="https://user-images.githubusercontent.com/29312997/27486113-73bd6490-57fd-11e7-9bae-5546b40b8497.png">

**Comment by hellobrian** [comment]
Hey @tay-aitken! 

Yes, the inline-select is wrapped with a `<div>` element that can be given a smaller fixed width. 
Below are screenshots of what happens when I add `width: 250px;` to the wrapping `<div>`. 

![image](https://user-images.githubusercontent.com/4185382/27589422-f461ee8e-5b10-11e7-8bb0-a38f08b42dcd.png)
![image](https://user-images.githubusercontent.com/4185382/27589347-b9e09bde-5b10-11e7-8d68-a1bf9bdb81a0.png)
![image](https://user-images.githubusercontent.com/4185382/27589356-c1d3a5c0-5b10-11e7-9f49-fd2c9761d62a.png)

**Comment by tay-aitken** [comment]
Hey what's up @hellobrian!

Great! Can we add in some documentation then that states that the width of the dropdown select box should be the width of the default placeholder text (whatever text is there before the user makes a selection) + 16px of padding. And whatever option the user selects should truncate down to that size and not change the width of the box. I am only asking that we put that in code, since I don't know how often the devs go to the usage tab.

**Comment by hellobrian** [comment]
We can close this when someone adds docs to carbon-components and the website about this.

**Comment by tay-aitken** [comment]
Assigning myself to update any content to reflect this and adding @marijohannessen and @tw15egan to fix the component itself and reflect the changes in dev documentation.
