### ISSUE TITLE
IE11: Demo environment JS syntax error

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2046]
This JS error is blocking interaction for all components in the demo environment (thus Carbon website).

![image](https://user-images.githubusercontent.com/1691245/54148961-35388d00-4403-11e9-9129-3d4390133ebd.png)

Clicking on demo.min.js to find location of error, cursor position is on a `class` keyword which IE11 doesn't recognize.

![image](https://user-images.githubusercontent.com/1691245/54149094-76c93800-4403-11e9-83c8-8726db782e77.png)

**Comment by asudoh** [comment]
Hi @mattrosno :wave: thank you for reporting! First, you are right that both our dev env as well as Carbon website (`v10` one as well as `v9` one) are broken. The breakages come from different reasons for different ones of each, though:

* (Deployed version of) dev env in `carbon-components`: [`rollup-plugin-babel` we run for `markdown-it`](https://github.com/IBM/carbon-components/blob/v9.70.0/tools/rollup.config.dev.js#L53-L55) does not run at all somehow. My bet is we do dependency mocking for that module and thus the path validation fails, presumably with newer version of `rollup-config-babel`
* next.carbondesignsystem.com: It's due to missing `Object.values()` polyfill. There may be other missing polyfills
* carbondesignsystem.com: It's due to non-transpiled object spread operator (`{children:e,...t}`), seems that the code comes from a tool or a library, which needs more investigation

Also please note that Carbon dev env and Carbon website use separate build configurations, for Babel as well as for the bundler (Rollup/Webpack).

**Comment by asudoh** [comment]
Moved next.carbondesignsystem.com one to: carbon-design-system/carbon-website#1292

**Comment by akash-srivastava-ibm** [comment]
Hi, we are using overflow menu from carbon vanilla js. And it doesn't open up in IE11. 
It seems that the overflow menu code uses CustomEvent() which isn't supported in IE11. 
Is there a fix/workaround available for this ?
