### ISSUE TITLE
Progress indicator breaks apart if container is not flexbox

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2138]
See screenshot. Vanilla dev env, React dev env, Carbon website... all component containers use flexbox display.

When using progress indicator in a normal block display, it breaks apart and has visual gaps between the steps.

We can't assume that progress indicator components will always be used in flexbox containers.

This appears to be new to v10.

![image](https://user-images.githubusercontent.com/1691245/54642945-ca6efd80-4a63-11e9-9c8a-c66c58c0bce5.png)

**Comment by mattrosno** [comment]
Not stale.

**Comment by davidicus** [comment]
Could this be solved by changing the ul container of the progress step to `display: inline-flex` instead of `display: flex`?

![image](https://user-images.githubusercontent.com/1590966/61974996-ea846f80-afb5-11e9-9aa2-7eaf3034e338.png)

**Comment by emyarod** [comment]
is this related? #3526 #3538

**Comment by davidicus** [comment]
yes. I think your PR will fix this as well. May be worth changing the `ul` to `inline-flex` in case people want to put content next the progress indicator but not necessary to fix this issue.

**Comment by asudoh** [comment]
I can see the original issue being fixed by going to https://the-carbon-components.netlify.com/component/progress-indicator--default.html and removing `display:flex` rom the parent `<div class="demo--container__panel">`. Putting some content next to progress indicator sounds for a separate issue - Likely that we need to hear more on the use case.
