### ISSUE TITLE
Tabs focused item's bottom border is too high

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2171]
See screenshot. When a tab item has focus, I expect the bottom blue border to be in line with the other tab bottom borders.

![image](https://user-images.githubusercontent.com/1691245/54645094-0193dd80-4a69-11e9-9992-455806be2ff5.png)

**Comment by shixiedesign** [comment]
Actually this might be by design. Lemme check Slack conversation.

**Comment by shixiedesign** [comment]
Found the conversation. The reason it was high was because we didn't know how to have it baseline align without bumping the type up and down, and reposition type was not acceptable. Looks like the PR fixed it without bumping type 🎉 ! I approved it. Thank you for the fix @joshblack !

![image](https://user-images.githubusercontent.com/15144993/54782573-3b8dec80-4bed-11e9-9a1a-5469ba2494a8.png)
