### ISSUE TITLE
[Carbon 10: Data Table] missing modifiers

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#2279]
## Detailed description

> Describe in detail the issue you're having.

Based on the [documentation](https://www.carbondesignsystem.com/components/data-table/code) there are 6 modifiers.  Applying any of these classes to either to container element or the table do not change the way the table looks visually.

> Is this issue related to a specific component?

Data Table

> What did you expect to happen? What happened instead? What would you like to see changed?

Expect the modifier classes to visually change the table

> What browser are you working in?

Chrome, FireFox, Safari

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Steps to reproduce the issue

1. Apply a modifier class to the table (or container element) 
2. View the table styles

**Comment by jnm2377** [comment]
Hi 👋 some of the Data Table variations are still under construction (and are considered a known issue in v10), or have been recently updated since release, so we are still working on updating the documentation for them. Some of the selectors have been deprecated which is why there's no visual change, and those that are still a WIP don't show a visual change because the styles for those selectors haven't been included in the latest version of Carbon.

**Comment by elizabethsjudd** [comment]
Is there a timeline on these updates?

**Comment by dakahn** [comment]
@jnm2377

**Comment by elizabethsjudd** [comment]
@jnm2377 Looks like #1303 is the issue for this WIP?

**Comment by jnm2377** [comment]
Yes @elizabethsjudd there's an open PR for it right now, which will hopefully get merged by the end of the week.

**Comment by elizabethsjudd** [comment]
@jnm2377 Is this issue resolved?

**Comment by jnm2377** [comment]
@elizabethsjudd this will be included in our 10.3 release in a few days.
