### ISSUE TITLE
Carbon 10: Expandable Data Table Icon Positioning in IE11 + Edge

### ISSUE THREAD

**Issue by vincentsnagg** [carbon-design-system/carbon#2299]
## Detailed description

> Describe in detail the issue you're having.

- In IE11 + Edge chevrons within expandable data table rows are not vertically centered
- Additionally, expandable data table styles generally inconsistent between browsers IE11 + Edge (header height, vertical icon positioning within headers) **See screenshots below**

> Is this issue related to a specific component? 

Expandable Data table

> What did you expect to happen? What happened instead? What would you like to see changed?

Chevron's should be vertically centered on both IE11 + Edge

> What browser are you working in?

IE11 + Edge

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Steps to reproduce the issue

1. View data table styles

## Additional information

Edge: 
![Screen Shot 2019-04-12 at 12 58 53 PM](https://user-images.githubusercontent.com/3158307/56053935-746c3d80-5d23-11e9-8a93-29df172cae33.png)

IE11:
![Screen Shot 2019-04-12 at 1 00 13 PM](https://user-images.githubusercontent.com/3158307/56053930-70402000-5d23-11e9-9f79-d433fc5fbc93.png)

**Comment by elizabethsjudd** [comment]
Not stale

**Comment by emyarod** [comment]
~~just to confirm, this issue is visible in all browsers and not just IE and Edge right? (https://github.com/carbon-design-system/carbon/issues/3053)~~

my mistake, seems this is about the default (non-short) table unlike #3053. but I am unable to reproduce this issue in Edge. not able to check IE at the moment but will have to review when I am able

viewed in Edge 
![image](https://user-images.githubusercontent.com/8265238/59444301-3f33a880-8dc3-11e9-8472-60e1bf229645.png)
