### ISSUE TITLE
Design Spec for Shell Header (Scallop)

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon#2334]

**Comment by chrisconnors-ibm** [comment]
two week window for stale[bot] is a little aggressive @shinytoyrobots

**Comment by aagonzales** [comment]
### Header elements:
(the name is the only required element, the rest are optional/configurable)
- Name - `.bx--header__name`
- Hamburger - `menu-trigger`
- Links - `menu-item`
- Menus - `sub-menu`
- Icons - `actions`
- Button (single or group)
   - primary
   - ghost
- Search

### Header configurations 
Below are all possible but not the only header configurations. Just a sample of what a team should be able to build.
![header configurations](https://user-images.githubusercontent.com/11670886/57465018-5f5fcd00-7243-11e9-9e5c-ebcb30eab594.png)

### Header themes
The header should also be themeable. Not sure how we'll do this at the moment but just want to make a note.

**Comment by ghost** [comment]
Has this been tested with real product names?  Guidelines end up giving us rather long strings like "IBM Z Development and Test Environment Enterprise Edition", thus leaving less room for other features.

**Comment by aagonzales** [comment]
## Header pieces
updated: 5-13-19

![Header pieces](https://user-images.githubusercontent.com/11670886/57656460-fd35fd80-759d-11e9-812e-83f5ed73f577.png)


## Header patterns
updated: 5-13-19

![header patterns](https://user-images.githubusercontent.com/11670886/57656473-045d0b80-759e-11e9-8720-d0a218415a60.png)



**Sketch file**: https://ibm.box.com/s/i45sfzlwg4u4hwh8xskwwg66yiz4fwmn
cc: any feedback? @chrisconnors-ibm @jeanservaas @laurenmrice @designertyler @shixiedesign

**Comment by aagonzales** [comment]
@dayzed007 this is an mvp we're trying to get out to teams to test to find problems like you mentioned and hopefully have them propose solutions that will work for them.

That name wont even fit on a mobile screen (320px), we'd have to make a way to truncate the name if this is a legitimate scenario, either through purposeful truncation, ie could just IBM Z  work at small screensize otherwise we'd have to most likely ellipse at some point. I'd be interested to know if a user always need to know/cares about all the information being presented in that title. 

Do you know what that product currently does with its name at small screen sizes?

![image](https://user-images.githubusercontent.com/11670886/57558974-7a1a6a80-7345-11e9-8caf-ca1e06c99cf6.png)

**Comment by ghost** [comment]
#aagonzales Thanks for looking deeper into this.

That is infact legit scenario.  Fortunately we have surveyed our users in the past and learnt that small screen sizes aren't a priority, but as you know, with modernization priorities change so trying to get ahead of it.  I'm even concerned that in some cases even at large screen sizes there wouldn't be enough room for name & navigation.

We have been negotiating with legal to use shortened versions of the name, however even with certain legal accommodations, the general rule of thumb is that the first instance must be spelt out fully, and guess where the first instance is :-(?  "IBM Z" alone can't work since IBM Z covers a vast portfolio of products of which this is just one.  And I know that legal would never allow ellipse's  The truth is this is more about IBM Legal protecting names & IP.  I know it might not be ideal, but have you considered a two line heading?

The IBM portfolio has 800+ software product, granted not all will use carbon, but we can bet that many will try.  I've attached a PDF with some of the more concerning names (this was just a random grabbing), the longest I found was "**IBM Cloud Orchestrator Content Pack for OpenLDAP and Microsoft Active Directory**"

[product-names-long.pdf](https://github.com/carbon-design-system/carbon/files/3173228/product-names-long.pdf)

**Comment by chrisconnors-ibm** [comment]
we are not recommending links to views within your products in the header, for exactly this reason (and others). If you actually have a name that long in your header you won’t have room for much else. Our component will support links in the header because they are used in existing products but we don’t advocate the approach.

**Comment by chrisconnors-ibm** [comment]
If guideline land us at a product name like 
**IBM Cloud Orchestrator Content Pack for OpenLDAP and Microsoft Active Directory.**, perhaps they need to be revisited. 

The title there seems like
**IBM Cloud Orchestrator**
With a sub title (which you’d show in the view rather than the header:
_OpenLDAP and Microsoft Active Directory Content Pack_

**Comment by ghost** [comment]
> we are not recommending links to views within your products in the header, for exactly this reason (and others). If you actually have a name that long in your header you won’t have room for much else. Our component will support links in the header because they are used in existing products but we don’t advocate the approach.

Can you please clarify?  I'm not sure what you mean 'links to views'?  Surely you aren't saying we can't use our actual product names in our headers?

**Comment by ghost** [comment]
> If guideline land us at a product name like
> **IBM Cloud Orchestrator Content Pack for OpenLDAP and Microsoft Active Directory.**, perhaps they need to be revisited.
> 
> The title there seems like
> **IBM Cloud Orchestrator**
> With a sub title (which you’d show in the view rather than the header:
> _OpenLDAP and Microsoft Active Directory Content Pack_

Yes, as I mentioned that was just a random example.  In the IBM product index it is spelt out fully as the legal product name.

**Comment by ghost** [comment]
@aagonzales confirmed, previous versions allowed wrapping, thus going to two lines;

![image](https://user-images.githubusercontent.com/24781332/57630340-6a7c6b00-756b-11e9-8526-54148d34f1cf.png)

**Comment by ghost** [comment]
@aagonzales how can I access the sketch file in box to test for my needs?  It seems I need special permission.

**Comment by ghost** [comment]
> If guideline land us at a product name like
> **IBM Cloud Orchestrator Content Pack for OpenLDAP and Microsoft Active Directory.**, perhaps they need to be revisited.

I found the [naming guidelines](https://w3-03.ibm.com/marketing/namingtool/ntapp.nsf/EntryScreen?OpenForm) and noticed even several the examples they gave wouldn't fit in the 320px header.  I guess it's obvious, but this is a fundamental problem if our design standard cannot support our own product names without truncation.

I invite you to take it up with the Brand Strategy team if you think we should be using shorter names.  Maybe they'll listen. In the mean time we need to move forward with the names we have without splitting or truncating them.

**Comment by aagonzales** [comment]
Dev issue for scallop release: https://github.com/carbon-design-system/carbon/issues/2401

**Comment by aagonzales** [comment]
@dayzed007 thank you for the feedback address this in future releases. Looks like it will need some more exploring and research about what to do with long names.

**Comment by ghost** [comment]
I stumbled on some work that IoT has done with the shell;

![image](https://user-images.githubusercontent.com/24781332/57721620-a9d1b700-7652-11e9-911a-d2f6b4199738.png)
becomes;
![image](https://user-images.githubusercontent.com/24781332/57721691-cd94fd00-7652-11e9-9516-951e2299bd34.png)

Sorta surprised this issue has been closed given it has a major deficiency that will affect a vast majority of products.

**Comment by aagonzales** [comment]
@dayzed007 We'd appreciate seeing any solution your team comes up with for this problem. 

As for closing this issue, as I've previously stated, this is an MVP issue for our 10.3 release at the end of May. We will continue work on the shell for future release. This shell is also still in "experimental" meaning more work will be done on it.

**Comment by chrisconnors-ibm** [comment]
@dayzed007 I genuinely appreciate your comments here and value the ways in which you've helped expand our thinking.

You don't have to worry - closing this issue means "we've documented what we can contain in this round of iterative delivery." In no way does it mean to stand as the last word on this problem space.

**Comment by chrisconnors-ibm** [comment]
With your example above, the issue is not the title length, it's that the system nav items on the right would not persist at this screen width.

so these items:
![57721620-a9d1b700-7652-11e9-911a-d2f6b4199738](https://user-images.githubusercontent.com/35537391/57733736-389ffd00-766e-11e9-9153-435e8b5d77f6.png)

would collapse into a menu:
![system_items_collapse](https://user-images.githubusercontent.com/35537391/57733774-51101780-766e-11e9-8ef3-9d5530dc71f3.png)

**Comment by ghost** [comment]
Thanks for clarifying, I can only go based on what I've seen.  I wasn't quite sure the behavior of this area after seeing the examples provided by Anna;

![image](https://user-images.githubusercontent.com/24781332/57775264-9eca6580-76ea-11e9-97ee-754a1a5f7d6b.png)

So medium names are covered, now we just have to worry about long names.

In the case of the example I gave earlier, we decided to drop "enterprise edition" and simply put this in the legalese (since the other editions don't actually have an interface [yet]).  We will now need to debate with naming/legal about abbreviating our name.  Sometimes this is OK, sometimes not so much.

**Comment by ghost** [comment]
Unrelated to the naming topic, since I can't access the sketch files in Box, I'm unsure how your designs for the shell are translating to the 4 color themes. @aagonzales any guidance?
