### ISSUE TITLE
Add vertical and horizontal handle bars

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon#2355]
### Summary
Could you please add vertical and horizontal handle bar user interface components? These user interface controls are grab-able, adjustable bars that allow users to change the amount of displayed space in a panel.

![Vertical_and_horizontal_bars](https://user-images.githubusercontent.com/12902530/56913546-86feaa80-6a77-11e9-838f-bcbb89d982e4.png)

### Justification

These features allow users to quickly, easily, and intuitively resize the amount of information shown in a panel to meet task needs or individual preferences. Vertical and horizontal handle bars are particularly popular in information-dense enterprise applications.

### Desired UX and success metrics

The page displays multiple panels. The user wants to see more information in one panel. The user grabs the vertical handle bar and drags it to the left to see more information in the right panel. Or, the user grabs the vertical handle bar and drags it to the right to see more information in the left panel. The same user interface styles apply to horizontal handle bars.

### "Must have" functionality

The grab affordances must be obvious and visible, either passively or when the user hovers on the bar. 

### Specific timeline issues / requests

My enterprise application uses multiple horizontal application. Do you think you could add vertical and horizontal handle bars to a release in the next six months?

### Available extra resources

What resources do you have to assist this effort?

I can iterate the design with you and may be able to show it to prospective users.

**Comment by asudoh** [comment]
@IBM/carbon-designers Do you think a "splitter" described above fits well in Carbon design ecosystem? Thanks!

**Comment by designertyler** [comment]
This might be too specific to a domain or application for the core Carbon library and could be better suited as an [add-on component](https://www.carbondesignsystem.com/contributing/add-ons/#page-title). It can be difficult for the Carbon team to support more specific components since we aren't as close to those user's needs as the product team. That makes it difficult for the Carbon team to build, maintain, and offer a component that's equally valuable for all users of Carbon.

One thing to be aware of when exploring the designs is that there is a `draggable` icon available in 16px, 20px, 24px, and 32px sizes in Carbon's icon elements package.

Here's the reference library
https://carbon-elements.netlify.com/icons/examples/preview/#32%2Fdraggable

And elements repo for icons https://github.com/IBM/carbon-elements/tree/master/packages/icons

<img width="864" alt="Screen Shot 2019-04-30 at 7 52 20 AM" src="https://user-images.githubusercontent.com/19270502/56962748-ea8ee380-6b1c-11e9-86ad-1306314d0561.png">

**Comment by asudoh** [comment]
Closing as the use case/component doesn't represent Carbon's use case in general (more specific). Thanks @designertyler for your response!
