### ISSUE TITLE
[Button] Add 40px height option aka "field button"

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#2365]
Need to decide if we want 40px form field and button option, or 48px.

- [x] Make decision
- [x] Make specs for dev to implement
- [x] Implement 🤖 
- [x] Update kits with new designs

![Screen Shot 2019-04-30 at 11.15.41 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/05972d45-42c5-4c2a-bfe7-16211d7ba263)

**Comment by shixiedesign** [comment]
### Add field button

Adding 40px option for buttons so it may match our fields height! Here's the spec. **Ready for dev.**

![image](https://user-images.githubusercontent.com/15144993/57539684-9fd94c80-7310-11e9-8bdf-baa643d84d7e.png)

**Comment by laurenmrice** [comment]
If the different variations of inputs are horizontally next to eachother (ex: no label, labels, helper text, helper text+ label) We would align the fields and buttons.
![Artboard](https://user-images.githubusercontent.com/43969356/57729026-d2f64580-765a-11e9-824e-f3ea3f9a660e.png)

**Comment by shixiedesign** [comment]
## 📖 Guidance to add
 @connor-leech 
> If the different variations of inputs are horizontally next to eachother (ex: no label, labels, helper text, helper text+ label) We would align the fields and buttons.

**Comment by lovemecomputer** [comment]
thanks @laurenmrice ! 

@laurenmrice & @shixiedesign can we verify what happens when error text is present in such a state? if we have dynamic measurements for both the text above and below the input fields, that might be pretty tricky to implement… but we can definitely dig into (and hopefully solve) the feasibility of this if we can check against a spec!

also, just thought to myself: will we suggest wrapping-to-next-line on these elements by giving them a default minimum width? (this is something that could be left up to the product team implementing to solve when implementing them on a page, but if some kind of default is sensible and not too technically restrictive, we could look at that)

**Comment by shixiedesign** [comment]
@lovemecomputer error messages goes under the inputs, so it shouldn't affect the buttons aligned to the field, and only push down the next set of field+button as a group. 

> will we suggest wrapping-to-next-line on these elements by giving them a default minimum width? 

At the moment, we are not technically offering a field+button as a component, so how product teams want to align/stack/arrange elements is completely up to them (we also don't have the context to restrict behaviors I think). For this issue at least, we just need to add a set of buttons with 40px height. How it positions next to input fields are guidelines to add, and no implementation needed! Lemme know if this make sense.
