### ISSUE TITLE
TooltipDefinition cut off at the border of the window

### ISSUE THREAD

**Issue by gmoehler** [carbon-design-system/carbon#2460]
## Detailed description

> `<TooltipDefinition>`s do not work well on the edges of the window. E.g. when the trigger text/component is right aligned and its width is smaller than 208px the tooltip is cut off. 
I have also seen cases in which the tooltip is cut-off by the bounds of a parent component, but need to reproduce this in sandbox.

> Related to `<TooltipDefinition>` component

> `<TooltipDefinition>` always seem to be left aligned with the left side of the tirgger component with a constant width, which makes them cut off by the window boundary. One solution would be to right align them with the tigger component.  I have an intermediate solution using the `right` and `left` style attibutes as shown in the last button of https://codesandbox.io/s/6l2qvkr3rw. Please take a look.

> Not sure what exactly the solution would be for the top, maybe move the tooltip automatically to the bottom.

> Chrome & firefox

> carbon-components@7.2.0

> **IBM Cloud SQL Query - we would like to release a Carbon 10 version in the days to come. So this is crutial to us**

## Steps to reproduce the issue

1. Place the trigger of a <TooltipDefinition> (width < 208px) to the right side of a window or at the top and you will see it

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/6l2qvkr3rw

## Additional information
![Screenshot 2019-05-07 at 12 46 46](https://user-images.githubusercontent.com/17567047/57357997-a632c180-7174-11e9-869f-71a1d40c671e.png)
![Screenshot 2019-05-08 at 09 51 22](https://user-images.githubusercontent.com/17567047/57359002-e8f59900-7176-11e9-8490-b796e7b4f4e5.png)
cut-off at component bound (not covered by codesandbox yet):
<img width="442" alt="Screenshot 2019-05-08 at 11 27 11" src="https://user-images.githubusercontent.com/17567047/57364929-64aa1280-7184-11e9-9281-a12539fcb142.png">

**Comment by aagonzales** [comment]
The original tooltip design spec did include all orientations for the tooltip. I would be great if the tooltip would be aware of the edge of the window and re-orient itself. 

![image](https://user-images.githubusercontent.com/11670886/57536719-61d92a00-730a-11e9-8b3c-63e5e9175bea.png)

**Comment by emyarod** [comment]
this will be resolved in https://github.com/carbon-design-system/carbon/pull/2663 cc @asudoh

**Comment by elizabethsjudd** [comment]
@emyarod according to the spec there is left/right position not just alignment.  I don't see that in @asudoh's PR.  I also only see the alignment right (end) in the PR.  Is there going to be an issue to add these remaining items from the spec?

**Comment by emyarod** [comment]
@elizabethsjudd from my understanding this issue (#2460) is regarding tooltip definition alignment which is covered in #2663. we can definitely address tooltip positioning in a separate issue

**Comment by elizabethsjudd** [comment]
@emyarod 2640 is a "Tag List" issue (wrong number due to mono-repo updates?).  I'm fine doing the tooltip positioning in a separate issue but shouldn't the left/start alignment be part of #2663 or is that going to be a separate issue as well?  Do we have issues to finish implementing these specs that we can follow?

**Comment by emyarod** [comment]
@elizabethsjudd corrected to #2460 not 2640

I'm a bit confused about your left/start alignment point

after searching it doesn't look like the tooltip positioning is captured in a separate issue, esp since it looks like the spec screenshot was only posted a few hours ago by @aagonzales

**Comment by elizabethsjudd** [comment]
Thanks for the corrected links!

Tooltip positioning is not a new issue. I've had multiple conversations around it in the last week in multiple issues/PRs. Each time, I'm told that it's beyond the scope of the PR... which I'm fine with. However there should be an issue (either a new issue or an existing one) for implementing this remaining work that keeps getting brought up.  This way Carbon users have an issue to reference and quit having the same discussions. This issue would also allow us to track the progress on completing the implementation.

My point with the alignments were it looks like there are 3 alignments (left, center, and right). The PR covers center and right, I didn't understand why left wasn't handled as well since it is very closely related to the the work already being done.

**Comment by emyarod** [comment]
I opened https://github.com/carbon-design-system/carbon/issues/2678 to capture this issue. feel free to add references to the relevant conversations you've had as well. in the future also please don't hesitate to create new issues to cover discussion points that are dropped or missed

[WRT the alignments, all 3 alignments are handled and captured no?](https://github.com/carbon-design-system/carbon/pull/2663/files#diff-916183444c3885c676548407d734df75)

**Comment by elizabethsjudd** [comment]
@emyarod Thank you for opening the issue. 

WRT the alignment... no, the sass only has right and center so even though the template supports all three there wouldn't actually be any visual styles updated with the class https://github.com/carbon-design-system/carbon/pull/2663/files#diff-3f7a610695bad7f8958dd0852177b98bR230

**Comment by emyarod** [comment]
because the default styles are for start/left alignment...is this not the case when you view the component?

**Comment by elizabethsjudd** [comment]
Ah yes! My bad. Thanks.

**Comment by asudoh** [comment]
@emyarod @shixiedesign Do we think #2678 should supersede this? Thanks!

**Comment by shixiedesign** [comment]
There's a PR adding Left/Right tooltips now, but just to clarify, this issue's original description does not require L/R tooltips to be available. To make sure tooltip is not cut off, you should be using Top/Bottom right aligned tooltip instead of the default left alignment. We only recommend side tooltips for usage in side rails and vertical toolbars on the icon buttons. 

@elizabethsjudd @gmoehler Lemme know if this makes sense. Thank you! 

Closing this issue as dev progress is tracked in #2678

**Comment by gmoehler** [comment]
@shixiedesign agreed to track this in #2678 since what i need are right aligned definition tooltips, which seems to be covered by that issue. Any plans when they are available?

**Comment by shixiedesign** [comment]
Hi sorry @gmoehler you might have misunderstood. We will **not** be providing side tooltip options for definition tooltips. 

**Side tooltips in #2678 are only for icon tooltips** and are intended for side-navs with icons (such as vertical toolbar). 

In this case, based on your screenshots, you should be using these alignments, which are already available, merged in #2663: 

![image](https://user-images.githubusercontent.com/15144993/57642191-4bd2a000-757c-11e9-8c48-7916218bdc31.png)

**Comment by gmoehler** [comment]
@shixiedesign  ok perfect - #2663 is exactly what i was looking for. Thanks for pointing out!
When can i expect a new carbon-components-react version to be released (last one was from May1)?

**Comment by shixiedesign** [comment]
Look out for another release around end of May/beginning of June. It would be version 10.3. @gmoehler
