### ISSUE TITLE
DropdownV2 - itemToElement not taken into account when selectedItem is used

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon#2511]
I would like to have icon next to selected dropdown option and next to list options.
DropdownV2 has **itemToElement** prop to allow this:
![image](https://user-images.githubusercontent.com/17591704/54918671-2cfe4880-4eff-11e9-9119-4265d9db8247.png)
Unfortunately this prop is not taken into account for selected dropdown item (selectedItem prop), itemToString is used there:
![image](https://user-images.githubusercontent.com/17591704/54918830-8797a480-4eff-11e9-8674-216c14547bfd.png).

Result looks like below, there is a missing icon next to selected value (itemToString using only label value):
![image](https://user-images.githubusercontent.com/17591704/54918929-c3cb0500-4eff-11e9-8545-70578bb355dc.png)

Currently this is blocking issue for SPSS Statistics, so I'm asking for quick fix.

**Comment by sanduteo95** [comment]
Hi, just wondering if you are still working on a fix for this or looking for some outside help now. I could open a PR with a fix I've found, so let me know if you'd be happy with that.

**Comment by tw15egan** [comment]
@sanduteo95 Would welcome a PR to fix this if you've got a solution ready 🙏

**Comment by sanduteo95** [comment]
By chance I found that someone else had attempted a similar fix to mine and then reverted their changes: https://github.com/carbon-design-system/carbon/pull/5023. From the comment linked in that PR it sounds like it might not be a good idea to allow custom components as the dropdown label, so I'll put off opening a PR for now.

**Comment by tw15egan** [comment]
@joshblack based on the revert of #5023 , is this something we will not support?

**Comment by joshblack** [comment]
@tw15egan I think we'd have to pass on it but definitely not 100% sure. When talking to Jen, I think two things came up:

- Controlling color contrast on the field
- Controlling what is announced for the value on a field

It seemed like we wanted to limit what is displayed in the field to our design specs, but if there is a good use-case for otherwise I would get it. For the value, I think it was important that it serialized into something readable which could be addressed by this?

Overall, it seemed worth it at the time to restrict usage of this to help steer folks in a clear direction. Let me know if what I shared above is missing something though, or misinformed 👍

**Comment by tw15egan** [comment]
That makes sense, going to close this out then as it does not seem like something we are going to take on / enforce.
