### ISSUE TITLE
Favor explicit usage of <FormItem> component

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#2549]
Currently many form item components contain a wrapper div within them with the `.bx--form-item` class. When composing forms, these wrapper divs are often duplicated or erroneously added, causing components to diverge from the spec. Examples of this can be seen in the current `<NumberInput>`, `<ComboBox>, `<MultiSelect>`, <FilterableMultiSelect>`, and `<Slider>` stories

**Comment by vpicone** [comment]
I'm not sure forcing devs to wrap all of our form inputs with a `FormItem` wrapper is a great idea it gets really gnarley for complex forms. Using the FormItem to combine label logic though could be a good move.

As of now, the FormItem component doesn't really serve a purpose as a public since it's baked into our other form inputs. I wonder if we should just delete the story?

**Comment by emyarod** [comment]
I'm unsure about the origins of exposing this component as a public and the discussion around the original PR is now missing because of the monorepo move. but to me it seemed like it was a way to enforce spacing between form elements. right now we already wrap our form inputs in `.bx--form-item` so this wrapper component doesn't have much use

IIRC the reason the idea of explicitly requiring `FormItem` when building forms came up is so that we wouldn't have to constantly override the default form spacing/margin in components (like `Slider`, `Pagination` which consume other components like `NumberInput`, `Select`)

**Comment by tw15egan** [comment]
@emyarod is there any action we want to take here or do we want to close this out?

**Comment by emyarod** [comment]
this can be closed since the discussion went nowhere
