### ISSUE TITLE
Dropdowns not accessible when used in Modals

### ISSUE THREAD

**Issue by diana-sun** [carbon-design-system/carbon#2579]
## Detailed description

> Describe in detail the issue you're having.

I wish I could be more detailed about it but, our feds are saying that the carbon dropdowns don't work well in modals. 

> Is this issue related to a specific component?

Yes - the dropdowns + modals

> What did you expect to happen? What happened instead? What would you like to see changed?

I wanted to have the carbon dropdown in a modal, but instead it uses the default browser dropdown which is... not pretty :)  Hopefully carbon dropdowns can work out of the box in modals?

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v9

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Kubernetes Service

## Steps to reproduce the issue

1. Put a single-select regular/default dropdown in a modal
2. Not sure

## Additional information

* Screenshots or code
<img width="542" alt="screen shot 2018-10-12 at 2 08 28 pm" src="https://user-images.githubusercontent.com/10226935/46889376-21273a00-ce29-11e8-9b62-31cd414a46c6.png">

Thanks!!

**Comment by bjones526** [comment]
@diana-sun Do you know if your build is including vendor prefixes on the styles you pull in from carbon? I've seen the browser add those default styles (i.e. the little black arrows) to form input components when prefixes are missing. 

I also noticed that in your screenshot, the blue arrow icon is pointed down (indicating that you attempted to open the dropdown), but none of your select options are visible. Is this the case, and are you able to see them if you scroll down inside the modal? If you are, that seems very similar to what I'm seeing in #1472, which is why I mentioned your issue there.
