### ISSUE TITLE
AVT violation on tooltip

### ISSUE THREAD

**Issue by kiddove** [carbon-design-system/carbon#274]
![image](https://user-images.githubusercontent.com/2195199/29176122-f4744e4c-7db8-11e7-95cd-6740d93b6468.png)

There are two violations on the tooltip.
1. The identifier element has the id "identifier" that is either empty or already in use.
2. All content must reside within a WAI-ARIA landmark or labelled region role.

**Comment by iangfleming** [comment]
@kiddove this is a demo environment and both these violations are results of the environment. 

1. The id is used twice because all our component variations are loaded in the DOM together. In an actual use case a user would replace "unique-id" with their *unique id*.
2. This is a demo environment so we any violations outside the component itself are not relevant.

**Comment by kiddove** [comment]
@iangfleming , there are two tooltips with the same id, no matter in your demo page or our page, on matter what id I use. Unless I'm using the tooltip in a wrong way. Please advice. Thanks.

**Comment by kiddove** [comment]
@iangfleming , thanks, you're right, I copied the demo code into our page.
