### ISSUE TITLE
Gap between tabs and tab container

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2799]
The `a.bx--tabs__nav-link` declaration sets height of 2.5rem, making the computed height bigger than the visible height, leaving a gab between the bottom of the tab and the top of the tab content.

![image](https://user-images.githubusercontent.com/1691245/58128160-98515780-7bdc-11e9-84be-9e7f4da8f605.png)

When using the tab component, that gap means I can't have even spacing above and below my tab content:

![image](https://user-images.githubusercontent.com/1691245/58128404-29c0c980-7bdd-11e9-99d7-9db436793ed3.png)

Seems like height is set in many places to accommodate absolute positioning which seems very unnecessary and error prone for something like tabs.

**Comment by abbeyhrt** [comment]
Thank you @lovemecomputer for fixing this through #3410! Seems like we might want to have a more general discussion about refactoring the fixed tabs heights. @mattrosno Would it work for you for me to close this issue and make a discussion issue to address refactoring the hardcoded heights so that idea isn't forgotten?

**Comment by mattrosno** [comment]
@abbeyhrt we set heights and widths and min-heights and min-widths quite a bit across many components - I don't think that's high-enough priority right now. Maybe it'll come up in the future w.r.t. theming. No need for an issue right now that will just get hit with stalebot :).
