### ISSUE TITLE
HTML elements and JS binding gets lost

### ISSUE THREAD

**Issue by leondroidgeeks** [carbon-design-system/carbon#282]
## HTML elements and JS binding gets lost
It happens from time to time, that HTML elements which require some JS code don't work anymore

### Detailed description
I am working on an Angular 2 project using the Carbon Components Framework. I am still in development and using the ng cli and ng serve command to run the application. To remove any doubts I included the JS file directly into the index.html. In my application for now I am using the InteriorLeftNav and the Tooltips. The problem is that sometimes the InteriorLeftNav doesn't work anymore. It does not react on any clicks. 
It seems like this is an JS problem because other elements who are using JS like Tooltips don't work either. I checked this with the Dropdown module as well.
I really cannot say how to reproduce this, it just happens randomly. To fix this it normally helps to restart the ng serve or the browser.

> What browser are you working in?
Safari and Firefox

> What version of the Carbon Design System are you using? 
Latest

**Comment by hellobrian** [comment]
Maybe @asudoh can help you out. 

Have you tried disabling the auto-initialization of the JS and then calling `init()` manually?

![image](https://user-images.githubusercontent.com/4185382/29286361-0d4a374a-80ef-11e7-9b7b-ecefb6de423d.png)

```js
CarbonComponents.InteriorLeftNav.init();
CarbonComponents.Tooltip.init();
```

[Source](http://carbondesignsystem.com/getting-started/developers)

**Comment by asudoh** [comment]
Another thing that may help is setting a breakpoint inside https://github.com/carbon-design-system/carbon-components/blob/75614889181af04dc62104d4640c45ec558f9717/src/components/interior-left-nav/interior-left-nav.js#L23-L58 and see if it the event listener runs or not. If the event listener runs even in the failing situation, it's likely that the code failed to find the corresponding nav item (e.g. due to unexpected markup). If the event listener does not run in the failing situation, it's likely that the corresponding `InteriorLeftNav` instance is missing as @hellobrian implied.

**Comment by leondroidgeeks** [comment]
Thank you both! @hellobrian your solution works!
For me I had to include the script .angular-cli.json as
`"scripts": [ "../node_modules/carbon-components/scripts/carbon-components.min.js"]`
because the path to the script changes when I build the application.
Now I have to turn on each component in the index.html in a script block.
