### ISSUE TITLE
[icons-angular] Add clarification around icon size differences/usage

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#2911]
Each icon is designed at a specific size, which requires our separate components per icon - that reasoning isn't clear in the current documentation.

Assigning myself for `icons-angular` ... but this can expand to the other icon packages if needed.

**Comment by joshblack** [comment]
Hi @cal-smith! Will make sure to update this on the website when we're ready to GA `@carbon/icons` and `@carbon/icons-react` 👍 We had to invest some time to author the sketch plugin so that this work could manifest in Sketch for designers to use, and then funnel that to the site with the icons, and then finally the assets for developers.

**Comment by cal-smith** [comment]
Totally makes sense ... I've had a couple questions on this topic now, so I figured I'd at least make sure the angular readme was solid

**Comment by cal-smith** [comment]
stale bot, why do you torment me and my lack of time 😭

**Comment by cal-smith** [comment]
🙂

**Comment by cal-smith** [comment]
🙁

**Comment by cal-smith** [comment]
Okay fine, you win stale bot ... this isn't even a conversation, just something I have to do 😒
