### ISSUE TITLE
[SelectableTile] Failed prop validation and null target value

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon#2959]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

On initial render, I get the following warning in console:
```
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

Also, I am trying to log the value of the selected box, but I'm getting the following error:
```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist().
```

> Is this issue related to a specific component?

Yes, `SelectableTile`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When the tile is clicked, I am expecting to be able to log the value of the selected item.

> What browser are you working in?

Latest Chrome

> What version of the Carbon Design System are you using?

v9 and v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

cloud.ibm.com/vpc

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/8ll6k38989

## Additional information
<img width="872" alt="Screen Shot 2019-06-06 at 4 25 19 PM" src="https://user-images.githubusercontent.com/7707326/59064193-ba530700-8877-11e9-9b65-22a3f09ea198.png">

**Comment by abbeyhrt** [comment]
@rob-richards Thanks for making this issue! PR #3431 will address the Warning: Failed Proptype error and I am working now to add the ability to log out the target value. I will update this issue when that is merged in!

**Comment by abbeyhrt** [comment]
@asudoh Looking into this, it seems like the Tile component isn't made to be able to log out `evt.target.value`, do you know if there is any particular reason it was made this way or could it be changed? Maybe naively, it does seem like a good enhancement for a user to be able to log the value of a selected tile.

**Comment by asudoh** [comment]
@abbeyhrt Some event listener callback in `<SelectableTile>` seems to run as a callback of `setState()`. Given `setState()` callback runs asynchronously, we need to call `event.persist()` for the `event` to live longer.

**Comment by abbeyhrt** [comment]
@asudoh Yeah! One thing I forgot to mention is that the synthetic event warning stated in the issue has already been fixed in newer versions of carbon-components-react because `event.persist()` was added. However, it still seems like `event.target.value` will always be undefined because the `value` isn't being supplied to the target.  I could for sure be doing something wrong but here's a code sandbox that shows what I mean: https://codesandbox.io/s/carbon-components-react-krwsq

**Comment by asudoh** [comment]
Seems that [this line](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/react/src/components/Tile/Tile.js#L293) is the culprit for the particular case. Given the `click` event is fired on `<label>` instead of the `<input>`, `event.target` is `<label>` instead of `<input>`, and thus does not have `value`. Not sure how hard it'll be to ensure event fires on the `<input>`, but if it's not possible, the typical case we'd do is adding a second argument, which is an object, that tells more context of the event, which is, the new `value`. This approach is akin to [`event.detail` in `CustomEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/detail).

**Comment by xubinnb** [comment]
Any progress for this issue? The issue was found in the product which is using carbon-components version 9.91.4 and carbon-components-react version 6.115.5.

**Comment by tw15egan** [comment]
Closed via https://github.com/carbon-design-system/carbon-components-react/pull/2401
