### ISSUE TITLE
[UI Shell Theming] - Development - add global tokens for theming functionality

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#2998]
- [ ] Add theme tokens for UI Shell components
    - header
    - sidenav 
    - right panel
    - navigation links
- [ ] Update any necessary documentation on website

**Comment by vpicone** [comment]
Just want to clarify on this one, the goal is to use theme tokens to define the shell variables right? Component-specific tokens like `$shell-side-nav-accent-01` should be tied to theme tokens if possible I think, `brand-01` in this case rather than the hard coded blue-60.

This would mean users only need to override brand-01 for color changes to propagate into the components

**Comment by tw15egan** [comment]
@vpicone that's correct, also to simplify the number of variables there currently are.

**Comment by vpicone** [comment]
Not stale, we still need this for the gatsby theme. I imagine other projects would like to theme this component as well.

**Comment by xSCIven** [comment]
I am interested in this feature? Any possibility of it being added?

**Comment by tw15egan** [comment]
@xSCIven this is part of our V11 effort and updates can be tracked in https://github.com/carbon-design-system/carbon/issues/8409
