### ISSUE TITLE
UI shell option for no padding on content

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#3010]
2rem padding was introduced on `bx--content` in 10.3.0.

![image](https://user-images.githubusercontent.com/1691245/59237055-68cfb280-8bbe-11e9-868b-8ce05d3f81dc.png)

If you're using grid in UI shell, `bx--grid` sets the outermost 2rem padding.

![image](https://user-images.githubusercontent.com/1691245/59237096-89980800-8bbe-11e9-803d-7179077a65d1.png)

UI shell should have an option to not add padding to `bx--content` to give the application full control over its layout. Or, default to no padding and have an option (class) to add padding.

**Comment by mattrosno** [comment]
Not stale

**Comment by mattrosno** [comment]
Not stale

**Comment by fabpico** [comment]
I ran in to the same issue, there is even a comment linked to this issue in the [official Carbon React tutorial's index.scss](https://www.carbondesignsystem.com/developing/react-tutorial/step-4).
```
/// Padding was introduced in 10.3.0, needs an option to let grid set the viewport gutter
/// @link https://github.com/carbon-design-system/carbon/issues/3010
.bx--content {
  padding: 0;
}
```
Even if i use `bx--grid--narrow`, the additional left padding is still there. IMO the problem is more on the combined usage of the `Content` component and the Carbon Grid classes, not the UI Shell (which only consists in Header, Left-/Right Panel as far i can see).

I see it can be [compensated](https://www.carbondesignsystem.com/guidelines/2x-grid/implementation#how-it-works):

> Each column has horizontal padding (aka a gutter) that defines the space between them. You can negate this padding at the row level with negative margins, allowing the content within your columns to be aligned along the left side.

But for me this is a workaround, not an option.

**Comment by mattrosno** [comment]
Hi @FabianPiconeDev - thanks for your comment. I agree that this override should not be required by everyone who uses the `Content` component with the grid.

We are currently evaluating CSS Grid as part of our 2021 release. See https://github.com/carbon-design-system/carbon/issues/7538

CC @joshblack @tay1orjones can we make sure to look at the `Content` component to make sure it plays nicely with our updated grid, so we can then remove this override used in the tutorial?

**Comment by Medformatik** [comment]
@mattrosno Can you give an update on the override in the tutorial? Is it still required?

**Comment by mattrosno** [comment]
Hi @Medformatik - this issue was opened 2019. Looking at the code for the React tutorial, as of September 2023, it appears yes. The override is still used in the tutorial.

https://github.com/carbon-design-system/carbon-tutorial-nextjs/blob/d59bede4f1ef71f0a8e43273ac3cf8d1f6b75e68/src/app/globals.scss#L22

You can see a preview of the completed tutorial here:

https://carbondesignsystem.com/developing/react-tutorial/overview
