### ISSUE TITLE
Scrollable tabs header

### ISSUE THREAD

**Issue by Pablodotnet** [carbon-design-system/carbon#3022]
### Summary

If we have a lot of tabs, they should have a limit of showable tabs and add a navigation method to navigate to the not showing tabs, like left/right arrows or scrollable header.

### Justification

We can have a lot of tabs and now it is designed to display every tab available, so it should have the ability to limit by the size of the container or by another method.

### Desired UX and success metrics

I'll show how Angular Material handles this issue on the next screenshot:
<img width="652" alt="Screen Shot 2019-06-11 at 12 25 23 PM" src="https://user-images.githubusercontent.com/10190000/59299636-c0b7f900-8c52-11e9-91d4-592a4612235d.png">

### "Must have" functionality

Set a limit of tabs or make it respect the container width to set the navigation and scrollable header.

### Specific timeline issues / requests

We need this functionality so it can be implemented in angular carbon components as soon as possible as it is for a really important project that needs to be presented to high rank executives in IBM in this month.

### Available extra resources

The screenshot of how it is implemented in Angular material and the link to the example:

https://material.angular.io/components/tabs/overview

<img width="652" alt="Screen Shot 2019-06-11 at 12 25 23 PM" src="https://user-images.githubusercontent.com/10190000/59299812-37ed8d00-8c53-11e9-9818-5b403f37ed07.png">

**Comment by asudoh** [comment]
Hi 👋 IIRC our guidance is using drop-down style for where the horizontal space is constrained. You can try narrowing your browser at https://the-carbon-components.netlify.com/component/tabs--default.html to see what it's like. Thanks!

**Comment by Pablodotnet** [comment]
@asudoh Hi, I'm not talking about responsiveness behavior,  I'm talking about when you have a big amount of tabs, in your example I added some more and they get out of the screen: 

<img width="1276" alt="Screen Shot 2019-06-13 at 11 41 49 AM" src="https://user-images.githubusercontent.com/10190000/59451166-6ba1f180-8dd0-11e9-92a0-941a5d162163.png">

**Comment by asudoh** [comment]
IIRC our recommendation is using an alternate means (e.g. side navs?). CC @carbon-design-system/design to get their insights.

**Comment by chrisconnors-ibm** [comment]
our current guidance is varies between desktop and mobile.

on desktop the guidance is: 
1) Avoid this wherever possible;
2) If it can't be avoided (seriously, rethink groupings, organization, IA, and possibly the underlying data model to avoid this), the off-screen tabs should cascade into a `overflow menu` (this is the original use of this item and source of the name; the tabs 'overflowed' the width.) When you select the last tab from the overflow, presumably the first couple are now off screen to the left, so the overflow moves to the left and contains the overflow tabs from the beginning of the tab row.

On mobile the typical move is to translate the tabs into a dropdown selector (that's a mobile platform choice) when they exceed the view dimensions. in each case you are making a mutual selection and changing the driven view based on the choice.

However, since horizontal scrolling on mobile/touch UIs is _much_ less onerous than side scrolling on mouse mediated UIs, a side scrolling tab component for mobile is currently under exploration.

when I look here, I don't see the swipe under example in your screen shots, having inspected the page, put it in mobile mode, couple different devices. I also didn't see that behavior in just responsive mode (narrow browser). **how did you provoke it?**
![image](https://user-images.githubusercontent.com/35537391/59533513-b3e90e80-8eb9-11e9-987c-d0461070cfca.png)
![image](https://user-images.githubusercontent.com/35537391/59533566-dbd87200-8eb9-11e9-9354-262dcf3acf22.png)

**Comment by laurenmrice** [comment]
not stale

**Comment by shixiedesign** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by joshblack** [comment]
Thanks so much for submitting this proposal! 🥳 We want to move forward with this work but will use the following issue to keep track of things. Thanks again! https://github.com/carbon-design-system/carbon/issues/4758
