### ISSUE TITLE
[Accordion] Write specification

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3076]
**Create content structure**
- [x] Define the component 
- [x] Structure of component
- [x] Visual images of spec
- [x] Keyboard interactions
- [ ] Compliant rules

**Comment by laurenmrice** [comment]
### Definition ###
An accordion is a vertically stacked set of headers that each contain a title, additional elements, and a section of content upon expansion. The headers enable users to reveal or hide sections of content. The accordion component delivers large amounts of content in a small space through progressive disclosure. Accordions are commonly used to reduce scrolling and work especially well on mobile interfaces or whenever vertical space is at a premium.

![accordion_component_spec](https://user-images.githubusercontent.com/43969356/60611419-e2a52700-9d8b-11e9-88eb-9e663d0a0089.png)


----------------------------------------------------------------------------------------------------

### Structure ###
**Accordion header**
A title with an accompanying chevron icon to collapse and/or expand hidden content.

![accordion_component_spec _header](https://user-images.githubusercontent.com/43969356/60611365-c73a1c00-9d8b-11e9-86d4-f977f994e424.png)


**Accordion content**
A section of content associated with an accordion header upon expansion. In some accordions, there are additional elements that are always visible adjacent to the accordion header.

![accordion_component_spec_content](https://user-images.githubusercontent.com/43969356/60611396-d325de00-9d8b-11e9-8e93-cb2f5ff4a074.png)

----------------------------------------------------------------------------------------------------
### Theming ###
**Color**

Class | Property | Color token
-------- | -------- | -------- 
`.bx--accordion__title` | color | `$text-01`
`.bx--accordion__content` | color | `$text-01`
`.bx--accordion__arrow` | fill | `$icon-01`
`.bx--accordion__item` | border-top | `$ui-03`

**Typography**
All accordion labels are set in sentence case and should not exceed three words. Set body text appropriately based on content.

Class | Font-size (px/rem) | Font-weight | Type token
-- | -- | -- | --
`.bx--accordion__title` | 14 / 0.875 | Regular / 400 | `$body-long-01`
`.bx--accordion__content` | 14 / 0.875 | Regular / 400 |`$body-long-01`

**Structure**
There is no limit to the height of an open row, but there should always be a border bottom 24px padding. The width of an accordion varies based on the content, layout, and page design. Avoid having any text within 16px / 1rem of the accordion’s sides. Additionally, include padding between headers, content, and separation rules to provide breathing room between elements.

Class | Property | Px/rem | Spacing token
-- | -- | -- | --
`.bx--accordion__heading` | height | 32/2 | -
`.bx--accordion__item` | border-top | 1 | -
`.bx--accordion__arrow` | size | 16/1 | -
`.bx--accordion__arrow` | padding-right | 16/1 | `$spacing-05`
`.bx--accordion__title` | margin-left | 16/1 | `$spacing-05`
`.bx--accordion__content` | padding-right | 25% | -
`.bx--accordion__content` | padding-top | 8/0.5 | `$spacing-03`
`.bx--accordion__content` | padding-left | 16/1 | `$spacing-05`
`.bx--accordion__item--active` | padding-bottom | 24/1.5 | `$spacing-06`

----------------------------------------------------------------------------------------------------

### Keyboard Interaction ###  
_(dev - to-do test links)_

**Enter**
When focus is applied to an accordion header for collapsed content, enter expands the hidden content. By default, multiple headers can be expanded at a time. If the implementation allows one header to be expanded at a time and if another header is also expanded, the previous expanded header will be auto-collapsed.

When focus is applied to an accordion header for expanded content, enter collapses the expanded content.

By default, implementation supports collapsing and all headers can remain collapsed or open at the same time. A feature of an accordion requires one header to be expanded at all times and allows one header to be expanded at a time, they do not support a collapse function.

**Tab**
Moves focus to the next focusable element; all focusable elements in the accordion are included in the page Tab sequence.

**Shift + Tab**
Moves focus to the previous focusable element; all focusable elements in the accordion are included in the page Tab sequence.

**Down Arrow**_(Like to have - need fail link)_
When focus is on an accordion header, the down arrow will move focus to the next accordion header below it. When focus is on the last accordion header, the down arrow either does nothing or moves focus to the first accordion header. 

**Up Arrow**_(Like to have - need fail link)_
When focus is on an accordion header, the up arrow moves focus to the previous accordion header. When focus is on the first accordion header, the up arrow either does nothing or moves focus to the last accordion header.

**Home**_(Like to have - need fail link)_
When focus is on an accordion header, the home key moves focus to the first accordion header.

**End**_(Like to have - need fail link)_
When focus is on an accordion header, the end key moves focus to the last accordion header.

----------------------------------------------------------------------------------------------------

### Roles, States, and Properties ### 
_(dev to-do)_

**Comment by laurenmrice** [comment]
WIP box note: https://ibm.box.com/s/pvefjo8kbkvuz1q32ct0asznd4ht0tgl

**Comment by elizabethsjudd** [comment]
Can I get access to the box note

**Comment by elizabethsjudd** [comment]
Thanks @laurenmrice! This document seems to be a lot more DRY while still being very comprehensive.

## Accordion
* the level of detail between the button and accordion structures are quite different.  The button shows each element that makes up the component, where in the Accordion header it only calls out the height of the header. The header is the whole container which has the title and section state indicator (chevron) as children. I personally liked the more detailed section as it helped represent the actual pieces that make up the header and show what Carbon views as possible "content areas".
* `In some accordions, there are additional elements that are always visible adjacent to the accordion header.` doesn't this belong under the `Accordion header` section?
* The 25% padding-right for the content area has been a confusing conversation in Modals as well as I've seen multiple conversations in slack and GitHub where "text" is only suppose to be 75% the width but that other elements (tables, input fields, etc) should be 100% width. This document would be a great place to clarify that expectation.
* In regards to the height of headers, is this value derived from the font-size + padding/margin or is it a hard coded value?  If it's a hard-coded value, does that mean that an offering wouldn't be able to ever have two lines of text within the header?
* For the size of the chevron, you use `16/1` where in button the size of the icon is represented as `16px x 16px`. I think consistency is really key in these types of documents.
* For keyboard interactions there are a few places where we say a key can do "this" or "that". I understand that as far as a11y is concerned that either is a valid option but to have consistent user experiences Carbon should note the "preferred" experience and  note that the other option is valid but deviates from the ideal Carbon experience if it's going to include two different options (e.g. `the down arrow either does nothing or moves focus to the first accordion header. `).
* The user should be able to press `space` as well to expand/collapse accordion headers (https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html)
* `A feature of an accordion requires one header to be expanded at all times and allows one header to be expanded at a time, they do not support a collapse function.` Typo?
* By nesting the different "features" such as restricting how many headers can be open, if all headers can be collapsed, etc. under the keyboard interactions, it makes it difficult to find especially since this experience applies to all user types.  Just like button's had sizes, kinds, etc., these different features should be in their own section (personally, i view it as a modifier of the accordion).
* The keyboard interactions are great but we should also consider the screen reader user's experience when describing the spec of a component.  For accordion specifically, the screen reader should announce the state of the accordion section (expanded or closed) when they are on the title and when the accordion section is closed the screen reader should not have access to the content within the panel.
* Because the header is an interactive element, there should be focus/hover states to inform users that they can interact with it.

**Comment by scottnath** [comment]
hi @laurenmrice 

On the structure of the specification itself, and with comparing this doc to the [button specs](https://github.com/carbon-design-system/carbon/issues/3080), there may be a consistency issue that will arise with how keyboard interactions are documented. 

My suggestion would be that component interactions are instead broken up by feature or element and the given circumstances. The reason being, each feature or element has multiple user-input and system-output options, and some items (like arrows or tabs) will have different functionality according to the feature's needs, if the element that has focus, etc. The structure above may be difficult to navigate on more complex components that have a lot of moving parts.

as an example, if a developer is creating the header of the accordion, then they need to know:

* what happens when a user focuses on the header?
  * if the header is open...
    * user may click the header and close it
    * user may hit enter and close it
    * user may hit tab to go through tab-able content in the open accordion
    * user may hit shift-tab to navigate to the previous accordion item
    * user should be informed by the screen reader the state of this section
    * user should be informed of the title of the accordion section by the screen reader
    * user may single-tap the header and close it
  * if the header is closed...
    * mouse user experience
        * are there hover states?
        * are there disabled-headers? does that affect hover?
    * keyboard user experience
        * tab in / out
        * key that opens it, where to move cursor
    * screen-reader user experience
        * what's read to them? 
    * touch user experience (future feature)
        * different than click in some instances, how do we program for that?

The concern I'm raising with the above structure is that the keyboard section is broken up by `key`, then there needs to be a separate section to detail each screen reader expectation, each mouse user's experience, etc. Also, each `key` can have X number of features connected to it, so if a developer needs to know what `key`s should have an affect on a given accordion header, then they'll need to read all of the keyboard specs to determine what keys will have an effect. The same for anyone who is writing testing for these components - they'll need to read through each paragraph of each keyboard interaction to make sure they didn't miss a keyboard-related expectation for an accordion header.

For a developer programming this, or a QA person testing this, they'll need a clear way to know what happens under various given circumstances. 

The given circumstances are important in that they not only tell the developer what should happen in each possible user-interaction, they also inform the testing as to what setup to create in order to test that the component is doing what's expected. e.g. - "view the accordion in the browser, tab through to the last header, hit `enter` - test that: 1. the last accordion is open, 1. the focus has moved to the first focusable item in the content, the `arrow-up` button ?, the `arrow-down` button ?, the screen reader says 'meow', etc" 

Here's an example of the kind of circumstances that a breakdown of a feature could look like:

## User interactions

### Component-wide

### Accordion header

#### When focused and closed

#### When focused and open

#### When disabled

#### When header is the first header element

#### When header is the last header element

### Accordion content

#### When closed

#### When open

#### When content is the last accordion element


This clearly would change the specifications into something larger and more granular, but clarity will also give a very clear definition of done.

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale , need to be open for future work on component spec project

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by joshblack** [comment]
Going to close this out, let me know if this is in error @laurenmrice!

**Comment by josh-tt** [comment]
@laurenmrice I’m a bit confused. The specs on site show 32px headers as does the code demo. The png on the site style page directly below that info shows 40px. The sketch doc uses 40px. Which is it and/or Is the accordion meant to resize with text? Or is it always meant to be displayed at a fixed size. If body text on page is 16, should accordion use 16 and 16 content or should it always use 14 and 14 content. Thanks

**Comment by laurenmrice** [comment]
This is an old issue that was a wip. Our current according is 32px, if its 40px in the sketch kit then that was a bug. However we are considering offering three different sizes of accordion (48px, 40px and 32px), we will update that in the kit once it's in code. A row in an accordion can grow to different sizes once expanded depending on how long the content is inside of it. Accordion should always use 14px if you are using Carbon.

**Comment by josh-tt** [comment]
Thank you very much for clarifying. I think having additional sizes would be helpful.

Yes, the sketch libraries are 40px height.

Additionally, on the carbon website accordion ‘code’ page, the demo is 32px with 14px title and 16px content.

On the carbon accordion style page (typography) the specs say ‘set appropriately based on content’ which is a bit unclear, given that the specs below indicate 14px for both title and content.

And below those specs there is a image showing a 40px height for the title.

🙏

**Comment by laurenmrice** [comment]
Yes, the component demo on the code page is currently a new enhancement we added recently and that is a bug they are working on 👍🏻. The content inside should also be 14px.
