### ISSUE TITLE
[Button] Write specification

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#3080]
**Create content structure**
- [x] Define the component 
- [x] Structure of component
- [x] Visual images of spec
- [x] Keyboard interactions
- [ ] Compliant rules

**Comment by laurenmrice** [comment]
### Component Definition ### (when and why)
An accordion is a vertically stacked set of headings that each contain a title, additional elements, and a section of content upon expansion. The headings enable users to reveal or hide sections of content. The accordion component delivers large amounts of content in a small space through progressive disclosure. Accordions are commonly used to reduce scrolling and work especially well on mobile interfaces or whenever vertical space is at a premium.

### Anatomy ###
Accordion heading
A title with an accompanying chevron icon to collapse and/or expand hidden content.

Accordion content
A section of content associated with an accordion header upon expansion. In some accordions, there are additional elements that are always visible adjacent to the accordion header.

**Comment by laurenmrice** [comment]
### Definition ###
A button enables users to initialize an action or event, such as signing up for an account, submitting a form, canceling an action, or deleting an item. There are five different kinds of buttons. Each button kind comes with three variations of what can be inside a button. Buttons can be set at three different sizes. Avoid using mixed button sizes on one page. Buttons can also be in displayed in sets. Do not use buttons as navigational elements. Instead, use links when the desired action is to take the user to a new page. 

----------------------------------------------------------------------------------------------------

**Kind**
There are five different kinds of buttons: primary, secondary, tertiary, ghost and danger.

![button_component_spec _kind](https://user-images.githubusercontent.com/43969356/60612140-98bd4080-9d8d-11e9-8aa8-5f1432300096.png)

Kind | Purpose
-- | --
Primary | Used as the principal call to action on a page.
Secondary | Reserved for supportive or secondary actions on a page.
Tertiary | Similar to primary buttons but require less emphasis on a single call to action.
Ghost | Used when an action does not require primary dominance on the page.
Danger | Used for negative actions.

----------------------------------------------------------------------------------------------------

**Size**
There are three different sizes of buttons: default, field and small.

![button_component_spec _size](https://user-images.githubusercontent.com/43969356/60612250-cd30fc80-9d8d-11e9-95f1-1675efc81b7e.png)

Size | Purpose
-- | --
Default (48px) | need content
Field (40px) | Lives directly next to an input element, to visually align component heights.
Small (32px) | Used when there is not enough vertical space for a default button. This issue is most found in tables. Small buttons should have three words or less.

----------------------------------------------------------------------------------------------------

**Variant**
_(might not be the right word)_

There are three different variants of a button: a button with text, text and icon, and only icon.

![button_component_spec_variant](https://user-images.githubusercontent.com/43969356/60612351-ff425e80-9d8d-11e9-8835-0678261d699b.png)

Variant | Purpose
-- | --
Text only | need content
Text and icon | An icon can be paired with text in a button to better communicate what the button does.
Icon | Icons are used in the product to present common actions and commands. Modify the fill property to change the color of the icon. The name property defines which icon to display. For accessibility, provide a context-rich description with the description prop.

----------------------------------------------------------------------------------------------------

**Set of buttons**
When an action required by the user has more than one option, always use a negative action button (secondary) paired with a positive action button (primary) in that order. Negative action buttons will be on the left. Positive action buttons should be on the right. Buttons in a set should be flush together and always be equal size in height and width. The width for a set of buttons is determined by the button with the longest label. When these two types of buttons are paired in the correct order, they will automatically space themselves apart. _(do we really want to say 'negative action button' , to me this almost references a danger button? should we get rid of the last sentence?)_

![button_component_spec_set of buttons](https://user-images.githubusercontent.com/43969356/60612419-2a2cb280-9d8e-11e9-8de3-f60601266b09.png)

----------------------------------------------------------------------------------------------------

### Structure ###

**Container**
Buttons have a visible container around the text and/or icon. Ghost button is the only exception when a container is only visible on hover, active and focus.

**Label**
Text is required except when using an Icon button.

**Icon**
Icons are used in the product to present common actions and commands. Modify the fill property to change the color of the icon. The name property defines which icon to display. For accessibility, provide a context-rich description with the description prop. _(this may need rewording)_

![button_component_spec_structure](https://user-images.githubusercontent.com/43969356/60612483-53e5d980-9d8e-11e9-8dd0-85e23fda79bb.png)

----------------------------------------------------------------------------------------------------
### Theming ###

**Structure**
A button with text has 16 pixels /1 rem padding on the left and 64px on the right after the last letter of the label. A text and icon button has a 16px padding on the left, 32px padding between the last letter of the label and the icon and 16px right padding after the icon (Ghost button is an exception and gets a 8px padding between the last letter of the label and the icon). 

Class | Property | Px / rem | Spacing token
-- | -- | -- | --
`.bx--btn--primary` | height | 48 / 3 | -
`.bx--btn--sm` | height | 32 / 2 | -
`.bx--btn__icon` | size | 16 x 16 | -
`.bx--btn` | padding-left | 16 / 1 | `$spacing-05`
`.bx--btn` | padding-right | 64 / 1 | -
`.bx--btn--sm` | padding-left | 16 / 1 | `$spacing-05`
`.bx--btn--sm` | padding-right | 64 / 4 | -
`.bx--btn__icon` | margin-left, margin-right | 16 / 1 | `$spacing-05`
`.bx--btn--ghost` | padding-left, padding-right | 16 / 1 | `$spacing-05`

**Typography**

Class | Font-size (px/rem) | Font-weight | Type style
-- | -- | -- | --
`.bx--btn` | 14 / 0.875 | Regular / 400 | `$body-short-01`

**Color**
**Primary button**
![button_component_spec _kind_primary](https://user-images.githubusercontent.com/43969356/60996170-bbb19c80-a319-11e9-8c49-69c8b9424ca8.png)

Class | Property | Color token
-- | -- | --
`.bx--btn--primary` | text color | `$text-04`
`.bx--btn__icon` | svg | `$icon-03`
`.bx--btn--primary` | background-color |`$interactive-01`
`:hover` | background-color | `$hover-primary`
:`active` | background-color | `$active-primary`
`:focus` | border | `$focus`
`:disabled` | background-color | `$disabled-02`
:`disabled` | text color | `$disabled-03`

**Secondary button**
![button_component_spec _kind_secondary](https://user-images.githubusercontent.com/43969356/60996187-c10ee700-a319-11e9-86e9-93de89841fad.png)

Class | Property | Color token
-- | -- | --
`.bx--btn--secondary` | text color | `$text-04`
`.bx--btn__icon` | svg | `$icon-03`
`.bx--btn--secondary` | background-color | `$interactive-02`
`.bx--btn--secondary` | border | `$interactive-02`
`:hover` | background-color | `$hover-secondary`
`:active` | background-color | `$active-secondary`
`:focus` | border | $focus
`:disabled` | background-color | `$disabled-02`
`:disabled` | text color | `$disabled-03`

**Tertiary button**
![button_component_spec _kind_tertiary](https://user-images.githubusercontent.com/43969356/60996211-ccfaa900-a319-11e9-981f-0cbe97d1e82b.png)

Class | Property | Color token
-- | -- | --
`.bx--btn--tertiary` | text color | `$interactive-03`
`.bx--btn__icon` | svg | `$interactive-03`
`.bx--btn--tertiary` | background-color | `transparent`
`.bx--btn--tertiary` | border | `$interactive-03`
`:hover` | text color | `$text-04`
`:hover` | svg | `$icon-03`
`:hover` | background-color | `$hover-tertiary`
`:active` | background-color | `$active-tertiary`
`:focus` | border | `$focus`
`:disabled` | background-color | `$disabled-02`
`:disabled` | text color | `$disabled-03`

**Ghost button**
![button_component_spec _kind_ghost](https://user-images.githubusercontent.com/43969356/60996226-d126c680-a319-11e9-8e12-f5a780ad0d73.png)


Class | Property | Color token
-- | -- | --
`.bx--btn--ghost` | text color | `$link-01`
`.bx--btn__icon` | svg | `$link-01`
`.bx--btn--ghost` | background-color | -
`:hover` | text color | `$hover-primary-text`
`:hover `| svg | `$hover-primary-text`
`:hover` | background-color | `$hover-ui`
`:active` | background-color | `$active-ui`
`:focus` | border | `$focus`
`:disabled` | text color |` $disabled-03`

**Danger button**
![button_component_spec _kind_danger](https://user-images.githubusercontent.com/43969356/60996239-d6841100-a319-11e9-9fa1-4b04677fcbe3.png)


Class | Property | Color token
-- | -- | --
`.bx--btn--danger--primary` | text color | `$text-04`
`.bx--btn__icon` | svg | `$icon-03`
`.bx--btn--danger--primary` | background-color | `$support-01`
`:hover` | background-color | `$hover-danger`
`:active` | background-color | `$active-danger`
`:focus` | border | `$focus`
`:disabled` | background-color | `$disabled-02`
`:disabled` | text color | `$disabled-03`


----------------------------------------------------------------------------------------------------

### Keyboard Interaction ###
_(dev - to-do test link)_

**Space**
When focus is on a button, space activates the button.

**Enter**
When focus is on a button, enter activates the button.

**Activation**
- When activating the button opens a modal, the focus moves to the first element inside of the modal. 

- When activating the button closes a modal, the focus will return to the button that opened the modal unless the function performed in the modal context logically leads to a different element. For example, activating a cancel button in a modal returns focus to the button that opened the modal. However, if the modal were confirming the action of deleting the page from which it was opened, the focus would logically move to the next logical element.

- When activating the button does not dismiss the current context, the focus will remain on the same button after activation. For example, Reload button, Apply button.

- When the button action indicates a context change, such as moving to the next step in a wizard or adding another item, then focus should move to the starting point for that prompted action.

   

----------------------------------------------------------------------------------------------------
### Roles, States, and Properties ### 
_(dev)_

WIP box link: https://ibm.box.com/s/60a4drazrgb6izd3rg8n7eipenzy4j6m

**Comment by elizabethsjudd** [comment]
Can I get access to the box file

**Comment by elizabethsjudd** [comment]
Thanks for typing this up @laurenmrice. Overall it's very comprehensive around the specifications of the Button component.  Most of my comments are around the maintainability of the document as the information is repeated in multiple locations and if it's not automated can very easily become out of sync.

I saw you had a question around the name "variants", in Watson Health we use the term "scenarios" to describe different content models/HTML structures for components.  We use "variants" instead of "kind" though which is why we have something different. (https://pages.github.ibm.com/Watson-Health/presentations/mvp.html#/3/4/1 -- click on "demo types" for more information on how we break down our categories).

## Button
* `signing up for an account` this example could easily be taking the user to a new page and would be a link which could then be confusing to the user since we say links are used for any navigation.
* By defining the number of kinds, variants, and sizes in the description there is additional maintenance to keep that information in sync.  Is it necessary when the breakdown is immediately following that paragraph?
* Includes implementation specific instructions (`Modify the fill property to change the color of the icon. The name property defines which icon to display. For accessibility, provide a context-rich description with the description prop`). I think there could eventually be a "common configuration" that a component follows no matter what the framework but peppering it in the prose is difficult to keep in sync since it's repeated and not easily findable. I also feel like this may be out of scope for initial spec work.
* I agree that it's confusing to use `negative action` for both "danger" and "secondary" within a set. Maybe the danger definition could be something more like 'the user should be cautious of taking the action, such as actions that can not be undone.
* `always use a negative action button (secondary) paired with a positive action button (primary) in that order.` Don't modals do the exact opposite?
* `The width for a set of buttons is determined by the button with the longest label.` don't they take up the space provided, such as in modals, they are 50/50 of the space even if the words within a button are short.
* Icon-only buttons should have the context-rich description available to users when they interact (hover/focus) with the button unless it's disabled. This is inherited from the `icon tooltip` component.
* The label is still required for an Icon only button, it's just not visible to users in its default state.
* Typo: `.bx--btn | padding-right | 64 / 1	| - ` --> 64 should be 4rems
* The structure table for the `margin-left/margin-right` values are confusing. Isn't there `0` margin right
* The structure table for the `padding-left/padding-right` values are confusing. Isn't there `0` padding-right and `8` padding-left based on the prose before the table?  Having this information in the document twice (unless automated) is very easy to get out of sync.
* Are the the themeing tables automated?  This could be very easily outdated with the code otherwise. 
* Some typos for the states where the semi-colon is not part of the `<code>` element in the primary button color table
* For `bx--btn__icon` wouldn't the property be `fill` since `svg` is a selector.
* For Keyboard actions, enabled buttons should also be in the page tab order and can be navigated to via the `tab` and `shift+tab` keys.
* Under `Activation` the first two bullet points are actually examples of the the last two points. Maybe switch their order or make them sub-bullets of the more generalized statements.

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale , need to be open for future work on component spec project

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by joshblack** [comment]
Going to close this out @laurenmrice, let me know if I should re-open!
