### ISSUE TITLE
Modal customization

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3084]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

Can I customize the Modal header to have more complex structure rather than a simple title? I mean If I need to put a combo-box there... something like:

Is Modal good enough for such complex component? Any other ways?

And one more thing, is it possible to change the launch button of the modal to be simply a hyperlink?

**Comment by asudoh** [comment]
Hi 👋 the modal looks very different from our modal intends. Wondering if this is something that came from discussion with your designer on Carbon version of your application.

From technical perspective, [`<ComposedModal>`](http://react.carbondesignsystem.com/?path=/story/composedmodal--using-header-footer-props) is the closest, which allows you to put any content you'd like. Also technically, anything can launch modal, because `<Modal>` or `<ComposedModal>` has `open` prop that opens or closes the modal.

**Comment by zbeedatm** [comment]
I'll consider the ComposeModal.
In the meanwhile I used the InputModal from WrapperModal, but it doesn't have the open property.

**Comment by asudoh** [comment]
`<ModalWrapper>` merely is a demonstration-purpose-only component. You can use `<Modal>` instead, which has `open` prop.
