### ISSUE TITLE
Is it possible to have Tabs displayed vertically and not horizontally?

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon#3085]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary

Is it possible to make tabs displayed vertically?

**Comment by emyarod** [comment]
it doesn't appear that vertical tabs are part of our component spec, but if you could elaborate more on your use case it may be achievable with some CSS tweaks

**Comment by zbeedatm** [comment]
Based on this post it seems possible by some css tweak:
https://stackoverflow.com/questions/53960066/how-to-make-vertical-tabs-with-react

Also you can see this example from other component that has this feature:
https://garden.zendesk.com/react-components/tabs/#tabpanel

**Comment by emyarod** [comment]
yeah it's not something we offer out of the box with Carbon currently but it may be something our design team has considered cc @carbon-design-system/design. if it is something we want to support in our library we can add this to our queue of enhancements to work on. but in the meantime it is also possible to implement on your end as you've found

**Comment by shixiedesign** [comment]
This would be an enhancement! We will evaluate next month. Thanks.

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by zbeedatm** [comment]
Hi, is it planned to have this feature soon?

**Comment by carmacleod** [comment]
Note: When you add this feature, please be sure to add `aria-orientation="vertical"` to the element that has `role="tablist"` and ensure that `up/down arrow` keys navigate through the tabs instead of `left/right arrow`, as per this [APG advice for accessible vertical tablists](http://w3c.github.io/aria-practices/#tabpanel).

Here's a few alternative styles:

1. Exactly like horizontal, except vertical:
![image](https://user-images.githubusercontent.com/3331913/68512505-98a2e500-0246-11ea-9b62-6139c2cc703b.png)
2. Almost the same, except selected tab is color instead of black:
![image](https://user-images.githubusercontent.com/3331913/68531522-f71ca180-02e0-11ea-984d-35bdf36de570.png)
3. Similar to 2, except without lines, and tabs are closer together (useful when there are more tabs):
![image](https://user-images.githubusercontent.com/3331913/68531506-cccae400-02e0-11ea-9fcd-239df17a7a8f.png)

**Comment by jeanservaas** [comment]
What I think you're proposing is more of a vertical content switcher and I don't think Carbon wants to support this functionality. It's a bit problematic because anytime you stack items like you have above, the expectation is that you're showing more of a contextual or on-page navigation... not that the content in the target zone will be switching.

We would actually like to build a contextual navigation that I described above — i.e. a component that allows the user to jump to different parts of the page.

@janchild and I have been exploring alternate treatments to the anchor links on the Carbon site and I'm going to make sure the issue is prioritized in a near-term future release, I'll circle back and link to the issue here.
