### ISSUE TITLE
Slider: can't type in random number if the min value is not 0

### ISSUE THREAD

**Issue by q1401030115** [carbon-design-system/carbon#3107]
For the Slider component, I set the min to a non-zero value(10 for example). Then if I want to input a value 20, 30, 40, etc, the value will be set to other value and I can't input my needed value. Also, if I want to delete the value in the textbox, it could be set to the min value.

![image](https://user-images.githubusercontent.com/27209340/59742558-95f82100-92a0-11e9-8fbc-f2d8e77843b1.png)

**Comment by emyarod** [comment]
would you mind creating a [Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) that illustrates the issue you are facing?

**Comment by q1401030115** [comment]
@emyarod Look at the component below:
![image](https://user-images.githubusercontent.com/27209340/62764510-a66a9200-bac0-11e9-91c0-8cadeb0a2b44.png)

Now, If I want to input the value 25, it just change to 105:
![image](https://user-images.githubusercontent.com/27209340/62764647-f9444980-bac0-11e9-9829-2ae879a6f49e.png)


Also, I can't delete the value and leave the input box blank which is not good.

**Comment by tw15egan** [comment]
Can you link to the CodeSandbox you are referencing?

**Comment by q1401030115** [comment]
@tw15egan https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

**Comment by asudoh** [comment]
^ It's the link of the CodeSandbox we provide, could you please put the link to yours?

**Comment by q1401030115** [comment]
@asudoh I'm sorry, but I can't understand how should I provide my codesandbox to you? I just copy the link and paste here. Could you tell me the way to provide it?

**Comment by asudoh** [comment]
You can click on the fork button that gives you a new URL. That's when you can start putting your stuff.

**Comment by ucbdiaz2015** [comment]
I can reproduce this issue with carbon-components v10.10.1 and carbon-components-react v7.10.1. 

Seems to be fixed in 10.10.2 and 7.10.2, but that has another issue where typing in a number sets anything less than min to `min*2` and anything above that to `input + min`. 

I've also seen issues with this version where the value changed on its own each time the component was mounted (probably related to the previous issue).

And another issue with this version setting state too many times when the component mounts, causing my react app to crash.

Here is my sandbox where you can view behavior of the two versions I mentioned above: https://codesandbox.io/s/sleepy-morse-qt1bz

**Comment by asudoh** [comment]
Seems that there is a recent regression, reopening.

**Comment by hongcbjch** [comment]
@asudoh I met this same issue，may I know which carbon version includes the fix? Thanks.

**Comment by tw15egan** [comment]
@hongcbjch looks like any version above  `7.11.0`

**Comment by hongcbjch** [comment]
@tw15egan Thank you.
