### ISSUE TITLE
Unordered list breaks if 10 or more items

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon#3133]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

Unordered list

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Spacing should work for any amount of items in an unordered list (or at least 100)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

website

## Steps to reproduce the issue

https://codepen.io/alisonjoseph/pen/ydgxQe

**Comment by asudoh** [comment]
@alisonjoseph Does #2941 make this better...? Thanks!

**Comment by alisonjoseph** [comment]
No, that PR just seems to address multiple nested list items, this issue has to do with when the numbers have more than one digit there isn't enough space to view them.

**Comment by vpicone** [comment]
@jeanservaas Some more context:


The initial spec for ordered lists asks to increase the space between the counter and the actual item's text based on the counter's value which isn't possible without JavaScript.

![image](https://user-images.githubusercontent.com/4078018/59952771-03dc4e00-9443-11e9-940f-958491a9ff27.png)

To keep _both_ left aligned numbers _and_ left aligned text, we need to increase the space between the counter and the content indiscriminately. Meaning this would happen for each item, even when the list is <10 items (the majority of the time).

I put together a code pen to show what that increased space might look/feel like. You can toggle to higher number sets with the buttons: https://codepen.io/vpicone/pen/GbWdpM. As you can see we're essentially kicking the can down the road until we hit 1000 items.

Implementing this for Carbon would mean permanently increasing the space [here](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/list/_list.scss#L53) along with the nested equivalents. Likely the unordered list as well so that bulleted content aligns with ordered content on a page.

**Comment by alisonjoseph** [comment]
We need @carbon-design-system/design input on how to proceed here, since matching the spec is impossible without adding javascript, which is overkill for an ordered list.

This is currently broken for anyone using Carbon with an ordered list with more than 9 items.

**Comment by jeanservaas** [comment]
@vpicone I thought we decided to solve this your way for lists up through the 100s by adding the fixed width you proposed in your preview link above... it would still be broken for lists with a 1000 or more items, but that use case seemed unlikely to us. I'm going to go back and look at our thread.
