### ISSUE TITLE
[Data table] Zebra stripe table needs help....

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3143]
G10 theme shows that zebra stripes are colored wrong. Stripes should not be getting G10. But I need to check the rest of the component. **Not ready for dev yet**
![image](https://user-images.githubusercontent.com/15144993/59935430-64539700-9413-11e9-9daf-87a308f7606b.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design is this still an issue?

**Comment by laurenmrice** [comment]
yeah i think this is still not right in react. We do have some designs for this which keeps the same color as the default rows but adds a 40% opacity.

**Comment by tw15egan** [comment]
<img width="734" alt="Screen Shot 2020-01-27 at 12 07 29 PM" src="https://user-images.githubusercontent.com/11928039/73209774-cee15980-40fd-11ea-88d0-14a5cade3d31.png">


This is the current Zebra striping (in g10), what hex value do we want to change the odd-numbered rows to?

**Comment by laurenmrice** [comment]
Can you put an opacity on a color token to work across all themes? or do you need the hex value instead to apply the opacity per theme? 

The color token in every theme would use would be `ui-01` with a 40% opacity for the zebra rows.

**Comment by tw15egan** [comment]
Hmm, not sure if that will work. The background of the table is `ui-01`, and the other rows are `ui-01`. An opacity of  .4 on`ui-01`, over a `ui-01` background will just result in every row having the same color. 

<img width="750" alt="Screen Shot 2020-01-27 at 2 48 21 PM" src="https://user-images.githubusercontent.com/11928039/73221241-35be3d00-4115-11ea-863c-7d29845998fd.png">


I think we will have to add a custom zebra striping color for each theme (the actual hex value of $ui-01 at 40%).

**Comment by laurenmrice** [comment]
okie ui-01 hex values in each theme: 

White theme
Gray 10 - #f4f4f4

Gray 10 theme
White - #ffffff

Gray 90 theme
Gray 80 - #393939

Gray 100 theme
Gray 90 - #262626

**Comment by laurenmrice** [comment]
Instead of having a full sized background behind the data table and its rows, could we change it so that the background is only in the header area where the title is? I was wondering if there was a strong reason for putting the same color background underneath rows with the same color token. If we could do this, it might solve the problem we have with zebra striping.

Ex:
<img width="876" alt="Screen Shot 2020-02-10 at 12 47 45 PM" src="https://user-images.githubusercontent.com/43969356/74180029-4b972c00-4c04-11ea-837e-269920d7792f.png">


We don't show an example of an empty state table, but if people need to use it could they just adjust the first cell to whatever size they wanted it for the empty state area?

**Comment by ChevonNwosu** [comment]
Will the bug in #3946 be fixed in this issue?

**Comment by emyarod** [comment]
seems unrelated to #3946, but this may be blocked by #4345

I have a working demo for this otherwise

**Comment by laurenmrice** [comment]
I think andrew came up with a good solve for this. We can revisit once that issue is unblocked and when this becomes more of a priority.

**Comment by tw15egan** [comment]
Seems to be resolved
