### ISSUE TITLE
[Icons Angular] SVG container has unexpected dimensions

### ISSUE THREAD

**Issue by Licen-it** [carbon-design-system/carbon#3171]
## What package(s) are you using?

- [x] `@carbon/icons-angular`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The SVG container is taking unexpected dimensions (sometimes bigger, sometimes smaller). In the screenshot below you can see the issue
![immagine](https://user-images.githubusercontent.com/35496522/60110874-c3434400-9764-11e9-9582-1f9856d3bc3e.png)
In orange is the SVG itself, while the container is 4px higher (the red part). Dimension of the svg are width 20px height 20px, while container is width 20px height 24px

> What did you expect to happen? What happened instead? What would you like to
> see changed?
the svg container should have same dimensions as the svg itself.

> What browser are you working in?
any browser

> What version of the Carbon Design System are you using?
`"@carbon/icons-angular": "^10.1.1"`

**Comment by tw15egan** [comment]
@cal-smith do you know if this issue is still relevant anymore?

**Comment by cal-smith** [comment]
There _can_ be some funky effects with icons when you use the component (`<ibm-icon-my-icon>`) syntax, but that's unavoidable due to the angular host element and how the browser/style positions it and the inner SVG ... @Licen-it I would recommend upgrading to a newer release (10.8.0 is out!) and using the directive form `<svg ibmIconMyIcon>` wherever possible - you shouldn't have any alignment issues that way :+1:

I would say this can be closed since we really do recommend the directive form over the component form at this point. Future `icons-angular` issues can be opened here: https://github.com/carbon-design-system/carbon-icons-angular

**Comment by tw15egan** [comment]
Thanks for chiming in @cal-smith, I will redirect any future issues over that way! 👍
