### ISSUE TITLE
Status icon extensions to indicate severity

### ISSUE THREAD

**Issue by JosephACooper** [carbon-design-system/carbon#3179]
### Summary

These are the severity icons we use across the Hybrid Management portfolio that have been designed and adapted to fit the new IDL and Carbon releases. 

They are extensions to the current set of the status icons provided in Carbon. They allow for another level of granularity and also allow a user to quickly prioritise and understand what action(s) should be taken.

### Justification

The basic structure of these icons have been used by our portfolio for many years and are well understood by users. We believe it would be great to standardise these to ensure there is consistency in shape and colour being used across products.

### Available extra resources

**Preview:**
![Severity icons](https://user-images.githubusercontent.com/17928838/60179768-4d97b080-9816-11e9-97ee-c62de34bd0d6.png)

**Sketch file:** https://ibm.box.com/s/6bkajfpvwwdf5qg3c24iv2z3eogri3yk

**Designing for accessibility:**
The most common form of color blindness is red/green color blindness. The inability for some users to distinguish between red and green means that products cannot simply rely on color to show status. As a result, the severity system relies on 3 key elements; color, shape, and symbol.

For example, the Critical icon is not just “red”, it is the sum of the following elements: 
Color = Red
Shape = Circle
Symbol = X

The icons above the different shapes require different user actions. These are:
Circle = Action needs to be taken
Triangle = Action  might need to be taken
Square = No action needed
Diamond = Unknown

**Common usage:**
- Status in Tables – In table views the status icon should be shown in its own column. The icons size should be 16 pixels.
- Status in Topology – When showing status in topology views, the status icon should be treated as an overlay on top of the resource to which it is related.

**Comment by asudoh** [comment]
CC @carbon-design-system/design to see if there is an interest in the team.

**Comment by shixiedesign** [comment]
This is a enhancement. We will evaluate the next round of project cycle when we have a focus on enhancements.

**Comment by chrisconnors-ibm** [comment]
Color styling is always applied using CSS; icons in the package are black. The color styling you should provide as guidance for your designers/ feds. make sure you've chosen colors from the IBM Design Language Palette.

These exist:
Fatal = svg/32/misuse.svg
Critical = svg/32/error.svg
Major = svg/32/warning--alt-inverted--filled.svg
Minor = svg/32/warning--alt--filled.svg

Warning, Harmless, undefined, and unknown do not have an equivalents.

@JosephACooper if you create .svgs (in illustrator) for these three or 32x32px artboards in 
`https://github.com/carbon-design-system/carbon/tree/master/packages/icons/src/svg/32` and submit a PR @conradennis and I will review them. Please get the tips of the corners for undefined and unknown right on the pixel border rather than just over:

![image](https://user-images.githubusercontent.com/35537391/62082826-82d35c00-b223-11e9-9cae-1106ed472215.png)

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale
