### ISSUE TITLE
[Link] Add inline link variant

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#3228]
## Inline link (spec updated Aug 30)

**Usage guidance** :book: @connor-leech 

Inline by default has underline. Its intended use is in paragraphs and sentences, where underline makes it more accessible, so that color blue is not the only visual differentiator. 

![image](https://user-images.githubusercontent.com/15144993/64035333-201cfb00-cb16-11e9-876c-8793caec9367.png)

**Comment by shixiedesign** [comment]
not stale

**Comment by shixiedesign** [comment]
not stale

**Comment by mjabbink** [comment]
I’d say this variant should be default as an inline link because a "non underlined" link within body copy does not meet accessibility contrast ratio requirements. Blue 60 against black or grey 100 is not enough which might make the link undetectable. Someone should double check me on this.
@alisonjoseph @vpicone
