### ISSUE TITLE
Using a MultiSelect in a TableToolbar

### ISSUE THREAD

**Issue by nunomaia** [carbon-design-system/carbon#3271]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Summary

Using a MultiSelect in a TableToolbar don't show items. 

![Multiselect](https://user-images.githubusercontent.com/771138/60548625-70482e80-9d1a-11e9-9e4d-8ce01dc21ff4.png)

 
## Relevant information

When a MultiSelect component is added to a TableToolbar, items of MultiSelect  aren't displayed properly. There is any property to overcome this ?

````javascript

        <TableContainer
          title="Sample Tile"
          description="Sample description">
          
          <TableToolbar>
            <TableToolbarContent>
              <TableToolbarSearch />
              <ToolbarItem>
                <MultiSelect id="carbon-multiselect-example" 
                  useTitleInItem={false} 
                  label="MultiSelect Label" 
                  invalid={false} 
                  invalidText="Invalid Selection" 
                  items={[
                    {id: 'table-filter-0',text: 'Successful', label :"Successful"},
                    {id: 'table-filter-1',text: 'Aborted On Error', label :"Aborted On Error"},
                  ]} />  
                </ToolbarItem>
            </TableToolbarContent>
          </TableToolbar>`

**Comment by asudoh** [comment]
Hi 👋 would you want to adjust `z-index` of the dropdown body?

**Comment by nunomaia** [comment]
Yes, even if I increase the value on z-index it has no effect

**Comment by emyarod** [comment]
can you create a Code Sandbox illustrating this issue? https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

**Comment by nunomaia** [comment]
Sure, 

https://yoi2b.codesandbox.io/

**Comment by emyarod** [comment]
@asudoh seems this is caused by [`clip-path`](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/data-table/_data-table-action.scss#L33), after removing that rule and increasing the `z-index` the issue appears resolved. from what I can tell it does not affect the toolbar animations, but want to double check on that with you

![image](https://user-images.githubusercontent.com/8265238/60604853-14af8c80-9d7e-11e9-957d-fe7ed36aa9c4.png)

**Comment by emyarod** [comment]
@asudoh seems this is caused by [`clip-path`](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/data-table/_data-table-action.scss#L33), after removing that rule and increasing the `z-index` the issue appears resolved. from what I can tell it does not affect the toolbar animations, but want to double check on that with you

![image](https://user-images.githubusercontent.com/8265238/60604853-14af8c80-9d7e-11e9-957d-fe7ed36aa9c4.png)

@nunomaia for now I believe you can add these rules as a workaround:

https://codesandbox.io/s/codesandbox-km93k

```css
.bx--toolbar-content {
  clip-path: none;
  z-index: 1; /* some nonzero z-index value */
}
```

**Comment by asudoh** [comment]
Uh `clip-path` is for the animation of batch action selection... My apologies for that, need to look to see how both features can be achieved.
