### ISSUE TITLE
Table: Support for vertical and horizontal scroll is missing

### ISSUE THREAD

**Issue by abhisheksinghrana** [carbon-design-system/carbon#3296]
Hi Team,

Support for vertical and horizontal scroll is missing in Table component.
I need these features as I have to implement infinite scrolling and have lot of columns in table with nowrap content.

In case of vertical scrolling 'overflow-y' is there but have to write some more css to make scrollbar to work.

I am using
Angular v6
"carbon-components": "^10.2.0",
"carbon-components-angular": "^3.7.0",

**Comment by asudoh** [comment]
Hi 👋 vertical one is coming in our next release (ref: #2965), though we don't recommend infinite scrolling due to performance concerns. We don't have an imminent plan to add horizontal one - I suggest you work your designer to come up with the UX that fit in (current) Carbon design ecosystem. Anyhow, stay tuned on the vertical scrolling!

**Comment by asudoh** [comment]
Duplicate of: #2824
