### ISSUE TITLE
[TableToolbarSearch] collapsed icon off center

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon#3305]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The hover styles for the TableToolbarSearch component make the icon appear off-center

> Is this issue related to a specific component?
`TableToolbarSearch`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected the icon to be centered when the TableToolbarSearch has a hovering cursor

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.x

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Security Connect

## Steps to reproduce the issue

1. Go to the DataTable with toolbar [preview](http://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar)
2. Hover over the search icon
3. notice the style issues

## Additional information
![Kapture 2019-07-08 at 15 09 25](https://user-images.githubusercontent.com/5973294/60839519-f9d08400-a192-11e9-9076-6b567669bb75.gif)

**Comment by ptaunton** [comment]
It's also more obvious/worse when the search icon is right next to the primary button:

![image](https://user-images.githubusercontent.com/23031207/60971667-9d00d500-a31c-11e9-9da3-f3dc5a2b704b.png)

and with hover state:

![image](https://user-images.githubusercontent.com/23031207/60971726-bbff6700-a31c-11e9-92dd-e465335b66ef.png)

**Comment by jendowns** [comment]
I fixed this in https://github.com/carbon-design-system/carbon/pull/3245 ? 🤔 

Looks like the fix isn't showing up in Storybook because the change hasn't been released yet, perhaps? For example if you look at the story here & inspect the search button...

http://react.carbondesignsystem.com/?path=/story/datatable--with-batch-actions

You can see it doesn't have that `position: initial` I added 🤔 

![Screen Shot 2019-07-10 at 9 47 36 AM](https://user-images.githubusercontent.com/9057921/60979205-e8ed5300-a2f7-11e9-85ad-9d3e7b545d07.png)

And when you add `position: initial` in the dev console, it looks fixed again:

![Screen Shot 2019-07-10 at 9 48 05 AM](https://user-images.githubusercontent.com/9057921/60979225-eee33400-a2f7-11e9-9609-d54bec37703a.png)


So perhaps it just needs a release to show the fix?

**Comment by abbeyhrt** [comment]
@joshblack like what Jen said, is this issue still present because the fix is tied in release?

**Comment by joshblack** [comment]
Yeah, @jendowns the storybook reflects the latest stable release 👍
