### ISSUE TITLE
Modal body overflows unexpectedly and scroll bar is not in container

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3412]
We recently had a user report that detailed that the modal body overflows unexpectedly, and the resulting scroll bar is also placed in an awkward location:

![image](https://user-images.githubusercontent.com/3901764/61308590-2d746500-a7b6-11e9-930d-515e83fe6c8c.png)

https://slkm7.codesandbox.io/

Can reproduce on latest Chrome.

**Comment by asudoh** [comment]
@carbon-design-system/design Seems that modal content currently takes up 3/4 of the modal width, wondering if it makes sense to extend it to 100%. Any thoughts?

**Comment by elizabethsjudd** [comment]
Here is the [design](https://github.com/carbon-design-system/carbon/issues/3261#issuecomment-507864039) I got from Anna wrt to scrolling/focusing the container in the modal. Looks like the content area needs to have padding instead of a margin

**Comment by jeanservaas** [comment]
@asudoh the content only spans 3/4 of the modal because we have right padding in all of our containers... i.e. the line length never extends the full width of our containers by design... but this is really a rule that applies to the typography, not so much other elements within a modal. For instance, if you had, say, a data table in the modal, it would take up the full width.

**Comment by asudoh** [comment]
Cool thanks @jeanservaas for clarifying!

**Comment by asudoh** [comment]
@emyarod Would you agree with swapping `width: 75%` with `padding-right: 25%` or a like? Thanks!

**Comment by emyarod** [comment]
@asudoh yeah I think that's fine
