### ISSUE TITLE
UI rail bug fixes and enhancement contributions

### ISSUE THREAD

**Issue by vikkipaterson** [carbon-design-system/carbon#3611]
### Summary

We would like to provide enhancements and bug fixes to the UI shell and rail. 

I'm raising this issue at the request of Tyler Tate and Josefina Mancilla  @jnm2377 after discussions around contributing enhancements and bug fixes to the UI rail. 

The request isn't for the carbon team to provide any design or development but for us to provide both. 

### Justification

The integration portfolio of products in Cloud, Data and AI have some requirements around navigation which aren't quite met yet with the current availability of the UI shell and the up and coming UI rail work.  

We have a short timeframe in which we need to have the components ready so we are happy to fix the outstanding bugs on the UI rail as well as add the additional enhancements and contribute straight back so they can all be included in the carbon end of Aug release. 

(Outstanding bugs https://github.com/carbon-design-system/carbon/issues/3529 & https://github.com/carbon-design-system/carbon/issues/3527 )

### Desired UX and success metrics

Proposed enhancements...

1. Alternative hover
2. Alternative pin open
2. Small / Large click space
3. Theme
5. Influencer
6. Responsiveness

**Alternative hover**
Primary hover behaviour is currently specified to be that hovering on the UI rail fully expands the side rail, collapsing again when hover moves off.

Proposed alternative hover behaviour doesn’t fully expand the UI rail, instead it displays only the rail item that is being hovered on.  

Hovering on a primary item in the rail displays only the primary nav item’s name
Hovering on a nav item in the rail with secondary nested navigation displays the name of the primary nav item and all of the secondary nav items.

(Obviously only one of these would ever be displayed at a time, both are only on this image for illustrative purposes)

Notes: typography on ‘Monitor’ is still to be confirmed 

_Implementation suggestion (React): Add a new prop to `SideNav` to not add the mouse enter/exit listeners, Add a new prop to `SideNavMenu, SideNavItem` to add mouse enter/exit listeners (which toggle a css class) enabling this effect_

<img width="235" alt="image" src="https://user-images.githubusercontent.com/11173284/62241762-b6ec7f80-b3d1-11e9-80cd-09be4b429bb5.png">

**Alternative pin open**
The UI rail currently has the ability to pin open via the hamburger icon in the top left.  We propose an alternative which would allow the same behaviour but the action is placed at the bottom of the rail, not the top. 
This allows for avoidance of double nav situations within products (or more likely paks).  This secures the top left space for the pak nav to be accessed and allows the pinning of the product nav to be accessed from the bottom.  
(one rail would never have both, this is an either or property)

_Implementation suggestion (React): As above, we would need a new prop on the `SideNav` component to not add the mouse enter/exit listeners. Otherwise, nothing else required - there is a `SideNavFooter` component which contains a button which could act as a toggle. It is on the person using the SideNav in their app to use this, and plug its change of state into the `SideNav`'s expanded property to toggle the expansion via click rather than hover._

<img width="883" alt="image" src="https://user-images.githubusercontent.com/11173284/62246897-88c06d00-b3dc-11e9-84ce-57fe2d611f09.png">

**Small / Large click space**

The UI shell  and rail currently only support one size of 'click point' space (which houses the icon), we would like to add the ability to choose between the smaller size or a slightly larger size.  

The small is great when there are a large number of items in the nav, however when there are less items in there having the slightly larger option works better, a larger size of icon could be supported in there and it increases the touch 'click point' 

_Implementation suggestion (React): Add a large property to `SideNavItem, SideNavMenu` to add a new css class to make the item take more space_

**Theme**
We would like there to be a property that allows products to choose which theme they want to apply to the UI shell and rail.  

_Implementation suggestion: it looks like there is a seperate scss file for the UI shell's theme (https://github.com/carbon-design-system/carbon/blob/94dd6af3556feaa7fbe8431811da773c8f10cd70/packages/components/src/components/ui-shell/_theme.scss). This currently maps variables used in the shell to 'hardcoded' carbon colour codes. This means if we have specified another theme, this will not be used/respected. I have seen no mention of how to override this in documentation. Is this intended? Why does it not follow the more general carbon theme selection approach/use of color variables?_

**Grid Influencer**

We would like there to be a property which allows you to state whether the rail is a grid influencer or not (meeting set up with Josefina on Friday 2nd Aug to discuss details)

### "Must have" functionality

We require all of the above and are happy to implement all of them as optional enhancements on the components

### Specific timeline issues / requests

We need these by end of Aug so are willing to do all the work, just looking to have agreement that carbon are willing to work with us on accepting and approving the contributions in time to make the end of august release. 

### Available extra resources

We (IBM Event Streams) will do all the work - both design and dev, we would just need the carbon team's agreement to work with us on ensuring reviews and approvals are done for us to meet the end of August release.

**Comment by shixiedesign** [comment]
Thank you for the detailed analysis! We will need a bit of time to look through carefully. Just want to let you know this issue hasn't slipped. Thank you for your patience.

**Comment by vikkipaterson** [comment]
Thanks for the comment.  Josefina and Tyler are aware of everything in here and have already spoken with our visual and dev so hopefully there are no surprises :)

**Comment by designertyler** [comment]
Following up since it's been a while when we met with Peter and Matthew about the shell. I saw the PR for the outstanding bugs (THANKS!) was there anything else you guys need from Carbon? I remember pointing to the UI rail that Security has built It's very similar to the requirements listed for the alternate hover. https://ibm-security.carbondesignsystem.com/?path=/story/patterns-shell--default

![image](https://user-images.githubusercontent.com/19270502/63448676-07209580-c404-11e9-8a97-5fc51c29959f.png)

![image](https://user-images.githubusercontent.com/19270502/63448684-0daf0d00-c404-11e9-86f7-73b93ea3cf47.png)

The behavior is slightly different. On hover, you only get the name and it doesn't expand to show the sub nav. It would be a good reference for visuals if that type of behavior doesn't won't meet your needs. 

Let me know where we can help start to cross things off this list.

**Comment by matthew-chirgwin** [comment]
Hi @designertyler / @jnm2377 . Following the call we had a few weeks ago (and that we never heard back saying you guys did not want any of what we proposed), I have been working on making the changes we would like. Given that discussion, we are looking to contribute the following:

- Alternative pin open
- Small/Large navigation items
- Alternative hover states for navigation items
- Grid influencer prop

Things we were waiting for feedback on:

- Responsive state for the SideNav (when not using the header)
    - Sketch files were provided but we have not heard back on them. Due to this and our time constraints, we will not be able to contribute this at this time.

Things we are not going to contribute/worked around downstream:

- UI Shell theme changing/alteration

The first PR with some of the changes @vikkipaterson described above is now open here: https://github.com/carbon-design-system/carbon/pull/3802

This PR adds support for/completes:

- Alternative pin open
- Small/Large navigation items

It includes one visual change - ‘large’ navigation items (example here):  https://deploy-preview-3802--carbon-components-react.netlify.com/?path=/story/ui-shell--sidenav-w-large-side-nav-items . The other change is to offer the option to remove the mouse listeners from the `SideNav` component - which then enables us downstream to the use the `SideNavFooter` component to control the rail expansion state in a consistent manner.

The other major change we would like to contribute at this time is the alternative hover state when the rail is collapsed. I have made a start on this (but have nothing worth sharing yet). Fundamentally from a visual side, it is your existing menu (adds a blue arrow bottom right to indicate expansion, removes the arrow from the button), which can be interacted with on hover. Similarly, a link will now appear in a bubble on hover. The link is similar to the example you linked @designertyler from security, but the the menu is quite different to what we require. For completeness, would there be any issue in contributing our proposed additions to you from a design/visual side?

Unfortunately due to the time required to get #3527 and #3529 into master, I will need to look/plan how I could implement the alternative hover and grid influencer capabilities in time for our next release. It likely will be the case I will implement it locally first just for us and not contribute it immediately to Carbon. If you still want it of course, it could be contributed later.

If possible, could the PR of my current changes (https://github.com/carbon-design-system/carbon/pull/3802) be reviewed promptly from a code and design side, and any feedback alterations required be passed on to me quickly? As @vikkipaterson mentioned when opening the issue, our timeline is very short to complete this work, so quick feedback would be much appreciated!
