### ISSUE TITLE
Button: Icon-only visual issues

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3664]
## What package(s) are you using?
- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description
> Describe in detail the issue you're having.

1. Icon only buttons when using the ghost variant have incorrect padding so icon isn't centered
2. double focus outline inherited from the icon tooltip component

> Is this issue related to a specific component?

Button

> What did you expect to happen? What happened instead? What would you like to
> see changed?

1. ghost icon-only buttons have the icon centered
2. Focus only has 1 border

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Health Design Pattern & Asset Library

## Steps to reproduce the issue

1. hover over ghost icon-only button to see the background color

1. focus on any icon-only button

> Please create a reduced test case in CodeSandbox

https://codepen.io/elizabethsjudd/pen/JgpWeP

## Additional information

<img width="1308" alt="Screen Shot 2019-08-06 at 5 20 53 PM" src="https://user-images.githubusercontent.com/1275779/62578416-197cca00-b86f-11e9-8e43-ff2db3532cdb.png">
<img width="1308" alt="Screen Shot 2019-08-06 at 5 21 02 PM" src="https://user-images.githubusercontent.com/1275779/62578418-197cca00-b86f-11e9-8149-22dbb896413e.png">

**Comment by tw15egan** [comment]
The double border seems to be fixed with https://github.com/carbon-design-system/carbon/pull/3598

Not sure what the reasoning for the padding logic on the icon only ghost buttons is though... 

<img width="279" alt="Screen Shot 2019-08-06 at 3 52 29 PM" src="https://user-images.githubusercontent.com/11928039/62582731-44acec80-b862-11e9-9162-788a208cf0e0.png">

<img width="188" alt="Screen Shot 2019-08-06 at 3 52 35 PM" src="https://user-images.githubusercontent.com/11928039/62582738-4a0a3700-b862-11e9-9ace-03edb619c60c.png">

Seems to have come from [this PR](https://github.com/carbon-design-system/carbon/pull/2366)

**Comment by elizabethsjudd** [comment]
I can take a look at the padding issue in the next week or so if you want to assign this issue to me.

Also I saw [this thread](https://ibm-studios.slack.com/archives/C0M053VPT/p1565121987316400?thread_ts=1565119217.314900&cid=C0M053VPT) on slack and was surprised to find that Icon-only buttons where only meant to be supported by primary and secondary variants.  I know within Watson Health the majority of use cases I've seen have used the ghost variant.   @carbon-design-system/design Can you explain why you chose to only support the 2 variants?

**Comment by shixiedesign** [comment]
At the moment there wasn't any need for other variants. If you'd like to add ghost icon buttons, could you provide full page product screens / ghost icon buttons in context so we can understand the usage? Icon buttons are newly added and still waiting to be stress-tested. This is a good opportunity to write some usage documentation if you have any suggestions. 

That said, we do have icon buttons in the toolbar, so perhaps by "ghost icon buttons", you could also use the toolbar which offers a more subtle hover state.

**Comment by jeanservaas** [comment]
@shixiedesign don't want to muddy the icon button waters, but is there also an issue about the fact that the icon buttons, ghost or not should always have a square container, not a rectangle.

**Comment by elizabethsjudd** [comment]
@shixiedesign I just spoke with one of our designers and they thought Carbon always supported the ghost Icon-only button.  They sent me these two screen shots from Sketch to show what they see.  They noticed that under button icon-only was only under primary and secondary buttons but they saw "icon button" which to them is the ghost icon-only button which just led to confusion.  Can we get some clarification on this?

Button component options (only shows for primary and secondary)
<img width="1214" alt="Screen Shot 2019-10-18 at 2 18 05 PM" src="https://user-images.githubusercontent.com/1275779/67125579-226d0e80-f1c3-11e9-9c8b-90353a049ccf.png">

Icon Button (what they thought was the ghost button equivalent) 
<img width="781" alt="Screen Shot 2019-10-18 at 2 17 53 PM" src="https://user-images.githubusercontent.com/1275779/67125578-226d0e80-f1c3-11e9-9b77-28152349528d.png">


@jeanservaas The small icon-only buttons have always been rectangles in the code.  We can certainly include that update in this issue if you'd like as it should be a pretty straight forward update.

**Comment by aagonzales** [comment]
The icon-only button started as a Sketch hack so we didn't always have to re-create it in the Sketch file. However, the icon only ghost button is now being updated in code to match the Sketch icon button and we will be moving icon button in the Sketch file under the button component. 

Available in `v10.10` closing because PR is merged. 
Related issue: https://github.com/carbon-design-system/carbon/issues/5312
PR: https://github.com/carbon-design-system/carbon/pull/5313
