### ISSUE TITLE
<Link /> component does not allow onClick if href is missing

### ISSUE THREAD

**Issue by Acts7** [carbon-design-system/carbon#3711]
## Title line template: Link component disabled onClick when href property is not used

-->

## What package(s) are you using?

`carbon-components`
`carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The <Link /> component is often used to trigger modals etc.
These require an onClick but no href.
The lastest major release of carbon-components disables all mouse / cursor interaction when the href is not present.

> Is this issue related to a specific component?

<Link />

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected that the <Link /> would function as it did in previous major releases.
I'd like to request the scss to disable mouse / cursor events be removed.

have found the source in carbon-components : _link.scss

``` CODE BELOW:
&:not([href]) {
      color: $disabled-02;
      cursor: not-allowed;
      pointer-events: none;
      touch-action: none;
...
}
```

I'm not sure why the team decided to disable links as it is still valid without an href.
Of course `role='button' tabindex='0'` would be helpful for accessibility.
But I can't see disabling it.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

User Self Care

## Steps to reproduce the issue

```
<Link 
        className='list-link' 
        onClick={(): IArrowFunction => { props.grabAuthenticatorClients(); }}
    >
    {securityKeys.ibmVerifyAdd}
    </Link>
```

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/codesandbox-3k43r

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
@carbon-design-system/design do we want to allow links to trigger modals? Or should Modals only be triggered from `button` elements? 

Do you have an example screen of the flow where you are running into this problem?

**Comment by shixiedesign** [comment]
@Acts7 Hi! Like TJ's saying, we'd really need to see some product screen flows to decide because this gets into the question of is it good UX. Thank you!

**Comment by jendowns** [comment]
@tw15egan @shixiedesign  This came up in one of our Slack channels so I wanted to share what I posted there + some additional accessibility info I found...

## Accessibility

https://webaim.org/techniques/hypertext/

> Links must have a non-empty href attribute in order to be considered true links and to be accessible to keyboard users.

WebAIM doesn't even like ~`onClick`~ `onmouseover` when used with an `href` -- it considers it a link that goes nowhere for a keyboard user:

```
Bad Example
The link in this example goes nowhere. Its only purpose is to activate a JavaScript function.

<a href="#" onmouseover="dropdownmenu()">Products</a>
```


## Spec concerns

https://html.spec.whatwg.org/#the-a-element

From the spec above:

> If the `a` element has an `href` attribute, then it represents a hyperlink (a hypertext anchor) labeled by its contents.

> If the `a` element has no `href` attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element's contents.

So fundamentally the `href` attribute's presence = a link. Without an `href`, an anchor is a placeholder.
## Suggestion 

As TJ said, I think in this case the best solution is to advocate that someone use a `Button` with an `onClick` instead. A ghost type `Button` would even give a link-like appearance. 

And the benefit of going with a `Button` here is that you would be following general button vs anchor roles (i.e., anchors need to go somewhere and buttons need to be actions) and also keep things compliant with accessible tooling and general spec guidance.

Plus just wanted to point out that generally I like that `&:not([href]) { ... }` style block because it encourages conversations like this, which help us reconsider which HTML elements are right for the job 😅

**Comment by tw15egan** [comment]
Thanks for the in-depth reference, @jendowns! @Acts7, does this sound reasonable?

**Comment by Acts7** [comment]
It IS reasonable.
We had some developers who used link to open modals.
Until we can get back and update all Links which are not anchor links , I have updated our scss to NOT disable anchor tags
```
.bx--link:not([href]) {
	// we currently allow links which do not have an href
	cursor: pointer;
	pointer-events: all;
	touch-action: all;
}
```

To that end, @tw15egan , Does Carbon10 have a style for button that looks like a link?

**Comment by tw15egan** [comment]
Closest we support is Ghost Button: https://www.carbondesignsystem.com/components/button/code/#ghost-button

**Comment by jendowns** [comment]
@Acts7 Again I think this is a case where a `Button` is better than a `Link`.

Here's a great resource that came to my attention recently, from an accessibility advocate: https://marcysutton.com/links-vs-buttons-in-modern-web-applications

She specifically calls out that buttons are ideal for opening modals, and adds:

> The starkest difference between a link and a button to me is that a link navigates the user to a new resource, taking them away from the current context (internal links are the only wrinkle here). A button toggles something in the interface, like a video player; or triggers new content in that same context, like a popup menu using aria-haspopup.

In this case, all you'd have to do is switch from the Link you are using to something like `<Button type="ghost" onClick= ... />` and you'd be good! 🎉 It would also ensure that your markup is accessible. (And remove the need for style overrides, which are only going around this problem and not addressing the root cause -- that a Link isn't ideal for this situation)

(EDIT: Looks like TJ beat me to it! https://github.com/carbon-design-system/carbon/issues/3711#issuecomment-525473988 Yes follow that link he shared. Ghost buttons look just like links but are used for this purpose 🎉 )

**Comment by shixiedesign** [comment]
Thanks again @jendowns. I'd love to capture some of these into our guidance for button/modal usage. Do you think @connor-leech this can be a bookmark when we review our component documentations? Not sure what would be the best format. We can start a new issue if you like.

**Comment by Acts7** [comment]
SUPER!!
Thank you team. I'm going to close this.
I'm about to wrap up our conversion to Carbon10 / @carbon/ibm-security.
So I'll just make this part of that commit.

I've been so deep in programming lately - I had not even heard of ghost buttons.
Thank you so much for that.

But I agree for the need to document ghost buttons if users need a button that looks like a link.
