### ISSUE TITLE
The width for dropdown component is too narrow when a short value is selected

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#3753]
It is really hard to read dropdown options when working with small texts. Is there a way to create a minimal width for the component, so that users would have a better visualization.

Raised from https://github.com/carbon-design-system/carbon-components-vue/issues/512

![image](https://user-images.githubusercontent.com/15086604/63168147-40838a80-c02b-11e9-863a-204a11ec238b.png)

Here is a code pen reproducing the issue.
https://codepen.io/lopesleandrorj/pen/LYPNyeP

Select the option All

**Comment by asudoh** [comment]
Hi @lee-chase 👋 components like our dropdown, multi select, etc. define their width by their container, instead of the component itself. It allows application to change the width of the dropdown depending on the application's context. Our React storybook shows an example of setting `300px` width, at: https://github.com/carbon-design-system/carbon/blob/v10.5.0/packages/react/src/components/Dropdown/Dropdown-story.js#L73

**Comment by lee-chase** [comment]
The examples in core carbon wrap the dropdown in a form item.

This form item has style settings; display: flex; flex-direction: column; align-items: flex-start;

The result is the dropdown shrinks to the smallest width.

The user has to set not only width but also align-items to something else e.g. initial.

Alternatively, they are left with styling bx--dropdown__wrapper directly.

**Comment by tw15egan** [comment]
@carbon-design-system/design should all inputs/dropdowns have some sort of minimum width to avoid this situation?

**Comment by marion-bruells** [comment]
is this something Carbon is planning to work on? We have the same issue in our UIs as shown above.

**Comment by aagonzales** [comment]
Setting a min width could potentially still cause truncation problems. The issue seems to be the field and menu is changing sizes based on the width of the selected content. It seems we need a way to allow the user to set the size of the dropdown so it doesn't change based on the content. Ideally the menu should never be changing sizes when making different selections.

**Comment by aagonzales** [comment]
@aledavila @tw15egan does that help unblock this topic?

**Comment by tw15egan** [comment]
This was recently addressed in https://github.com/carbon-design-system/carbon/pull/6297

```css
min-width: rem(288px);
max-width: rem(480px);
```

Both of which can be overridden by the user if needed, but will prevent the dropdown from jumping as much.
