### ISSUE TITLE
Tooltip doesn't work with checkbox

### ISSUE THREAD

**Issue by codeYuyuan** [carbon-design-system/carbon#3766]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When there is a tooltip under checkbox options, clicking tooltip won't open the tooltip content box.

> Is this issue related to a specific component?

Tooltip

> What browser are you working in?

Chrome.

> What version of the Carbon Design System are you using?

latest v10
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Voice Agent with Watson, we are moving from v9 to v10 during which we came across this issue.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox
https://codesandbox.io/s/overflow-1h1iu
## Additional information

- Screenshots or code

![captured](https://user-images.githubusercontent.com/26753671/63361911-ffe38400-c33e-11e9-84d0-d60559029011.gif)

- Notes

**Comment by asudoh** [comment]
Hi 👋 the problem happens because you have tooltip in the `<label>` of the check box. Users's gesture to open the tooltip also goes to the `<label>` that causes the check box to take over the focus, and thus the tooltip's close-on-blur behavior happen.

That said, would you try separating the tooltip from the check box?

**Comment by codeYuyuan** [comment]
@asudoh 
Hi, yeah for sure there might be a work around. But this is still an issue right?
This issue is similar with https://github.com/carbon-design-system/carbon/issues/3448 which hasn't been fixed yet.
The cause might be tooltip doesn't stop the event propagation.

**Comment by asudoh** [comment]
This is different from #3448, given the fix for #3448 is more of preventing user gesture vs. not on `<label>` rather than support for interactive tooltip.

BTW is the screenshot from what your designer gave you? Wanted to see if interactive tooltip in `<label>` is a valid use case from broader design perspective. CC @carbon-design-system/design

**Comment by tw15egan** [comment]
For #3448, you could just set the `labelText` to `null` and move the `Tooltip` adjacent to the `Select`, instead of rendering it inside of `Select` as the `labelText`.

Seems like this is also solved by just moving it outside of the `RadioButton` like @asudoh suggested, and using CSS to align them properly.

**Comment by emyarod** [comment]
this issue appears to be resolved on the latest version of Carbon, feel free to reopen the issue if it persists
