### ISSUE TITLE
incorrect icons for expanding/collapsing rows in table

### ISSUE THREAD

**Issue by murtdagi** [carbon-design-system/carbon#3774]
The chevron icon that is used to expand the rows in the table in previous versions of carbon was pointing right for collapsed and pointing down when expanded.
From carbon 10 the direction of the chevron has changed to pointing down when collapsed and pointing up when expanded.
To some extent it does make sense that it shows you the direction where the expansion or collapsing will happen.
But the pattern in carbon 10 and before, both the patterns are used in various products, but the pattern used in earlier version of carbon is the most widely used pattern.
My concern is for the existing users on previous version of carbon and for them arrow pointing down means the row is expanded, but once they get our products with carbon 10 the initial feeling they will get is that the rows are expanded bcoz the chevron is down.

I personally feel we should not change the direction of the chevron. May be others may have their own thoughts about this.

**Comment by ghost** [comment]
I would agree. I find the change confusing. The arrow should indicate the current state of the row.

**Comment by tw15egan** [comment]
@carbon-design-system/design thoughts?

**Comment by designertyler** [comment]
For reference: V9
![image](https://user-images.githubusercontent.com/19270502/63546814-46c4ab80-c4f0-11e9-92b7-0d46f173ee49.png)



V10
![image](https://user-images.githubusercontent.com/19270502/63546826-4f1ce680-c4f0-11e9-8127-22416a8cd7f5.png)


We made the decision for v10 to let the icon show the action it will take rather than the state to follow the same convention as our dropdown and accordion components. It's also becoming more of a standard for expanding/collapsing on the web.

It's tagged as a11y, were there any specific concerns that we missed when making the change?

**Comment by murtdagi** [comment]
To be honest i have never seen the icons for expanding/collapsing rows in table as you have in carbon 10. So far I have come across the pattern used in v9 on the web.
My biggest concern is that it will confuse our existing users when they first see the arrows changing direction when we release with carbon 10.
I personally thing the semantics is completely different in the dropdown and the row expansion. With the drop down users knows that it will show the list of items when clicked. but with the table rows, what we need is to give an indication that this row is expandable.

I still think it would be best to stick to the pattern used in v9 for the row / accordion expansion icon

**Comment by chrisconnors-ibm** [comment]
Thanks for filing this issue. We haven’t seen any evidence of the concern as described. If evidence emerges of users struggling with this, or not being able to complete this task, we're happy to re-evaluate this issue.
