### ISSUE TITLE
Use DatePicker inline, currently falling to a new line

### ISSUE THREAD

**Issue by trsiddiqui** [carbon-design-system/carbon#3792]
## What package(s) are you using?

- [] `carbon-components`
- [x] `carbon-components-react`

## Relevant information

I am trying to implement the single selection filtering layout as explained [here](https://www.carbondesignsystem.com/patterns/filtering/#single-selection). I am having issues with aligning dates in the single row of filters which already have a multiselect and a drop down. Since multiselect and dropdown controls have a property called _type_ to use these controls inline, I am wondering if the datepicker control has a similar property because no matter how i lay it out, datepicker always falls to a new line.

**Comment by tw15egan** [comment]
Can you produce a reduced case test scenario so we can try to debug? 

> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

**Comment by trsiddiqui** [comment]
Hello, I apologize for taking this long to respond. Github is not a regular app on my stack and hence I missed updates on this. I will try and create an account with my work email.

**Comment by trsiddiqui** [comment]
Here is a codesandbox link.
[https://codesandbox.io/embed/codesandbox-hpzo1](url)

**Comment by tw15egan** [comment]
Can you just put all the items inside of a flex container? In your example, if I set `#root div { display: flex; }` they all appear on one line.

**Comment by tahaimt** [comment]
Yeah that worked, but is there an alternative for IE11 (I couldnt test in IE11 as the project is not set up with proper polyfills)? I was also wondering if there was a collection of ready to use classes for different layouts that could be used with carbon for react, and if yes, is there documentation around those? The reason I am asking is because I am not a full time designer and I could save a lot of time if I was able to find documentation around layout and positioning of element in carbon design system.

**Comment by tw15egan** [comment]
There are no predefined classes for layouts other than what comes with the Grid package ([documentation](https://carbon-elements.netlify.com/grid/examples/preview/)).

I was also under the impression that basic `flex` layouts can be achieved in `IE11` [source](https://caniuse.com/#search=flex)
