### ISSUE TITLE
[React Overflow Menu] carry over a11y changes from vanilla

### ISSUE THREAD

**Issue by elizabethsjudd** [carbon-design-system/carbon#3814]
changes were made to the vanilla version of overflow menu that need to be carried over to React

https://github.com/carbon-design-system/carbon/pull/3181

**Comment by abbeyhrt** [comment]
Since this has been open awhile, I am going to close this. It's difficult to track exactly what work needs to be carried over and I believe that all accessibility issues with OverflowMenu would have been documented by IBMa. If something still needs to be addressed, feel free to open an issue with details about the specific accessibility problem so it's easier to figure out what work needs to be done.
