### ISSUE TITLE
[Feature Request] Support server side sorting in DataTable for React

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4189]
### Summary

Apparently DataTable only support client side sorting as sortRow event is triggered for all the rows in the table to compare there values on client. I am not sure if there is way to trigger server side sort when a header is clicked. 

### Justification

To support server side sorting

### Desired UX and success metrics

No UX impact

### "Must have" functionality

An event like **sortRow** that is triggered only once when a sortable header is clicked

### Specific timeline issues / requests

As soon as possible.

**Comment by asudoh** [comment]
Hi 👋 for such kind of use cases I'd suggest using [presentational components behind `<DataTable>`](https://github.com/carbon-design-system/carbon/blob/v10.6.0/packages/react/src/components/DataTable/stories/with-sorting.js#L28-L47) instead of using `<DataTable>` itself, with your own state manager.

**Comment by NoMercy235** [comment]
I have the same problem with our application. I see that you have provided an `handleSortBy` callback which I want to use for our server-side sorting. However, the current implementation provides the old value for `sortDirection` as an input argument to the function because it does not wait for the state to change.

```
onClick: composeEventHandlers([
  this.handleSortBy(header.key),
  onClick
    ? this.handleOnHeaderClick(onClick, {
      sortHeaderKey: header.key,
      sortDirection,
     })
    : null,
]),
```
 Over here, the `sortDirection` comes straight from the state and does not wait for the state change.

Would it be possible to move the callback call in the `setState` callback of the `handleSortBy` method so that it receives the correct value? Or call the callback with the `getNextSortState(sortDirection)` so that we get the correct value.

Right now I have to make a weird mapping knowing that when I get the `"NONE"` direction, the user actually clicked the sort and it should be done in ascending order (`"ASC"`). The mapping looks like this:
- NONE -> ASC
- ASC -> DESC
- DESC -> NONE

This is pretty weird and unintuitive. I would like to refrain from keeping a separate manager in the app for the sort logic, as suggested above since I already have what I need in the `DataTable` component.

**Comment by tahaimt** [comment]
Kind of hacky, but this is what I did in my table component to sort on server side using the client sort event `sortRow`. 1000 millisec is the time it took to compare all rows with each other on client side for the max number of rows supported in my app (100 rows, paginated). I know its not a proper solution which would have been to use presentational components behind datatable, which would have involved table state management in the UI as well. But it was a quick solution and worked without any issues.


                <DataTable
                  rows={dataRows}
                  headers={visibleColumns.length ? visibleColumns : headers}
                  isSortable={isSortable}
                  {...(
                    serverSideSorting ? 
                      {sortRow: (e, a, columnSortInfo) => { 
                      if (!localIgnoreSortTrigger) {
                        filterMethod(columnSortInfo);
                        localIgnoreSortTrigger = true;
                        setTimeout(() => { 
                          localIgnoreSortTrigger = false; 
                        }, 1000);
                      }
                    }} : 
                    null)
                  }........></DataTable>

**Comment by akmalmzamri** [comment]
Would love to have this feature implemented `DataTable` without needing to use the presentational components

**Comment by Sourtoast** [comment]
I understand this is closed issue but It would make many lives easier
