### ISSUE TITLE
Number input does not correctly apply `aria-invalid` & `data-invalid` when error is present

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon#4294]
## Detailed description

`carbon-components-react`: `7.7.0`

The way the `aria-invalid` and `data-invalid` attributes are written in the `NumberInput` React component, the *only* way that these two attributes can be added to the underlying input element is if the `invalid` prop is updated to `true` by the user:

https://github.com/carbon-design-system/carbon/blob/4b03c81d2fa321c356a10432ad192242d78ae172/packages/react/src/components/NumberInput/NumberInput.js#L387-L389

As it stands right now, if you go the storybook demo & enter something invalid into the number input, `aria-invalid` and `data-invalid` are not added to the input:
![Screen Shot 2019-10-10 at 1 45 37 PM](https://user-images.githubusercontent.com/9057921/66597817-54e48f00-eb65-11e9-8178-60fa2ee0d0ed.png)

Again this is because the `invalid` prop is false (as shown below in the React Chrome extension). Though the value of `invalid` in this case is understandable because it is user-provided info...
![Screen Shot 2019-10-10 at 1 44 54 PM](https://user-images.githubusercontent.com/9057921/66597854-6463d800-eb65-11e9-8e6a-a0a6c497702c.png)

## Possible solution
I think an invalid state could perhaps be tracked within this component, as a way of properly applying `aria-invalid` and `data-invalid`? 🤔

**Comment by abbeyhrt** [comment]
Testing this, I found that "Number is not valid" does read correctly to screenreaders despite the aria-invalid and data-invalid attributes not applying correctly. Since this doesn't seem to be affecting functionality, I removed this from the milestone and am going to mark this as an accessibility enhancement. This should definitely be addressed and fixed but it's just not going to be part of our work to consider Number Input accessible.
