### ISSUE TITLE
Table with overflow menu has cell height issue

### ISSUE THREAD

**Issue by nitishjain07** [carbon-design-system/carbon#4298]
Hi Team,

In table component, if we choose short size table, height of all the cells will be 32px which is fine. However, if we have a table with overflow menu, height of header cells is 32px but all other cells is around 45px. I believe we need to change some padding/margin around overflow menu inside table so that cell size doesn't exceed 32px height. 

You can check this over here => https://angular.carbondesignsystem.com/?path=/story/table--with-overflow-menu.

Thanks in advance!

I am using below carbon versions.
"carbon-components": "10.6.4",
"carbon-components-angular": "3.17.4"

**Comment by emyarod** [comment]
I believe this is due to the overflow menu trigger button being 32x32 and the checkbox label having a `min-height` of 1.5rem, so the additional padding increases the row height. a workaround would be to modify those values for now

```css
td .bx--checkbox-label {
  min-height: auto;
}

tr td:last-of-type {
  padding: 0 1rem 0 .75rem;
}
```

I'm not sure there's any action we can take on the library side given the row heights will change based on the content

**Comment by aledavila** [comment]
Closing this as it seems no action can be taken. If there is further issue feel free to respond.
