### ISSUE TITLE
DatePicker: Add proptype change warning 

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#4344]
Ref #4215 

Through the patch release process, we noticed that the PropTypes are changing in #4215.  `appendTo` can no longer be a string like before.  For this case, it was a totally reasonable change and is okay to be added to a patch release. Before it's officially released though, since there was a change to the types of prop that will be accepted, we wanted to add a warning to the user in the code just to be safe. 

@asudoh don't know if you want to tackle this one but if you could that would be wonderful!

**Comment by asudoh** [comment]
@abbeyhrt Thank you for your thoughts! As the matter of fact, using a string for `appendTo` did not work even before the change of #4215. That's why the prop type changed.

**Comment by joshblack** [comment]
@asudoh I think it's more-so that that our public API included `PropTypes.string`, regardless of if it worked or not. If someone supplied this option thinking it would work, and then updated, this would be an unexpected change as they would receive a prop type validation error in a semver patch release.

The amount of folks doing this may be 0 though, so if we feel like no one would be impacted by this we could keep it as-is. If we're going by the versioning guide, this is a case of a prop type being more specific which could be why this was raised.

**Comment by asudoh** [comment]
The code supporting query selector for `appendTo` (as a string) was deprecated in `v9` timeframe and removed in `v10`. That said, no `v10` user effectively can use `appendTo` as a string, and thus no `v10` user is likely to be affected by prop-type change.

**Comment by joshblack** [comment]
Nice! Makes sense 👍

**Comment by abbeyhrt** [comment]
Okay great! Thank you for clarifying @asudoh! I'll close this issue and that PR will get released in the next patch 👍
