### ISSUE TITLE
Overflow Menu has first option always highlighted

### ISSUE THREAD

**Issue by tbcross** [carbon-design-system/carbon#436]
## Detailed description

I'm using the vanilla version of the Overflow Menu, and whenever I open the menu, the first item in the list is always highlighted, even when I hover over a different item (which results in both items behind highlighted).  

![image](https://user-images.githubusercontent.com/16770793/32804201-c4413616-c94b-11e7-9f6c-5a5b59110b1e.png)

> Is this issue related to a specific component? 
Yep.  Overflow Menu

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected nothing to be highlighted initially (since my cursor was still on the kabob-circles).  When I did hover over an item, getting ready to select it, I expected only that specific item to be highlighted, not that one and the top one.  

> What browser are you working in? 
Chrome 

> What version of the Carbon Design System are you using? 
7.23.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Open an overflow menu
2. Notice that the first item is permanently highlighted.

**Comment by asudoh** [comment]
@tbcross IIUC what this issue is about - You can change the behavior by removing `data-floating-menu-primary-focus` attribute from the 1st menu item. In other words, the highlight of the 1st item indicates focus and the highlight moves when you hit tab. If a designer can quickly provide a differentiated focus style from hovering over, I can put it in. CC @tw15egan

**Comment by tw15egan** [comment]
@tay-aitken @aagonzales this brings up the question of whether we should have differing `focus` and `hover` styles. Any ideas?

**Comment by aagonzales** [comment]
Oh interesting. I never realized the focus remains even if you move the cursor. Will the first item always be focused? And it only becomes un-focused if the user tabs or clicks another item? Just hovering doesn't change the focus?

Because I think have a focus and a hover at the same time will always cause a little bit of confusion to the user.

I think a quick fix would be to change the focus state to an underline.
![image](https://user-images.githubusercontent.com/11670886/32847091-a4eaac54-c9ee-11e7-9b6e-6d59a88bb14b.png)

**Comment by tbcross** [comment]
if I remove data-floating-menu-primary-focus from the first menu option, then the whole overflow menu is focused and doesn't look good at all (but it does fix that the item isn't highlighted anymore):
![image](https://user-images.githubusercontent.com/16770793/32847390-7250b422-c9ef-11e7-8d83-493663aa9e37.png)

**Comment by aagonzales** [comment]
oh yeah that's not great which I guess is why we changed the focus to the first item.

Can we have to focus stay on the ... icon? (option 2) Or is that weird?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/11670886/32848284-af83fe92-c9f1-11e7-912e-6a183945aeca.png">

**Comment by tw15egan** [comment]
Accessibility wise, focus will need to go to each menu item otherwise it will negatively affect screen-readers

**Comment by aagonzales** [comment]
I wasn't suggesting removing the focus for all items but where the first focus is. Theoretically so no menu item was focused on open and focus on items only appears when the user starts tabbing.

**Comment by tw15egan** [comment]
@aagonzales I like that solution

**Comment by asudoh** [comment]
@aagonzales @tw15egan @tbcross Focus-on-first-item-on-open idea came from the limitation of overflow menu (floating menu); The location of DOM is so distinct that I see no way to tell browser that the next focus item to the trigger button is the overflow menu. The only way to get the focus stuff right is moving focus to overflow menu right when it opens.

One idea I’d have is designing the focus outline style for https://github.com/carbon-design-system/carbon-components/issues/436#issuecomment-344647315 condition. Browser’s default focus outline is not great there due to the nature of the pseudo element for triangle, but we can fix that by using custom outline style. Thoughts?

**Comment by alisonjoseph** [comment]
It looks like we have two options here, either change the focus state for the options in the overflow menu to the underline that @aagonzales has as the first option [here](https://github.com/carbon-design-system/carbon-components/issues/436#issuecomment-344653592)

or update the styling of default focus state with the `data-floating-menu-primary-focus`removed

Which would you prefer @aagonzales?

**Comment by marijohannessen** [comment]
@aagonzales do you have any input here?

**Comment by bsonefeld** [comment]
Need more design input before FED can move forward.

**Comment by aagonzales** [comment]
I think we we should avoid having a focus and hover on different items at the same time would be best. Option 2 would be the ideal solution. But Option 1 is acceptable if option 2 is not possible.

**Comment by carmacleod** [comment]
@aagonzales @alisonjoseph @marijohannessen 
I realize that this issue was fixed (using Option 1), and closed a year ago, but just so you know, there is an "Option 3".  :)

You could _have focus follow hover within the popup_. 

Details and code example in https://github.com/carbon-design-system/carbon-components/issues/2259
