### ISSUE TITLE
Resolve 64px vs 72px discrepancy when scaling for editorial use-cases

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4504]
There are a couple situations that @laurenmrice has noted when scaling up our container-04 sizes for a digital use-case. This issue is to track the resolution for the cases where 72px is being used instead of 64px to see if they can be systemized or if they will be one-offs in the digital case.

**Comment by laurenmrice** [comment]
### Places where 72px occurs:

**Multi line notification**
-Maybe this won't be a problem since it has the same padding we are using and the increased line height will just push the container content larger to the 72px? If anything they can just override this size.

**Data table row**
-They did an exploration on row heights with the increased line height. 
-We currently have our `tall` rows at 64px. They wanted to increase theirs to 72px to fit the increased line height appropriately. Would that be easier than forcing them to stick with 64px with an increased line height? It may not be a container token for 72px but they could just override it
