### ISSUE TITLE
[Link] can not focus with keyboard in Safari and Firefox

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon#4565]
## What package(s) are you using?

- [x] `carbon-components` 10.7.3
- [x] `carbon-components-react` 7.7.3

## Detailed description

> Describe in detail the issue you're having.

When I use Safari or Firefox I can not focus on link with keyboard.

> Is this issue related to a specific component?

Link

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect to be able to focus on link using keyboard.

> What browser are you working in?

Firefox 69.0.3 (64-bit)
Safari Version 13.0.2

Works in Chrome though (Version 78.0.3904.70 (Official Build) (64-bit))

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Hyper Protect, release ~ Q4

## Steps to reproduce the issue

1. Try to focus on the Link using only keyboard

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/codesandbox-qusfd

**Comment by jendowns** [comment]
Hey @ZrianinaMariia, you'd likely see the same results if your changed the `<Link href="444">test</Link>` in your example to `<a href="444">test</a>`.

With Firefox and Safari, you usually need to enable certain settings within the browser preferences in order to navigate webpages with a keyboard --

### For Firefox: 
> When you go to the Firefox menu and select `Preferences`, the `General` panel `Browsing` section includes the setting **Always use the cursor keys to navigate within webpages**. 
https://support.mozilla.org/en-US/kb/accessibility-features-firefox-make-firefox-and-we#w_using-a-keyboard

![Screen Shot 2019-11-05 at 10 22 30 AM](https://user-images.githubusercontent.com/9057921/68225545-3633b580-ffb6-11e9-8198-9c723bc0f59a.png)


And then you can tab to the "body" of the page, and click on the down arrow to select the link in your codesandbox example.

### For Safari: 
![Screen Shot 2019-11-05 at 10 17 43 AM](https://user-images.githubusercontent.com/9057921/68225354-e7861b80-ffb5-11e9-9d8e-50d0258ab031.png)

And then you can tab to the link in your codesandbox example.

**Comment by ZrianinaMariia** [comment]
Thanks a lot, it was very helpful @jendowns
