### ISSUE TITLE
Unable to program events for Modal instance with JavaScript (Angular 5.0)

### ISSUE THREAD

**Issue by rahulsethione** [carbon-design-system/carbon#458]
## Unable to program events for Modal instance with JavaScript (Angular 5.0)

I am not able to figure out a way to configure a Modal instance to do something on supported events. Link given below:

[Carbon design documentation for Modal](http://carbondesignsystem.com/components/modal/code#events)

I am trying the approach below:
```
const modalOptions =  { eventBeforeShown: () => console.log('eventBeforeShown') };
let theModal = Modal.create(document.querySelector('[data-modal]'), modalOptions);
```

The above approach does not work. Please suggest a solution. Thanks.

**Comment by asudoh** [comment]
@rahulsethione `eventBeforeShown` option is a string that determines the DOM event name fired on modal’s root element, instead of an event listener function. As [the same document](http://carbondesignsystem.com/components/modal/code#events) says, `modal-beingshown` DOM event by default is fired on modal's root element (e.g. `document.querySelector('[data-modal]')`) right before it's shown.

That said, you can use [a regular DOM API](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) to hook on the event, e.g.:

```javascript
const modalElem = document.querySelector('[data-modal]');
modalElem.addEventListener('modal-beingshown', (evt) => {
  console.log('modal-beingshown fired:', evt)  ;
});
Modal.create(modalElem).show(); // You'll see a message with event object in browser console
```

Hope it helps.

**Comment by marijohannessen** [comment]
Closing this issue as it seems to be resolved.
