### ISSUE TITLE
Table with overflow menu is showing bigger rows and vertically misaligned row content

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon#4586]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description
First reported here: https://github.com/IBM/carbon-components-angular/issues/886

This issue follows from that, as this appears to be a styling bug

## Steps to reproduce the issue

https://angular.carbondesignsystem.com/?path=/story/table--with-overflow-menu

https://react.carbondesignsystem.com/?path=/story/datatable--with-overflow-menu

## Additional information

It appears that the `2rem` height on the overflow menu button is interfering with the row styles

**Comment by vronjec** [comment]
Hi! Putting an overflow menu in datatable rows seems to be a common pattern, and we also came across this issue when using the React version of Carbon (see another demo that reproduces it here: https://codesandbox.io/s/lingering-pond-mukh3).

The way we solved it was that we added a custom class to the parent table cell to it's width to a fixed value (in order to get rid of the spacing right to the overflow menu button), and used the class to target and alter the overflow menu button styles so they wouldn't interfere with the row styles.

Would adding a utility class be sufficient to solve this issue? Or are there other concerns as well?
