### ISSUE TITLE
[React] OverflowMenu component does not work in IE (carbon tutorial)

### ISSUE THREAD

**Issue by tahaimt** [carbon-design-system/carbon#4594]
## What package(s) are you using?

- [x] `carbon-components`: 10.7.3
- [x] `carbon-components-react`: 7.7.3

## Detailed description

I am working off a [forked version](https://github.com/tahaimt/carbon-tutorial/tree/react-step-6) of the [Carbon React Tutorial](https://github.com/carbon-design-system/carbon-tutorial/tree/react-step-6). I have added the required polyfills for the app to work in IE11 (works in IE10 too). 

I have put an OverflowMenu component in the header. However, it only works in chrome and firefox but does NOT work in IE11. The overflow menu does not open when you click on the button.

## Steps to reproduce the issue

1. Clone/Download the react-step-6 branch of the above mentioned repo at [https://github.com/tahaimt/carbon-tutorial/tree/react-step-6](https://github.com/tahaimt/carbon-tutorial/tree/react-step-6)
2. Install dependencies and run the project using the following commands.
`yarn`
`yarn start`
3. Open the app in IE11 [http://localhost:3000](http://localhost:3000).
4. Click on the button that is placed in the middle of the right section of the header between Notification and App icons.
5. An overflow menu should appear but it does not.

## Additional information

I would have created a sandbox but they dont support more than 250 modules and apparently the tutorial has more.

**Comment by tw15egan** [comment]
Hey @tahaimt , sorry to hear you're having issues. I would ensure you've got all the correct polyfills loaded in so that our components render correctly in all browsers. You can take a look at the ones we use here:

https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/components/demo/polyfills/index.js

You can also taker a look at this issue if it helps at all:
https://github.com/carbon-design-system/carbon/issues/5355

For now, I'm going to close this, but if you feel there is still an error just let me know and we can reopen and move it over to the tutorial repo.
