### ISSUE TITLE
Carbon Component "overflow menu" is not giving popup we click it

### ISSUE THREAD

**Issue by abd2312** [carbon-design-system/carbon#46]
I am trying to use carbon component "overflow menu" I am not getting pop up when i click on it.
have copied code for same from carbon design site and  included css for same.
 have included the carbon component “overflow-menu” with  attribute 'data-overflow-menu'and 
also included CarbonComponents.OverflowMenu.init() in my controller
I have included the carbon-components.min.js. still Overflow menu is not working

To check if there is certain issue with controller, I removed scopped variable from html page and 
disabled controller for this html page, Still pop up for overflow menu not coming.

**Comment by asudoh** [comment]
@abd2312 Could you please create a (reduced) test case so that we can reproduce your issue? If you have a public website or GitHub repo of your code it may also work.

Or if you want to debug further by yourself - https://github.com/carbon-design-system/carbon-components/blob/a0e8664/src/components/overflow-menu/overflow-menu.js#L70-L89 should run when you click on overflow menu.

**Comment by abd2312** [comment]
I am using overflow menu in carbon data table, When i click on overflow menu i am getting below error in console log
uncaught Error: Cannot find the target menu.
    at OverflowMenu.changeState (abc.js:1633)
    at OverflowMenu._handleDocumentClick (abc.js:1675)
    at HTMLDocument.<anonymous> (abc.js:1602)
    
        
Queryselector is unable to select any element with selector '.bx--overflow-menu-options' so it is returning null. 
In my case the only difference is that i am generating rows in carbon data table dynamically using ng-repeat. 
i.e
if (!this.optionMenu) {
        var optionMenu = this.element.querySelector(this.options.selectorOptionMenu);
        if (!optionMenu) {
          throw new Error('Cannot find the target menu.');
        }

**Comment by asudoh** [comment]
@abd2312 If `<div data-overflow-menu …>` is in `ng-repeat`, you have to wait for those repeat DOMs being populated before creating carbon-components `OverflowMenu` instance. You can do so by:

1. Setting `CarbonComponents.settings.disableAutoInit = true;` after carbon-components.js is loaded, and before `DOMContentLoaded` event fires
2. Create/destroy carbon-components `OverflowMenu` instances upon addition/deletion of repeated DOMs - `overflowMenuInstance = OverflowMenu.create(element)` for creating, `overflowMenuInstance.release()` for destroying. For example, you can wrap each row in Angular directive so that you can use Angular directive's lifecycle events (`$link`/`$scope.$destroy`) to run `create()`/`release()`.

Hope this helps.

**Comment by abd2312** [comment]
@asudoh I have created custom directive for overflow-menu and written function OverflowMenu.create(element) to be called when user click on the custom directive in html

Added "CarbonComponents.settings.disableAutoInit = true;" in controller to be called after carbon-components.js is loaded, and before DOMContentLoaded event fires i.e 

CarbonComponents.settings.disableAutoInit = true;
angular.element(document).ready(function ($element) {
 CarbonComponents.Tab.init();
  CarbonComponents.DataTable.init();
 CarbonComponents.OverflowMenu.init();
  CarbonComponents.Modal.init();
});

**Still i am getting same error.**
uncaught Error: Cannot find the target menu.
at OverflowMenu.changeState (abc.js:1633)
at OverflowMenu._handleDocumentClick (abc.js:1675)
at HTMLDocument. (abc.js:1602)
-

Can you share a sample code for overflow menu to be used with ng-repeat?
regards-Sanjay

**Comment by asudoh** [comment]
Please note that both 1. and 2. steps [I mentioned](https://github.com/carbon-design-system/carbon-components/issues/46#issuecomment-298715644) should be done.

**Comment by hellobrian** [comment]
Thanks for assisting @asudoh! 
@abd2312, I'm going to close this issue. Hopefully, this was resolved for you. Feel free to comment here again if you're still having problems and we can try to troubleshoot again.
