### ISSUE TITLE
Export class names in JS module

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#460]
This is a future-facing feature request, the goal being to derive component classes from the `scss` we write and then publish those as part of the JS module so that implementations can derive their class names from this exported set, with the benefit being that an update in our `scss` would generate a new class name in the exported module which would then update in any consuming library.

The simplest way to get this to work would be to go through our generated CSS and convert the BEM-style to a camelCase convention, and just export the resulting object with the key being the camelCase variation and the BEM style being the value.

The usage from a consumer standpoint would look like:

```
import { classNames } from 'carbon-components';

classNames.dropdown; // 'bx--dropdown'
```

**Comment by scottnath** [comment]
This is excellent. This will help end-users more-easily transition when the classNames inevitably change.

A hurdle I see is now you need a naming convention for your html structure.

For instance, look at [tooltip](http://carbondesignsystem.com/components/tooltip/code)

## classNames needed:

* bx--tooltip
* bx--tooltip__trigger
* bx--tooltip__label
* bx--tooltip--simple
* bx--tooltip--simple__top

## consumer standpoint

```
import { classNames } from 'carbon-components';

classNames.tooltip // typeof: object
classNames.tooltip.container // bx--tooltip
classNames.tooltip.trigger // bx--tooltip__trigger
classNames.tooltip.label // bx--tooltip__label
classNames.tooltip.simple // typeof: object ?
classNames.tooltip.simple.container // bx--tooltip--simple ?
classNames.tooltip.simple.top // bx--tooltip--simple__top ?
```

**Comment by joshblack** [comment]
I really like the example you posted, the pattern seems super clear. Another option could be translating the BEM syntax directly, e.g.:

```
classNames.tooltip__trigger
classNames['tooltip--simple__top']
```

Another one could be a slight tweak on BEM naming so that mods are camelCases versus using `--`, would look like:

```
classNames.tooltip__trigger
classNames.tooltipSimple__top
```

Both options, unfortunately, seem much more difficult to map intuitively to the CSS selectors, I think, but figured I'd share them to see what others thought.

**Comment by joshblack** [comment]
Another option could just be a flat object that contains all selectors, where basically the BEM conventions just serve as a place to change it to `camelCase`.

**Comment by scottnath** [comment]
possible hiccup on selectors - what if we had variable selectors (like a variable to decide a heading number) - then how would we know where to put the class?

I'm nervous for the selectors to just be the classNames or follow bem - if it ever changes, then we get non-bem data with bem.

We could look for the commonalities and start to experiment component by component. For instance, one assumes each component has a single containing element - therefore we'd could know that _every_ component would have a classNames.[component].container. So that one is at least easy. But then it gets complex...

## easy
http://carbondesignsystem.com/components/list/code

```
<ol class="bx--list--ordered">
  <li class="bx--list__item">Ordered List level 1
    <ol class="bx--list--nested">
      <li class="bx--list__item">Ordered List level 2</li>
      <li class="bx--list__item">Ordered List level 2</li>
    </ol>
  </li>
  <li class="bx--list__item">Ordered List level 1</li>
  <li class="bx--list__item">Ordered List level 1</li>
</ol>
```

classNames.list.container // bx--list
classNames.list.orderedList.container // bx--list--ordered
classNames.list.nestedList.container // bx--list--ordered
classNames.list.item.container // bx--list__item

## harder
http://carbondesignsystem.com/components/text-input/code

First off...no main container listed for textarea, but it should, right?

Second, two of the same thing.

```
<div class="bx--form-item">
  <label for="text-input-1" class="bx--label">Text Input label</label>
  <input id="text-input-1" type="text" class="bx--text-input" placeholder="Placeholder text">
</div>

<div class="bx--form-item">
  <label for="text-input-2" class="bx--label bx--label--disabled">Text Input label</label>
  <input id="text-input-2" type="text" class="bx--text-input" placeholder="Placeholder text" disabled>
</div>

<label for="text-area-1" class="bx--label">Text Area label</label>
<textarea id="text-area-1" class="bx--text-area" rows="4" cols="50" placeholder="Placeholder text."></textarea>
```

(I think the `item2` is probably not needed tho)

classNames.form.item.container // bx--form-item
classNames.form.item.label.default // bx--label
classNames.form.item.label.modified? .disabled? // bx--label--disabled
classNames.form.item.input.default // bx--text-input
classNames.form.item.input.modified? .disabled? // no class
classNames.form.item2.container // bx--form-item
classNames.form.item2.label.default // bx--label
classNames.form.item2.label.modified? .disabled? // bx--label--disabled
classNames.form.item2.input.default // bx--text-input
classNames.form.item2.input.modified? .disabled? // no class
classNames.form.item.label.default // bx--label
classNames.form.item.textarea.default // bx--text-area
