### ISSUE TITLE
The 'Graph' name in DataVis components is misleading

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon#477]
In computer science (an math) a `Graph` is a set of notes (vertices) connected by edges (arcs, links) i.e. a network.

Maybe DataVis should use the name `Chart` instead? Or `Plot` or `Scene` or something similar?

**Comment by bsonefeld** [comment]
Hi @gmosx , are you referring to the [Line Graph](http://carbondesignsystem.com/data-vis/line-graph/code) component? 

@tay-aitken and @tsaitsaitsai spent a lot of time researching the naming system we use for Data Vis, so they'll be able to provide some additional context for you.

**Comment by gmosx** [comment]
Yes, the LineGraph component.

I am curious to hear the rationale behind this name....

**Comment by tsaitsaitsai** [comment]
Good question, @gmosx! Graphs and charts overlap to some extent in that they’re both visual representation of data. Graphs are great for illustrating trends in data over time whereas charts are used to show frequency or part-to-whole relationships. Stephen Few and Edward Tufte have been great data vis resources if you’re looking for more info!

**Comment by gmosx** [comment]
@tsaitsaitsai Graph means something completely different in Math/Computer-Science 

https://en.wikipedia.org/wiki/Graph_theory
https://en.wikipedia.org/wiki/Graph_(abstract_data_type)

**Comment by tsaitsaitsai** [comment]
Thanks for the links, @gmosx. It looks like these are broad definitions of graph theory. However, they do not cover how graph theory applies to data visualization. Additionally, sourcing from wikipedia is discouraged due to reliability issues. 

Our naming conventions are derived from research that includes attending a data vis conference, studying several books published by leading industry experts, and exploring other design systems. I suggest “The Visual Display of Quantitative Information” by Edward Tufte and “Show Me the Numbers” by Stephen Few to get more familiar with the subject. Feel free to reopen this issue if you have more research regarding data vis, otherwise, we’re closing this for now and sticking with the current naming structure.
