### ISSUE TITLE
[UI Shell]  Header menu items must be links

### ISSUE THREAD

**Issue by cwgormanIBM** [carbon-design-system/carbon#4840]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

In our header, we wanted to show the name of the current page, instead of using that space for clickable menu items.

![image](https://user-images.githubusercontent.com/11217351/70464711-6ecf1f00-1a8d-11ea-89fb-845a3b5d846b.png)

However, to get them to look right, simply applying the `bx--header__menu-item` class is insufficient, because [that style rule is scoped to `a` elements with `role="menuitem"`](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/ui-shell/_header.scss#L178). 

We ended up having to duplicate these styles in a new class in our codebase. It would be nice if this rule was more flexible, or if these styles were in a more generic class.

> Is this issue related to a specific component?

**Comment by joshblack** [comment]
Hi @cwgormanIBM! 👋 Could you provide more details around the use-case that you're trying to achieve? Is this related to the last pattern below for showing the current page?

![image](https://user-images.githubusercontent.com/3901764/70470355-72b07080-1a90-11ea-9074-be0fbf9c232d.png)

**Comment by cwgormanIBM** [comment]
We would like that to say the name of the page, but not be interactive. For example, instead of "Link 1", it might say "Home".

**Comment by designertyler** [comment]
We’re trying to drive consistency between IBM platform Shells and adding a non-interactive label for the current page could introduce more variation in the headers.  Our current guidance is to use the selected state in the shell and a page header to indicate the current page.

**Comment by dblanchaIBM** [comment]
Hey team! The distinction here is that our product consists of "Apps/Modules", so the label isn't identifying a "Page" with-in the product, it's identifying an "App", as shown in Carbons own example here:

<img width="802" alt="TopNav-AppName" src="https://user-images.githubusercontent.com/58753734/70576937-23456f80-1b78-11ea-9b8c-d03bceb7f467.png">

This pattern has been represented in products before and I believe it's something that should be considered as another variation that perhaps the Carbon team has not encountered yet. We frequently white label our sub-offering(s) as well so this is a unique case to our specific product. Since we are identifying an "App", not a "Page", this should be suitable.

**Comment by designertyler** [comment]
ah, when I first read the request it sounded like it was for the page title and not the app/module.

We don't have it in our guidance, but the intent was to have the app/module name as part of the lockup. The IBM/offering/application would all be one (the "Application Name" in that example would be closer to "IBM Offering Name")

Let me double-check with the team and come back with a better response.

**Comment by joshblack** [comment]
Bump @designertyler! (assigned ya but feel free to unassign if that doesn't make sense!)

**Comment by designertyler** [comment]
@joshblack thanks for the reminder. I'm moving this back to the backlog since I don't think this ever started or was completed and looks like it was forgotten about over winter break.
