### ISSUE TITLE
Can Carbon Design System be used in React Native project?

### ISSUE THREAD

**Issue by elaineyl** [carbon-design-system/carbon#4934]

**Comment by gavbarosee** [comment]
bump

**Comment by joshblack** [comment]
Hi all! 👋 Sorry for the delay, we just recently returned from vacation 🌴 When it comes to React Native, unfortunately, we are unable to support it since our styles are written in Sass/CSS. While this is definitely something we want to do, it's not something we're able to offer currently 😞 

Going to close this for now, but if you have any other questions I'll be happy to help answer them!

**Comment by vko-online** [comment]
No react-native in 2021 coming?

**Comment by olnsbr** [comment]
It's 2023 now. Any updates?

**Comment by melchisedech333** [comment]
Is there any way to use Carbon in React Native? Are there any third party projects that address the issue?
