### ISSUE TITLE
Latest version causing build failures.

### ISSUE THREAD

**Issue by arnajdas1992** [carbon-design-system/carbon#4941]
## What package(s) are you using?
10.9.0

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

The latest version of this is causing build errors

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1.  Step one
2.  Step two
3.  Step three
4.  etc.

## Additional information

- Screenshots or code
<img width="1232" alt="Screenshot 2019-12-30 at 4 13 02 PM" src="https://user-images.githubusercontent.com/46365045/71579447-93fdfd00-2b22-11ea-8794-6fea1ebef3cd.png">

- Notes

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure
that your issue is properly categorized. This will help us to better understand
and address your issue.

**Comment by asudoh** [comment]
Given the error in above screenshot is not shown with our build - Would you want to create a reduced case, probably one based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox?

**Comment by elbrus** [comment]
After digging a bit more into it I found out that this bug is related to @carbon/themes, when not a default theme is specified to be used.

Basically there are 2 cases:
1. you updated carbon-components, but forgot to update @carbon/themes.

2. you updated everything, but you are using custom theme. It depends how custom theme is used. In my case I was creating new theme and adding it with `@include carbon--theme($my-custom-theme);`. But now theme got way more info, i.e. spacing and so on. If I want to keep using custom theme the same way, I'd need to add all that additional info to avoid compilation problems.

@arnajdas1992 , I suppose you have similar issue

@asudoh , probably this issue could be closed. Oh and I'm not sure would it be reproducable in codesandbox

**Comment by asudoh** [comment]
Closing for now given the comment above - Can reopen if e.g. things end up with Carbon's hard-breaking change.
