### ISSUE TITLE
Carbon site: components: accordion (demo) should expand from center 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#4988]
the type sizes being different is the bigger issue.

https://www.carbondesignsystem.com/components/accordion/code

should expand downwards not from center.

**Comment by mjabbink** [comment]
also the type sizes should be the same

current:
![Screen Shot 2020-01-09 at 7.22.10 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3c3d9b45-2ab7-44e8-bb07-df432048a16c)

**Comment by emyarod** [comment]
the downwards expansion should be because of the container on the website page

are the type sizes alright in the component [storybook](https://carbon-components-react.netlify.com/?path=/story/accordion--default)? it looks like the fonts being loaded are different but this might be a website-only issue

**Comment by aagonzales** [comment]
Its correct in the story book, this is just an issue with the demo on the website. I have it logged in this other issue as well.
https://github.com/carbon-design-system/carbon-website/issues/746#issuecomment-571335368

**Comment by tw15egan** [comment]
Closing this since it will be tracked over on the website repo.
