### ISSUE TITLE
Clear button on combobox: appears after selection is made

### ISSUE THREAD

**Issue by ericgendreau** [carbon-design-system/carbon#4992]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

After a selection has been made in a combobox, the clear button from the filter still appears. 

> Is this issue related to a specific component?

Combobox

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The clear button should not appear after a selection and the dropdown is closed.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Z. We have no pressing ship or release dates.

## Steps to reproduce the issue

1. Select an item from a combobox

## Additional information

![image](https://user-images.githubusercontent.com/56488380/72094791-2e113280-32e5-11ea-8e7c-149daa650a61.png)

**Comment by jendowns** [comment]
Hey @ericgendreau, I'm not familiar with the spec in the design kit, but based on your screenshot, I think that component state in the design kit is out-of-date. And, likewise, the code / website is more up-to-date. (But perhaps a designer can weigh in here? @carbon-design-system/design)

To that point, you wrote above:

> The clear button should not appear after a selection and the dropdown is closed.

I would say that the opposite is true: the "clear" icon *should* appear after you have made a selection... otherwise, how do you think someone should clear a selected item from the `ComboBox`? The "clear" action cannot be made until the options list is closed & a selection is made. (See it in action here: http://react.carbondesignsystem.com/?path=/story/combobox--default)

**Comment by ericgendreau** [comment]
Hi, @jendowns . I had discussed this on one of the Carbon Slack channels to get the team's take and it appeared to be a code bug, so hopefully @laurenmrice could weigh in here. Below is what I wrote in the channel to give more context:

> For comboboxes, does the clear button for text entry remain after a selection has been made? Looking at the code examples on the Carbon site, it looks like it does, while in the Sketch design kit it does not. If the clear button does remain, the signifier that differentiates between a selection that has been made vs text entered into the filter is that if a valid selection is not given, then the dropdown is closed, the filter's input text is cleared and the component's default placeholder text is shown. This is definitely fair but my two cents: I like the design kit's implementation. I think the stark differentiation between the filter state (with clear button) and the selection state aligning with regular dropdowns is more clear when choosing and confirming a selection has been made and when scanning through a form with comboboxes. If a user clicks on the currently selected text, then the clear button can return to indicate the filtering/selection process has been reactivated, clearly distinguishing the two "modes". Attached is a screenshot of the component as seen within the design kit versus carbon's website, today. I'd love to know your thoughts/opinions/direction on this :slightly_smiling_face:

The clear icon appears once a user starts entering text into the input field, filtering the dropdown list. If a user selects an item, the clear icon should be removed since a selection has been made and no further text entry is needed. If the user wants to remove their selection, they may select the combobox again, reactivating the text field with the ability to clear the text.

**Comment by jendowns** [comment]
Thank you for the context -- I'm confused about the distinction between when something is clearable, versus something isn't clearable. 

The clear button being present is a pattern I've seen elsewhere as well, like for the `Search` - http://react.carbondesignsystem.com/?path=/story/search--default (And likewise `DataTable` with a toolbar search). When you enter text for a search and click away, the clear icon is still there for you to use. This also makes it easier for folks using keyboard-only navigation so they can clickly tab to and then clear an entry.

And you could even say that the pattern of the `MultiSelect` is kinda similar in the way that you can directly clear selected items right away, instead of having to open the options list and de-select: http://react.carbondesignsystem.com/?path=/story/multiselect--default Similarly this has benefits for accessibility, allowing keyboard-only users to quickly clear a number of selected entries without having to de-select in the options list.

**Comment by jendowns** [comment]
OH one additional point from a code perspective --

I'm mentally modelling how, code-wise, you'd differentiate events to decide when the clear button goes away. And how you'd ensure it would be accessible for keyboard users.

Going with what you said here:

> If a user selects an item, the clear icon should be removed since a selection has been made and no further text entry is needed. 

Let's say "no further text entry is needed" means that a selection was made and then the filtering input no longer has focus. This can mean that the user clicks away, OR that the user tabs away...

Now, imagine this: 
I've filtered to something, selected it. My focus is still on the input, so I still see the clear button. 
If I'm a keyboard user, I would need to tab to the clear button in order to clear my selected/filtered entry. But tabbing *away* from the input causes the input to lose focus, which would remove the clear button. How would this work? (EDIT: I suppose this could be worked around but it's just one example of a challenge that comes to mind)

**Comment by ericgendreau** [comment]
Absolutely. The clear button should always appear when entering text. This is the case when a user begins filtering the combobox's list. After an item in the list is selected, however, the user is no longer entering text and the selected item appears more akin to a read-only state (although a user may always reactivate this by clicking on it).

You bring up an excellent scenario. To describe my thinking about this, I thought it'd be best to mock-up a user flow: 
![image](https://user-images.githubusercontent.com/56488380/72102501-28234d80-32f5-11ea-8974-e36d3c8456f4.png)

**Comment by chrisconnors-ibm** [comment]
Is the issue just that the design kit doesn't reflect the behavior in the actual react component (to the degree that's possible, given the static nature of the design kit assets)?

I don't think there's anything inherently _wrong_ with the (x) remaining in the combo box text field whether it has focus or not, as long as it contains a value that could be cleared.

**Comment by ericgendreau** [comment]
Hi, @chrisconnors-ibm. After checking with the Carbon team on Slack, it appears that the code does not reflect the behavior specified in the design kit and that it was a bug. As I mentioned on Slack, the current implementation is not _wrong_ nor is it unusable but I wanted to learn what Design's stance was on the desired implementation, which in my personal opinion I think their interaction design provides a _better_ overall experience for users (see my comment on Slack, noted in a comment above for my reasoning on this).

Of course, this is not my team so someone from Design on Carbon would need to make the call on this. Since Design thought this was a bug, I offered to open the issue for them 🙂

**Comment by chrisconnors-ibm** [comment]
the bug being: the persistent (x) as implemented (rather than some dynamic behavior on focus)?

**Comment by ericgendreau** [comment]
Yup. The capability to clear text from the filter's text field (x) still persists after a selection has been made.

**Comment by ericgendreau** [comment]
Please note, I'd highly recommend speaking directly with a designer who worked on this. The mockup I provided was something I created based on my interpretation of what I think was the team's intent.

**Comment by laurenmrice** [comment]
yes, I say we should revisit how/when the close icon appears if its closed and you have already selected something and are active in another part of the page. We could mark this as an enhancement instead of a bug for now since combobox is functioning properly.
