### ISSUE TITLE
[Tab] Container tabs needs text truncation. 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#5016]
The container tab text needs to elipse 16px from the edge like the default tabs do. 

Container tabs:
![image](https://user-images.githubusercontent.com/11670886/72187058-4738e280-33bc-11ea-9caa-f57c77d2c033.png)

**Default tabs:**
![image](https://user-images.githubusercontent.com/11670886/72187174-91ba5f00-33bc-11ea-9093-975d29d860cf.png)

**Comment by tw15egan** [comment]
I've been messing around with this but since that container tab is a flex item, it doesn't want to truncate. A quick fix would be to just set it back to `inline-block`, but that would cause the tab label to be aligned to the top. 

<img width="937" alt="Screen Shot 2020-01-13 at 1 36 53 PM" src="https://user-images.githubusercontent.com/11928039/72294252-033b1d00-360a-11ea-9427-fbe0770cf43b.png">

**Comment by aagonzales** [comment]
😐 hmm yeah I don't think we want it to top align the text.

**Comment by asudoh** [comment]
Seems that the ellipsis thing slipped from the checklist when the container tab was implemented (sorry). I haven't got time to look into this, but if flex item doesn't work, some other tricks in this space I can think of are `display: table-cell` or changing line height (to the height of the tab).
