### ISSUE TITLE
Removing placeholder text from Carbon Design System

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#5022]
### Summary

According to our guidance placeholder text should be avoided and definitely not used to convey critical information (input format etc) to the user. That said, there has been some discussion recently about what it might take (from a dev and design standpoint) to take placeholders out (?).

### Justification
Lots of research around placeholders and user expectations. Here's some I had on hand. Feel free to edit and add other links:

https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research

### Questions

There are many, but one that came up in conversation was -- what would the blast radius of removing this feature be? Potentially any of our text inputs can have hidden labeling (and be using Placeholder as an ad hoc label 🤷‍♂

**Comment by asudoh** [comment]
CC @carbon-design-system/design

**Comment by joshblack** [comment]
_Proposal Triage Meeting, January 21st, 2020_

**Potential problems with removal**

- If a team is _not_ using a label, this would remove a user's ability to discover what the input is for

**Usage in the wild**

- Some teams use placeholders instead of labels
- Some teams use placeholders instead of helper text
  - These are both WCAG AA violations because of contrast requirements for text

**Next steps**

- We have a variation of a component that could help with this use-case
- Should consider adding a prompt token that hits contrast requirements (or update placeholder)
