### ISSUE TITLE
[ToastNotification]: add guidance and styles for rendering action buttons

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#5055]
### Summary
Add action buttons to the `ToastNotification` component.

The ghost button makes alignment here awkward. Would need design spec/guidance before development.

### Justification

Right now, only `InlineNotifications` are spec'd for Action buttons.
![Screen Shot 2020-01-15 at 1 48 28 PM](https://user-images.githubusercontent.com/4078018/72466034-ca33b180-379d-11ea-9246-601d66f68af4.png)

However, there are some circumstances where a `ToastNotification` might prompt the user for some confirmation/action:

![waow](https://user-images.githubusercontent.com/4078018/72466199-0830d580-379e-11ea-8255-4271d503c18b.gif)

Another example might be a cookie preferences notification.

Inline notifications are designed to "show up in task flows". For application-wide events or notifications where we don't want to totally interrupt the user experience (as with a Modal), a `ToastNotification` with action would be very helpful.

### Desired UX and success metrics

- Add styles/design spec for action buttons in a `ToastNotification`
- Considering [WCAG 2.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits.html) toast notifications with an action _should not_ expire after a time limit. They should only be dismissed after the user manually closes or otherwise interacts with the notification.

### Specific timeline issues / requests

Need this feature for https://github.com/carbon-design-system/gatsby-theme-carbon/pull/655

### Available extra resources

I can build it!

**Comment by jeanservaas** [comment]
@vpicone here's the spec. I'm also making an issue on the systems board because the three of us decided to add the info icon to all information notifications... that will allow us to use the ghost button in both the toast and the inline notifications. 

ps, those info icon "i" 's should be black in the dark theme, not white

![image](https://user-images.githubusercontent.com/43144260/73196672-a190ad80-40f5-11ea-9eae-8d1a96b39125.png)

**Comment by rgblee** [comment]
Could you please have at least two action buttons? Reach out to me at andrew.lee1@ibm.com if you want to discuss why or which services are in need of this.

**Comment by jeanservaas** [comment]
Just talked to @aagonzales about this... we will need to put something on the board for design to create guidance around this for February / March planning and add it to the kit.

- It will act like the Mac OS system update notification and NOT be time sensitive; we cannot have actions on something that disappears... so we need to make that clear.

**Comment by vpicone** [comment]
@jeanservaas totally, mentioned the accessibility implications in the initial post. From a design perspective, guidelines could just be "Don't automatically disappear if there's an action."

@aledavila This could be developed and enforced today. If they give us an action, we'd just ignore the default timeout as well as any timeout passed all while warning the developer using custom prop validation.

**Comment by joshblack** [comment]
We'll hold development on the system side until what @jeanservaas pointed out gets settled. I don't think we can build this into toast since the behaviors are incompatible (timeout versus persist until dismiss). From our guidance:

> Usage
> Short, time-based messages that slide in and out of a page and provide nondisruptive information

> Duration and interaction
> Disappear automatically or can be dismissed by user

Would this fall under a "banner" notification per https://www.carbondesignsystem.com/patterns/notification-pattern#notification-types ?

**Comment by joshua-vaughn** [comment]
I don't see any reason why these behaviors are incompatible. If a toast message automatically dismisses, it will likely be saved to a Notifications page or panel where a history of all notifications appears. The messages and actions can be accessed from this page at a later time, so it's no big deal if a user doesn't see it or act on it when it appears as a toast message.

**Comment by joshblack** [comment]
@joshua-vaughn we might be speaking from different perspectives/contexts, I think the dominant concern with timed notifications would be this criteria that we have to meet: https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-no-exceptions.html

With text, we could communicate it using live regions that actively or passively inform the user. With content that is interactive, we would need to provide a way for keyboard and screen reader users to navigate to the notification. This interaction pattern seems distinct from the current usage guidance of toast, although it could be changed if we feel like it falls under this category.

One thing to note, while it may be likely that consumers will store notifications in a dedicated location, it's not a guarantee that all groups do this (or have the capability to do this) and we may have to build things defensively as a result.

**Comment by vpicone** [comment]
@joshblack just learned that the gatsby service worker now automatically fetched updates on route change: https://twitter.com/gatsbyjs/status/1229589052329881601?s=21

This might not be a blocker if we can just use a service worker silently (this is what gatsby www does.)

**Comment by jeanservaas** [comment]
@rgblee I'm not sure Carbon is quite ready to add this to core without some more research. I will tag this issue as a proposal and you can go ahead make your business case here in the issue, along with some UI images illustrating the context.

Then after some discussion the team can decide how to proceed...obviously there's a lot of interest in a site-wide status notification with actions. Thanks!

**Comment by aagonzales** [comment]
**Related**: 
We'll need a two button solution as well.
https://ibm-studios.slack.com/archives/C0M053VPT/p1582734506056900?thread_ts=1582566672.011600&cid=C0M053VPT

This will need a visual pass. I don't think we want to do fluid buttons in this scenario because they could stack. 

![image](https://user-images.githubusercontent.com/11670886/75366526-7def8d00-5884-11ea-9e09-588ef19b2cb6.png)
![image](https://user-images.githubusercontent.com/11670886/75366624-9e1f4c00-5884-11ea-9ec9-e7d8251b2ea4.png)

**Comment by vpicone** [comment]
@joshblack @aagonzales Gatsby isn't as smart about refreshing as I would have hoped this is still technically a blocker for adding service workers to the theme site.
