### ISSUE TITLE
Asking about will-change property 

### ISSUE THREAD

**Issue by xxxle0** [carbon-design-system/carbon#5110]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Relevant information

Im debugging the ui-shell issue #4718. It's related to the will-change: transform. It will be add when we have svg icon in our page then it make the last dropdown doesn't work. I know about will-change property but it's a un-predicable property in css. How do you guys think ?

**Comment by tw15egan** [comment]
Interesting, running it locally I'm not running into any issues when I add in another MenuItem... But I see the issue when I checkout the CodeSandbox. Seems like this may be fixed in the newest release when it's released. I'm seeing a bunch of fixes for UI-Shell that are not out yet: https://github.com/carbon-design-system/carbon/compare/v10.9.2...master

![ui-shell](https://user-images.githubusercontent.com/11928039/72834190-23d42a00-3c3d-11ea-9d1a-7402581c51c6.gif)

**Comment by tw15egan** [comment]
Icons no longer adding `will-change: transform` by default with this PR https://github.com/carbon-design-system/carbon/pull/5274/files
