### ISSUE TITLE
[Data table] Column header padding wrong

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#5360]
Padding on table headers is currently 8px left/right but it should be 16px left/right

As-is:
![image](https://user-images.githubusercontent.com/11670886/74566660-97fea680-4f39-11ea-97d3-250f9a54728d.png)

**Comment by xxxle0** [comment]
how about the padding of the table body ? if you change table header padding 8 px -> 16 px. I think the structure of table seems not consistent. 
<img width="1117" alt="Screen Shot 2020-02-15 at 3 00 42 PM" src="https://user-images.githubusercontent.com/18297839/74584345-f42dfd00-5003-11ea-8202-7e48cec5781d.png">

**Comment by tw15egan** [comment]
@xxxle0 I'm assuming each `td` in `tbody` should also be updated to be `1rem` instead of the current `.75rem` to match the correct table headers 

https://github.com/carbon-design-system/carbon/blob/50b14ff8ced774585fe1162192f22356d577aaef/packages/components/src/components/data-table/_data-table-core.scss#L88-L91

https://github.com/carbon-design-system/carbon/blob/50b14ff8ced774585fe1162192f22356d577aaef/packages/components/src/components/data-table/_data-table-core.scss#L117-L123

**Comment by aagonzales** [comment]
Opps yeah both should be updated. Great point.
