### ISSUE TITLE
[Dropdown, Mulitselect]: inline variants truncate text too early

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/carbon#5389]
If you look at https://carbon-components-react.netlify.com/, you'll see that the inline variants for MultiSelect and Combobox truncate the text aft "O..." and the border bottom doesn't extend through the whole width. 
<img width="141" alt="Screen Shot 2020-02-18 at 11 58 46 AM" src="https://user-images.githubusercontent.com/17281178/74763858-2af35580-5246-11ea-9cb4-ce10e8b23b4f.png">
<img width="226" alt="Screen Shot 2020-02-18 at 11 59 02 AM" src="https://user-images.githubusercontent.com/17281178/74763862-2d55af80-5246-11ea-8bbb-a605a07aa76e.png">

**Comment by tw15egan** [comment]
Seems like this was introduced via https://github.com/carbon-design-system/carbon/pull/4753, which takes in to account the various os behaviors and possible scrollbars when the checkmark is present...

**Comment by asudoh** [comment]
Right @tw15egan @abbeyhrt my apologies for that. I think #4753 made the (inline-mode-only) [right padding](https://github.com/carbon-design-system/carbon/blob/v10.9.3/packages/components/src/components/list-box/_list-box.scss#L233) of the `<div class="bx--list-box__menu-item__option">` redundant (given #4753 added a margin to the same element).

Wrt scroll bar, I suggest us not to do scroll bar detection, because it requires layout calculation that makes things complex and [has performance problems](https://gist.github.com/paulirish/5d52fb081b3570c81e3a). Ref: https://github.com/carbon-design-system/carbon/pull/4753#issuecomment-573272691
