### ISSUE TITLE
Pagination is not showing the current page information when page input is disabled.

### ISSUE THREAD

**Issue by leftyrivera** [carbon-design-system/carbon#5433]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-angular`

## Detailed description

We work in an application where access to data is sequential as a result when we use the pagination component we disable the ability to go to random pages.

> Describe in detail the issue you're having.

When I disable the page input that allows the user to move between pages I loose ability to see which page I'm on.

> Is this issue related to a specific component?

Pagination component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would like to see a label showing "x of y pages" when I disable the page input. 

> What browser are you working in?

Firefox & Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "10.7.4",
"carbon-components-angular": "3.2.8"

**Comment by nictownsend** [comment]
Hi, I see that on all themes but white - https://www.carbondesignsystem.com/components/pagination/code - with page input disabled the select seems like the wrong colour:

![image](https://user-images.githubusercontent.com/47386186/81099632-22d0bb00-8f03-11ea-8c42-86cbff16607d.png)

Is that intentional?

**Comment by tw15egan** [comment]
@nictownsend seems like a bug, do you mind opening a new issue for that?
