### ISSUE TITLE
[NumberInput]:  missing propTyles

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#5434]
- [ ] `carbon-components`
 - [x] `carbon-components-react`

## Detailed description

`NumberInput` is missing propTypes which is affecting the component demo on Carbon website. 
You can see they all say `node` even though they're not node.

![Screen Shot 2020-02-25 at 1 00 21 PM](https://user-images.githubusercontent.com/32556167/75278072-d82e1680-57ce-11ea-926f-2e9639a7079e.png)
<img width="1249" alt="Screen Shot 2020-02-25 at 1 00 04 PM" src="https://user-images.githubusercontent.com/32556167/75278076-d95f4380-57ce-11ea-88a9-d71b2ccd74f2.png">

**Comment by tw15egan** [comment]
Seems like this is an issue with ForwardRefs and PropTypes, see https://github.com/storybookjs/deprecated-addons/issues/7

Looks like we'll run into this issue with the following components:
- `InlineCheckbox`
- `NumberInput`
- `OverflowMenu`
- `RadioButton`
- `Tooltip`


Might be fixed by implementing Storybook Docs to replace Storybook Info addon, so going to take some time looking into that. https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by tw15egan** [comment]
Displaying correctly now 👍🏻
