### ISSUE TITLE
[RadioButton]: missing propTypes

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#5435]
- [ ] `carbon-components`
 - [x] `carbon-components-react`

## Detailed description

`RadioButton` is missing propTypes which is affecting the component demo on Carbon website. 
You can see they all say `node` even though they're not node.

<img width="1002" alt="Screen Shot 2020-02-25 at 1 14 52 PM" src="https://user-images.githubusercontent.com/32556167/75279333-09a7e180-57d1-11ea-961d-5e869ac3f3db.png">
<img width="1002"src="https://user-images.githubusercontent.com/32556167/75279367-19bfc100-57d1-11ea-809f-a00d014b770d.png">

**Comment by tw15egan** [comment]
Seems like this is an issue with ForwardRefs and PropTypes, see https://github.com/storybookjs/deprecated-addons/issues/7

Looks like we'll run into this issue with the following components:
- `InlineCheckbox`
- `NumberInput`
- `OverflowMenu`
- `RadioButton`
- `Tooltip`


It might be worth adding these to a larger issue that tracks these components as a whole since the same solution can probably be used to fix all of them.

**Comment by tw15egan** [comment]
Prop types should be displaying properly now 👍🏻
