### ISSUE TITLE
16px icon size 

### ISSUE THREAD

**Issue by Eva-Dage** [carbon-design-system/carbon#5500]
## Environment

> Navigation and action icon items in our products

## Detailed description:

There’s a growing concern over 16px sized icons in navigation.  The concern is that it might be very small for the users that don’t have an excellent screen resolution and general accessibility issue. Also, small action targets are more difficult to select accurately and requires more cognitive effort for the user and can leave them feeling frustrated and dissatisfied after making mistakes. I feel like it’s important for us to think about all the different types of users that will be using our products.   Perhaps, it could be that the touch target needs to be more specified to fix this temporarily. 

What are the current and future thoughts and concerns in regards to this issue? Is there a way to fix this temporarily and long term?

**Comment by joshblack** [comment]
Hi @Eva-Dage! 👋 With respect to the size of icons, the general recommendation is not to use the icons as the click target otherwise you do run into the issues you noted. When placed in a button, for example, then you'll end up with a larger click target.

For screen resolution concerns, we do use SVG assets to help with scaling and also create bespoke assets for the cases where the icons render blurry on non-retina displays.

Let me know if you have any other questions!
