### ISSUE TITLE
[Tag] - needs default type for carbon website component demo

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#5506]
If we hard code a specified type, it won't change colors when you select the other knobs. However, if we don't specify a type, it starts off with no color at all until you select a type because it doesn't have a default type. We need a default type for the demo to work correctly.

#### no default type
<img width="1200" alt="Screen Shot 2020-03-02 at 12 28 34 PM" src="https://user-images.githubusercontent.com/32556167/75705816-c2629a80-5c81-11ea-9364-f8986e71c397.png">

#### only shows the bg color once you select a type
<img width="1196" alt="Screen Shot 2020-03-02 at 12 28 42 PM" src="https://user-images.githubusercontent.com/32556167/75705826-c4c4f480-5c81-11ea-8968-18e5e7928605.png">

**Comment by asudoh** [comment]
@emyarod Thoughts...? Thanks!

**Comment by emyarod** [comment]
@asudoh I think we have a couple of options. we can add default prop type setting to the website knob container similar to storybook (this may be a major change), we can style the "typeless" tag (since the prop is not currently required), or we set a default type value in the core library. if we end up adding "typeless" tag styles or changing the default prop type in the core lib we will need input from design to decide which value should be the default

**Comment by asudoh** [comment]
Thanks @emyarod for your thoughts.

> we set a default type value in the core library

I think this makes the most sense.

@carbon-design-system/design - Any thoughts on the default tag style (type)?

**Comment by alisonjoseph** [comment]
from Lauren - 
> If we needed a default tag, I think it would be the gray tag. Since that is what we are basing our themes off of.
