### ISSUE TITLE
UI Shell Left Panel: Strategy needed for list items that are too long

### ISSUE THREAD

**Issue by tessarodes** [carbon-design-system/carbon#5520]
Hi there – posting my question as a github issue so the solution can be shared with my dev team.

Using the UI Shell left panel (256px width), what is the correct solution for overflowing a list item with a name that's either too long in some languages or all languages?

![image](https://user-images.githubusercontent.com/10426703/75817744-50f81a00-5d5d-11ea-880d-b4e277e7fa82.png)

Let's assume for the purposes of discussion that we can't simply rename the offerings, which will be considered.

### 1. Line wrap
![image](https://user-images.githubusercontent.com/10426703/75818320-45f1b980-5d5e-11ea-9d01-482589ed7fbb.png)

### 2. Truncate text
![image](https://user-images.githubusercontent.com/10426703/75818199-12169400-5d5e-11ea-83b6-aadc76c2e307.png)

### 3. Expand width of overall shell component
![image](https://user-images.githubusercontent.com/10426703/75817933-a3393b00-5d5d-11ea-8667-dcd57904c8a5.png)

**Comment by tessarodes** [comment]
One interesting additional detail that affects our decision but isn't part of the UI Shell Left panel per se:

We're using a pinning interaction in our nav on hover, so some of our items are short enough not to overflow until the pin icon is visible, as shown here:

![image](https://user-images.githubusercontent.com/10426703/75820349-cd8cf780-5d61-11ea-9433-df74f2b01795.png)

(To answer your inevitable question, yes we can remove the "Beta" tag in this case, but with the new expandable chevron we're implementing, the problem still exists).

**Comment by aagonzales** [comment]
# Current implementation 

The current implementation is **option 2: text truncation**. You can see it in the [story book](https://react.carbondesignsystem.com/?path=/story/ui-shell--fixed-sidenav) if you inspect and add more text to the items.

![image](https://user-images.githubusercontent.com/11670886/75820814-ab47a980-5d62-11ea-8a2c-93ea5f15df05.png)

![image](https://user-images.githubusercontent.com/11670886/75821023-1beec600-5d63-11ea-8873-269fda1ec7d7.png)

# Alternative solutions
We, of course, can always iterate on this if it is not meeting your needs.

### Option 1
Carbon designers have talked among ourselves and agreed that text wrapping to a second line would also be suitable. I think we still need to decide if that would be the default/only behavior or if we surfaced both options in the system. 

![image](https://user-images.githubusercontent.com/11670886/75825063-4a23d400-5d6a-11ea-9f7a-80b6d87f55a1.png)

Note: this could be a problem with the [side rail](https://react.carbondesignsystem.com/?path=/story/ui-shell--sidenav-rail) version and cause inconsistent gaps in the closed state.

### Option 2 (enhancement) 

**Add tooltip on hover/focus**
In order to make the truncation more user friendly and help with hidden content we can add a tooltip on focus and hover that will reveal the full name. 

(though it looks like on Cloud y'all already have a tooltip appear on any nav item with a prolonged hover)

![image](https://user-images.githubusercontent.com/11670886/75824300-e351eb00-5d68-11ea-839f-85ac1d562508.png)
_just conceptual not a final spec_

**Truncate with pin on hover**
I also think if the problem is just because of the pen function there are some alternative interactive solutions where the pen appearing would cause the content to truncate. 

![image](https://user-images.githubusercontent.com/11670886/75924037-dc3fe100-5e2b-11ea-9be3-460a9e922312.png)


Or/also have the pin replace the tag on hover and when its pinned. 

![image](https://user-images.githubusercontent.com/11670886/75923849-84a17580-5e2b-11ea-93e6-c84413028aa8.png)


Avoid text wrapping that's is caused by stateful change. 

![image](https://user-images.githubusercontent.com/11670886/75923612-0d6be180-5e2b-11ea-858d-b55b1da6c0f6.png)



### Option 3
This is the least desirable option and should be avoid. We're not really considering making a variation of the left nav that is wider like option 3 suggested because the width would have to be more than a marginal difference to be worth it and for the variation to have any visual distinction and added spacial value. I still don't think even that is a fail safe solution because the length of any nav item in any language is unpredictable and there will always be words/names that won't fit. Therefore I think there's a stronger argument for maintaining the 256px width of system consistency. 256px width also works well with 2x grid and language grid proportions. 

We'd want to keep the default nav at 256px and adding a larger left nav would also cause consistency issues in product with on page nav.

**Comment by amberfeinerman** [comment]
Hi @joshblack and the Carbon team! Is there an ETA on when this could be completed? [An issue was raised](https://github.ibm.com/ibmcloud/security-compliance/issues/651) in my product team's repo and I'd love to provide an update/timeline on when we can expect this issue to be fixed. Thanks!

**Comment by tw15egan** [comment]
Seems like we are sticking with `option 2: text truncation` so I'm going to go ahead and close this as resolved. If we want to revisit and implement another one of the options we can reopen 👍
