### ISSUE TITLE
JAWS 2020 Code Snippet "Copied to clipboard" and "Copyable code snippet" announced twice

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#5553]
Reference #2523 

## Environment

> Operating system

Windows 10

> Browser

Firefox

> Assistive technology used to verify

JAWS 2020

## Detailed description

While using JAWS 2020 on our code snippet component "Copied to clipboard" and "copyable code snippet" are read twice.

> What version of the Carbon Design System are you using?

latest

https://github.com/carbon-design-system/carbon/issues/2523#issuecomment-592197856

**Comment by aledavila** [comment]
This issue has been tested and the issue is not that it is repeating itself. There is not bug with that. Jaws is working as it should. Rather this is an issue with the interaction implementation of the component itself. 

Issue: 
When navigating to the copy button. It says "copy to clipboard button" > then once you press enter it says "copied to clipboard" and then when the animation hides the feedback/tooltip it repeats "copy to clipboard". This is becaue the animation causes a change in the label and what is showing forcing Jaws to announce the change. So Jaws is working as intended. 

This would need a bigger deep dive in how the the Copy Button and Copy components are built.
