### ISSUE TITLE
MultiSelect Component No Longer Supports Opening Up

### ISSUE THREAD

**Issue by cmuentes** [carbon-design-system/carbon#5588]
## What package(s) are you using?
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The `MultiSelect` component no longer supports opening `up` - some of the mixins are left in for the `up` prefix but they need to be added back to `Listbox` and `Dropdown`.

## Steps to reproduce the issue

1. Open code sandbox: https://codesandbox.io/s/reverent-paper-bw6gs
2. Observe the `direction` attribute passed to `MultiSelect`
3. Observe the drop down still opens downward

**Comment by tw15egan** [comment]
cc @carbon-design-system/design making sure this variant is still allowed, or if this was purposefully removed

**Comment by aagonzales** [comment]
The vanilla version of dropdown has the `open up` function but it is not in react. Having the prop to open up is useful when the dropdown is at the bottom of a page or container but it also will cover up the title and any helper text when open so could cause some ux issues. 

I'm not sure if it was intentional or not to exclude it in React. I'll have to investigate that a little further.

**Comment by asudoh** [comment]
Vanilla uses legacy markup of dropdown. So I imagine that when the markup of newer dropdown (list box) was implemented, the drop-up option was slipped.
