### ISSUE TITLE
[Carbon Type Package]: Add IBM Plex Condensed

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#5615]
Carbon Charts uses the condensed in X and Y-axis and axis labels
https://carbon-design-system.github.io/carbon-charts/

Teams like IoT are using Carbon Charts and getting Helvetica in place of Plex Condensed in all their Bar Chart versions
https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-barchartcard--simple-bar

sample:
<img width="523" alt="Screen Shot 2020-03-12 at 6 03 31 PM" src="https://user-images.githubusercontent.com/32881239/76574943-ce253c80-648b-11ea-926f-b4893a09309d.png">

**Comment by tw15egan** [comment]
Very odd... I get the correct fonts in Chrome:

<img width="582" alt="Screen Shot 2020-03-13 at 9 44 28 AM" src="https://user-images.githubusercontent.com/11928039/76641722-441eb780-650f-11ea-8969-ceba5b2614c1.png">

But I get Helv in Safari / on mobile

<img width="588" alt="Screen Shot 2020-03-13 at 9 46 07 AM" src="https://user-images.githubusercontent.com/11928039/76641904-8cd67080-650f-11ea-8492-351ba94aee6f.png">


Possibly because I have the fonts loaded on my laptop. 

@joshblack seems like we need to add `IBM Plex Sans Condensed` to the `font-face` declarations?

**Comment by joshblack** [comment]
@tw15egan ah do we use condensed for charts??

**Comment by tw15egan** [comment]
Yeah seems like it so we need a way to turn on the condensed styles. Doesn't look like we ship that out as it stands? Do we just need to mimic the other `font-face` files in `type/scss/font-face`, and add one in for `_sansCondensed`?

**Comment by vpicone** [comment]
@tw15egan that’s my impression. We just don’t provide the google fonts `@font-face` declarations for condensed Plex like we do for serif, sans, and mono. 

Considering we supply the sources for Serif despite not using it in Carbon/product, it seems like it we should be including it.

**Comment by tw15egan** [comment]
Do you know how / where we get the url for the fonts?

e.g. https://github.com/carbon-design-system/carbon/blob/d31eadd33d25ada72adf7cc0d247c4e8d7f1def9/packages/type/scss/font-face/_sans.scss#L21

**Comment by vpicone** [comment]
@tw15egan we just get them off google fonts. Typically when someone uses google fonts, the link they give you fetches a style sheet With the latest font face definitions. We just do that fetch a head of time and commit it. The negative side effect is that our version of Plex can get out dated. Here’s the link for they give for condensed. 

https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Condensed

**Comment by theiliad** [comment]
@tw15egan On a machine where I have Plex installed I'd get Plex on the IoT pages because the browser will locate the font locally. But if you don't have it installed you'll get the fallback fonts
