### ISSUE TITLE
IBM product specific loader icon which can be displayed to load the first view of the UI

### ISSUE THREAD

**Issue by nsharma1989** [carbon-design-system/carbon#5633]
### Summary

Hi like many companies use a private product loader when the website or view is first loaded . Can we have a similar component for creating custom product specific loader. Or something common to IBM products. 

### Justification

Its kind of looks weird to display a big circular loader icon when the page takes time to load in the beginning. Also it will enhance the UI to display IBM specific loader icon.

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.
- If this loader is to be used with the beginning of launching the view it will use something like 
`<Product Loader icon={branding icon} label="Loading page" showProgressBar={true/false} behaviour={blink/rotate/fadeIn FadeOut} overlay={true/false}>`

### "Must have" functionality

behaviour={blink/rotate/fadeIn FadeOut} 
overlay={true/false}
icon= custom branding/ product icon

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release? no

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

I can help in developing this component.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
Hi 👋 do some in https://www.carbondesignsystem.com/patterns/loading-pattern/ close to what you need?

**Comment by nsharma1989** [comment]
Hi, @asudoh this is similar to the full page loading but with a product icon instead of a big circle. something like this 
![Screen Shot 2020-03-11 at 3 24 26 PM](https://user-images.githubusercontent.com/18398195/76861769-77c15080-6833-11ea-9b89-e51fdafbba7d.png)

**Comment by laurenmrice** [comment]
Thank you for taking the time to make a proposal!

Carbon uses skeleton states for an initial page load for UIs instead of spinners or progress bars (usually lasting a couple of seconds). If loading may take longer than a matter of seconds, we recommend using a progressive loading technique (loading in batches) described in our Loading pattern https://www.carbondesignsystem.com/patterns/loading-pattern . 

Spinners and progress bars are explicit loaders and we argue that these forms of loading could pause user interaction, unlike skeleton states that create the illusion of an instant transition.

Since we recommend using carbon skeleton states for this scenario, we won’t be adding this specific loader to our core components, but your team can implement this on your end.
