### ISSUE TITLE
React storybook

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#5640]
I have a couple questions/thoughts about the react storybook. 

--------------------------------------------------------------------------------------------------

### Testing environment or source of truth?
Carbonites, as well as our users, tend to reference our storybook to help answer support questions. Links to react are shared in order to verify what is true to code, to show people how they can interact with certain modifiers and/or variations of a component, etc. 

- My concern about this is that we also are currently using react as a demo testing environment for devs. I end up finding there are stories with examples that designers are unaware of and are not correct from a ux/visual perspective (these were made for testing purposes). If we want to be able to show people react, do we have an option to hide our testing stories from the public so we don't confuse people?  I've personally have had folks reach out to me wondering about some of these things as well.

- Does react need to be restructured so it correctly shows our structure here? https://github.com/carbon-design-system/carbon/tree/master/packages/components/src/components

- Ideally the component switcher could fix all of these problems. We could direct people to this instead of react for the future. The component switcher is not finished yet, but I feel that this shows we need it.

### Knobs within storybook
Are there current plans in the works to move away from knobs in react? Currently we are still adding to them whenever we add enhancements.

- I have heard this come up in discussions that the desired state would be to move away from them, but was wondering if there are thoughts about what we should do instead of knobs? 

- How or will this influence the component switcher?

**Comment by asudoh** [comment]
@laurenmrice Thank you for sharing your thoughts!

> I end up finding there are stories with examples that designers are unaware of and are not correct from a ux/visual perspective (these were made for testing purposes)

Those stories should be (clearly) marked as such, so that our users won't create UX from them. Great if our design team try to look at the stories and find ones that are wrong from UX perspective. Some of such wrong UX ones may be just bugs, or one solely to demonstrate our API as you pointed out.

> Does react need to be restructured so it correctly shows our structure here?

Do you have any stories as an example, where you think their structures are wrong?

> I have heard this come up in discussions that the desired state would be to move away from them, but was wondering if there are thoughts about what we should do instead of knobs?

I think Knobs is a good way to demonstrate and manual-test our API, showing the UI with different set of props. That said, if a specific combination of props shouldn't be used from UX perspective, we can document it. Or great to hear your thoughts if you think Knobs has adverse effect to other UX means.

**Comment by joshblack** [comment]
@laurenmrice I think these points are all spot on, and definitely points to the fact that storybook has been used more as a development environment and, as a result, it doesn't directly serve folks who might want to reference it for documentation.

Features like knobs are a good example of this where it is hard to know what combination of knobs to use to achieve a specific usage of a component, it also obfuscates the code so that one cannot just copy and paste the example into their own project.

In general, it seems wise that we move towards dedicated component documentation pages. Some examples include:

- https://reacttraining.com/reach-ui/accordion
- https://reakit.io/docs/dialog/
- https://chakra-ui.com/accordion
- https://material-ui.com/components/buttons/

And it's important that we map out the following information:

- Why would one use this component
- How would one install this component
- How would one use this component to accomplish some particular usage
- What options are there for configuring this component for certain usage
- What are all the ways in which one can configure this component (API)

**Comment by shinytoyrobots** [comment]
Lauren's point about Storybook is an important one, though. Storybook, whether developer environment or not, should definitely reflect the true implementation of our components.

I think dedicated component documentation pages are the right move. But depending on timelines, we might also look at addressing inconsistencies between design and development guidance on our site, and what is presented in storybook.
