### ISSUE TITLE
Sass Layout and Breakpoint Variable Access

### ISSUE THREAD

**Issue by jharvey10** [carbon-design-system/carbon#5648]
### Summary
Our team would like access to the breakpoints sass partial similar to what we currently have for spacing, typography, color, etc...

Example using spacing
```scss
@import 'carbon-components/scss/globals/scss/spacing';
.custom-thing {
  margin-right: $layout-03;
}
```

Example using typography
```scss
@import 'carbon-components/scss/globals/scss/typography';
.custom-thing {
  @include type-style('productive-heading-02');
  }
```

In order to do the same for breakpoints, we have to use
```scss
@import 'carbon-components/scss/globals/grid/grid';
```
or hijack another module that imports the breakpoints for us (such as `carbon-components/scss/globals/scss/typography`)

There are two problems with this:
1. Importing grid seems to cause a lot of "stuff" to be done aside from just making some variables and functions available.
2. Importing grid is not practical within a scss module, which we use extensively to isolate individual sub-applications and components within our react framework.

**Comment by justindm234** [comment]
To expand on what Joe stated above... The sass mixins our CSS Modules are after are provided @carbon/layout's _breakpoint.scss - `carbon--breakpoint-{between,down,up,etc}`.

Using carbon-components, we can currently import these mixins in 1 of 4 ways, none of which seems ideal:
- Using carbon-components' vendor scss (making our code depend on carbon-components dependencies).
- Importing carbon-components/scss/globals/grid/grid, which creates component-scoped bx--grid css (e.g. Banner-module__bx--grid__<hashstring>) which adds 32k unused css to the CSS module output
- Importing carbon-components/scss/globals/scss/typography (which only works because it imports ../../globals/scss/vendor/@carbon/elements/scss/type/styles which imports @carbon/layout/breakpoints)
- Add a project dependency for @carbon/layout (which we would need to keep in sync with the version used by carbon-components)

**Comment by joshblack** [comment]
Hey @jdharvey-ibm ! 👋  Sorry about the delay in response, I went and opened up #6627 as a potential solution for this by exposing the layout package under the `_layout.scss` global entrypoint. Hope this works!

**Comment by jharvey10** [comment]
Sweet! I think it will! Thanks 👍
