### ISSUE TITLE
IBM Plex Sans Condensed font not exposed through Carbon styling modules

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon#5653]
Hi 👋 
This is a major issue considering that most of the dataviz styling work involves `IBM Plex Sans Condensed`.

We ship styles that rely on the font, however product teams using Carbon would not automatically get the condensed font into their application, and will only be adding `IBM Plex Sans`.

**Comment by tay1orjones** [comment]
Yes, due to this we [added condensed declarations in the `carbon-addons-iot-react` package](https://github.com/IBM/carbon-addons-iot-react/pull/998/files#diff-6a2256f44598ec970b4bd034962e011e) pointing to unpkg.

We would prefer to have it upstream in `@carbon/type`/`@carbon-components` - we have [an open issue](https://github.com/IBM/carbon-addons-iot-react/issues/1007) to follow the outcome of this issue to hopefully be able to remove these declarations from our sass.

**Comment by tw15egan** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/5615
