### ISSUE TITLE
Decrease contrast of hover state for white components?

### ISSUE THREAD

**Issue by tessarodes** [carbon-design-system/carbon#5797]
This is a subjective and preference-based submission. After you consider it, feel free to close. 

For reference, we have just implemented the Gray 10 theme and thus we interact primarily with White components. 

## Description
There's a discrepancy in the contrast between the hover states of Gray 10 theme components (1.14:1) and White theme components (1.25:1) because they're using the same hover color for the two themes (#e5e5e5). This is a rare scenario where I may want lower contrast for the white theme.

This nuance ONLY bothers me on data table and tile.

![image](https://user-images.githubusercontent.com/10426703/78305080-b4fd3200-7505-11ea-98b2-864c0634c8a2.png)

## Examples
Here are some examples of the prominent hover state on White theme data table and tile in our product.

### Hover on white data table:
![image](https://user-images.githubusercontent.com/10426703/78307246-18d62980-750b-11ea-88f7-4bb2eba080cc.png)
![image](https://user-images.githubusercontent.com/10426703/78308004-e3324000-750c-11ea-8ed4-353e7b3a4ae4.png)
We have several scenarios where folks will have only one item in their data table, or the first item may be expanded by default.

### Hover on white tiles:
![image](https://user-images.githubusercontent.com/10426703/78304263-f12f9300-7503-11ea-9fec-df26ff3d8dff.png)
![image](https://user-images.githubusercontent.com/10426703/78307888-98182d00-750c-11ea-9aa9-d5cde16344a1.png)
![image](https://user-images.githubusercontent.com/10426703/78307957-c39b1780-750c-11ea-87cb-05594ace7dd7.png)
Sometimes the hovered item can look a bit disabled instead of almost selected.

## Suggestion
The same way #e5e5e5 is not an "official" IDL step between Gray 10 and Gray 20, I suggest considering making a step between White and Gray 10:
![image](https://user-images.githubusercontent.com/10426703/78306683-9b5de980-7509-11ea-905e-526dbd6139b9.png)
(Excuse the hacked-together screenshot)

I stole the #f8f8f8 color from Slack, which uses that color for hover on white, and which happens to be a contrast midpoint between white and gray 10.

Here's how that would look on a white theme Data Table:
![image](https://user-images.githubusercontent.com/10426703/78306409-ee836c80-7508-11ea-885b-fe310e097c1c.png)

For tiles, the catalog team has already broken the convention and decided to use a different strategy (an outline) for their clickable tiles:
![image](https://user-images.githubusercontent.com/10426703/78308187-6d7aa400-750d-11ea-9f98-0f959584e729.png)

Of course, I understand you already use an outline for the selected state of selectable tiles. I've seen both that blue border and a lower-contrast border in my reviews (existing selected state on the right):
![image](https://user-images.githubusercontent.com/10426703/78308670-aebf8380-750e-11ea-8b7b-9730bee208db.png)
I'm not crazy about these solutions, either, so this one would need some additional thought.

**Comment by asudoh** [comment]
CC @carbon-design-system/design

**Comment by aagonzales** [comment]
Yup, the white hover is a known issue that both Jeannie and Mike ~constantly~ complain about. The current problem is in both the White and Gray 10 themes that hover color has to work on both backgrounds. The two solutions we've previously discussed are:
1. **New token**: Introducing a new token to work on the opposite color, and add hover to the `light` variable and other instances where the alternate ui background is used. 
2. **New hover style**: the second option would be to change the hover colors from solid hexes to a darken/lighten effects instead and therefore the base color would always change proportionally. Sadek and Vince have been in communication about how this transition would work and look like. The original hover solid colors came from Brand so we're having to work through that with them.

**Gray 5**
The solution of Gray5 wouldn't work as a solution for updating the one `$ui-hover` token because it would break the color logic of hover always going a darker shade. So anything on gray-10 would actually  lighten which breaks the language logic. This would be something we'd have to talk to Mike and Sadek about and I don't think they would be in favor or it but we can discuss it.

**Tiles**
Tiles again are a big motif of Brand and I think they're pretty attached to the background change on hover. Would lightening the hover still work for you here or would you still want a non-background change on hover. Would this just be for selectable tiles or for all tiles? We use the tiles a lot across the Gatsby templates and I think they would want to maintain the background hover state changes for those.

**Comment by kingtraceyj** [comment]
our load balancer and virtual server teams are having similar issues with their expanded tables:

load balancer:
![Load balancer](https://user-images.githubusercontent.com/20582179/84055009-d6e9b980-a979-11ea-8cb7-ca0a6f4a747f.gif)

Virtual server:
![image](https://user-images.githubusercontent.com/20582179/84055078-ee28a700-a979-11ea-95c4-9b5a535eb114.png)

**Comment by tessarodes** [comment]
@aagonzales Just saw your answer about Gray 5! Thanks for your response. I wasn't suggesting we use Gray 5 as a hover color for gray 10 too, only for white, therefore maintaining the logic that hover would always darken. Gray 10 would hypothetically continue to darken to "Gray 15," while white only would use Gray 5. 

In Tracey's example above, the status indicator color would still be accessible on a color like the proposed Gray 5, although I'll admit we should probably just darken our status color to account for the possibility of it appearing on gray 15 anyway, it just hasn't been a problem until now.
