### ISSUE TITLE
Overflow menu for data table rows should be visible on hover

### ISSUE THREAD

**Issue by ljitendra** [carbon-design-system/carbon#5804]
### Summary

Based on storybook link for data table component, the overflow menu is visible for every row. Based on UX discussions, there should be a prop to make the menu appear only on hover or visible for each row.

<img width="1384" alt="Screen Shot 2020-04-03 at 3 11 29 PM" src="https://user-images.githubusercontent.com/15458935/78396652-bdb13f00-75bd-11ea-961c-b64eff7d4239.png">

**Comment by asudoh** [comment]
Hi 👋 we used to do what you suggested, but we switched to make the current way because users seem to have difficulties to discover the overflow menu icon. CC @carbon-design-system/design

**Comment by ConradSchmidt** [comment]
Like @ljitendra said, the design team decided to specified the UX so that the menu is shown on row hover. Maybe this can be discussed with the Design team - to avoid overwriting Carbon, it would be nice to have this behaviour available as a prop (like "actionsOnHover").
If we would provide a PR would it be more feasible to get this implemented?

If you changed this recently, please update your Documentation:
https://www.carbondesignsystem.com/components/data-table/usage/
**Persistent overflow menu**
By default, the overflow menu icon appears **on hover or focus**. This reduces visual clutter and drives user interactions with clear context and results.

**Comment by laurenmrice** [comment]
I think we could add a prop for overflow hover. 👍🏻

**Comment by ConradSchmidt** [comment]
But just to be clear, is the Carbon site/guideline outdated, when it comes to this topic? Because the guideline says something different than @asudoh as quoted [here](#issuecomment-609653982)

**Comment by laurenmrice** [comment]
Yes, we need to update that to what we have as default (persistent overflow icons)! A designer on our team is actually working on docs for data table this month, so we will update it.

**Comment by joshua-vaughn** [comment]
So, I'm confused since this issue is closed but the documentation doesn't seem to have been updated yet.
- Is there a hover/persistent property?
- If so, is it now "persistent" by default in the code, and this just hasn't been updated in the data table docs yet?
- Could my application suite decide that "hover" is more appropriate for our data scientist users?

Thanks!

**Comment by asudoh** [comment]
Hi 👋 #5822 introduces `overflowMenuOnHover`. The default is _not_ changed. Please see #5822 for more details.

**Comment by andreagmann** [comment]
@joshua-vaughn Right, the component has not changed, the default has always been persistent for the _component_. In fact, the react component did not use to support on hover, and our developers (CPD) were manually doing so.

@laurenmrice The website documentation however is still misleading. It states the default behavior is on hover and that there are usability issues with making the icons persistent. When can we expect this documentation to be updated?

<img width="763" alt="Screen Shot 2020-05-07 at 8 12 06 AM" src="https://user-images.githubusercontent.com/14081333/81311768-a9d47f00-903a-11ea-86f7-ccf0fd36b434.png">

**Comment by laurenmrice** [comment]
@garciaam A designer on our team is currently working on updating data table usage documentation. We are introducing a new documentation structure to our usage tabs which will cover more sections than we are showing now. Data table is one of our largest components so we are taking the time to make sure the content is thorough. The section about overflow menu will be addressed. There is no exact timeline on when this will be available, but it is actively being worked on as a high priority project.
