### ISSUE TITLE
Proposal to update tooltip placement logic

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#586]
This issue corresponds to the work done in #583 and is being used to organize groups who may have implemented their own placement logic.

Would love to hear @asudoh's opinions on the work he's introduced in #583. I believe @scottnath also has been doing some work here to update the tooltip logic that we need to sync-up on.

I'm unsure of what the requirements are here for the placement logic so would love for either Akira or Scott to suggest what the requirements are here.

**Comment by marijohannessen** [comment]
@joshblack @asudoh any update here?

**Comment by joshblack** [comment]
None on my end 👍

**Comment by asudoh** [comment]
Given this issue seems more for discussion, some background - Floating menu is hostile to modern web development approaches, and tend to involve complex layout calculation if we don’t do it carefully.

Because of that, the goal of the floating menu placement logic is keeping it as minimum as possible, basically deliberately limiting it to calculating the position of edges of the trigger button relative to the top/left corner of the viewport. We use “adjustment” mechanism for others like arrow size, and expose it as `objMenuOffset` option (which can take a function) in overflow menu and tooltip so that application can override it.

There were some issues with IE that have been fixed. There is a request for using alternative DOM element as the target (stemming from [a focus issue](https://github.com/carbon-design-system/carbon-components/issues/910), etc.) that I’ve been considering.

Other issues are tracked individually and can be worked around by using the adjustment mechanism. Hope it helps!
