### ISSUE TITLE
Update Storybook React docs and edit for clarity

### ISSUE THREAD

**Issue by 3dfoster** [carbon-design-system/carbon#5902]
### Summary

The storybook documentation for React Carbon components is unprofessional. Text ought to be re-written so it is informative and mature.

### Justification

It's important people think of a library built by IBM in a professional manner.

### Examples
<img width="1278" alt="Screen Shot 2020-04-21 at 12 14 33 PM" src="https://user-images.githubusercontent.com/13704150/79893846-3d1a7d00-83ca-11ea-998c-1117c94dfed3.png">Text is not helpful in understanding how the component works. The documentation for this component in particular is not even complete. 

---
<img width="1278" alt="Screen Shot 2020-04-21 at 12 18 59 PM" src="https://user-images.githubusercontent.com/13704150/79893990-70f5a280-83ca-11ea-8592-a979e75fff56.png">The first time I read the `helperText` prop that stated "This is not helper text" I had to think for one minute to understand it was a joke. That was one minute I could have better spent more of the Carbon system.

**Comment by joshblack** [comment]
Hi there @3dfoster! 👋 

Thanks so much for taking the time to make this issue. We definitely agree that the docs can and should be better. Teams rely on us and spend a lot of time working with the work that we do and we should be respectful of their time and expertise. As a result, we are actively working on this as part of our April 2020 plan for our first set of 6 components.

The same way you expect professionalism in documentation and reference material, we expect professionalism in how we engage through tools like GitHub and Slack. Especially during this time, it's important to have empathy and be respectful online.

As it stands, the way this issue is written does not meet our [code of conduct](https://github.com/carbon-design-system/carbon/blob/master/.github/CODE_OF_CONDUCT.md). We're happy to hear and better understand your frustrations and work on, or with, community members to improve outcomes. In order to do this, we all need to be respectful and understanding.

If you could edit this issue to better reflect these characteristics, it would help us out a lot to move forward. Detailing specific component stories or places where things are incomplete or unhelpful will help us move forward with addressing things and improving the experience folks have while using carbon.

**Comment by 3dfoster** [comment]
Updated for professionalism. Here's to hoping the docs get updated in the same manner as well 🤞

**Comment by joshblack** [comment]
We'll definitely try our best, similarly, we'll always accept PRs from contributors.

Some of these things are storybook limitations as well and are outside of our control. In your screenshots above, this shows up with the prop table. In these situations, would recommend leveraging the component source file which can provide prop type information.

For the specific helper text, this is being updated in: https://github.com/carbon-design-system/carbon/pull/5867

**Comment by joshblack** [comment]
Hey there! Wanted to follow up on this, we are tracking updates to docs for each of our components over in: https://github.com/carbon-design-system/carbon/issues/6645

You can see a preview of the updated format under the "docs" tab here: https://react.carbondesignsystem.com/?path=/docs/accordion--accordion

Let me know if you have any questions/comments! Feel free to weigh in if there are any other topics you'd like to see addressed :smile:
