### ISSUE TITLE
[CodeSnippet]: fails inside Jest testcase with codeContentRef.current.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#5926]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Can't use CodeSnippet inside a Jest testcase without mocking createNodeMock

> Is this issue related to a specific component?

CodeSnippet
> What did you expect to happen? What happened instead? What would you like to
> see changed?

codeContentRef.current.getBoundingClientRect is not a function
    at /Users/scottsd/Documents/GitHub/maximo-asset-monitor-ui/node_modules/carbon-components-react/lib/components/CodeSnippet/CodeSnippet.js:80:58

Error thrown and fails Jest testcase, I'm forced to mock the ref, we should check if current is null before calling getBoundingClientRect

> What browser are you working in?

jest/jsdom

> What version of the Carbon Design System are you using?

"carbon-components": "10.9.1",
"carbon-components-react": "7.9.1",

**Comment by emyarod** [comment]
there already is a truthiness check in place for `codeContentRef.current` https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/CodeSnippet/CodeSnippet.js#L43

what is the value of `codeCurrentRef.current.nodeType` before mocking the ref? I assume it is a truthy value but it is not an `Element` (which is why the `getBoundingClientRef` method is not found)?

**Comment by joshblack** [comment]
Hi there! Going to close this out due to inactivity, feel free to comment and I can re-open!
