### ISSUE TITLE
Adding className property to the radio of the radio button

### ISSUE THREAD

**Issue by peterloveland** [carbon-design-system/carbon#6037]
We've got a use case to provide 3 options, with radio buttons. 2 of these options have additional text inputs to enable our use case.
We've managed to get the following without any overrides to Carbon (just providing classNames and CSS to the right pieces) but are stuck with this alignment of the actual radio button:
![image](https://user-images.githubusercontent.com/2086381/81315718-90572580-9082-11ea-9158-01e889dfd679.png)

Ideally we'd just like to be a able to add a property to the radio selector itself:
`.bx--radio-button__appearance ${optional class here}`.

Is there a more 'Carbon approved' way of handling this scenario? Or would it be possible to have this optional class plumbed in?

cc. @matthew-chirgwin

**Comment by tw15egan** [comment]
Hey Peter! We could certainly add in a prop that is applied directly to the `.bx--radio-button__appearance`. 

Just curious, what would the benefit of adding a class directly to the `span.bx--radio-button__appearance`, rather than doing something like `.myCustomWrapperClass .bx--radio-button__appearance`? Just trying to figure out what you are hoping to achieve 🙂
