### ISSUE TITLE
[List] Reduce spacing between list items to 0px

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#6138]
Currently there's a 4px spacing between list items. Upon review with @jeanservaas, this spacing should be removed so it's 0 spacing between list items. 

![image](https://user-images.githubusercontent.com/15144993/82936803-1e754c00-9f5d-11ea-9cd9-b6d9ff1f62de.png)

The **Dotcom Reboot** team and **Digital Design System** team are dependent on this change.

**Comment by mariuszmickiewicz** [comment]
@shixiedesign 

Hi,
I'm going to update Carbon Sketch library with this change. I have a question about text style here.

* Carbon libraries use **body-short** version 
* I have an isolated Sketch file for the list component (for ibm.com library I think) and it uses **body-long**

The difference is the **line-height** (and size of the text, but this is to be expected). Should Carbon also use **body-long** (because of reduced spacing which influences perception) or should it stay **body-short**, because of the way Carbon is used (for a product, and not long text pages)?

**Comment by shixiedesign** [comment]
Hi @mariuszmickiewicz ibm.com library is using `body-long` in anticipation that Carbon will eventually unify and have only 1 line height option. So in my opinion, either long or short would be fine, and short would look more consistent with today's implementation. Though I'd defer to @aagonzales and @jeanservaas if this is the best idea. Thanks!

**Comment by shixiedesign** [comment]
![image](https://user-images.githubusercontent.com/15144993/88548269-e20dad00-cfec-11ea-9592-556b52a02d8e.png)
