### ISSUE TITLE
TableToolbarSearch: if I set a defaultValue, the onChange callback is called inconsistently

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon#6157]
TableToolbarSearch calls onChange back differently if a defaultValue is set, than when the actual value is typed, this required two different versions of my onChange handler

## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The callback onChange code when an event is typed comes back like this

onChange(event)

but when a default value is set, it is called like this

onChange('',defaultValue)

Here's my workaround to handle both cases
 <TableToolbarSearch
            defaultValue='mydefaultvalue'
            onChange={(event, defaultValue) =>
              onApplySearch(defaultValue || event.currentTarget ? event.currentTarget.value : '')
            }
          />

> Is this issue related to a specific component?
TableToolbarSearch

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.12.0

**Comment by emyarod** [comment]
@scottdickerson I believe I have a solution for this but just for me to further test and debug could you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox)?

**Comment by tay1orjones** [comment]
The default `handleOnInputValueChange` function in DataTable also checks for `event.target` or `defaultValue`

https://github.com/carbon-design-system/carbon/blob/0a1e7b5de5246efc94e5dc82ae8d4bf37c44c438/packages/react/src/components/DataTable/DataTable.js#L628-L636

**Comment by tay1orjones** [comment]
@emyarod here's a reduced test case: https://codesandbox.io/s/sweet-dubinsky-nhu8m The values are output to the console
- Click the button to programmatically set `defaultValue`, the event is `''`
- When you type into the input, the event is the full event object.

EDIT: Honestly, you could argue that this is a feature - a way to assess if the update is from a defaultValue or typing in the input. I think it would make more sense for event to be `undefined` instead of an empty string though.

One additional thing to note - The TableToolbarSearch does not update when a new defaultValue is passed in, it's only read once at creation. In the example I had to key the component based on the defaultValue to get the button to work.

**Comment by emyarod** [comment]
I've lost a lot of the issue context over the last 2 months so just to clarify:

no action is needed for the `onChange` handler regardless of whether or not a `defaultValue` is specified right? since no event object would be available if a default value is being used. is the callback function signature fine as is? (aside from maybe using null/undefined rather than empty string in place of the missing event object)

regarding the note about updating when a new `defaultValue` is used, I believe the method with using a key is the correct method since `defaultValue` is only read on component mount IIRC (https://github.com/facebook/react/issues/4101#issuecomment-111307019).

**Comment by tay1orjones** [comment]
Correct, and yeah I personally feel that the signature is fine as is with maybe the change to undefined/null instead of empty string for the missing event object.

Thanks for the response regarding the `key` too, that was confusingly tied up in a related bug in our repo but we got the clarity needed through the related PR #6517 and then fixed on our end https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1406
