### ISSUE TITLE
Carbon build time problem

### ISSUE THREAD

**Issue by baeharam** [carbon-design-system/carbon#6161]
When I develop with `yarn start` which executes `react-scripts`, starting duration is slow. So, I wanna improve this speed. I analyzed chunk size with `webpack-bundle-analyzer` and knew that Carbon is occupying lots of capacity. Then, Is this the problem of Carbon? How can I improve starting time? I searched for many issues and saw that Carbon components use CommonJS module system which hinders tree shaking of webpack. Is it right? How can I improve?

**Comment by joshblack** [comment]
Hi there, @baeharam! 👋 

For our projects, we do export ESM for folks using bundlers. Most likely what you're experience for build times is a slow sass compilation time. Unfortunately, for projects using webpack this tends to be a slow experience because of `sass-loader` and there isn't much we can do about that.

There are a couple of tricks to help alleviate the problem, namely:

1. Split out vendor style imports in your JavaScript from product imports

```js
import './vendor.scss';
import './my-styles.scss';
```

You can then place the references to `carbon-components` in vendor, and changes to your project can happen in `my-styles` (or in other sass imports). This will split out what needs to get recompiled when webpack detects a change.

2. Optimize how you bring in Carbon

There are a couple of tricks for optimizing build times with Carbon that you can look at over here: https://github.com/carbon-design-system/carbon/blob/master/docs/guides/sass.md#optimizing-your-sass-builds

Hope this helps!

**Comment by baeharam** [comment]
@joshblack 
Thanks for your answer! I have several question.

1) I didn't understand the meaning of first method, you mean `@import @carbon/elements/scss/elements` is not recommended?
2) In second method link, code imports `carbon-components/scss/globals`, but I'm using `@carbon/elements/scss/elements`. What is the difference?
3) I'm using several icons, but the number of icons are less than 20. However, when I analyze with `webpack-bundle-analyzer`. It has lots of capacity. What is wrong with me?
<img width="1440" alt="스크린샷 2020-05-30 오후 12 24 49" src="https://user-images.githubusercontent.com/35518072/83318504-92229c00-a270-11ea-9775-a4175ddef70d.png">

I'm solving 3) issue and I'm using CRA and **why all icons are imported even when I use single icon?** Also, when I use single icon like `import Search16 from '@carbon/icons-react/es/search/16';`, it cannot search type for this icon. How can I solve type?

Typing error!
>Could not find a declaration file for module '@carbon/icons-react/es/search/16'. '/Users/haram/haram/github/my-project/node_modules/@carbon/icons-react/es/search/16.js' implicitly has an 'any' type.
  If the '@carbon/icons-react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/carbon__icons-react`

**Comment by joshblack** [comment]
Hey there @baeharam! 👋 

Thanks for clarifying, importing elements as you have noted totally is fair 😄 

For the specific messages that you're bringing up, it seems like it may be an issue with TypeScript.

For bundling problems, it seems like some part of the setup is causing the module not to be tree-shaken. In a stock create-react-app, you'll find that the icons package end up getting tree-shaken. It would be worth trying to apply configurations on top of a default project to match to see where the mismatch occurs.

**Comment by joshblack** [comment]
Going to close this one out, feel free to comment and I can re-open!

**Comment by rla** [comment]
Related: #4882 

Type definitions refer to lib (non-esm) version: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a9a5d93c87e7cc8ae4c8cf21e9ccc1688fc636d5/types/carbon-components-react/index.d.ts

This is the reason why Typescript cannot find the types and VS Code cannot show usable intellisense.
