### ISSUE TITLE
React datepicker minDate has wrong propType

### ISSUE THREAD

**Issue by johnjesse** [carbon-design-system/carbon#6174]
## React datepicker minDate has wrong propType 

- [x] `react`

## Detailed description

- The d.ts file for the date picker allows "Date | string | number" for the minDate prop whereas the required propType in the react code is "string" - one of these is clearly wrong. When I provide a "Date" as the minDate prop it works - but I get a big console error stating I've used the wrong prop type

I haven't checked but I suspect the same is true for the maxDate prop too.

**Comment by emyarod** [comment]
the type definitions are independently maintained, and I believe you can open this issue against [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by johnjesse** [comment]
I can do that - I'll close this then

**Comment by petersandor** [comment]
Flatpickr does support `Date` object in `minDate`, so why is it restricted to `string` only here? https://github.com/carbon-design-system/carbon/blob/7be55cd74d0aaf522751e22c53ed45555f1d6964/packages/react/src/components/DatePicker/DatePicker.js#L245-L248

We get a prop type check warning for no reason since supplying `Date` object still works.
