### ISSUE TITLE
New Filter Enhancement

### ISSUE THREAD

**Issue by ChandanBhat07** [carbon-design-system/carbon#6209]
**Summary**
A module window, where a user is able to filter a large set of data.
Accommodating a large data set in a module, where the user is able to filter them.
For both design and development.

**Justification**
A piece of huge data information is ingested in the application. To accommodate it in a format where the user is able to find or filter them easily without any loss of those data.

**Desired UX and Success Metrics**
User Experience: Once the user decides to use the Filter function, the user clicks “show more” and a window pops up. In this module, the user is able to multi-select, search, and can further filter alphabetically.
       Metrics: Above 75%

**“Must have” functionality**
On click Show more, a window pops up. Further filters alphabetically. Dynamic search.

**Specific timeline issues/requests**
Before Q4. This is a part of a release.
[Filter window.pdf](https://github.com/carbon-design-system/carbon/files/4742112/Filter.window.pdf)

**Comment by ChandanBhat07** [comment]
Hello team, Please let me know if further more information needed in terms of validation. Since this is my first time, it would be great to know the process as well.

**Comment by ChandanBhat07** [comment]
I am adding an Invision prototype as well. 
[https://ibm.invisionapp.com/share/EJO026QZMNF#/319550079_A05](URL)

**Comment by aagonzales** [comment]
@ChandanBhat07

Thanks for submitting. At this time we feel that this component is not universal enough for the common component library (we also haven't built any basic filter components at this moment either). That said we think you could easily build this using the existing passive modal and other components from the library.

You are also welcomed to submit this pattern as an addition to the [filtering pattern](https://www.carbondesignsystem.com/patterns/filtering) which are more design guideline based and normally don't have supported code (from the common level). 

We did have a few ux concerns about the pattern as well. Have you concerned using pagination in the model instead of a horizontal scroll? Have you seen this type of pattern elsewhere, is it normal for these filters to horizontally scroll?

**Comment by ChandanBhat07** [comment]
@aagonzales 

Yes. Most of the patterns had a horizontal scroll rather than having pagination. If, to submit to the filtering patterns, what actions are to be taken? Can you please guide me.

**Comment by aagonzales** [comment]
You will need to write up the content and provided any images. It would be added to the [filter page ](https://www.carbondesignsystem.com/patterns/filtering/#selection-methods)as a new "selection method" and should follow the same format as the other methods. You can submit the content in a PR or you can post the content here for review.
