### ISSUE TITLE
Date formats in Carbon guidance should follow IBM Style standards

### ISSUE THREAD

**Issue by jwsese** [carbon-design-system/carbon#6216]
I noticed, while looking for something in the Carbon Design System, that the date formats on the [Date picker page](https://www.carbondesignsystem.com/components/date-picker/usage) don't match [IBM Style's rules for date formats](https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W580a84a67242_4da6_81cf_69e3db4bdbfa/page/Dates%20and%20times?section=General%20guidance%20for%20dates). This could be confusing if an IBM content person like me is coming to the Carbon site for date formatting guidance. Please change your Carbon example dates to follow the format defined in IBM Style. This format is esp. useful for preventing confusion in countries where the day comes first (and not the month) in a date formatted like this: 04/08/20 (US = April 8, 2020; elsewhere = Aug. 4, 2020).

thanks!

**Comment by tw15egan** [comment]
cc @carbon-design-system/design should we update `DatePicker` examples and placeholder to this format (not sure what placeholder text would look like)?  

<img width="332" alt="Screen Shot 2020-06-08 at 1 47 29 PM" src="https://user-images.githubusercontent.com/11928039/84063175-7a849b00-a975-11ea-8e29-51bdad5f52cd.png">


We would simply need to update the default Flatpickr `dateFormat` to `n F Y`
(https://flatpickr.js.org/formatting/)



There is also this paragraph in the documentation that states 

>Exception: Use of an all-numeric representation is allowed when space is limited, as in a user interface, or when doing so greatly enhances readability. For example, a table that specifies a date in one of its columns might be easier to scan and sort visually when the units (year, month, day) are all numeric.




The current implementation does support [localization](https://flatpickr.js.org/localization/) so that confusion for users across the world is reduced, i.e someone in Europe would see DD-MM-YYYY as long as the correct locale was provided by the developer
