### ISSUE TITLE
AccordionItem uses `title` as string, but listed as type 'node'

### ISSUE THREAD

**Issue by jhpedemonte** [carbon-design-system/carbon#6235]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Recent changes to `AccordionItem` have started to use the `title` prop as a string value. However, it's listed as type `node`. Leads to DOM like this:

```html
<button aria-controls="accordion-item-1" aria-expanded="false"
  class="bx--accordion__heading" title="[object Object]" type="button">
```

## Steps to reproduce the issue

```javascript
const titleNode = (
  <div>This is a title</div>
);
return (
  <AccordionItem title={titleNode}>content</AccordionItem>
);
```

**Comment by tombrunet** [comment]
Note - can see the problem with this here: https://react.carbondesignsystem.com/?path=/story/accordion--default
When you hover over the 4th item, which contains html in the title, the hover tooltip shows "[object Object]". Since the title attribute is already shown as the main content of the AccordionItem, I'm not sure what good it does to provide that same content in the tooltip.

**Comment by tw15egan** [comment]
Yeah, it seems like this prop has a confusing name, it should probably be named something like `accordionHeading` (we can tag this for a prop rename for v11).

Should we simply stop setting the `title` attribute by default on these elements to resolve this issue? It doesn't seem to be providing much value.

**Comment by tw15egan** [comment]
ref https://github.com/carbon-design-system/carbon/issues/4356
