### ISSUE TITLE
[React-Button] It could be better to add an optional delay on the tooltips of the button.

### ISSUE THREAD

**Issue by miniwangdali** [carbon-design-system/carbon#6303]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary
I hope there is an attribute to delay the tooltip showing after the mouse hovers on the button.
Sometimes, it's annoying to show the tooltip immediately.

### Justification
we are making a rich text editor in Watson Assistant tooling.

### Desired UX and success metrics

The icon-only buttons in the toolbar show tooltips immediately after the button gets hover.
It can be annoying in an RTE or rich text input, especially if a user gets familiar with the editor.

### "Must have" functionality
an `iconDescriptionDelay` attribute in the Button component.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

None.

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by miniwangdali** [comment]
I currently implement this by overwriting the CSS classes. I don't know if that is an anti-pattern to implement the same effect... If that is the correct way to do so, please confirm and I will close this issue. Thanks a lot.

**Comment by aagonzales** [comment]
Hello @miniwangdali ! Thanks for inquiring about this. The appearance time of the tooltip is intentional for icon-only buttons and we will not be increasing the delay. Many icons may not be intuitively understood by users. While some people may see it annoying that it appears instantly other users who need help understanding the icons may find it annoying to have to repeatable wait for a tooltip to appear. Having it appear instantly is the more inclusive experience.
