### ISSUE TITLE
The underline for the link should connect as one

### ISSUE THREAD

**Issue by gengjw** [carbon-design-system/carbon#638]
When we set the hyperlink in our env, we found the underline of the link is discontinuous when met the descenders as below:
![image](https://user-images.githubusercontent.com/9087841/37016342-b0817192-2146-11e8-91ab-00f43f2a3741.png)
And we found the same problem occurs in other bluemix env. also.
This problem may could be solved by change the css style of by setting the "text-underline-position" from "auto" into "under". Pls have a check and help to solve it, thx.

I could provide another page address and you could found the underline discontinuous of the last link in the letter "g". I think this is a common issue in all IBM Cloud productions:
https://console.bluemix.net/catalog/services/cloud-object-storage?taxonomyNavigation=vmWare
![image](https://user-images.githubusercontent.com/9087841/37016349-bceed9d8-2146-11e8-8dac-1ca761081c36.png)

 I could found another solution in the docs, where they using border bottom instead of the underline.But this style is only setted in the docs. I think it need to be unified in our productions:
https://console.bluemix.net/docs/services/vmwaresolutions/index.html#gettingstarted
![image](https://user-images.githubusercontent.com/9087841/37016362-c5dbc2ae-2146-11e8-8202-3241680fdc38.png)
![image](https://user-images.githubusercontent.com/9087841/37016366-c7f152fc-2146-11e8-927a-dd1b223d6320.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design Does this seem like a valid change?

**Comment by tay-aitken** [comment]
I'm noticing that  when you use `text-underline-position:under;` the underline does not change colors on hover, only the text does. Whereas when its `text-underline-position: auto;`, the way we currently have it, the underline changes color on hover. Is there a way to maintain this hover while it is still using `text-underline-position:under;`?

**Comment by bsonefeld** [comment]
Concerned about browser capability - looks like `under` is only supported in Chrome at the moment

_Ref_: https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position

**Comment by mven** [comment]
Hi - the effect you see behind the descenders is a Safari/Chrome (Webkit/Blink) specific feature that's built into their respective rendering engines. I believe this was originally implemented to increase legibility for various character sets. 

The way the docs example is handling an underline is somewhat hacky (using a border-bottom) and is not advised as it's always best to let the browser handle this type of stuff, instead of trying to force things.

If there's a real need to turn this effect off, then there's a way to do this in the browsers that enable it:

In Safari, you'll need to set `-webkit-text-decoration-skip: objects;` in the CSS declaration block. 
In Chrome: `text-decoration-skip-ink: none;`.

Some historical discussion on Chromium's implementation: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/47BHtmz0jVY/itAC_xpwBgAJ

**Comment by tw15egan** [comment]
I agree with @mven, I'd rather let the browser handle things like this
