### ISSUE TITLE
Change accordion title and area-label

### ISSUE THREAD

**Issue by reinisg** [carbon-design-system/carbon#6436]
Hello!
I have a question about react accordion component. I`m using accordion component as it's mention [here](https://react.carbondesignsystem.com/?path=/story/accordion--default). But there are no parameters with which change text on tag's title and aria-label field. 
Here is the screenshot, which text I need to change.
![image](https://i.ibb.co/NjhSfyb/carbon-acc-titles.png)

Is there any accordion component parameter which could change texts?

Regards, Reinis

**Comment by tw15egan** [comment]
Can you try updating to the latest version? We've changed this component a little bit and it might resolve these issues. The title is no longer set, since the text will always be visible, and we no longer set any aria-label on the SVG

![Screen Shot 2020-07-10 at 11 31 33 AM](https://user-images.githubusercontent.com/11928039/87186797-f2115700-c2a0-11ea-9658-7c9e09fdb0d6.png)

**Comment by reinisg** [comment]
Yes, this did a magic trick and removed those labels. Thanks! 😃 
Updates:
`carbon-components 10.11.2 -> 10.15.0`
`carbon-react-components 7.11.3 -> 7.15.0`
