### ISSUE TITLE
Warnings on build for feature-flags grid-columns-16

### ISSUE THREAD

**Issue by greenisagoodcolor** [carbon-design-system/carbon#6453]
- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

Hello, upon building our package with NPM,  we are seeing this warning. Should we remove grid-columns-16? What is the future of this setting in the features-flags? 

```
our use is in styles.scsss 
$feature-flags: (
  grid-columns-16: true
);
$carbon--theme: $carbon--theme--rg;
@include carbon--theme();
```

We encounter this message
```
14:41:59.140  
WARNING: Usage of non-default feature flags was found: grid-columns-16. Feature/code under non-default feature flags are either experimental, deprecated, or support for edge cases. They are subject to change any time. Use them at your own risk.
14:41:59.140  
         on line 193 of styles.scss, in function `merge-feature-flags`
14:41:59.141  
         from line 203 of styles.scss
14:42:22.701  
Compiled successfully.
```

should this be not included? is this a concern?

## Steps to reproduce the issue

1. Step one

Use feature-flags grid-columns-16: true in styles.scss

2. Step two

try to build package (npm build)

3. Step three
encounter warning

**Comment by greenisagoodcolor** [comment]
Has anyone else encountered this issue on build?

**Comment by joshblack** [comment]
Hey there, @greenisagoodcolor! 👋  Currently `grid-columns-16` is a feature flag that is enabled for teams that want to use 16 columns instead of 12 columns. Unfortunately, during our migration from v9 to v10 we needed to have the default set to 12 columns since most teams were still using 12 columns during release. As we move towards our next major release, we'll update to 16 and you won't have to worry about this warning any more!
