### ISSUE TITLE
javascript API in documentation

### ISSUE THREAD

**Issue by rccc** [carbon-design-system/carbon#6472]
Hello,

I like the Carbon design sytem very much but the documentation is not as clear as what we can found on Bootstrap :

**there is absolutly no documentation on the JS API !**

This is crazy guys, as your product is really beautiful, how can you let us with no API documentation ?

**Comment by rccc** [comment]
Re,

Crazy, i found this [link](http://v7.carbondesignsystem.com/components/modal/code) for the V7 with all the JS APIs documented !

The new website do not have these documentation.

Cheers
Eric

**Comment by AlanGreene** [comment]
@rccc The equivalent page to the one you mention can be found here for Carbon v10 (current version): https://www.carbondesignsystem.com/components/modal/code

All of the components have a 'Code' page showing code examples. They also have live demos for different variations of the components by setting the modifiers, changing theme, etc. For some components this live demo can be found on the 'Usage' tab.

They also provide links to the Storybooks for the React, Angular, and Vue implementations, and a similar site for the vanilla JS implementations.

As a user I've found these resources to be very helpful.

**Comment by joshblack** [comment]
Hey there! 👋  I apologize if things have been confusing for the JavaScript API of the project. In the past, as you noted, there was a VanillaJS implementation that was exposed on the site. Now, the project's primary focus is React and we use the Storybook for documenting behavior and APIs (with an update coming soon!)

Unfortunately, with all the various frameworks implementing the design system, we opted to these storybooks instead of inlining one particular framework's API on the page. Hope this helps!
