### ISSUE TITLE
Pagination overflow on smaller viewports

### ISSUE THREAD

**Issue by atikenny** [carbon-design-system/carbon#6540]
## Pagination overflow issue

On smaller viewports the pagination overflows its' container.

## What package(s) are you using?

- [x] `carbon-components-react` - 7.15.0

### Expected result

The pagination is visible and if overflowing then scrollable on smaller viewports.

### Actual result

The pagination is overflowing its container.

## Steps to reproduce the issue

1. Include the pagination in a container that is smaller so that it overflows
2. Make sure that you are above 42rem (that is when the overflow is set to visible)

See example here:
https://codesandbox.io/s/carbon-pagination-overflow-issue-zt71k

### Screenshots

Codesandbox:

<img width="658" alt="Screenshot 2020-07-24 at 14 06 06" src="https://user-images.githubusercontent.com/6061509/88389471-dc2e8680-cdb6-11ea-9dcd-3c3bd19ceb13.png">

IBM Cloud:

<img width="671" alt="ibm-cloud-pagination-overflow-bug" src="https://user-images.githubusercontent.com/6061509/88389617-1a2baa80-cdb7-11ea-96c3-eed9fc915ec0.png">

**Comment by tw15egan** [comment]
Since you're setting such a small width on the container, you may just need to override the `overflow` property in this scenario. 

You can set it to `overflow-x: scroll` at a much lower breakpoint (or all the time, if you want), but we didn't set this at the Carbon level because the button tooltips do not render when the overflow is set to scroll.

**Comment by atikenny** [comment]
Thanks @tw15egan for the quick response, unfortunately anything below 650 causes the same issue. Things potentially could get worse if the language is not as "short" as English is. I imagine if I overwrite the overflow property I will also lose the button tooltips, which is not ideal. Is there a way to make this component "smaller container friendly" without losing the tooltips?

**Comment by atikenny** [comment]
While writing the previous comment I haven't realised that the component does lose the tooltips on smaller viewports (below 42rem). Therefore it is actually the intention that we don't show them when there is not "enough space". @tw15egan please correct me if I am wrong.

**Comment by tw15egan** [comment]
The only thing we can really do is lower the breakpoint, but even then it would probably be better to do this at the application level where you have a better knowledge of what exactly will be contained in the pagination. Unfortunately, with the way absolute positioning works, you lose the tooltips whenever there is an `overflow` property. A `y` overflow could be added, but then you'd have a vertical scroll bar and potential to cause more visual issues than it would help. Since the scrolling is mainly a mobile fix, and hover tooltips would not be shown anyways, we felt this trade-off would be acceptable. 

Happy to take a look at any PR's you would like to submit to try and handle this at the Carbon level, though.
