### ISSUE TITLE
Guidance on basic usage of carbon packages

### ISSUE THREAD

**Issue by maxjowett** [carbon-design-system/carbon#6586]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Summary

I'm working as a developer for small company and we've recently decided to adopt carbon as our preferred framework. 🚀

I'm having a difficult time navigating documentation, it is overwhelming looking for answers when the pieces of information are scattered across many different pages, and often times have either vague, or conflicting information.

What is the preferred method to make use of packages like `@carbon/themes` or `@carbon/type` for a React project?

[carbondesignsystem.com/guidelines/themes/code](https://www.carbondesignsystem.com/guidelines/themes/code) makes it very clear that if you're using `carbon-components`, there is no need to separately install `@carbon/themes`. The page suggests instead referring to [carbondesignsystem.com/get-started/develop/react](https://www.carbondesignsystem.com/get-started/develop/react) which as far as I can tell, offers no guidance on how to use themes. I figure I must be looking in the wrong place, navigating back to [carbondesignsystem.com/guidelines/themes/overview](https://www.carbondesignsystem.com/guidelines/themes/overview) there are some useful code snippets that give me the impression I can import a theme like so:
```
@import "@carbon/themes/scss/themes";
// Use the gray 10 theme
$carbon--theme: $carbon--theme--g10;
@include carbon--theme();
```

Again, I find myself questioning whether or not I need to install `@carbon/themes` or not.

Did some digging around in closed issues and found #6088 which @joshblack suggests this approach:
```
@import '~carbon-components/scss/globals/scss/theme';
```

This works! I feel like I must be not looking in the right places, surely this is documented somewhere? Where?

Moving forward, when I want to reach for the `colors` or `type` packages, do I take the approach below?
```
@import '~carbon-components/scss/globals/scss/<package>';
```

## Relevant information

Becoming frustrated I figured I should take a step back, and run through the [React tutorial](https://www.carbondesignsystem.com/tutorial/react/overview). Once I've installed the necessary dependencies and fire up localhost, I reach for some basic components and they work great. Scrolling down the end of [Step 1](https://www.carbondesignsystem.com/tutorial/react/step-1), I learn that `The UI Shell has experimental status at the moment.` and it is not recommended for production environments.

How would one become aware of this information looking anywhere else? All documentation for `carbon-components-react` point to the [Storybook](https://react.carbondesignsystem.com/). Conveniently, components like `Toolbar` and `Pagination` are both flagged as either deprecated or unstable. Which is helpful in indicating they are likely unsuitable in production environments. Yet - `UIShell`, to someone like myself looking to get up and running, looks to be fully supported.

Again, I find myself in a position where either I'm looking for documentation in the wrong places, _or_, the only indication that `UIShell` is an experimental component is buried at the bottom of a page in the tutorial?

If the latter is true, it would seem to me that there is a larger problem here with documentation. However if there is some documentation that I could benefit from I would appreciate being directed that way.

Sorry for the long read, any guidance would be appreciated.

**Comment by joshblack** [comment]
Hi there @maxjowett! 👋  So sorry about the delay in response, really appreciate you taking the time to write this out and share your experience trying to use the library.

Definitely agreed, this stuff is not well documented or things are out-of-date. We're still trying to figure out how to tackle the scope of the project and make sure that everything stays connected as the status of work changes. I think you're also catching us in a weird midde-ground with `carbon-components` itself. The project itself has definitely outgrown how it was structured in 2015. As a result, we want to simplify how to include the elements as you noted and make the Sass imports predictable (and documented!) for type, themes, etc.

For the questions that you had shared, I would say that you are spot on with the current practice of importing entrypoints off of `carbon-components/scss/globals/scss/<entrypoint>`, some entrypoints are clear while others might not align with the elements packages that you mentioned.

Let me know if you have any other questions, or just want to chat to talk more about your experience using the project, I'd love to learn more and see what the gaps are so that we can make this experience less frustrating for folks in the future. Thanks again for taking the time to write this up, it was incredibly informative and very much so appreciated 🙏

**Comment by maxjowett** [comment]
Thanks for the response @joshblack 

Some remaining questions/gaps:

1. Is UIShell experimental or not?
2. Is conditionally rendering content in a `DataTable` row possible? I also opened #6655 about this specifically.
3. I'm finding it really difficult to pull up code for certain components. As I scroll through each `DataTable` story, clicking 'Show code' results in the following:
<img width="1604" alt="Screen Shot 2020-08-12 at 3 20 37 PM" src="https://user-images.githubusercontent.com/33435443/90074216-96772680-dcaf-11ea-9e41-bcc53242d142.png">
Is this the intended behavior?

**Comment by joshblack** [comment]
Hey @maxjowett! 👋 

> Is UIShell experimental or not?

Should be stable! Going through the project and removing references to experimental now 😄 

> Is conditionally rendering content in a DataTable row possible

Yes, it should be! For Data Table you should be able to programmatically filter rows and their content

> I'm finding it really difficult to pull up code for certain components

Definitely agreed, sadly storybook isn't inlining the code that we use for these stories. This is a current item that I'm working on this week for data table over in: https://github.com/carbon-design-system/carbon/issues/6631

**Comment by tw15egan** [comment]
Closing as resolved, if you feel that isn't the case please feel free to reopen!
