### ISSUE TITLE
Primary button inner border has wrong color in dark themes

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon#6636]
originally reported by @laurenmrice 

![image](https://user-images.githubusercontent.com/8265238/89684431-07899900-d8c0-11ea-8205-f1de5238e778.png)

**Comment by laurenmrice** [comment]
For example:  The transparent inset space on focus will show the background color the button sits on.
<img width="865" alt="Screen Shot 2020-08-26 at 2 06 41 PM" src="https://user-images.githubusercontent.com/43969356/91348788-ebd02f00-e7a9-11ea-98d9-e33a3f45c932.png">

**Comment by tw15egan** [comment]
I believe this is working as expected, we recently changed it to `ui-background` because `transparent` would cause the background to extend https://github.com/carbon-design-system/carbon/issues/7025#issuecomment-707320476, not actually be transparent due to the nature of the box shadow. It is currently set to `ui-background` in all themes and was bundled in this PR: https://github.com/carbon-design-system/carbon/pull/7029

Going to close this as resolved and based on @laurenmrice's feedback in #7029, but let me know if there are any other issues with `Button` 👍
