### ISSUE TITLE
How can i sort all the pages in React DataTable? by default it sorts only the current one.

### ISSUE THREAD

**Issue by shubh1608** [carbon-design-system/carbon#6763]
## What package(s) are you using?

- [ 9.62.1 ] `carbon-components`
- [ 6.61.1 ] `carbon-components-react`

## Relevant information
We are using React DataTable with Pagination and Sorting Enabled. Right now for sorting all the pages, we are using the custom sort function on sortRow prop and then we are updating the table by sorting the whole list and rebinding it to the table by updating the state. 

This is not a good solution as the custom sort function is not meant to use like this, it should return -1, 0, or 1 as mentioned in the documents, but we are using it to sort all the pages as I mentioned before. 

This leads to some issues like the table not getting unsorted on the third row click as table is not able to preserve the initial row order because of our implementation which rebinds the whole list to the table on every header click.

I am looking for an ideal solution to sort all the pages in a data table, not just the current one so that I can resolve the above issue.

**Comment by joshblack** [comment]
Hi there @shubh1608! 👋 

It seems like you may be using the previous versions of Carbon (v9 and v6) instead of the current versions of Carbon (v10 and v7) which might be causing some of the issues here.

Separately, definitely understand what you mean with the sorting behavior. Could you share a [codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) example of what you're trying to accomplish and we can help out?

**Comment by fatima-afzal** [comment]
Facing a similar issue. I am using current versions of Carbon (v10 and v7). 

We have a complete list of items and we have enabled both, pagination and sorting, on it. When we click on the sort header it only sorts the current page and not all items in the table. Is there a way where sorting is applied to the entirety of the items in the DataTable rather than just the current page?
