### ISSUE TITLE
Accordion item does NOT respect open state

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon#6766]
We have an accordion with 2 items.
On each I set the open state (locally managed)

I find that this is not respected, only at loading time, 

I need to have only one open at each time, and not both open 

This behaviour probably happens because there is no useEffect on the open state (and is handled internally by the accordionItem)
```
 <AccordionItem
                  onHeadingClick={item => onAccItemClicked(0, item)}
                  title={<p
                    className="secretsPanel__accordion-title">{t('manageSecrets.table.secretInfoPanel.detailsHeader')}</p>}
                  open={selectedAccordionItem === 0}
                >

<AccordionItem
                  onHeadingClick={item => onAccItemClicked(0, item)}
                  title={<p
                    className="secretsPanel__accordion-title">{t('manageSecrets.table.secretInfoPanel.lifeSpan')}</p>}
                  open={selectedAccordionItem === 1}
                >

```

**Comment by joshblack** [comment]
Hi there, @alon24! 👋  Unfortunately, the `AccordionItem` component is not strictly controlled or uncontrolled. Due to legacy implementation, the way that it works is that if the `open` prop _changes_ then the internal state of the component is updated. It doesn't stop the internal state from changing, however.

This behavior is definitely a frustrating one that we've had to work with, and it will be changed in our next major release 👍
