### ISSUE TITLE
Accept prop is not working in fileUploader component on windows [bug]

### ISSUE THREAD

**Issue by shikha-pixel** [carbon-design-system/carbon#6864]
Sandbox link: https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/drag-and-drop-file-uploader
![image (1)](https://user-images.githubusercontent.com/67314998/93764225-60bf4900-fc30-11ea-97f4-0f7b6c32f750.png)
Though in the code it is mentioned that supported extensions are only "jpeg" or "png". I am still able to select .txt file in the File Upload component.
FYI: This issue is only visible in windows operating system, but works as expected in MAC.
Version: "carbon-components": "10.20.0",
    "carbon-components-react": "7.20.0",

**Comment by emyarod** [comment]
we determined on Slack that this is not an OS specific component issue and is instead due to you selecting the option to allow all file types to be selected 

![image](https://user-images.githubusercontent.com/8265238/93793432-6ef37200-fbfc-11ea-8151-cc22daa6804b.png)

![image](https://user-images.githubusercontent.com/8265238/93795560-2e492800-fbff-11ea-87a6-91607f2ee2fc.png)

The workaround would be to not select the option to choose all file types in your OS's native file chooser dialog, and to implement the validation logic in your application (where the file size validator logic is in the code sandbox and storybook examples)
