### ISSUE TITLE
Windows High Contrast Mode support for Firefox🦊 and Edge👔

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon#6869]
Background: https://hacks.mozilla.org/2020/07/adding-prefers-contrast-to-firefox/

[In the past Carbon Components did not support Windows High Contrast Mode](https://github.com/carbon-design-system/carbon/blob/master/docs/on-windows-hcm-support.md) (WHCM) for Firefox due to technical limitations. Firefox version 80 has added a media query `prefers-contrast` that will allow us to address inconsistencies and visual accessibility errors in Windows High Contrast Mode moving forward. At time of writing (September 2020) the media query is a [preference the user must enable](https://groups.google.com/g/mozilla.dev.platform/c/bTEmQxffGvA?pli=1) in their settings while the spec and implementation are finalized by the CSS Working Group.

This epic will track our work against issues raised during a component by component audit of current WHCM support. 🏄

**Comment by wkeese** [comment]
According to https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/, Edge supports a `forced-colors` media query, and in the future will support `prefers-contrast`.   Since Firefox also already supports `forced-colors` (see https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors), that may be the way to go, instead of `prefers-contrast`.

**Comment by dakahn** [comment]
For now our current changes work. We can re-evaluate if the need arises though for sure @wkeese

**Comment by tw15egan** [comment]
Looks like all issues have been closed 🎉 👍🏻

**Comment by wkeese** [comment]
I guess you should update https://github.com/carbon-design-system/carbon/blob/main/docs/on-windows-hcm-support.md.
