### ISSUE TITLE
Determine changes in pictogram assets

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#6923]
The brand team has delivered a set of new pictogram assets that have been redrawn to support `fill` instead of `stroke`. We need to determine the scope of these changes in order to verify the following:

- What pictogram assets have changed? (For example, what has been renamed)
- What pictogram assets have been removed? What are they to be replaced with? (if anything)
- What pictogram assets are staying the same?

[Pictogram_Breaking_Change.zip](https://github.com/carbon-design-system/carbon/files/5293550/Pictogram_Breaking_Change.zip)

[Master_naming_update_091020.xlsx](https://github.com/carbon-design-system/carbon/files/5293566/Master_naming_update_091020.xlsx)

Using this information, we can coordinate a migration path for the affected assets when we release our breaking change.

**Comment by emyarod** [comment]
currently awaiting updated batch of pictograms following 2nd audit

**Comment by vpicone** [comment]
@joshblack @conradennis  So glad fonts are being exported as outlines now so they don't require Plex to be loaded on the page as a specific font-family.

I'm not sure what the audit @emyarod mentioned entails, but the SVGs should probably be exported with unique Object ids as well. Otherwise if someone puts multiple svgs on the same page, they'll get conflicting IDs. The `java` pictogram has a generic id of `Layer_1` for example.

We could do this during the build phase with `prefixIds for SVGO. However, this wouldn't help if folks download the source svgs. Also, I think we should try to do as much as we can in the illustrator export config rather than leaning on SVGO to catch and fix all the source file issues.

## Illustrator export
Presentational attributes and and Unique object Ids ensure we don't have collisions with other classes on the page.

![image](https://user-images.githubusercontent.com/4078018/95814600-5dbff180-0ce0-11eb-9ae5-b3e863829815.png)
