### ISSUE TITLE
Modal: Set default primary focus to something besides primary button

### ISSUE THREAD

**Issue by crhuff** [carbon-design-system/carbon#6939]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Currently the default focused button on a modal is the primary button if it exists. In situations where users are interacting quickly with the UI, they might inadvertently trigger the primary button event which could include things like deleting.

> Is this issue related to a specific component?

Modal that has `passiveModal = false`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Set default primary focus to be either the secondary button or close button.

> What browser are you working in?

Brave Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

carbon-components-react 7.21.0-rc.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Cloud IKS UI, no

**Comment by tw15egan** [comment]
You can change which element receives focus when the modal opens with the `selectorPrimaryFocus` prop. Take a look at this link for more info: https://react.carbondesignsystem.com/?path=/docs/composedmodal--title-only#focus-management

Hope this helps!

**Comment by finken2** [comment]
@tw15egan This is about having a logical default choice on the dialogs. Making the primary button the default seems less than optimal for a couple of reasons:
1) the user may accidentally submit the dialog
2) often times the primary button is disabled when the dialog is first rendered, either b/c some data is being gathered or there's some confirmation within the contents.  If the primary button is disabled, focus goes nowhere by default.

The suggestion here is to instead default to the secondary button.   We could still do a series of fallbacks:
selectorPrimaryFocus || secondary button || close button
That way we get a reasonable default and only have to pass in selectorPrimaryFocus in the unique circumstances that we need it.

**Comment by tw15egan** [comment]
Makes sense to me, seems like a sensible enhancement if we use the suggested series of fallback focus elements 👍

**Comment by asthas** [comment]
Hi,
 I want to claim this task? Please may I know if I can get started on this?

**Comment by tw15egan** [comment]
@asthas sure thing!

**Comment by asthas** [comment]
@tw15egan When try to push my changes I get the following error
`remote: Permission to carbon-design-system/carbon.git denied to asthas.
fatal: unable to access 'https://github.com/carbon-design-system/carbon.git/': The requested URL returned error: 403`

Please may I know how to resolve this
EDIT: Resolved (Forgot to fork 🤦‍♀️ )

**Comment by tw15egan** [comment]
@asthas I'd take a look at https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#start-contributing

**Comment by asudoh** [comment]
My personal perspective; `confim('foo')` JavaScript API (though it's effectively deprecated) puts focus on the OK button. Similar thing applies to Mac native dialogs, though it has a distinction between the default action (OK) vs. focused action (Cancel or others).

But I think it makes sense to focus on secondary button by default for danger modal, in a similar manner as how Mac handles user action of cleaning up individual files in trash.

**Comment by chrisconnors-ibm** [comment]
@crhuff, @finken2  -  If the secondary button has focus by default and receives the keyboard handler for return or enter, it is, by definition, the _Primary Button_.

More important than whether a secondary button should be the defacto Primary Button by intercepting the keyboard event that should be going to the Actual Primary Button by definition, but what action the design in question is assigning to each button. There's no reason the Primary button has to be action that confirms or takes the action the dialogs is referring to; **Primary does not have to always be confirmation**.

![image](https://user-images.githubusercontent.com/35537391/95115984-57e07400-0714-11eb-8449-3d4ce369babd.png)


![image](https://user-images.githubusercontent.com/35537391/95101466-2b226180-0700-11eb-8b76-fc7d58662f54.png)

Another approach you see is if the Primary button is something consequential or dangerous, it's not uncommon to add friction so that the likelihood of inadvertent  keyboard entry is reduced. You see this in patterns where user is forced to type a specific string before the dangerous or irreversible Primary Button is enabled.

**Comment by aledavila** [comment]
I'm going to close this issue as we have gotten no reponse. If you feel like there is additonal information we can look at reopening. Thanks!
