### ISSUE TITLE
Use of position relative has consequences for stacking context 

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#6948]
Position relative has consequences for stacking context, it should be used sparingly and perhaps not at all on components that might move around the screen on scroll.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
See here
https://codesandbox.io/s/fixed-carbon-button-3q26r

In this scenario, the button should scroll under the header and not over it.

> Is this issue related to a specific component?
Button but there may be others.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Where possible avoid use of position relative as per the 'fixed-button' css in the link above.

> What browser are you working in?
Chrome, firefox, safari

> What version of the Carbon Design System are you using?
10.20

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

See linked code

**Comment by joshblack** [comment]
@lee-chase trying to resolve this in our Sprint 7 and am taking a look today 👀 

It seemed like this would need to be a strict requirement on all components where their top-level wrapper cannot have `position: relative`. Is that correct?

This might be a difficult convention to enforce as some top-level components may need their content to be relatively position. In those situations, would the recommendation be to add in a wrapper div to reset it back to display: block?

**Comment by lee-chase** [comment]
I think a wrapper solves the problem @joshblack. The user should be able to dictate the display type of the wrapper without issue but block by default is fine

**Comment by joshblack** [comment]
Circling back on this, after talking with the team it seemed like something that will need to be tackled by the end-user 😞  We will definitely try and take this on as a convention but unfortunately can't dedicate time to addressing it now nor could we quickly use tooling to verify that components aren't following this practice.

Thanks so much for bringing this up though, @lee-chase. I wish I could give a better update but just wanted to share where we are right now.

Going to close this out since we won't be addressing this immediately, let me know if I'm missing something and should re-open!
