### ISSUE TITLE
Feature request: Pivot Tables

### ISSUE THREAD

**Issue by Pablodotnet** [carbon-design-system/carbon#6987]
### Summary

There are special tables with a complex behavior that are used on analytics, they are called Pivot tables, which are tables that it's content is controlled by filters and options that some of them are drag and drop.

### Justification

Analytics on IBM internal applications

### Available extra resources

https://github.com/nicolaskruchten/pivottable
https://github.com/flexmonster/pivot-angular
https://www.syncfusion.com/kb/11109/how-to-get-started-easily-with-syncfusion-angular-8-pivot-table

**Comment by aagonzales** [comment]
Hey @Pablodotnet! This feature is too unique for the Carbon common team to build. This would be a feature that your team would need to build and support on your own. Since it is about data manipulation the IBM Data Viz guild may be interested in this as well. We are closing the issue but we'd be willing to advise on design if needed. Let us know if you have any questions. Thanks!
