### ISSUE TITLE
[button] inset focus needs to be transparent

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon#7025]
For the `primary`, `secondary`, `tertiary` and `danger` buttons, the focus state should have a 1px inset transparent space from the 2px focus border.

Spec example:
![primary](https://user-images.githubusercontent.com/43969356/95779336-de0e3480-0c97-11eb-9d0a-ea07a722128c.png)

In the documentation on the style tab, I do see that `inverse-01` seems to be applied instead of a transparent space. Having an inset transparent space is the design intent.

**Comment by tw15egan** [comment]
@laurenmrice, since this effect is being created by a box-shadow, setting this to transparent would make the space created by the `inverse-01` to match the background color. 

![Screen Shot 2020-10-12 at 1 04 48 PM](https://user-images.githubusercontent.com/11928039/95785928-84077200-0c8b-11eb-8d18-3312c00ae635.png)

I believe background-color will always paint to the border, so I'm not sure of a workaround.

**Comment by laurenmrice** [comment]
In the dark themes right now, that inset 1px border is showing up as a color other than the ui-background and also not inverse-01
Ex:
![Artboard](https://user-images.githubusercontent.com/43969356/95787535-b58e3680-0ca7-11eb-9040-65e34836b42c.png)

**Comment by tw15egan** [comment]
Seems like its set to `ui-02`? Should we update it to `ui-background`?

**Comment by laurenmrice** [comment]
Yep, lets go with `ui-background`
