### ISSUE TITLE
DatePicker Range: calendar anchored to the bottom when inline=true

### ISSUE THREAD

**Issue by kwchan22** [carbon-design-system/carbon#703]
## Detailed description
When inline = true and static = true, the calendar is displayed at the bottom of the page. The calendar used to display under the range input selection. I think it's because the flatpickr instance is being added in the body document instead of inside the .bx--date-picker div. 

> Is this issue related to a specific component? 
Yes. DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?
The calendar should display below the range input.

> What browser are you working in? 
Chrome and Firefox

> What version of the Carbon Design System are you using? 
8.18.8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Watson Business Solutions - Expert Assist. 

## Steps to reproduce the issue

See https://codepen.io/kwchan/pen/mxNLWQ

## Additional information

<img width="346" alt="screen shot 2018-04-16 at 12 15 47 pm" src="https://user-images.githubusercontent.com/19690364/38821926-ee7df8fa-416f-11e8-9f14-e6d156f09341.png">

**Comment by asudoh** [comment]
Thanks @kwchan22 for reporting this issue! Seems that the Flatpickr's dropdown is located upon our hidden `<input>` instead of what we show as the UI. We'll see if we can make a reasonable workaround. Meanwhile if you have any insights feel free to contribute a fix!

**Comment by asudoh** [comment]
I have come up with [some workaround](https://github.com/asudoh/carbon-components/commit/2681af608fced691856b3fbae236f822a8bda471), but given the `inline` mode is for "sticking" date picker, I'd like to see whether our designers think it should be supported or not (CC @carbon-design-system/design). Here's what it looks like:

![date-picker-inline](https://user-images.githubusercontent.com/1259051/39229240-d8ad7fb2-489c-11e8-97ab-24853e656512.png)

**Comment by tay-aitken** [comment]
Akira could you elaborate more on what you mean by "sticking". I'm not following along.

**Comment by asudoh** [comment]
@tay-aitken Thank you for asking - Regular date picker is shown *only* when the `<input>` gets focus. The `inline` mode shows date picker *always* - That's why I meant by "sticking". Also the `inline` mode makes date picker takes up the space in the form - Meaning if there is another form item next to the `<input>` the date picker goes in-between the `<input>`s.

**Comment by tay-aitken** [comment]
Thank you for explaining! SO there would always be a gap between the input field and the calendar widget?

**Comment by asudoh** [comment]
@tay-aitken We can remove the gap. BTW another important thing to note about the `inline` mode is that the form element (e.g. `<input>`) next to the date picker input should be next to the calendar widget, instead of having calendar widget override such next form element - Otherwise there is no way for user to see such next form element because of `inline` mode’s “always-open” nature. Here’s the FlatPickr’s documentation about `inline` mode: https://flatpickr.js.org/examples/#inline-calendar
