### ISSUE TITLE
Datatable are missing focus frame borders with Safari brower

### ISSUE THREAD

**Issue by xiaolixu** [carbon-design-system/carbon#7049]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Datatable are missing focus frame borders with Safari brower

> Is this issue related to a specific component?

DataTable

## Steps to reproduce the issue

1. Go the story link https://react.carbondesignsystem.com/?path=/docs/datatable--usage with Safari browser
2. Try to focus several cells , you can see that some focus frame borders are missed.

## Additional information

- Screenshots 
<img width="1639" alt="Screen Shot 2020-10-14 at 1 53 56 PM" src="https://user-images.githubusercontent.com/24239504/96082958-caa8d680-0eee-11eb-948e-9beffa31d91f.png">

**Comment by tw15egan** [comment]
Since these are non-focusable data table cells, it makes sense that they do not receive focus styles. However, any element that can be tabbed to will receive focus when tabbed to.

![focus](https://user-images.githubusercontent.com/11928039/96162199-1b0f3c80-0ecd-11eb-8d2d-9f88a90cc04d.gif)


Keep in mind, you will need to enable this in your Safari settings

![Screen Shot 2020-10-15 at 9 58 54 AM](https://user-images.githubusercontent.com/11928039/96162146-0a5ec680-0ecd-11eb-97f0-947bd5934a48.png)
