### ISSUE TITLE
[component audit] data table bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon#7219]
**Code bugs:**
- [x] `tr` row hover should be using token `hover-ui` and not `hover-field`
- [x] ~In Safari, focus is not appearing on the column headers~ See TJs [comment](https://github.com/carbon-design-system/carbon/issues/7219#issuecomment-721407184) below
- [x] Disabled row styling is missing.
- [x] Zebra stripes: in the G90 and G100 themes the first row and the table headers are blending together. The first row should use the default color and the second row should use the zebra color. (we may need to re-evaluate this from a design perspective but this will resolve the main issue for now).
   ![image](https://user-images.githubusercontent.com/11670886/98048709-e1f32980-1df3-11eb-8f87-a8e7b55985e4.png)

**Visual bugs:**
- [x] Overflow menu: in G100 theme the menu blends into the table background.
   ![image](https://user-images.githubusercontent.com/11670886/98050464-5da2a580-1df7-11eb-93e0-967cdc357c1f.png)

Questions:
- Is the row of a data table supposed to be focusable? I cannot get it to focus in the storybook.
- Is disabling a row or the whole table possible?

**Comment by tw15egan** [comment]
Safari recenty changed how they handle focus so you may need to change your settings (Preferences --> Advanced)
<img width="793" alt="Screen Shot 2020-11-03 at 2 23 45 PM" src="https://user-images.githubusercontent.com/11928039/98047089-312f5f00-1de0-11eb-8bf7-259ea391bfd0.png">

Once I enable that, I'm able to get focus styles when I tab through elements. Chrome / Firefox / Safari all handle click focus differently (Chrome will show and keep focus on click, the others won't)
<img width="564" alt="Screen Shot 2020-11-03 at 2 23 34 PM" src="https://user-images.githubusercontent.com/11928039/98047284-85d2da00-1de0-11eb-890b-d9df20e9e9c2.png">


Rows can't be focused, only the focusable elements (since no action can be taken on a row). If you tab through a selectable row, the focus is on the input (since that is what is being checked / unchecked) 
<img width="1180" alt="Screen Shot 2020-11-03 at 2 24 04 PM" src="https://user-images.githubusercontent.com/11928039/98047127-3db3b780-1de0-11eb-8ebd-9b91b0c2c6cb.png">

**Comment by tw15egan** [comment]
Regarding the Overflow Menu, an end-user application would be able to use the `light` property to use the lighter variant of the menu when using the `g100` theme, but we don't have any way to specify a different variable per theme. We could turn on the `light` prop in the storybook, but we'd have that across all 4 themes

Reference if we use` light` in all themes:

<img width="257" alt="Screen Shot 2020-11-09 at 2 01 45 PM" src="https://user-images.githubusercontent.com/11928039/98601611-29663380-2294-11eb-8d4d-3c0642a7644f.png">
<img width="255" alt="Screen Shot 2020-11-09 at 2 01 35 PM" src="https://user-images.githubusercontent.com/11928039/98601614-29feca00-2294-11eb-9560-bdbc6cd5e428.png">
<img width="239" alt="Screen Shot 2020-11-09 at 2 01 24 PM" src="https://user-images.githubusercontent.com/11928039/98601616-2a976080-2294-11eb-98a5-ed0ff2efc73e.png">
<img width="304" alt="Screen Shot 2020-11-09 at 2 01 07 PM" src="https://user-images.githubusercontent.com/11928039/98601617-2a976080-2294-11eb-9d54-725ed3b90d0e.png">



Also, do we need to update the value for `$data-table-column-hover` in the dark themes?
<img width="352" alt="Screen Shot 2020-11-09 at 1 31 56 PM" src="https://user-images.githubusercontent.com/11928039/98606074-5e29b900-229b-11eb-8ffc-59b7be9df49b.png">

**Comment by tw15egan** [comment]
Also regarding disabled styles, we allow the focusable inputs (selection, expansion, sorting) to be disabled, but there are no full row disabled styles. If we want to add that in it may be best to track that in a separate issue as an enhancement 👍

**Comment by aagonzales** [comment]
@tw15egan Turning on the `light` prop for the overflow I think would solve that problem. I'm ok with it being like that across themes.

And yes we need to update `$data-table-column-hover`. 
- G100: `#4C4C4C`  
- G90:  `#656565`

**Comment by tw15egan** [comment]
Looks like those values were already there, just some issue with my local build. Deployed preview is using the correct values 👍  Just made the rest of the changes
