### ISSUE TITLE
Accordion collapse icon looks like checkbox

### ISSUE THREAD

**Issue by jvystrcil** [carbon-design-system/carbon#722]
## Detailed description

After expanding the accordion component the collapse icon looks like checkbox and can be easily interpreted that way. 

> Is this issue related to a specific component? 
Accordion

> What did you expect to happen? What happened instead? What would you like to see changed?
Should not be confused with checkbox  

> What browser are you working in? 
Firefox

## Additional information

![image 2](https://user-images.githubusercontent.com/19201752/39195710-ab2a99d8-47e0-11e8-8f82-8871bd707698.png)
* Notes

**Comment by asudoh** [comment]
Thanks @jvystrcil for reporting! @carbon-design-system/design Do we think we need a `:focus` style that alleviate this issue? Thanks!

**Comment by aagonzales** [comment]
This focus style is consistent with how we do focus on other icons. We can certainly look into new focus styles if this continues to be an issue. @jvystrcil have you been getting user feedback that people are interpreting this as a checkbox? Because if users are repeated having issues than we will make this a higher priority to investigate and potentially change. 

Personally, I'm not overly concerned with this issue because the `enabled` state does not look like a checkbox which would be a problem. To get this state the user has to interact with it so they (assumption) should know its not a checkbox because of both the action it preforms/triggers and  its non-focused states.

**Comment by jvystrcil** [comment]
@aagonzales see it in motion on screencapture below. (just remove the `.zip` suffix)
[accordeon.mp4.zip](https://github.com/carbon-design-system/carbon-components/files/1955031/accordeon.mp4.zip)

In fact I am the only customer complaining so far - realized when testing our new UI. After accordion page renders when opening, I was wondering why they added that new `checkbox` there. The problem is when whole new portion of UI appears on screen and user needs to visually parse it again...

**Comment by jv81** [comment]
Was this issue tackled somehow?

**Comment by aagonzales** [comment]
I think its a non-issue with Carbon 10. The whole focus is around the whole item and not the chevron which should make it no longer look like a check-box.

![image](https://user-images.githubusercontent.com/11670886/57099703-b533f280-6ce2-11e9-9e64-65d97118da3f.png)
