### ISSUE TITLE
Browser Render bug due to subpixel svg

### ISSUE THREAD

**Issue by DusanMilko** [carbon-design-system/carbon#7236]
The menu svg at size 20 has a subpixel height of 1.2 which causes some browsers to render it using incorrect calculation.

https://github.com/carbon-design-system/carbon/blob/master/packages/icons/src/svg/20/menu.svg?short_path=25adf20

![Screen Shot 2020-11-05 at 6 34 01 PM](https://user-images.githubusercontent.com/302239/98311635-7ba60c80-1f95-11eb-96ae-f737a4ee69ae.png)

possibly test in the browser to see if 1.25 height renders better or 1.3. Or consider using 1 or 1.5

**Comment by joshblack** [comment]
Hey @DusanMilko! 👋 

Thanks so much for raising this, this is something that we're trying to coordinate with the brand team who owns the icon and pictogram assets themselves. I'll make sure to forward this along and see if they send a response your way 👍

**Comment by joshblack** [comment]
cc @conradennis

**Comment by conradennis** [comment]
@joshblack @DusanMilko Ok it looks like the current `Menu` icon is still using bespoke versions for its 16, 20, 24px sizes which is why the bars are 1.2px at 20px scale. If the `Menu` icon were to be scaled to 20px from the original 32px artwork the bars would be 1.25px, however they'd render a bit blurrier bc of how they sit on the grid.

Here's how the 20px size sits on the grid when downsized from 32px (left) and how the current bespoke 20px icon sits on the grid (right):

<img width="1071" alt="Screen Shot 2020-11-11 at 11 27 29 AM" src="https://user-images.githubusercontent.com/16782944/98837516-0b720d80-2411-11eb-9161-2c0f1d181c86.png">

**Comment by joshblack** [comment]
Just following up on this, it doesn't seem like something we can do much with given the current brand guidelines. Since this is a broader issue, let's roll this up into: https://github.com/carbon-design-system/carbon/issues/6575
