### ISSUE TITLE
Modal overrides the font-size of all its content

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon#7404]
Modal overrides the font size of its content using the  `.bx--modal-content` class.

![image](https://user-images.githubusercontent.com/6926228/101207459-a8a21980-363e-11eb-846b-7193b58966d2.png)

## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

I was trying to use a `h3` heading inside a Modal body, but hit an issue where the HTML heading doesn't change the font size. It looks like the `.bx--modal-content` class. is overriding all the font properties for anything in the Modal body. Is this by design? If so, what is the recommended way to have different heading sizes in a Modal body?

https://codesandbox.io/s/carbon-headings-ym43d

> What browser are you working in?

Chrome 87.0.4280.88 (Official Build) (64-bit)

**Comment by tw15egan** [comment]
I'm assuming you want more granular control over the headings, rather than using the `modalHeading` prop, [like so](https://codesandbox.io/s/carbon-headings-in-modals-forked-b6lpk)? 

@carbon-design-system/design , do we want to ease up the enforcement of setting ALL text inside a Modal body to `body-long-01`

Relevant code:

https://github.com/carbon-design-system/carbon/blob/ab61506d52a9e500c4408b83b6b43ce3a87494d6/packages%2Fcomponents%2Fsrc%2Fcomponents%2Fmodal%2F_modal.scss#L266-L268

**Comment by aagonzales** [comment]
Yes, I think its ok to add more flexibility over the type inside the content area.

*The modal title should never be modified

**Comment by Yohanna** [comment]
Hi @tw15egan,

> I'm assuming you want more granular control over the headings, rather than using the modalHeading prop, like so?

I'm aware of the the `modalHeading` prop, I just wanted another smaller heading inside the body to differentiate two different subsections in the Modal.
