### ISSUE TITLE
Enhancement: Add align prop in Inline Dropdown component 

### ISSUE THREAD

**Issue by krzysztofwcislo1** [carbon-design-system/carbon#7491]
### Summary

Inline dropdown could have **align** prop to set whether its menu would be aligned to left site or right site, in order to avoid extending beyond parent component.

### Justification
Dropdown's menu often extends beyond its parent component and in result extends width of page. So this change would be helpful to determine alignment of menu and avoid situations as presented on screen below.

![bez nazwy(5)](https://user-images.githubusercontent.com/76486585/102904730-6b2cf100-4472-11eb-9f48-663ef7b257e6.png)

**Comment by emyarod** [comment]
can you create a [reduced test case in Code Sandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox) for easier testing and debugging?

**Comment by yrue** [comment]
I have same issue when using inline dropdown, and can reproduce as below on storybook : https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline
![image](https://user-images.githubusercontent.com/5738032/110323301-63cbbb80-804f-11eb-8d88-8d233127936c.png) 

Looks can resolve by removing min-width as
![image](https://user-images.githubusercontent.com/5738032/110323614-cb820680-804f-11eb-9d44-dfaf1e26f1ea.png)

**Comment by abbeyhrt** [comment]
Hey @krzysztofwcislo1! You're definitely right that that inline looks way too big and thus misaligned. In v11, you can add a className prop to the Dropdown and change the min-width so that the Dropdown items are more spaced based on their content and won't look misaligned. Here is a code example showing how! https://stackblitz.com/edit/github-npjdcn?file=src/App.jsx
