### ISSUE TITLE
Modal Positioning

### ISSUE THREAD

**Issue by rscoates** [carbon-design-system/carbon#7532]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
Hi there,
I'm using the React-Carbon library to design a new part of a frontend for a client, and I'm having problems with the positioning of a modal. As you can see in the image below, clicking on the button in the table opens the modal (and makes the 'darkening' div visible), but the position of the modal isn't relative to where the viewer is currently looking. As a result, it looks as if the modal hasn't opened until you scroll up.

![modalgif](https://user-images.githubusercontent.com/9936693/104302711-09840380-54c1-11eb-98fc-c708e994eaa3.gif)

I don't know if this is intended behaviour, a bug, or something that I have to override. Grateful for any answers.

**Comment by rscoates** [comment]
I managed to solve this using `React.createPortal`, but I'd love to know if there's a simpler way.

**Comment by tw15egan** [comment]
Hey there @rscoates, thanks for reporting! Do you have a link to a reproducible example?

**Comment by kubijo** [comment]
@tw15egan 

I believe the root of this is in the fact that your modals don't use React portals… several problems then stem from it… the major one being z-index issues because they don't break out of the html context & stay where rendered.

I have solved this on our end by creating a wrapper component that manages the rendering through `createPortal` into one DOM node in the document body getting something akin to this:

```html
<body>
    …

    <div data-cy="modals-root">
        <div data-modal-mount="workspace_switch-user-dialog">…</div>
        <div data-modal-mount="funds_accounts_overview_create-dialog">…</div>
        <div data-modal-mount="funds_accounts_overview_pause-dialog">…</div>
        <div data-modal-mount="global_exports-dialog">…</div>
    </div>
</body>
```

----------------------------------

Is there a specific reason for not using portals on your end?

**Comment by tw15egan** [comment]
I believe we moved away from using React portals because it was introducing some a11y concerns, can't remember the exact issue but there is a relevant discussion with this and dropdown menus (https://github.com/carbon-design-system/carbon/issues/7565#issuecomment-786921600)
