### ISSUE TITLE
Button onBlur function is not working on Firefox

### ISSUE THREAD

**Issue by yonghuay** [carbon-design-system/carbon#8175]
## What package(s) are you using?

- [x] `carbon-components 10.31.0`
- [x] `carbon-components-react 7.31.0`

## Detailed description

> Describe in detail the issue you're having.

The Button onBlur function is not working on Firefox ESR

## Steps to reproduce the issue

1. Open the component in Firefox

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/stoic-hoover-euity?file=/index.js

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/32554015/112324274-86dea800-8caa-11eb-8991-594ba31bbde1.png)
![image](https://user-images.githubusercontent.com/32554015/112324290-8a722f00-8caa-11eb-86c1-1ce490a657b1.png)

- Notes
Works fine in Chrome

**Comment by emyarod** [comment]
I believe this is [intentional for Firefox on macOS](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus) in order to match macOS convention, but it has been resolved in future versions of Firefox starting in version 87 from what I can tell

![image](https://user-images.githubusercontent.com/8265238/112657398-633d6e00-8e20-11eb-9b03-5b0d22ac8cac.png)

this behavior also occurs in Safari (https://bugs.webkit.org/show_bug.cgi?id=22261)
