### ISSUE TITLE
Code snippet Show More button hides content

### ISSUE THREAD

**Issue by atikenny** [carbon-design-system/carbon#8249]
## Brief description
When there is overflowing content in the code snippet, the show more button hides some of the content.

## What package(s) are you using?

- [x] `carbon-components-react` `v10.31.0`

## Steps to reproduce the issue

1. Make sure that the content is near the Show More button.

## Additional information

<img width="801" alt="Screenshot 2021-03-31 at 8 49 12" src="https://user-images.githubusercontent.com/6061509/113102187-f9490e00-91fd-11eb-98d0-9551fbd3ad13.png">

**Comment by atikenny** [comment]
I have a fix for this as well that I can contribute.

**Comment by tw15egan** [comment]
cc @carbon-design-system/design for guidance

**Comment by aagonzales** [comment]
I believe we didn't see this as a problem because you can see the content once you open the snippet with the "show more" function. If the "show less" button is covering content then that would be a problem. 

@atikenny can you post a spec of the fix you are proposing? Are you increase the padding right or bottom?

**Comment by atikenny** [comment]
@aagonzales yes it is as simple as that.
