### ISSUE TITLE
[ContextMenu] clean up click event listener for setCanBeClosed()

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon#8274]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Follow up issue from https://github.com/carbon-design-system/carbon/pull/8099 - in browsers that _aren't_ Safari, the click event listener should be removed in the useEffect cleanup function.

In theory the garbage collector will prevent this (small) leak but it would be best to ensure it's removed when the component is unmounted.

You can see in chrome that multiple event listeners are registered when the ContextMenu is opened a few times.
![image](https://user-images.githubusercontent.com/3360588/113327656-d3e10080-92e0-11eb-86c8-98deebffebda.png)

FYI @janhassel something I missed in review 🙃  
Thanks for taking a second look at this with me @andreancardona !

**Comment by janhassel** [comment]
Thanks for catching that, @tay1orjones and @andreancardona !

I just wanted to look further into this but I'm not sure if I understand exactly: the two additional event listeners (3 and 4) come from the internal `ClickListener` component and listen for an outside click to close the menu. Each `ContextMenu` is wrapped inside one of those and since the demo has a nested menu / two levels, there are two `ClickListener`s. For comparison: if you go to the "Multiple groups" story with only one level, you'll only see one of those event listeners.
I couldn't see any listeners piling up when opening and closing the menu a bunch of times.

Let me know if I'm missing something

**Comment by andreancardona** [comment]
@janhassel going to close this issue - @tay1orjones doesn't see it, and I don't see it - they must have been 👻 event listeners
