### ISSUE TITLE
[Tabs] Rounded corner focus state 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#8342]
Rounded corner focus state. I assume this is a bug? 

![image](https://user-images.githubusercontent.com/15144993/114189348-1b3a4300-9918-11eb-86a1-336f165c40ac.png)

**Comment by emyarod** [comment]
we are taking on the default focus styles from the browser now that tab panels are focusable when they do not contain focusable content (https://github.com/carbon-design-system/carbon/pull/7894)

**Comment by tw15egan** [comment]
@emyarod should we just add our `outline` focus styles here?

**Comment by emyarod** [comment]
I am confirming with design, but most likely yes

**Comment by ConradSchmidt** [comment]
Hey all,
we got some design review issues, because of the outline. @emyarod can you share the designs where the outline is specified?

Was the outline also intended to show up, when the tab is used as the main navigation element? It looks a bit weird, when the whole content of the page is outlined.

Are you aware that the described outline was only occurring in Safari (only tested Chrome, FireFox and Safari)? Now all non-Safari users are a bit confused seeing outlines around tab content.

**Comment by emyarod** [comment]
@ConradSchmidt I originally confirmed in a slack conversation with @aagonzales back in April, tagging her for more info
