### ISSUE TITLE
@Carbon/type import documentation incorrect

### ISSUE THREAD

**Issue by gptt916** [carbon-design-system/carbon#8379]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

In:
https://github.com/carbon-design-system/carbon/tree/main/packages/type and
https://www.carbondesignsystem.com/guidelines/typography/code

The example code has:

`@import '@carbon/type/scss/styles';`

But this doesn't work for me, and node-sass complains that the import statement cannot be resolved, however, changing it to 

`@import '@carbon/type/scss/type';`

Will work correctly. I checked the folder in node_modules and this is what I see:

![image](https://user-images.githubusercontent.com/20601623/114502250-7e1e2980-9bf9-11eb-9925-5fa98775ad9f.png)

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Documentation should be updated

**Comment by joshblack** [comment]
Hi there @gptt916! 👋 

I believe this is related to the project's `includePaths` setting provided to `node-sass`. The `type.scss` entrypoint has the imports "inlined" if they are in `node_modules` so that teams that haven't configured their project to use `includePaths` works as expected.

I believe if you update `includePaths` to include `node_modules` then the `styles` entrypoint will work as expected.

Hope this helps!

**Comment by gptt916** [comment]
That worked for me, thank you!
