### ISSUE TITLE
Remove deprecated code from `carbon-components` and `styles` package

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon#8419]
Part of #8410 

Remove deprecated styles, tokens, and files that are no longer necessary. Some of these things include
- [ ] Search for `deprecate` , `v11` , `major` and remove associated code
- [x] Remove styles for deprecated components
    - [x] DataTable v2
    - [x] Toolbar
- [x] Deprecated tokens in `_theme-tokens.scss` and any other unused tokens

**Comment by tay1orjones** [comment]
### Search for deprecate , v11 , major and remove associated code

* We only need to remove these in `styles`, since `components` will just re-export `styles` in v11.

Files with `todo`s:
- [ ] components/button/_button.scss
- [ ] components/code-snippet/_code-snippet.scss
- [ ] components/content-switcher/_content-switcher.scss
- [ ] components/copy-button/_copy-button.scss
- [ ] components/dropdown/_dropdown.scss
- [ ] components/file-uploader/_file-uploader.scss
- [ ] components/list-box/_list-box.scss
- [ ] components/text-input/_text-input.scss
- [ ] components/toggle/_toggle.scss
- [ ] components/ui-shell/side-nav/_side-nav.scss
- [ ] utilities/_convert.scss
- [ ] utilities/_tooltip.scss

Files with deprecations to remove/update in v11
- [ ] styles/scss/components/button/_button.scss
- [ ] styles/scss/components/content-switcher/_content-switcher.scss
- [ ] styles/scss/components/data-table/_data-table.scss
- [ ] styles/scss/components/data-table/action/_data-table-action.scss
- [ ] styles/scss/components/data-table/expandable/_data-table-expandable.scss
- [ ] styles/scss/components/data-table/sort/_data-table-sort.scss
- [ ] styles/scss/components/date-picker/_date-picker.scss
- [ ] styles/scss/components/dropdown/_dropdown.scss
- [ ] styles/scss/components/list-box/_list-box.scss
- [ ] styles/scss/components/modal/_modal.scss
- [ ] styles/scss/components/text-input/_text-input.scss
