### ISSUE TITLE
NumberInput: Allow clients to supply a scale prop

### ISSUE THREAD

**Issue by guigueb** [carbon-design-system/carbon#8690]
### Summary

NumberInput: Allow clients to supply a scale prop

Like the min and max props, allow a scale prop to limit the digits before and after the decimal.

### Justification

IBM Cognos uses NumberInput in many places where we limit the scale.
Perform numeric limiting - similar to min/max - for scale.
Allow clients to pass 0 to allow only integer values.
Allow clients to pass 2 to allow only 2 digits to the right of the decimal (dealing with money).

### Desired UX and success metrics

Setting...
- a value of 0, would allow only integer values
- a value of 1, would allow only values with 1 digit to the right of the decimal (*.X)
- a value of 2, would allow only values with 2 digits to the right of the decimal (*.XX)
- a value of 3, would allow only values with 3 digits to the right of the decimal (*.XXX)
Additional added value would be...
- a value of -1, would allow only values that are a multiple of 10
- a value of -2, would allow only values that are a multiple of 100
- a value of -3, would allow only values that are a multiple of 1000

### "Must have" functionality

- zero would be integers
- positive values limit digits to the right of the decimal

### Specific timeline issues / requests

asap

### Available extra resources

maybe

**Comment by sstrubberg** [comment]
hey @guigueb thanks for submitting this proposal and for chatting with us during office hours last week. Unfortunately, we won't be able to take this workstream on at this time because of other feature requests in our pipeline for Q3/Q4. We are more than happy to work with you and your design team around a community contribution if interested. Also, do make sure to log that error out that you showed us regarding the width of the input. Happy to get that prioritized in a future sprint.

**Comment by guigueb** [comment]
Hello Scott,

Any comments on these two issues?

New enhancement issue...
https://github.com/carbon-design-system/carbon/issues/11757
Closed(why) enhancement issue...
https://github.com/carbon-design-system/carbon/issues/8690

Bill
