### ISSUE TITLE
DatePicker in React does not handle scrolling when inside a fixed positioned element

### ISSUE THREAD

**Issue by ethanwinters** [carbon-design-system/carbon#8748]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

We are trying to use Carbon inside a fixed position widget. Many of the components (datepicker, overflowmenu, etc) run positioning calculations off of the body. This creates issues when they are created inside of a fixed position element as they don't "stick" to the fixed position elements during scroll behaviors. This issue is specifically in regards to datepicker only.

> Is this issue related to a specific component?

This issue is specifically for the datepicker component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Y'all provide access to `appendTo` to be passed into flatpickr, which only solves half the issue (and only injecting the calender into my fixed position element with the calculations still come from `<body>` only makes it much worse).
I need access to the underlying `positionElement` config item as an optional prop on datepicker inside flatpickr in order to make the calendar maintain correct position on scroll.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Assistant (web chat). We need this by end of June to finish our migration to Carbon from our own "fake Carbon" because Carbon couldn't reach our needs in the past. This work will allow us to bring in a datepicker inside Watson Assistant web chat (which is end user facing with millions of user impressions) –– this is a very common feature request and we’d like to start supporting it as soon as possible.

## Steps to reproduce the issue

Open one of the datepickers and scroll. The input field inside the div with position fixed will stay, the calendar will scroll with the page.

https://codesandbox.io/s/intelligent-goodall-zjnxt?file=/src/index.js

## Additional information

- Screenshots or code
- Notes

**Comment by arneshb** [comment]
@tw15egan and @joshblack , can you please help us get a fix for this issue prioritized?

This affects Watson Assistant, specifically our out of the box web chat UI. We need this asap to finish our migration to Carbon from our own "fake Carbon" because Carbon couldn't reach our needs in the past. This work will allow us to bring in a datepicker inside Watson Assistant web chat (which is end user facing with millions of user impressions) –– this is a very common feature request and we’d like to start supporting it as soon as possible.

Our release is planned for early September, but we need time to react to this fix -- we really need this by mid August to avoid a delay in our release.

**Comment by tw15egan** [comment]
Are you able to use the `appendTo` prop on the `DatePicker` to append it to the fixed container? In the example, the Datepicker menu is being placed on the outer body, thus causing the scroll.

**Comment by ethanwinters** [comment]
Yes, that worked for me. Before it seemed as though we also needed positionElement, but I think we have discovered some changes on our end that cleaned that up. Thanks!

**Comment by tw15egan** [comment]
Awesome, glad that worked! 👍🏻
