### ISSUE TITLE
[Modal]: buttons no longer span full width in Carbon x.35

### ISSUE THREAD

**Issue by vronjec** [carbon-design-system/carbon#8767]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The Carbon 10.35 update seems to have introduced a visual bug concerning modals:

<img width="1187" alt="Screen Shot 2021-05-26 at 18 51 49" src="https://user-images.githubusercontent.com/10489312/119700449-82be3a80-be53-11eb-81dd-d6fd5709f090.png">

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The Cancel/Add buttons on the modal should span full width as in previous versions of Carbon 10.

> What version of the Carbon Design System are you using?

Carbon 10.35, Carbon React 7.35

## Steps to reproduce the issue

1. Navigate to https://react.carbondesignsystem.com/?path=/story/components-modal--default

**Comment by tw15egan** [comment]
This was fixed in https://github.com/carbon-design-system/carbon/pull/8686 (rel https://github.com/carbon-design-system/carbon/issues/8685) and the fix can be found in [v10.36.0-rc.0](https://github.com/carbon-design-system/carbon/releases/tag/v10.36.0-rc.0). We will release `v10.36.0` today / tomorrow. Hope that helps!
