### ISSUE TITLE
[Progress indicator] Type style broke in v10.36

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#8783]
## Detailed description

`Second step` and `Third step` text labels are much smaller than other steps. 

https://react.carbondesignsystem.com/?path=/story/components-progressindicator--default

![image](https://user-images.githubusercontent.com/15144993/119887329-0171b100-bf02-11eb-95d7-a21cbe692d1e.png)

**Comment by joshblack** [comment]
Digging into this, this issue is caused by an import ordering issue where progress indicator is brought in before tooltip.

For teams impacted by this, you can address this by making sure progress indicator is brought in after tooltip. On our end, we'll update the progress indicator styles to include tooltip so that teams won't have to verify this manually in the future 👍
