### ISSUE TITLE
[Form: search] Field height is way too small

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#8900]
In the latest release, Search field in Form became too small, prob 16px. Expecting 40 or 48px.
https://react.carbondesignsystem.com/?path=/story/components-form--default

![image](https://user-images.githubusercontent.com/15144993/121899666-a1954b80-ccf2-11eb-834b-85b6f30c8825.png)

**Comment by jnm2377** [comment]
Looks like the issue is that it's no longer getting a default size, which was changed in this PR: https://github.com/carbon-design-system/carbon/pull/8824/files
@tw15egan Is there a reason we aren't providing a default size anymore (for sizes other than small)? Otherwise, we should add a specific size to the story.
