### ISSUE TITLE
ComboBox onClick does not trigger with null selectedItem when items is objects

### ISSUE THREAD

**Issue by TannerS** [carbon-design-system/carbon#8947]
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

I have noticed that, when passing in an array of objects into the ComboBox's `items` prop, that when the `selectedItem` prop is set to null, the `onClick` event handler is not called when you click the clear button. Any other case, that event handler is called when selecting an item from the drop down or clicking the clear filter/button in the search field except when that prop has null passed inside. I found this out when I used null to reset it. 

> Is this issue related to a specific component?

ComboBox

> What did you expect to happen? What happened instead? What would you like to

I learned that resetting the value to appear within the combobox by default via `selectedItem` works when passing in an empty object, but it took me a while to figure this out due to thinking null should work fine. So I would expect null to work the same as an empty object.

## Steps to reproduce the issue

I set up a sandbox with different scenarios commented out 

https://codesandbox.io/s/optimistic-bas-6ovuo?file=/src/index.js

## Additional information

This may not even be a bug, or if it is a very low one, but if it is not a bug, then it should be made aware the behavior differences between passing in null vs an object (or empty object in this case)

thank you!

**Comment by jnm2377** [comment]
Hey @TannerS 👋🏽   I think the problem is that you're hard coding `selectedItem` as `null` in the component, so it's not actually handling any other selections under the hood. In other words, it seems like it's a problem with how you're doing your state management. If I edit your codesandbox to use `initialSelectedItem` (as opposed to `selectedItem`) as `null`, then select an item and clear it, it actually does call the onClick function.

https://images.zenhubusercontent.com/84835535/b9d7aaaa-ebea-4b65-a341-be7cf49063d5/screen_recording_2021_06_21_at_11_46_46_am.mov

**Comment by TannerS** [comment]
Hey, I see. Problem is for our case, we don't need to use the

initialSelectedItem

We have a situation, where, we are using two combo boxes in our service.
One selected an option, populates the options for the second, so clearing
the first combobox, clears the any selected item in the second. I figure
this worked by setting the

selectedItem

Because, when I didn't do it, the previous item would stay selected and not
change even when th list got re populated, so using that prop was the only
way to clear it and that's how I found the issue

**Comment by jnm2377** [comment]
Hey @TannerS I think I'm understanding the issue. I have a few questions:
- Is the example in your codesandbox representing the combobox that populates the second combobox or the second one that's dynamically populated? It might help to see an example of how you're doing this since it's specific to this situation.
- you mention in your first comment that you're resetting the selectedItem to null. I think it could be considered a bug, maybe, since it works as expected if you reset it to an empty object. I'm wondering if this is an acceptable workaround?

**Comment by TannerS** [comment]
> Hey @TannerS I think I'm understanding the issue. I have a few questions:
> 
>     * Is the example in your codesandbox representing the combobox that populates the second combobox or the second one that's dynamically populated? It might help to see an example of how you're doing this since it's specific to this situation.
> 
>     * you mention in your first comment that you're resetting the selectedItem to null. I think it could be considered a bug, maybe, since it works as expected if you reset it to an empty object. I'm wondering if this is an acceptable workaround?

Hey, I won't lie, it's been a while since I looked at this I forgot my logic in the issue, however, looking at my comments in the sandbox, i no longer see the issue as described in the comments and noticed the sandbox is set to use the latest carbon react components.

With the fact I dont remember the exact details, i can't recreate it in the latest version as per described in the comments, and it was avery specific situations, I think it is safe to say we could probably close this
