### ISSUE TITLE
ListBox Tree Shaking Problems

### ISSUE THREAD

**Issue by mango906** [carbon-design-system/carbon#9111]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I'm using this framework on my service. I found one problem using this framework. I expect when i use `ListBox` components, tree-shaking did not working

I test this in simple cra projects

```
"carbon-components": "^10.38.0",
"carbon-components-react": "^7.38.0",
```

```javascript
import './App.css';
import ListBox from 'carbon-components-react/lib/components/ListBox';


function App() {
  return (
    <>
    <ListBox />
    </>
  );
}

export default App;

```

In this projects, I want only using `ListBox` components, but chunk file contains unnecessary files. I check this by [cra-bundle-analyzer](https://github.com/svengau/cra-bundle-analyzer)
(Like @carbon/icons-react/es)

![스크린샷 2021-07-05 오후 4 46 04](https://user-images.githubusercontent.com/38802280/124435989-8200b880-ddb0-11eb-8f35-69eeb66e7a4e.png)

> Please create a reduced test case in CodeSandbox
> - React:
>   https://codesandbox.io/s/restless-microservice-e6vwd?file=/src/index.js

how can i fix this problem?

**Comment by joshblack** [comment]
Hi there @mango906! 👋 

Just a heads up, the `ListBox` component is not a part of the public API which is why it's not available in the entrypoint of the package.

As a result, grabbing the export from `lib` will actually cause the CommonJS version of these packages to be loaded. These are not able to be tree-shaken, unfortunately, and I believe this is the issue that you're running into.

To address this issue, you will need to only import from the entrypoint as that will contain the ESM exports needed to support tree-shaking.

Hope this helps!

**Comment by mango906** [comment]
@joshblack Hello! Long time no see. Is the issue still in place in the latest version?
