### ISSUE TITLE
RGBA option for token values

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon#9142]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

rgba() tokens to the Carbon theme variables so that we can apply the theme based on what the adopter defines. Currently need to do a linear-gradient with the `$ui-background` with an opacity 0.6. We need the option to set the opacity of the token becuase currently our scss styles are not able to recognice `rgba($ui-background, 0.6)`

Clarify if you are asking for design, development, or both design and
development.

### Justification

Creating a image component with a gradient where the design requests this functionality. 

![image](https://user-images.githubusercontent.com/20210594/124830760-37597a80-df2f-11eb-9fb7-8dcc5371a8f6.png)

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by
which we can measure success/failure for the user.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with
you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

**Comment by joshblack** [comment]
Hi there @ariellalgilmore! 👋 

I believe that today `rgba($ui-background)` should work as you expect, is your team potentially using the CSS Custom property feature flag?

**Comment by ariellalgilmore** [comment]
Hi @joshblack sorry for the delay. We are using the css custom property feature flag but when adding the alpha value to `rgba($ui-background, 0.6)` the opacity does come into effect. 

cc: @proeung

**Comment by tay1orjones** [comment]
One concern I have here is regarding the intended use. The theme token values have been chosen with specific brand expression and accessibility requirements in mind. Allowing opacity to be configured opens consumers up to a lot of situations where things can go off the rails. 

@carbon-design-system/design are there concerns about opening up alpha values? Would we need some additional documentation work to feel confident in shipping these?

Additionally, there's some technical complexity in making alpha values a reality. Now that v11 ships tokens as css custom properties by default and pivotal features (like layering and theme switching) rely on these, RGBA conversion shouldn't be done in sass. Tokens need to remain a custom property, but this limits finding a solution here.

To be able to feed a custom property into `rgba()`, it needs to be a series of values:
```scss
$token: 253, 166, 60;
```

That would compile into:
```css
--token: 253, 166, 60; 
```

Then used as:
```css
background: rgba(var(--token), 0.5);
```
---

### Potential solutions to explore
1. Provide a secondary set of tokens alongside the existing ones that are compatible rgb values instead of hex values
```scss
$ui-background: #0f62fe;
$ui-background-rgb: 15, 98, 254;
```

2. Use 8 digit hex values, which are now [supported in all major browsers](https://caniuse.com/css-rrggbbaa) (though I'm not sure how users would configure and override the alpha value)
```scss
$ui-background: #0f62fe00;
```

3. Extend the existing tokens to no longer be a single value, but instead a map. This would allow future extensibility if we ever wanted to expand, though this would likely be a breaking change.
```scss
$ui-background: ("hex": #0f62fe, "rgb": (15, 98, 254));
```

**Comment by laurenmrice** [comment]
@ariellalgilmore @tay1orjones For RGBA-specific tokens, they will work for gradients on an image, but I was curious if there are any other specific uses you know have for having RGBA-specific tokens? Is there another way to achieve this besides using RGBA-specific tokens (just curious to know what options we have). I think if we were to add these, we would need to be specific in our documentation on when to use them.
