### ISSUE TITLE
Code snippet bug

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon#949]
Code in the code snippet is overflowing onto the ghost button. Was expecting it to push the code to a new line when it got within 16px of the ghost button (see image below

Current:
<img width="479" alt="screen shot 2018-06-28 at 7 06 54 pm" src="https://user-images.githubusercontent.com/29312997/42112733-d7566e4c-7bb6-11e8-943b-2bc6c3203ee7.png">

Proposed:
![image](https://user-images.githubusercontent.com/29312997/42112848-42025e54-7bb7-11e8-81cd-7616d41b1f00.png)

**Comment by tw15egan** [comment]
This button is absolutely positioned, so it has no awareness of the surrounding content and exists on a different plane than the text. 

We could move it down so that it has more padding, or add in a white background so the text goes underneath, but having text flow around it isn't possible with the way it is positioned

**Comment by tay-aitken** [comment]
Move it down, as in visually move it farther down, or something else?

I don't think we want text going underneath of it, would be difficult to read.

**Comment by tw15egan** [comment]
Move it down as in that 16px of padding above the button would have to span the entire code snippet, not just where the button is
