### ISSUE TITLE
[Datatable][isSortable] console error occurs when a column has been sorted and the user then deletes the header

### ISSUE THREAD

**Issue by yonghuay** [carbon-design-system/carbon#9512]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I have got an issue with removing a previously sorted header. Basically, when a column has been sorted and the user then deletes the header, a console error occurs.
I have created a sample code in codesandbox. 

https://codesandbox.io/s/rough-bird-x6of7?file=/index.js

## Steps to reproduce the issue

1. Create a data table.
2. Enable the sort function.
3. Add a new column function and remove the column function.
4. Sort the newly added column and then remove it.
Results: console error occurs.

Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/rough-bird-x6of7?file=/index.js

## Additional information

- Screenshots or code

![Untitled 2](https://user-images.githubusercontent.com/32554015/130226023-164cc4d9-ee2f-4bab-84dc-cfd559ddf7a1.gif)

- Notes

**Comment by tay1orjones** [comment]
Hi @yonghuay, yeah this is because it's trying to sort on a column that is no longer there. A few options:

* Place a `key` on the table and change it's value when you delete a header. This will create a new instance of the component with the sorting by default as it was on initial render.
* The `sortBy` action is made available in your render prop function so that you can [programmatically sort the table](https://react.carbondesignsystem.com/?path=/docs/components-datatable-sorting--usage#programmatic-sorting) by a different header. What I would recommend is on deletion of a header that was sorted on, use `sortBy` to sort the table via a different available header.

Let me know what you think. I'll close this for now but we can reopen at any time if there's something actionable we can do besides the options I outlined above.

**Comment by yonghuay** [comment]
Hi Taylor, @tay1orjones 

Thanks for the suggestions, I passed them on to my colleague. He told me that he used option 1 to solved this issue. 

Thank you very much.
