### ISSUE TITLE
[Switcher] Tool tip sticks and does not go away after opening/closing

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon#9521]
This issue has either come back or was never resolved from a previous issue.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/32881239/125745154-30c006a4-14bd-4237-b624-d435c02a5e67.gif)

**Comment by tw15egan** [comment]
Since the tooltip still has focus, it still shows the tooltip. Need someone from the a11y team to weigh in on the intended behavior here

**Comment by jnm2377** [comment]
<img width="688" alt="Screen Shot 2021-09-09 at 10 23 18 AM" src="https://user-images.githubusercontent.com/32556167/132714852-74c43810-05cd-4446-ad9e-418710e40f82.png">
Based on the discussion above, I think we consider this a bug. The expected behavior is that the tooltip should just show up on keyboard focus, not click. This way it will disappear when the item loses focus.

**Comment by tw15egan** [comment]
So we'll need to change the logic of icon-only `Button` and `TooltipIcon` (they share logic and a11y rules) to dismiss the tooltip when a click action has been taken
