### ISSUE TITLE
How to refresh DataTable preserving vertical scrollbar position without refreshing the all table

### ISSUE THREAD

**Issue by FainaGS** [carbon-design-system/carbon#9525]
We have a DataTable  with a vertical scrollbar. Each update  places scrollbar on the top. 
Each time we build the rows again and do setState for the rows causes the table to be refreshed without preserving the scroll position

**Comment by tw15egan** [comment]
Since you are re-rendering the table, the scroll position is getting reset each time. You could store the scroll-y position and use a scroll to function or use a `useMemo` hook to then scroll back to that position whenever the data is changed. Also, ensure each table row has a unique key. Hope that helps! Going to close this as this does not seem to be an issue with the components themselves, but feel free to reopen if there is anything else we can help with. 

A few resources: https://stackoverflow.com/questions/53044740/keep-scroll-y-after-rerender
https://medium.com/@mikolajkocieda/react-hooks-keep-scroll-position-during-change-list-views-cd86463f9629
