### ISSUE TITLE
Not able to prevent click event propagation on Checkbox/TableSelectRow

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon#9577]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Discover while we implement the 'onRowClick' on the table rows with `TableSelectRow`. I don't see a way to completely prevent the click from propagating from the Checkbox or the TableSelectRow because the event seems to be from the `label`
https://codesandbox.io/s/sparkling-sky-2d3uj?file=/src/index.js

> Is this issue related to a specific component?

Checkbox
TableSelectRow

> What did you expect to happen? What happened instead? What would you like to
> see changed?

`Checkbox.onClick` or `TableSelectRow.onSelect` should prevent the click from bubbleing up.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4D - WKC

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/sparkling-sky-2d3uj?file=/src/index.js

**Comment by tay1orjones** [comment]
Hi @nelsonchen90 👋  sorry this is confusing - the intended prop for catching change events on checkboxes is `onChange`.

`onClick` isn't part of the API for Checkbox. In the case of the sandbox example, `onClick` is just being passed through via prop spreading. `{...other)` containing the `onClick` is placed on the `input`:

https://github.com/carbon-design-system/carbon/blob/8ce0b4c0e5547837888b4050fa8630a7692df79b/packages/react/src/components/Checkbox/Checkbox.js#L44-L52

Similarly, TableSelectRow doesn't accept an `onRowClick`. The `onSelect` prop is the intended way to catch updates. `onChange` is also called each time the input is updated. 

https://github.com/carbon-design-system/carbon/blob/8ce0b4c0e5547837888b4050fa8630a7692df79b/packages/react/src/components/DataTable/TableSelectRow.js#L84-L92

**Comment by nelsonchen90** [comment]
@tay1orjones Thanks for taking a look at this.
I have updated the sandbox and added two more examples...
- using the `onChange(checked, id, evt)` to stop the propagation
- use a container to prevent propagation.

It seems like using a container is the only way as the `onChange` is bind to the change event on the input so the `evt` there is not for click. 

Please let me know if I misunderstood anything. If not, would you consider change / add `onClick` prop to the `Checkbox` so we are able to actually capture the click events (from both `input` and `label`)? Otherwise it seems like adding a container is the only way to go.

**Comment by marion-bruells** [comment]
@tay1orjones can you take a look at this again. 
We had feedback in the past that users shouldn’t be pulled out of their current work context. Therefore we provide them further meta data of an object in context of the page (in a sidepanel) triggered either by clicking on a row or by clicking an action button on the table row. The drilldown on a new page only happens when users clicks the link (name on first column). We want to avoid that we pull users easily out of their context which interrupts their current workflow if their main intent in a table shouldn’t be navigating into a different page. We worked on detailled guidance for this and published it to C&CS PAL: https://pages.github.ibm.com/cdai-design/pal/patterns/data-table/clickable-row-items 

@tay1orjones Can you make the change also for the `TableSelectRow` as described by @nelsonchen90 ? Multiple teams will require this in future. In this issue we have the behaviour described in more detail if you need more context: https://github.com/carbon-design-system/carbon/issues/7641

**Comment by tay1orjones** [comment]
@nelsonchen90 Yes, `TableSelectRow` uses the `InlineCheckbox`. The codesandbox provided used the `Checkbox`. It would be helpful to have a codesandbox repro demonstrating the issue using `TableSelectRow` similar to how you are in your app.

Have you tried using `onSelect` on `TableSelectRow` to achieve your use case?

The `InlineCheckbox` already places the `onClick` handler on the input through `{...inputProps}`. There is no wrapping `div` like in `Checkbox`.

https://github.com/carbon-design-system/carbon/blob/de5d85c5353e16005abfa4aea332bddab9f632d4/packages/react/src/components/InlineCheckbox/InlineCheckbox.js#L134-L145

Additionally the `TableSelectRow` renames `onSelect` to be `onClick`.

https://github.com/carbon-design-system/carbon/blob/de5d85c5353e16005abfa4aea332bddab9f632d4/packages/react/src/components/DataTable/TableSelectRow.js#L30

This is then passed down to the `InlineCheckbox` as `onClick`. 

https://github.com/carbon-design-system/carbon/blob/de5d85c5353e16005abfa4aea332bddab9f632d4/packages/react/src/components/DataTable/TableSelectRow.js#L35-L51

**Comment by tay1orjones** [comment]
@nelsonchen90 Here is our [example codesandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/custom-data-table-state-manager?file=/src/components/CustomDataTable.js:7608-7660) of a datatable with a custom state manager. `onSelect` is used to capture the click/selection of a row's `InlineCheckbox`.

**Comment by nelsonchen90** [comment]
Sorry for the late response!

@tay1orjones the problem with InlineCheckbox and capture the click event is that there are 2 items being clicked in it
- input
- label

Although we can stop the click event from propagating by using `TableSelectRow.onSelect` there is still another event being 'escaped'/propagated from the `label`.

I have created a super reduced case 
https://codesandbox.io/s/dark-fog-ubul2?file=/src/index.js

**Comment by tay1orjones** [comment]
@nelsonchen90 that codesandbox was super helpful, thanks! I see what you're saying - the click event associated with the `input` can be caught through `onSelect`, but the click event associated with the `label` can't be caught through `onSelect`. This is because the event is placed directly on the `input` and not on a wrapper of the `input` and `label`.

I'm sure there's some way we can address this. From my understanding, the `label` for `InlineCheckbox` never renders visible text or a visible click target. I can't think of a reason why a consumer would need access to the click event specifically from the `label`. What might make the most sense here is to immediately call `stopPropogation` on the label `click` event internal to `InlineCheckbox`.
