### ISSUE TITLE
[Feature Request]: To disable the options in MultiSelect

### ISSUE THREAD

**Issue by jillyj** [carbon-design-system/carbon#9610]
### Summary

We would like to disable the option(s) in MultiSelect because in the beginning, the options is valid, but afterward, it becomes invalid. But we don't want to remove the invalid options directly because of user experience concerns. 

### Justification

As above.

### Desired UX and success metrics

We want something like below.
![image](https://user-images.githubusercontent.com/47232763/132298794-09c9926e-3a8c-4a4c-af69-bd0b8f6d3be0.png)

### Specific timeline issues / requests

As soon as possible. Thanks.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hey @jillyj, you're right that there is not a way to disable individual items inside the MultiSelect listbox. MultiSelect uses the same primitive `ListBox` component as Dropdown and Combobox, which also do not have this functionality yet.

refs #6477, #7780

**Comment by tay1orjones** [comment]
Side note - I'm also unsure how to approach the use case from the screenshot in an accessible manner. 

If the item was `disabled`, I assume it would be removed from the accessibility tree and not navigable via keyboard. I'm unsure how a non-mouse/sighted user would get to the icon tooltip.

**Comment by jillyj** [comment]
Hi @tay1orjones , I have workaround to disable the items in MultiSelect here: https://codesandbox.io/s/cranky-leaf-5pnl5?file=/src/index.js. It's a very hacked way. But you are right, it's hard to solve the issue of keyboard. Currently, in my workaround, when I press space key, the item can't be selected but the summary tag at the top said there is 1 selected.

**Comment by liunate** [comment]
> tay1orjones: If the item was `disabled`, I assume it would be removed from the accessibility tree and not navigable via keyboard. I'm unsure how a non-mouse/sighted user would get to the icon tooltip.

Hello @tay1orjones 👋  I think you are right in general cases we should remove disabled elements from accessibility tree. 

For disabled interactive element in a widget, I did a research at that part and noticed in [WAI ARIA Practices 6.7 Focusability of disabled controls](https://www.w3.org/TR/wai-aria-practices-1.2/#kbd_disabled_controls) it suggests keep disabled options focusable. 

There are of course advantages and disadvantages doing so which are concerns competing each other, and in @jillyj case here are some views from myself feeling like to have disabled options focusable:
- some info is disclosed that why the option is disabled, so that user can take proper actions to remedy or seek for admin help
- unable to focus the disabled option also means the option is missing in the list, which could be confusing if user has configured the options elsewhere but is unable to locate it in the list
