### ISSUE TITLE
[Bug]: Multi Select not working (missing scripts) in vanilla implementation

### ISSUE THREAD

**Issue by rbeatty** [carbon-design-system/carbon#9615]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.41.0, v10.43.0, others 

### Description

Vanilla implementation includes multi-select styles and html but component does not function as scripts are missing from both compiled scripts and components folders. This is the case on [vanilla documentation site](https://the-carbon-components.netlify.app/?nav=multi-select) as well as when downloaded via npm/yarn.

Missing functionality includes: dropdown toggle, filtering, clearing selections.

This issue was logged last year in https://github.com/carbon-design-system/carbon/issues/6839 but was closed due to inactivity, not sure if it has re-occurred or persists from that time.

### CodeSandbox example

https://the-carbon-components.netlify.app/?nav=multi-select

### Steps to reproduce

**Option 1:**

[View vanilla documentation site](https://the-carbon-components.netlify.app/?nav=multi-select), try to interact with component examples

**Option 2:**

1. `npm install --save carbon-components`
2. check script folders (`node_modules/carbon-components/es/components/` and `node_modules/carbon-components/umd/components/`), notice `multi-select` component folder is missing here but available in html and scss folders

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by jnm2377** [comment]
Hi @rbeatty thanks for opening this issue! Unfortunately, we've moved to being react-first and are really only developing our react components. The vanilla library is being deprecated in v10, and as of now, anything besides the styles (since we're still consuming those for our react components) is community maintained. If you would like to contribute a PR to add the js necessary for the vanilla dropdown, we would be more than happy to include it, but we won't be working on this. I will close this issue for now, but can re-open if you would like to take it on. :)
