### ISSUE TITLE
[Bug]: NumberInput's placeholder doesn't use --cds-text-placeholder

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#9635]
### Package

carbon-components

### Browser

Chrome

### Package version

10.43

### Description

TextInput etc. color the placeholder according to `--cds-text-placeholder`, but it was forgotten for NumberInput.

_number-inputs.scss just needs:

```
.#{$prefix}--number-input::placeholder {
    @include placeholder-colors;
}
```

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-numberinput--default

### Steps to reproduce

You can see it on https://react.carbondesignsystem.com/?path=/story/components-numberinput--default etc.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by tay1orjones** [comment]
Hi @wkeese, it looks like the [design specification](https://carbondesignsystem.com/components/number-input/style) for `NumberInput` does not include placeholder text as a supported option.

Passing the extra prop `placeholder` likely works because `...other` is spread onto the input. To style this placeholder text you'll need to apply your own custom styling.

**Comment by wkeese** [comment]
OK, fair enough, `placeholder` isn't listed on https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/NumberInput/NumberInput.js either.
