### ISSUE TITLE
[Feature Request]: Detect user input method and then provide appropriate focus style

### ISSUE THREAD

**Issue by jjennings7** [carbon-design-system/carbon#9662]
### Summary

While keyboard tabbing manipulates the location of focus, mouse clicks do, as well. Many users find this behavior undesirable, preferring focus styling to be present only if a keyboard is used. This is part of the Keyboard Operations proposal led by Sam Ting, Visual Design Lead, CPD @thefirstartist. Here is the entire proposal: https://ibm.ent.box.com/notes/804183398946

[What-Input](https://ten1seven.github.io/what-input/) is a JavaScript library that listens for the kind of input a user is using. With this library, focus styling can be different for mouse and keyboard users. We recommend using this library or something similar. 

If a keyboard is the input method, use the current Carbon focus style. If a mouse is the input method, remove the focus ring, or change the focus style so it's not as prominent as it currently is in Carbon.

_Carbon example of focus ring on tab. It appears whether using keyboard or mouse input:_
<img width="425" alt="Screen Shot 2021-09-14 at 1 51 34 PM" src="https://user-images.githubusercontent.com/48838320/133332149-ed1596ac-8d0c-44e2-bc59-1d99bde305d0.png">

_For mouse click input, the focus ring should not show:_
<img width="414" alt="Screen Shot 2021-09-14 at 1 51 51 PM" src="https://user-images.githubusercontent.com/48838320/133332231-370f8ea7-7ced-417e-bf4b-9cada69b5a9a.png">

### Justification

According to [W3C recommendations](https://www.w3.org/TR/WCAG21/#focus-visible):
Success Criterion 2.4.7 Focus Visible§
Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.

For example, tabs already have selected states. Having a focus ring can be overkill and be confusing to mouse users. A tab with a focus ring can be confused for a tertiary button (This has actually happened during a CPD design review). 

### Desired UX and success metrics

- When user is using mouse, and clicks on components that don't bring them to a new page (for example: accordions, tabs, checkboxes, radio buttons, drop downs), there should be no focus ring.
- For form text fields, keep the current focus ring style for keyboard users, but provide a less prominent focus ring for mouse users.

### Required functionality

(See above)

### Specific timeline issues / requests

No

### Available extra resources

CPD design team has already worked with various members of Carbon and Accessibility team and we have discussed the above issue together. The following met with us in July: Jean Ann Servaas, Joshua Black, Mike Abbink, Shari Trewin  Jess Lin and Michael Gower from Accessibility

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
Hi there @jjennings7! 👋  Thanks so much for taking the time to write this up.

Following up from our last chat about this, I think the notable concern for this approach was if we could correctly flag the **intent** of mixed modality (keyboard, mouse) users.

The background for this was that some people may assume that a user is mouse-only or keyboard-only. As a result, it would be simple to predict the intent of the user because we would know which modality they were using.

Unfortunately, I think the keyboard-only user may be incorrectly assuming that they are only using a keyboard. While there are situations where this will be 100% true, there are situations where a user may require both inputs. This describes the mixed modality use case.

[This article](https://www.davidmacd.com/blog/sighted-keyboard-only-user.html) describes several situations where this may be the case.

In the case of What Input, I believe it may incorrectly detect the intent of the user's inputs in certain situations. For example:

- When a user switches from mouse to keyboard, it will not display the focus outline
- When a user switches from keyboard to mouse, it will remove the focus outline

These situations could be problematic for some of the situations described in the article mentioned above.

https://user-images.githubusercontent.com/3901764/133486272-602db507-c0ac-4f66-898b-161c4ae34a06.mov

There is also a great video from Eric Wright that demonstrates how this library interacts with Dragon: https://www.youtube.com/watch?v=b60O9CSlM_s

There is another approach we could take using [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible). However, I believe that proposal also has some issues in specific situations with screen readers (at least as far as I know).

Overall, I think we are trying to be cautious here and would not want the focus indicator to be hidden when a user expects it to be visible. Let me know if there is a way we could accomplish this the library mentioned, or other techniques, and what a good testing strategy for this approach may be 👀 

Thanks again for putting this together! Really appreciate it.

**Comment by thefirstartist** [comment]
Thank you Josh for getting back to us. 

Our biggest concern is that showing focus state in addition to the selected state is confusing and visually overkill. We don't really care a user is mouse-only, keyboard-only, or using both. What we really want is to hide or provide a less prominent focus style when the user clicks on it with a mouse. I don't recall seeing any major design systems showing the same focus ring on the mouse clicks and everyone we talked to agree that it's overkill to show the focus ring on mouse click.

:focus-visible seems a good solution. I have also found quite a few alternatives to make the keyboard-only focus. [Here](https://www.kizu.ru/keyboard-only-focus/)'s one of them.

**Comment by joshblack** [comment]
@thefirstartist what I'm hearing is that you would like to find a way to accommodate users for whom the focus indicator may not be helpful, or is seen as disruptive to their experience. What's been proposed, as I understand it, is a heuristic that tries to predict when a user may have that preference. Oftentimes, these heuristics predict intent based on a user's input modality.

What I was sharing above is that these heuristics can have gaps as they relate to the ways in which different users interact with the browser. One example from above was how speech recognition software like Dragon may result in an incorrectly predicted intent, but there are other examples like Mouse Keys where a user may use keys on a keyboard to move the mouse on the screen.

Our goal here would be to find a heuristic that works for everyone and doesn't degrade the experience of those who rely on focus indicators.

Let me know if I'm understanding what you shared correctly, in the meantime here are a couple design systems that I'm aware of that follow a similar approach. I definitely agree that design systems vary in how they approach this topic. On our end, especially with respect to accessibility, we tend to defer to GOV.UK along with IBMa.

- [United States Design System](https://designsystem.digital.gov/)
- [GOV.UK Design System](https://design-system.service.gov.uk/)

**Comment by mbgower** [comment]
@thefirstartist 
> everyone we talked to agree that it's overkill to show the focus ring on mouse click.

"Everyone" isn't accurate, since that wasn't the message from the accessibility team, who had a fairly similar concern to that given by Josh in his original [comment](https://github.com/carbon-design-system/carbon/issues/9662#issuecomment-920264749).

There are some nuances here I think are important to restate.

### Focus enhancements versus focus suppression
In some situations, mostly for native HTML components, Carbon has increased the browser default focus on some elements, usually either because the indicator differs by browser, or overall was considered insufficient.

In other situations, usually for non-standard or complex components, Carbon has had to provide its own focus indicator (since the user agent may not even provide anything on a div being repurposed as a widget).

It's important to understand that there are the differences in the focus indicator approaches here, depending on whether a default focus indicator exists. The outcome depends heavily on if you are talking about suppressing focus entirely or reducing focus enhancements.

It _may_ be viable to remove Carbon's focus _enhancement_ on a native component where mouse interaction is detected and leave just the browser's default indicator.

This is because the default indicator may meet accessibility requirements for the focus indicator. However, it is a bit more complicated than the 2.4.7 Focus Visible requirement you cite in your issue. WCAG 2.1 also has a requirement called [Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) which applies to states of UI components. There is no wording restrictive to keyboard in this SC. In other words, the focus state still has to have an identifiable focus state, even when it is caused by a mouse. If removing Carbon's focus enhancement results in zero focus indication, the component would probably fail Non-text Contrast.

Finally, WCAG 2.2, which is supposed to be release this fall, has a much more detailed new requirement for [Focus Appearance](https://w3c.github.io/wcag/guidelines/22/#focus-appearance-minimum). This _does_ have wording about "receiving keyboard focus", so it does not need to apply with mouse-caused events.

So, for each of the components, two things are required, IMO:
1. an assessment for the resulting indicator after removing the enhancements
2. user testing with users who are keyboard users (both blind and power users) or who are true hybrid users (such as Dragon users).
The first ensures IBM does not fail WCAG. The second ensures we make a delightful experience for all users.

**Comment by mbgower** [comment]
### Differences in interaction 
I thought I would provide some considerations and a few specific component examples to elaborate on why user testing is going to be important.

The first is that not all components are created equal when considering both keyboard and pointer interaction. Some provide immediate feedback at interaction or activation. Others, not so much. All of these types of components involve different considerations for interaction and focus handling.

#### Components that trigger focus changes/new content
Some components usually trigger a change in context. Links normally open a new page (or at least update content in the main region), buttons often launch dialogs or submit forms. Normally, focus would be set on something in this new content by default, regardless of the mode of interaction.

#### Components with a selection state
Many components retain focus at the target after being selected and have a visually clear selection state. Think of radio buttons, checkboxes, tabs, etc. You'll note if you look at native examples with different browsers that in many cases, the interaction differs with keyboard or mouse, and is very close to what you are seeking. I have a page with stock elements you can review for this http://wafflerama.com/a11y/keyboard.shtml These are the most likely components to pass user testing for acceptable behaviour, IMO. It would be very difficult to misunderstand what has focus when one clicks on it.

Other components retain focus at the target, but the selection state may not be as obvious. Think of text input and text area implementations where the only indicator is a flashing cursor. And of course as the user selects text in a text area, there is indication of selection state, etc.  Most of the browsers offer a focus indicator around the entire input as well as the insertion point and selection indicator. And that indicator is present regardless of keyboard or mouse operation. This is arguably very similar to the grouped component focus indicator you are advocating.

#### Components with children
Still other components reveal one or more children when activated and move focus there. Think of menus, date pickers, most dropdowns (select elements), etc. These sorts of components are most likely to confuse/disorient some users of those discussed so far, and so require more careful considerations of alterating affordances, such as focus indicators.

**Comment by mbgower** [comment]
### Indicator around grouped components

I suspect that these response are already too long, but I wanted to point out that focus indicators that encompass an entire component may allow a reduction in the one point of confusion I've heard your team mention (a mouse user thinking a focused tab item was a tertiary button). I think this is a really interesting approach with a lot of merit, but I also think I've heard your team stick with one implementation (dotted internal focus indicator) which while possible is not the only solution.
So I wanted to encourage you to consider how the overall focus indicator on, say, a tablist, can reduce interaction confusion for all users while also potentially allowing for a reduction in other focus enhancements for a pointer user. 

Again, this needs to be tackled on a component by component basis, and iterated based on user testing. Happy to take part in this exercise. I strongly advocate getting down to the devil in the details.
