### ISSUE TITLE
[Feature Request]: Allow React nodes as children in CodeSnippet

### ISSUE THREAD

**Issue by imp-dance** [carbon-design-system/carbon#9846]
### Summary

Allowing for react nodes in CodeSnippet allows developers to utilize the component when rendering more complex code snippet visualisations. 

### Justification

In our case, I wanted to add line-numbers to the component, so we did `codeString.split("\n").join((line) => <span>{line}</span>)` to achieve that effect. Typescript was bothered by this though, as the component expects `children` to be a string. Doing `<CodeSnippet>{parsedCodeString as any}</CodeSnippet>` worked perfectly fine, but it makes me uneasy considering the component could potentially change and need that prop to be a string specifically. 

### Desired UX and success metrics

Allow developers to pass `ReactNode`, `ReactElement` or `ReactNode[]` (or similar) as `children` to the `CodeSnippet` component, and update the types to reflect this. 

### Required functionality

The ability to pass react nodes as children to `CodeSnippet` without throwing a Typescript error or having to do `as any` to buypass said error.

### Specific timeline issues / requests

Whenever you're able to get to it, no worries. You may consider this a question as well - do you **need** the `children`-prop on the `CodeSnippet` component to be a string, or is it just fed directly into the resulting `<code>`-element's children? Since "Show more"/"Show less" still works fine when I passed ReactNode children as `any`, I'm assuming you are calculating that based on a ref-height, and not the string's length?

### Available extra resources

None as of now, but very interested in contributing down the line

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by joshblack** [comment]
@imp-dance thanks so much for taking the time to open this issue and fill out the template! From what I'm aware of, this specific use-case (line numbers) I think we want to tackle it in the component itself over in: https://github.com/carbon-design-system/carbon/issues/6519

In general, I think we require a type of `string` since what is passed in as a child is placed in the `<code>` HTML tag. Let me know if that issue would address your use-case or not, if so I think we'd like to move forward with that instead of updating the type for `children`.

**Comment by imp-dance** [comment]
@joshblack Sounds great, thank you!
