### ISSUE TITLE
[Bug]: Link does not navigate when placed inside a Tooltip inside a Tab's label

### ISSUE THREAD

**Issue by hnjoshi** [carbon-design-system/carbon#9912]
Code sandbox link for testing:
https://codesandbox.io/s/tool-tip-test-glsgf?file=/index.js

I have a Tooltip with learn more link inside Tab's label prop which does not trigger new tab with link.

![image](https://user-images.githubusercontent.com/3360588/138158862-16c7ca8c-2c08-4ba3-9b86-81b32cfa58f2.png)

**Comment by tay1orjones** [comment]
Thanks for opening @hnjoshi! Please use the [bug report template](https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+bug+%F0%9F%90%9B&template=BUG_REPORT.yaml&title=%5BBug%5D%3A+) when opening issues to help ensure we get all the pieces of information we need to act on reported issues.

I can add some additional context since this was discussed in [slack](https://ibm-studios.slack.com/archives/C046Y0YUD/p1634753820286700) 
- This is present in v10.46.0 and is present back to v10.40.0 (that's as far back as I went testing)
- I'm not sure how/if this was working in the past
- I lean towards it never working since Tabs explictily preventsDefault when a tab is selected 
https://github.com/carbon-design-system/carbon/blob/3c9fdbcc12116759c47605ad562aa4d3be78b9d5/packages/react/src/components/Tabs/Tabs.js#L333-L336
