### ISSUE TITLE
[Bug]: TooltipDefinition's message box will not disappear when a user hovers away if page is in read-only mode

### ISSUE THREAD

**Issue by SThiara** [carbon-design-system/carbon#9928]
### Package

carbon-components, carbon-components-react, @carbon/icons, @carbon/icons-react

### Browser

Chrome

### Package version

v10.10.1, v7.10, v10.6.0, v7.0.7

### Description

Within our software program, users have varying privileges. They can be given full privileges to view and edit a page, a "read-only" privilege where they are able to view a page's content but not interact with any of the text, checkbox, or dropdown components therein, and no privilege to view or edit. 

Read-only mode is set by passing in a prop to disable fieldsets on that page. TooltipDefinition components are contained within fieldsets accompanying textboxes, dropdowns, or checkboxes to provide descriptive text for a user. When a page is set to read-only mode and fieldsets disabled for that page, tooltip message boxes will not disappear after a user hovers away from the tooltip that spawned them. This is because the "mouse leave" event no longer fires for any tooltip within that fieldset. 

A workaround to this problem is to provide padding to the component. This provides space for the "mouse leave" event to fire and restores normal functionality to the tooltip message box. A negative margin can also be provided to maintain the spacing of the original UI, though this doesn't solve the issue of the message box being detached from the arrow pointing up to it from the TooltipDefinition component. 

This issue exists for the following package version combinations:
Carbon-components 10.10.1, Carbon-components-react 7.10, @carbon/icons-react 10.6.0, carbon-icons 7.0.7
Carbon-components 10.29.0, Carbon-components-react 7.29.0, @carbon/icons-react 10.31.0, carbon-icons 7.0.7

### CodeSandbox example

https://codesandbox.io/s/agitated-pascal-26ixl

### Steps to reproduce

Step 1: Verify in the console that "mouse enter" and "mouse leave" events fire appropriately when fieldset is enabled and padding is disabled. The tooltip message box will appear and disappear properly in this scenario. 

Step 2: Disable the fieldset and re-test. "Mouse enter" event should continue to fire, "mouse leave" event should no longer be firing, and the tooltip message box should persist after appearing for the first time instead of disappearing once you hover away from the tooltip definition. 

Step 3: Enable padding and re-test. Both "mouse leave" and "mouse enter" events should be firing and the tooltip message box should exhibit proper behavior.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by JSoet** [comment]
I work with @SThiara, just wanted to comment on a couple things... 

First, I think it wasn't clear from the sandbox which he created, but for us the issue is not just with the mouse event but from a visibility perspective the tooltips don't disappear after a user moves away from them, so when a user goes to a read only page and then moves the mouse around, they end up with something like this (where the tooltips can't be forced to disappear without leaving the page and coming back):

![image](https://user-images.githubusercontent.com/4523613/140437807-b5a6fddd-7801-4852-9c38-b36875f1a3fe.png)

Second, I just wanted to mention, I just found out that this does not seem to be an issue on firefox... The tooltips do disappear and I tried his sandbox, and the mouse enter and leave events both fire as expected. 

As to your point @joshblack :
> In other words, if a fieldset is disabled then any interactive descendants are disabled as well from what I can observe. Let me know if that is not your understanding

I think you're correct, but I think there is still a bug then in carbon, because why is the mouse enter event firing, and why does the tooltip get triggered and stay open as shown in the screenshot above? Ideally I would like it to behave as it does currently in firefox, where the tooltips work just as they do when the fieldset is enabled and disappear, but if interactive elements should be disabled then I would expect that the tooltip does not get triggered at all? But maybe this is a bug with either chrome or firefox... 

Anyway, in general I think you're right that there is an issue with using fieldset, due to the accessibility concerns with screen readers and keyboard users, so we will likely need to move away from using the fieldset in the longterm, but the fieldset is kind of baked into our software right now, so will likely be a bigger change which might take a while, and I was hoping there might be a quick fix for the tooltip issue in the meantime..

**Comment by joshblack** [comment]
@JSoet thanks so much for your response! I really appreciate it and I think the example you gave was really helpful.

For this part:

> why does the tooltip get triggered and stay open as shown in the screenshot above?

That's a great question, I'm not 100% sure. I also noticed different behavior if I moused over from a part of the page that wasn't disabled versus if I moused over while inside the disabled fieldset 🤔 

This may boil down to how browsers handle events for elements in a disabled part of the tree. I'll definitely add this to our sprint so we can investigate and see what's going on 🤔  If you all have any opportunity to dive deeper and figure out what's going on we'd appreciate any more info you can provide while we take a look!

**Comment by SThiara** [comment]
We've come up with a solution that seems to have fixed the issue, and it's one we're confident enough in that we've merged it into our master branch. It involves applying a `pointer-events: none` CSS property to `TooltipDefinition`. From the MDN Web Docs for that property value: 

`The element is never the target of pointer events; however, pointer events may target its descendant elements if those descendants have pointer-events set to some other value. In these circumstances, pointer events will trigger event listeners on this parent element as appropriate on their way to/from the descendant during the event capture/bubble phases.`

I hope that provides some additional insight into why this bug occurs. Happy holidays!
